{
  "hash": "6ec257c5d27019e3c9b27f1a22b6989e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Optimization algorithms, settings and budgets for the five Leaf River model slots\"\nsubtitle: \"Agent 10 (a10-optimization-advisor) — phase P3\"\nauthor: \"a10-optimization-advisor\"\ndate: 2026-09-16\njupyter: leafriver\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    fig-dpi: 150\n    tbl-cap-location: top\nbibliography: references.bib\n---\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport os, sys, json, time, warnings, contextlib, io\nfrom pathlib import Path\n\nROOT = Path.cwd()\nwhile not (ROOT / \"config\" / \"project.yaml\").exists():\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT)); os.chdir(ROOT)\n\nimport numpy as np, pandas as pd, yaml\nimport matplotlib as mpl, matplotlib.pyplot as plt\nwarnings.filterwarnings(\"ignore\")\nmpl.rcParams.update({\"figure.autolayout\": False, \"axes.grid\": True, \"grid.alpha\": 0.3,\n                     \"font.size\": 9, \"axes.titlesize\": 10})\n\nfrom src.common.data import (load_data, load_config, slice_run, metric_mask, internal_mask,\n                             n_jobs, torch_device)\nfrom src.common.metrics import kge, nse, kge_components          # CANONICAL\nfrom src.common.metrics_extra import objective as OBJ            # a04 recommendation\nfrom src.common.model_api import BaseModel, ParamSpec\nimport src.optimization.runner as R                              # the deliverable of this agent\n\nCFG   = load_config()\nSEED  = CFG[\"reproducibility\"][\"random_seed\"]\nFIG   = ROOT / \"results\" / \"figures\"; FIG.mkdir(parents=True, exist_ok=True)\nOCFG  = yaml.safe_load(open(ROOT / \"config\" / \"optimization.yaml\"))\nMCFG  = yaml.safe_load(open(ROOT / \"config\" / \"models.yaml\"))\nnp.random.seed(SEED)\n\ndf    = load_data()\nFRAME = slice_run(df, \"calibration\")                   # 1951-10-01..1988-09-30, warm-up included\nTRAIN = internal_mask(FRAME, \"train\")                  # 1952-10-01..1981-09-30\nVALID = internal_mask(FRAME, \"validation\")             # 1981-10-01..1988-09-30\nFULL  = metric_mask(FRAME, \"calibration\")              # 1952-10-01..1988-09-30\nprint(f\"run window {FRAME.index[0].date()}..{FRAME.index[-1].date()}  n={len(FRAME)}   \"\n      f\"train {TRAIN.sum()} d | validation {VALID.sum()} d | full calibration {FULL.sum()} d\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrun window 1951-10-01..1988-09-30  n=13515   train 10592 d | validation 2557 d | full calibration 13149 d\n```\n:::\n:::\n\n\n# Summary {#sec-summary}\n\nThis report fixes **how** each of the five model slots is calibrated. It does *not* choose the\nobjective — Agent 4 already did that, on evidence, and this agent inherits it unchanged:\n\n$$\\mathcal{O} \\;=\\; 0.5\\,\\mathrm{KGE}(Q_{sim},Q_{obs}) \\;+\\; 0.5\\,\\mathrm{NSE}(Q_{sim},Q_{obs})\n\\qquad\\text{maximised, untransformed daily } Q,$$\n\non the calibration metric window 1952-10-01..1988-09-30 (13,149 d); minimisers use\n$\\mathrm{cost}=1-\\mathcal{O}$ and map non-finite costs to $10^6$\n(`src.common.metrics_extra.objective` / `objective_cost`).\n\n**The single most important finding of this report is that compute is not scarce for slots 1–4.**\nOne objective evaluation costs 1.3 ms (GR4J), 1.0 ms (HBV-light), 25 ms (ARX–API ridge) and an\nestimated 5 ms (SAC-SMA) on this laptop. The 3 h-per-optimizer limit of `config/project.yaml`\ntherefore binds **only for slot 5 (LSTM)**. The correct response to that abundance is *not* one very\nlong run — every algorithm tested plateaus long before its budget cap — but **many independent seeds\nand a second, structurally different algorithm**, because the across-seed spread is the only thing\nthat distinguishes a converged calibration from a lucky one.\n\n::: {#tbl-reco .cell tbl-cap='Recommended optimizer per slot (generated from config/optimization.yaml, the authoritative file for a11-a15).' execution_count=2}\n``` {.python .cell-code}\nrows = []\nfor key, b in OCFG[\"per_model\"].items():\n    fin = b[\"stages\"][\"final\"]\n    rows.append({\n        \"slot\": b[\"slot\"], \"model\": key.split(\"_\", 1)[1],\n        \"d\": b[\"n_search_dimensions\"],\n        \"algorithm\": b[\"algorithm\"],\n        \"cross-check\": \", \".join(b.get(\"cross_check\", [])) or \"—\",\n        \"evals/seed\": f'{fin.get(\"max_evals\", \"—\"):,}' if isinstance(fin.get(\"max_evals\"), int) else \"—\",\n        \"seeds\": len(fin[\"seeds\"]),\n        \"total evals\": f'{b.get(\"total_evaluations\", 0):,}' if b.get(\"total_evaluations\") else \"—\",\n        \"expected wall\": f'{b[\"expected_wall_time_min\"]} min',\n        \"smooth?\": \"non-smooth\" if \"NON-SMOOTH\" in b[\"smoothness\"] else \"smooth-ish\",\n    })\nTBL_RECO = pd.DataFrame(rows).sort_values(\"slot\").set_index(\"slot\")\nTBL_RECO\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>model</th>\n      <th>d</th>\n      <th>algorithm</th>\n      <th>cross-check</th>\n      <th>evals/seed</th>\n      <th>seeds</th>\n      <th>total evals</th>\n      <th>expected wall</th>\n      <th>smooth?</th>\n    </tr>\n    <tr>\n      <th>slot</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>arx_api_ridge</td>\n      <td>7</td>\n      <td>optuna_tpe</td>\n      <td>de, sobol</td>\n      <td>1,000</td>\n      <td>5</td>\n      <td>20,000</td>\n      <td>9 min</td>\n      <td>smooth-ish</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>gr4j</td>\n      <td>4</td>\n      <td>sceua</td>\n      <td>cmaes, de</td>\n      <td>30,000</td>\n      <td>10</td>\n      <td>300,000</td>\n      <td>7 min</td>\n      <td>smooth-ish</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>hbv_light</td>\n      <td>9</td>\n      <td>cmaes</td>\n      <td>sceua, de</td>\n      <td>50,000</td>\n      <td>10</td>\n      <td>500,000</td>\n      <td>12 min</td>\n      <td>non-smooth</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>sacsma</td>\n      <td>15</td>\n      <td>sceua</td>\n      <td>cmaes, dds</td>\n      <td>100,000</td>\n      <td>10</td>\n      <td>1,400,000</td>\n      <td>90 min</td>\n      <td>non-smooth</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>lstm_seq2seq</td>\n      <td>10</td>\n      <td>optuna_tpe</td>\n      <td>—</td>\n      <td>5</td>\n      <td>5</td>\n      <td>—</td>\n      <td>100 min</td>\n      <td>smooth-ish</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nHeadline recipe, in words:\n\n1. **slot 1 `arx_api_ridge`** — closed-form ridge inside, 7 hyperparameters outside: **Optuna TPE**\n   (256 Sobol' start-up + 744 TPE trials) × 5 seeds, selected on the internal-validation window,\n   cross-checked with DE; final coefficients refitted in closed form on the full calibration window.\n2. **slot 2 `gr4j`** (4 par) — **SCE-UA** [@duan1992], `ngs = 2n+1 = 9`, 10 seeds, ≤ 30,000\n   evaluations each, cross-checked with CMA-ES and DE. (SCE-UA was developed *on this basin*.)\n3. **slot 3 `hbv_light`** (9 par, threshold-laden) — **CMA-ES** [@hansen2001], 10 seeds,\n   ≤ 50,000 evaluations, cross-checked with SCE-UA and DE. Derivative-free only.\n4. **slot 4 `sacsma`** (15 par, thresholds + integer sub-stepping) — **SCE-UA** with `ngs = 15`,\n   10 seeds, ≤ 100,000 evaluations, cross-checked with CMA-ES (10 seeds) and DDS (5 seeds).\n5. **slot 5 `lstm_seq2seq`** — **AdamW** inside (early stopping on internal validation),\n   **Optuna TPE + MedianPruner** outside (25 trials, hard 90 min cap), then 5 member seeds 42–46.\n   This is the only slot where the wall-clock limit is a real constraint.\n\nEverything is executed through one shared module, `src/optimization/runner.py`, so that the five\nslots produce comparable artefacts (@sec-runner), and the complete settings live in\n`config/optimization.yaml` (@sec-protocol).\n\n# What is already fixed before this report {#sec-fixed}\n\n| Fixed by | What | Consequence for a10 |\n|---|---|---|\n| user / `project.yaml` | evaluation 1948-10-01..1951-09-30, calibration 1951-10-01..1988-09-30 | the optimizer never sees evaluation rows; `runner.calibrate()` aborts if `LR_AGENT=a16` |\n| a04 / `metrics.yaml` | objective $\\mathcal{O}=0.5\\,$KGE$+0.5\\,$NSE, no transform, no $\\varepsilon$ | a10 designs the *search*, not the target |\n| a03 / `models.yaml` | five slots, parameter bounds, integer and ordering rules inside the models | the search box is rectangular in every slot |\n| a03 | conceptual slots calibrate on the full calibration metric window; trainable slots fit on internal train and select on internal validation | two-stage protocol in @sec-protocol |\n| a02 | scaling constants from the calibration window only | not an optimizer concern, but the runner never touches evaluation data |\n\n: Inherited decisions {#tbl-fixed}\n\n# Compute reality check {#sec-compute}\n\nAgent 3 measured 0.963 ms per GR4J run over the 13,515-day calibration window with Numba\n[@lam2015] — 40.5× the pure-Python loop and bit-identical output. The measurement below repeats it\nend-to-end through the actual objective path used by the runner (simulate 13,515 d → mask →\n$0.5\\,$KGE$+0.5\\,$NSE), which is what a budget must be sized against.\n\n::: {#surrogates .cell execution_count=3}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Non-authoritative surrogate models used for the benchmark (a06/a07 write the deliverables)\"}\nfrom numba import njit\n\n_MODELS = MCFG[\"models\"]\ndef _specs(slot):\n    p = [m for m in _MODELS if m[\"slot\"] == slot][0][\"parameters\"]\n    return [ParamSpec(q[\"name\"], float(q[\"lower\"]), float(q[\"upper\"]), float(q[\"default\"]),\n                      q.get(\"units\", \"-\"), False, q.get(\"description\", \"\")) for q in p]\n\n# ---------------- GR4J surrogate (4 parameters) ----------------\ndef _gr4j_uh(x4):\n    n1, n2 = int(np.ceil(x4)), int(np.ceil(2 * x4))\n    j1, j2 = np.arange(n1 + 1.0), np.arange(n2 + 1.0)\n    s1 = np.where(j1 < x4, np.clip(j1 / x4, 0, None) ** 2.5, 1.0)\n    s2 = np.where(j2 < x4, 0.5 * np.clip(j2 / x4, 0, None) ** 2.5,\n         np.where(j2 < 2 * x4, 1 - 0.5 * np.clip(2 - j2 / x4, 0, None) ** 2.5, 1.0))\n    u1, u2 = np.diff(s1), np.diff(s2)\n    return u1 / u1.sum(), u2 / u2.sum()\n\n@njit(cache=True)\ndef _gr4j_core(P, E, x1, x2, x3, u1, u2):\n    n = P.shape[0]; n1 = u1.shape[0]; n2 = u2.shape[0]\n    S = 0.30 * x1; Rr = 0.50 * x3\n    m1 = np.zeros(n1); m2 = np.zeros(n2); Q = np.empty(n)\n    for t in range(n):\n        p = P[t]; e = E[t]\n        if p >= e: pn = p - e; en = 0.0\n        else: pn = 0.0; en = e - p\n        s = S / x1; ps = 0.0; es = 0.0\n        if pn > 0.0:\n            th = np.tanh(min(pn / x1, 13.0)); ps = x1 * (1.0 - s * s) * th / (1.0 + s * th)\n        else:\n            th = np.tanh(min(en / x1, 13.0)); es = S * (2.0 - s) * th / (1.0 + (1.0 - s) * th)\n        S = S - es + ps\n        perc = S * (1.0 - (1.0 + (4.0 / 9.0 * S / x1) ** 4) ** -0.25)\n        S -= perc; pr = perc + (pn - ps)\n        q9 = m1[0] + 0.9 * pr * u1[0]\n        for k in range(n1 - 1): m1[k] = m1[k + 1] + 0.9 * pr * u1[k + 1]\n        m1[n1 - 1] = 0.0\n        q1 = m2[0] + 0.1 * pr * u2[0]\n        for k in range(n2 - 1): m2[k] = m2[k + 1] + 0.1 * pr * u2[k + 1]\n        m2[n2 - 1] = 0.0\n        f = x2 * (Rr / x3) ** 3.5\n        Rr = Rr + q9 + f\n        if Rr < 0.0: Rr = 0.0\n        qr = Rr * (1.0 - (1.0 + (Rr / x3) ** 4) ** -0.25)\n        Rr -= qr\n        qd = q1 + f\n        if qd < 0.0: qd = 0.0\n        Q[t] = qr + qd\n    return Q\n\nclass SurrGR4J(BaseModel):\n    \"\"\"NON-AUTHORITATIVE GR4J surrogate for the a10 benchmark (a06 writes src/models/model_2.py).\"\"\"\n    model_id = \"surr_gr4j\"; kind = \"conceptual\"\n    def param_specs(self): return _specs(2)\n    def simulate(self, forcing, params, initial_states=None):\n        x1, x2, x3, x4 = [float(params[k]) for k in (\"x1\", \"x2\", \"x3\", \"x4\")]\n        u1, u2 = _gr4j_uh(x4)\n        return pd.Series(_gr4j_core(forcing[\"P\"].to_numpy(), forcing[\"PET\"].to_numpy(),\n                                    x1, x2, x3, u1, u2), index=forcing.index)\n\n# ---------------- HBV-light surrogate (9 parameters, thresholds) ----------------\ndef _maxbas_w(mb):\n    n = int(np.ceil(mb)); x = np.linspace(0.0, mb, 2001)\n    y = np.where(x <= mb / 2, x, mb - x); y = y / np.trapezoid(y, x)\n    w = np.array([np.trapezoid(np.where((x >= k) & (x <= k + 1), y, 0.0), x) for k in range(n)])\n    return w / w.sum()\n\n@njit(cache=True)\ndef _hbv_core(P, E, FC, LP, BETA, PERC, UZL, K0e, K1, K2e, w, SLZ0):\n    n = P.shape[0]; nw = w.shape[0]\n    SM = 0.60 * FC; SUZ = 5.0; SLZ = SLZ0\n    mem = np.zeros(nw); Q = np.empty(n)\n    for t in range(n):\n        p = P[t]; pet = E[t]\n        rech = p * (SM / FC) ** BETA\n        if rech > p: rech = p\n        SM = SM + p - rech\n        if SM > FC:\n            rech += SM - FC; SM = FC\n        r = SM / (LP * FC)\n        if r > 1.0: r = 1.0\n        ea = pet * r\n        if ea > SM: ea = SM\n        SM -= ea; SUZ += rech\n        perc = PERC if PERC < SUZ else SUZ\n        SUZ -= perc; SLZ += perc\n        q0 = K0e * (SUZ - UZL) if SUZ > UZL else 0.0\n        q1 = K1 * SUZ\n        if q0 + q1 > SUZ:\n            sc = SUZ / (q0 + q1); q0 *= sc; q1 *= sc\n        SUZ -= (q0 + q1)\n        q2 = K2e * SLZ; SLZ -= q2\n        qt = q0 + q1 + q2\n        out = mem[0] + qt * w[0]\n        for k in range(nw - 1): mem[k] = mem[k + 1] + qt * w[k + 1]\n        mem[nw - 1] = 0.0\n        Q[t] = out\n    return Q\n\nclass SurrHBV(BaseModel):\n    \"\"\"NON-AUTHORITATIVE HBV-light surrogate for the a10 benchmark (a07 writes src/models/model_3.py).\"\"\"\n    model_id = \"surr_hbv\"; kind = \"conceptual\"; n_decoy = 0\n    def param_specs(self):\n        s = _specs(3)\n        s += [ParamSpec(f\"decoy{i}\", 0.0, 1.0, 0.5, \"-\", False, \"inactive dimension\")\n              for i in range(self.n_decoy)]\n        return s\n    def simulate(self, forcing, params, initial_states=None):\n        FC, LP, BETA, PERC, UZL, K0, K1, K2, MB = [float(params[k]) for k in\n            (\"FC\", \"LP\", \"BETA\", \"PERC\", \"UZL\", \"K0\", \"K1\", \"K2\", \"MAXBAS\")]\n        K0e = max(K0, K1); K2e = min(K2, 0.9 * K1)        # a03 ordering rule, enforced inside the model\n        SLZ0 = min(400.0, 0.40 / max(K2e, 1e-4))\n        return pd.Series(_hbv_core(forcing[\"P\"].to_numpy(), forcing[\"PET\"].to_numpy(),\n                                   FC, LP, BETA, PERC, UZL, K0e, K1, K2e, _maxbas_w(MB), SLZ0),\n                         index=forcing.index)\n\nclass SurrHBV15(SurrHBV):\n    \"\"\"HBV-9 inflated to 15 search dimensions with 6 inactive parameters (dimension-scaling test).\"\"\"\n    model_id = \"surr_hbv15\"; n_decoy = 6\n\nMODELS = {\"gr4j\": SurrGR4J, \"hbv\": SurrHBV, \"hbv15\": SurrHBV15}\n```\n:::\n\n\n::: {#tbl-cost .cell tbl-cap='Measured cost of ONE objective evaluation (simulate the 13,515-day calibration run window, mask, score). Slot 1 is timed with the real src/models/model_1.py; slot 4 is an a03 estimate that a14 must re-measure.' execution_count=4}\n``` {.python .cell-code}\ndef _timeit(fn, n=50):\n    fn(); t0 = time.perf_counter()\n    for _ in range(n): fn()\n    return (time.perf_counter() - t0) / n * 1e3\n\ng, h = SurrGR4J(), SurrHBV()\nqg = g.simulate(FRAME, g.defaults()).to_numpy(); obs = FRAME[\"Q\"].to_numpy()\nrows = [\n    {\"item\": \"GR4J simulate (numba)\", \"ms\": _timeit(lambda: g.simulate(FRAME, g.defaults()))},\n    {\"item\": \"HBV-light simulate (numba)\", \"ms\": _timeit(lambda: h.simulate(FRAME, h.defaults()))},\n    {\"item\": \"objective() on 10,592 d\", \"ms\": _timeit(lambda: OBJ(qg[TRAIN], obs[TRAIN]), 200)},\n]\no2 = R.Objective(g, FRAME, TRAIN, max_evals=10**6, trace=False)\nrows.append({\"item\": \"full runner evaluation, GR4J\", \"ms\": _timeit(lambda: o2(np.array([.5, .5, .5, .5])))})\no3 = R.Objective(h, FRAME, TRAIN, max_evals=10**6, trace=False)\nrows.append({\"item\": \"full runner evaluation, HBV\", \"ms\": _timeit(lambda: o3(np.full(9, 0.5)))})\ntry:\n    from src.models.model_1 import Model1\n    m1 = Model1(); p1 = m1.defaults()\n    def _one1():\n        m1.fit(FRAME.loc[TRAIN], FRAME.loc[TRAIN, \"Q\"], p1); m1.simulate(FRAME, p1)\n    rows.append({\"item\": \"full evaluation, ARX-API ridge (fit+simulate)\", \"ms\": _timeit(_one1, 10)})\nexcept Exception as ex:\n    rows.append({\"item\": f\"ARX-API ridge (not importable yet: {type(ex).__name__})\", \"ms\": np.nan})\nCOST = pd.DataFrame(rows)\nCOST[\"h per 100,000 evaluations\"] = COST[\"ms\"] * 1e5 / 3.6e6\nCOST.round(3).set_index(\"item\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ms</th>\n      <th>h per 100,000 evaluations</th>\n    </tr>\n    <tr>\n      <th>item</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>GR4J simulate (numba)</th>\n      <td>1.054</td>\n      <td>0.029</td>\n    </tr>\n    <tr>\n      <th>HBV-light simulate (numba)</th>\n      <td>0.672</td>\n      <td>0.019</td>\n    </tr>\n    <tr>\n      <th>objective() on 10,592 d</th>\n      <td>0.156</td>\n      <td>0.004</td>\n    </tr>\n    <tr>\n      <th>full runner evaluation, GR4J</th>\n      <td>1.256</td>\n      <td>0.035</td>\n    </tr>\n    <tr>\n      <th>full runner evaluation, HBV</th>\n      <td>0.860</td>\n      <td>0.024</td>\n    </tr>\n    <tr>\n      <th>full evaluation, ARX-API ridge (fit+simulate)</th>\n      <td>7.333</td>\n      <td>0.204</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWith these numbers, 100,000 evaluations cost **2.2 min** (GR4J), **1.6 min** (HBV), **≈ 8 min**\n(SAC-SMA at the a03 factor of 4) and **42 min** (slot 1). The 3 h limit is not binding for slots 1–4,\nso the budgets below are sized by *convergence evidence*, not by scarcity.\n\n# Catalogue of candidate algorithms {#sec-catalogue}\n\nThe response surface of a conceptual rainfall–runoff model on a heavy-tailed daily flow record is\nthe textbook hard case: it is **non-convex**, contains **flat regions and discontinuous derivatives**\nwherever a threshold switches (HBV's `UZL`, SAC-SMA's percolation and `ADIMP` logic, integer\nsub-stepping), it is **strongly interactive** (fast/slow partition versus recession constants), and it\nis **equifinal** — many parameter sets give practically the same objective [@beven1992].\nKavetski & Kuczera [-@kavetski2007] showed that the micro-discontinuities created by thresholds and\nadaptive sub-stepping create *spurious* local optima that are artefacts of the numerics, not of the\nhydrology; this is exactly why gradient-based search is excluded for slots 3 and 4.\n\n## Local, derivative-free\n\n| Algorithm | Principle | Key settings | Verdict here |\n|---|---|---|---|\n| Nelder–Mead [@nelder1965] | reflect/expand/contract a simplex of $n+1$ points | `xatol`, `fatol`, adaptive | excellent **polish**, unreliable alone in ≥ 9 d (@sec-exp-e) |\n| Powell [@powell1964] | successive line searches along conjugate directions | `xtol`, `ftol` | same, slightly worse on kinked surfaces |\n| Rosenbrock [-@rosenbrock1960] | rotating coordinate search | step contraction | historical; superseded by Nelder–Mead/Powell |\n\n## Local, gradient-based\n\n| Algorithm | Principle | Key settings | Verdict here |\n|---|---|---|---|\n| L-BFGS-B [@byrd1995] | quasi-Newton with box constraints, finite-difference gradients | `eps` (FD step), `ftol` | **forbidden for slots 3 and 4**: the FD gradient across a threshold is noise |\n| Gauss–Marquardt–Levenberg (PEST) [@doherty2015] | linearised least squares + Marquardt damping | derivative increments, lambda schedule | industry standard for smooth models; needs a Jacobian per iteration (16 runs for SAC-SMA) and the same smoothness assumption |\n| Adam / AdamW [@kingma2015; @loshchilov2019] | stochastic gradient with per-parameter moments | `lr`, `weight_decay`, schedule | the *only* sane choice for the 20,545 LSTM weights |\n\n## Global, population-based\n\n| Algorithm | Principle | Key settings | Python |\n|---|---|---|---|\n| **SCE-UA** [@duan1992; @duan1994] | shuffled complex evolution: partition a random population into `ngs` complexes, evolve each by competitive Nelder–Mead-like simplex steps, shuffle, repeat | `ngs`, `kstop`, `pcento`, `peps` | `spotpy 1.6.7` [@houska2015] |\n| **DE** [@storn1997] | vector differences of the population as mutation | `popsize`, `strategy`, `mutation`, `recombination`, `tol` | `scipy 1.17.1` [@virtanen2020] |\n| **CMA-ES** [@hansen2001] | adapts the full covariance of a Gaussian search distribution | `sigma0`, `popsize`, `tolfun`, `tolx` | `cma 4.0.0` [@hansen2019] |\n| **DDS** [@tolson2007] | single solution, perturb a shrinking random subset of dimensions | `r` (0.2), budget-dependent inclusion probability | 25 lines (in the runner) |\n| PSO [@kennedy1995] | swarm of particles with inertia and social/cognitive pull | `n_particles`, `c1`, `c2`, `w` | `pyswarms 1.3.0` [@miranda2018] |\n| GA [@goldberg1989] | selection/crossover/mutation on encoded strings | population, crossover/mutation rates | `pymoo 0.6` [@blank2020] |\n| Dual annealing [@xiang1997; @kirkpatrick1983] | generalised simulated annealing + local refinement | `maxfun`, `initial_temp`, `visit` | `scipy` |\n| Basin hopping [@wales1997] | random jumps + local minimisation, Metropolis acceptance | `T`, `stepsize` | `scipy` |\n\n## Surrogate / Bayesian\n\n| Algorithm | Principle | When it pays |\n|---|---|---|\n| EGO / GP-EI [@jones1998] | Gaussian-process surrogate, expected-improvement sampling | expensive evaluations (> 1 s) — **not** our slots 2–4 |\n| TPE [@bergstra2011] | density-ratio model $p(x\\mid y<y^\\ast)/p(x\\mid y\\ge y^\\ast)$ | mixed integer/continuous, 25–1,000 expensive trials → **slots 1 and 5** |\n| DYCORS / RBF [@regis2013] | radial-basis surrogate + dynamic coordinate perturbation | high-dimensional expensive problems |\n\nImplementation: `optuna 5.0.0` [@akiba2019] with `MedianPruner` (prune a trial whose intermediate\nvalidation score is below the running median — the single most effective way to buy trials for slot 5).\n\n## Uncertainty-aware sampling (not used for the ranking, but available)\n\nGLUE [@beven1992], DREAM$_{(ZS)}$ [@vrugt2016], SCEM-UA [@vrugt2003], MCMC with `emcee`\n[@foreman2013], ROPE, and Sobol'/Morris screening with `SALib` [@herman2017]. These answer\n*\"how well determined is the parameter set?\"*, not *\"what is the best parameter set?\"*. The project\nranks deterministic single-parameter-set models by KGE and NSE (CLAUDE.md), so they stay out of the\ncalibration path; a13/a14 may run a cheap Sobol' screening as a *diagnostic* of which parameters the\nobjective can actually identify.\n\n## Multi-objective\n\nNSGA-II/III [@deb2002] via `pymoo` [@blank2020], MOSCEM [@vrugt2003b] and Borg produce a Pareto front\nin (KGE, NSE) space. Agent 4 measured that KGE and NSE are only rank-correlated at ≈ 0.70 on this\nrecord, so a front would be genuinely two-dimensional — but the study's final ranking is\nsingle-objective by construction, and a front cannot be handed to a16 as one parameter set. The\n50/50 scalarisation *is* the project's declared compromise. Rejected for the calibration path,\nrecommended only as an optional diagnostic for slot 4.\n\n# Benchmark design {#sec-bench}\n\nFive experiments, all on **non-authoritative surrogates** of slots 2 and 3 (defined above; a06/a07\nwrite the deliverable models), all scored with the real objective on the **internal-train** window\n(1952-10-01..1981-09-30, 10,592 d), all executed through the deliverable runner\n(`R.Objective`, `R.ALGORITHMS`), so the benchmark exercises exactly the code path a11–a15 will use.\n\n| Exp. | Question | Design |\n|---|---|---|\n| **A** | which algorithm, at which budget? | 7 algorithms × 5 seeds (42–46); GR4J budget 10,000, HBV budget 20,000 evaluations |\n| **B** | how many SCE-UA complexes? | `ngs` ∈ {5, 10, 19, 20} × 5 seeds on HBV (9 par) |\n| **C** | does log-scaling parameters help? | linear vs log map for the scale-like parameters, DE and CMA-ES, 5 seeds, both models |\n| **D** | how does the cost scale with dimension? | HBV inflated from 9 to 15 search dimensions, 4 algorithms × 5 seeds, 30,000 evaluations |\n| **E** | is a multi-start *local* search enough? | single-start Nelder–Mead / Powell / L-BFGS-B, 15 independent starts, 2,000 evaluations each |\n\n: Benchmark experiments {#tbl-bench-design}\n\n::: {#bench-run .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Experiment driver (cached in results/figures/a10_bench_all.csv — delete to recompute, ~20 min)\"}\nGRID = np.array([200, 500, 1000, 2000, 5000, 10000, 15000, 20000, 30000])\nSEEDS = [42, 43, 44, 45, 46]\nALGOS_A = [\"sceua\", \"de\", \"cmaes\", \"dds\", \"pso\", \"dual_annealing\", \"nelder_mead\"]\nLOG_GR4J = {\"x1\": \"log\", \"x3\": \"log\"}\nLOG_HBV = {\"FC\": \"log\", \"K0\": \"log\", \"K1\": \"log\", \"K2\": \"log\"}   # PERC has lower bound 0 -> log undefined\n\ndef run_case(model_key, algo, seed, budget, settings=None, transforms=None, tag=\"\"):\n    mdl = MODELS[model_key]()\n    obj = R.Objective(mdl, FRAME, TRAIN, max_evals=budget, transforms=transforms, trace=False)\n    s = {\"max_evals\": budget, **(settings or {})}\n    t0 = time.perf_counter()\n    try:\n        R.ALGORITHMS[algo](obj, seed, s)\n    except (R.BudgetExhausted, Exception) as ex:\n        if not isinstance(ex, R.BudgetExhausted) and obj.best_x is None:\n            raise\n    wall = time.perf_counter() - t0\n    best = dict(zip(obj.names, obj.best_x))\n    sim = mdl.simulate(FRAME, best).to_numpy(); o = FRAME[\"Q\"].to_numpy()\n    h = np.asarray(obj.hist)\n    rec = dict(model=model_key, algo=algo, seed=seed, tag=tag, budget=budget, n_eval=obj.n,\n               wall_s=wall, ms_per_eval=1e3 * wall / max(obj.n, 1), obj_train=1 - obj.best,\n               obj_valid=OBJ(sim[VALID], o[VALID]), obj_full=OBJ(sim[FULL], o[FULL]),\n               t_best_s=obj.t_best, n_failed=obj.n_failed,\n               improvement_tail=obj.convergence()[\"improvement_tail\"])\n    for g_ in GRID[GRID <= budget]:\n        rec[f\"obj@{g_}\"] = 1 - (h[g_ - 1] if h.size >= g_ else h[-1])\n    rec.update({f\"p_{k}\": float(v) for k, v in best.items()})\n    curve = np.minimum.accumulate(h) if h.size else np.array([np.nan])\n    if curve.size < budget:\n        curve = np.concatenate([curve, np.full(budget - curve.size, curve[-1])])\n    return rec, curve\n\ndef cases():\n    C = []\n    for a in ALGOS_A:                                                   # A\n        for s in SEEDS:\n            C.append(dict(name=\"A\", model_key=\"gr4j\", algo=a, seed=s, budget=10000,\n                          settings={\"n_start\": 10}, transforms=None, tag=\"A\"))\n            C.append(dict(name=\"A\", model_key=\"hbv\", algo=a, seed=s, budget=20000,\n                          settings={\"n_start\": 10}, transforms=None, tag=\"A\"))\n    for ngs in [5, 10, 19, 20]:                                         # B\n        for s in SEEDS:\n            C.append(dict(name=\"B\", model_key=\"hbv\", algo=\"sceua\", seed=s, budget=20000,\n                          settings={\"ngs\": ngs, \"dbname\": f\"b{ngs}_{s}\"}, transforms=None, tag=f\"ngs={ngs}\"))\n    for mk, tf in [(\"gr4j\", LOG_GR4J), (\"hbv\", LOG_HBV)]:               # C\n        for a in [\"de\", \"cmaes\"]:\n            for s in SEEDS:\n                for lbl, t in [(\"linear\", None), (\"log\", tf)]:\n                    C.append(dict(name=\"C\", model_key=mk, algo=a, seed=s,\n                                  budget=10000 if mk == \"gr4j\" else 20000,\n                                  settings={}, transforms=t, tag=lbl))\n    for a in [\"sceua\", \"cmaes\", \"de\", \"dds\"]:                           # D\n        for s in SEEDS:\n            C.append(dict(name=\"D\", model_key=\"hbv15\", algo=a, seed=s, budget=30000,\n                          settings={\"dbname\": f\"d_{a}_{s}\"}, transforms=None, tag=\"15d\"))\n    for a in [\"nelder_mead\", \"lbfgsb\", \"powell\"]:                       # E\n        for mk in [\"gr4j\", \"hbv\"]:\n            for s in range(42, 57):\n                C.append(dict(name=\"E\", model_key=mk, algo=a, seed=s, budget=2000,\n                              settings={\"n_start\": 1}, transforms=None, tag=\"single-start\"))\n    return C\n\nf_csv, f_npz = FIG / \"a10_bench_all.csv\", FIG / \"a10_bench_curves.npz\"\nif f_csv.exists() and f_npz.exists():\n    B = pd.read_csv(f_csv); CURVES = dict(np.load(f_npz))\n    print(f\"loaded cached benchmark: {len(B)} runs\")\nelse:\n    C = cases(); t0 = time.perf_counter()\n    def _run(c):\n        rec, cv = run_case(c[\"model_key\"], c[\"algo\"], c[\"seed\"], c[\"budget\"],\n                           c[\"settings\"], c[\"transforms\"], c[\"tag\"])\n        rec[\"exp\"] = c[\"name\"]\n        return rec, (cv if c[\"name\"] == \"A\" else None)\n    try:                                   # runs are independent and seeded: identical either way\n        from joblib import Parallel, delayed\n        out = Parallel(n_jobs=n_jobs(1))(delayed(_run)(c) for c in C)\n    except Exception:\n        out = [_run(c) for c in C]\n    B = pd.DataFrame([r for r, _ in out])\n    CURVES = {f\"{r['model']}|{r['algo']}|{r['seed']}\": cv for r, cv in out if cv is not None}\n    B.to_csv(f_csv, index=False); np.savez_compressed(f_npz, **CURVES)\n    print(f\"computed {len(B)} runs in {time.perf_counter()-t0:.0f} s\")\n\nA_ = B[B.exp == \"A\"]; BEST = {m: A_[A_.model == m].obj_train.max() for m in [\"gr4j\", \"hbv\"]}\nprint({k: round(v, 6) for k, v in BEST.items()})\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nloaded cached benchmark: 240 runs\n{'gr4j': np.float64(0.885911), 'hbv': np.float64(0.919568)}\n```\n:::\n:::\n\n\n# Benchmark results {#sec-results}\n\n## Experiment A — which algorithm? {#sec-exp-a}\n\n::: {#tbl-expa .cell tbl-cap='Experiment A. Best objective reached on the internal-train window (median and spread over the 5 seeds), evaluations used, and the transfer of the best parameter set to the internal-validation window. `evals to 1e-4` is the median number of evaluations needed to come within 1e-4 objective units of the best value found by ANY algorithm for that model.' execution_count=6}\n``` {.python .cell-code}\ndef evals_to(model, algo, seed, target):\n    c = CURVES.get(f\"{model}|{algo}|{seed}\")\n    if c is None: return np.nan\n    hit = np.nonzero((1 - c) >= target)[0]\n    return float(hit[0] + 1) if hit.size else np.nan\n\nrows = []\nfor m in [\"gr4j\", \"hbv\"]:\n    tgt = BEST[m] - 1e-4\n    for a in ALGOS_A:\n        d = A_[(A_.model == m) & (A_.algo == a)]\n        e = [evals_to(m, a, s, tgt) for s in SEEDS]\n        rows.append({\"model\": m, \"algorithm\": a,\n                     \"O median\": d.obj_train.median(), \"O worst seed\": d.obj_train.min(),\n                     \"seed spread\": d.obj_train.max() - d.obj_train.min(),\n                     \"gap to best\": BEST[m] - d.obj_train.median(),\n                     \"evals used (med)\": d.n_eval.median(),\n                     \"evals to 1e-4 (med)\": np.nanmedian(e),\n                     \"seeds reaching 1e-4\": int(np.sum(np.isfinite(e))),\n                     \"O validation (med)\": d.obj_valid.median(),\n                     \"wall s (med)\": d.wall_s.median()})\nEA = pd.DataFrame(rows)\nEA.style.format({\"O median\": \"{:.6f}\", \"O worst seed\": \"{:.6f}\", \"seed spread\": \"{:.2e}\",\n                 \"gap to best\": \"{:.2e}\", \"O validation (med)\": \"{:.4f}\",\n                 \"evals used (med)\": \"{:.0f}\", \"evals to 1e-4 (med)\": \"{:.0f}\",\n                 \"wall s (med)\": \"{:.1f}\"}).hide(axis=\"index\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_62619\">\n  <thead>\n    <tr>\n      <th id=\"T_62619_level0_col0\" class=\"col_heading level0 col0\" >model</th>\n      <th id=\"T_62619_level0_col1\" class=\"col_heading level0 col1\" >algorithm</th>\n      <th id=\"T_62619_level0_col2\" class=\"col_heading level0 col2\" >O median</th>\n      <th id=\"T_62619_level0_col3\" class=\"col_heading level0 col3\" >O worst seed</th>\n      <th id=\"T_62619_level0_col4\" class=\"col_heading level0 col4\" >seed spread</th>\n      <th id=\"T_62619_level0_col5\" class=\"col_heading level0 col5\" >gap to best</th>\n      <th id=\"T_62619_level0_col6\" class=\"col_heading level0 col6\" >evals used (med)</th>\n      <th id=\"T_62619_level0_col7\" class=\"col_heading level0 col7\" >evals to 1e-4 (med)</th>\n      <th id=\"T_62619_level0_col8\" class=\"col_heading level0 col8\" >seeds reaching 1e-4</th>\n      <th id=\"T_62619_level0_col9\" class=\"col_heading level0 col9\" >O validation (med)</th>\n      <th id=\"T_62619_level0_col10\" class=\"col_heading level0 col10\" >wall s (med)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td id=\"T_62619_row0_col0\" class=\"data row0 col0\" >gr4j</td>\n      <td id=\"T_62619_row0_col1\" class=\"data row0 col1\" >sceua</td>\n      <td id=\"T_62619_row0_col2\" class=\"data row0 col2\" >0.885911</td>\n      <td id=\"T_62619_row0_col3\" class=\"data row0 col3\" >0.885911</td>\n      <td id=\"T_62619_row0_col4\" class=\"data row0 col4\" >7.30e-12</td>\n      <td id=\"T_62619_row0_col5\" class=\"data row0 col5\" >3.38e-12</td>\n      <td id=\"T_62619_row0_col6\" class=\"data row0 col6\" >3460</td>\n      <td id=\"T_62619_row0_col7\" class=\"data row0 col7\" >1286</td>\n      <td id=\"T_62619_row0_col8\" class=\"data row0 col8\" >5</td>\n      <td id=\"T_62619_row0_col9\" class=\"data row0 col9\" >0.8176</td>\n      <td id=\"T_62619_row0_col10\" class=\"data row0 col10\" >5.3</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row1_col0\" class=\"data row1 col0\" >gr4j</td>\n      <td id=\"T_62619_row1_col1\" class=\"data row1 col1\" >de</td>\n      <td id=\"T_62619_row1_col2\" class=\"data row1 col2\" >0.885911</td>\n      <td id=\"T_62619_row1_col3\" class=\"data row1 col3\" >0.885911</td>\n      <td id=\"T_62619_row1_col4\" class=\"data row1 col4\" >2.26e-10</td>\n      <td id=\"T_62619_row1_col5\" class=\"data row1 col5\" >1.66e-10</td>\n      <td id=\"T_62619_row1_col6\" class=\"data row1 col6\" >4992</td>\n      <td id=\"T_62619_row1_col7\" class=\"data row1 col7\" >1607</td>\n      <td id=\"T_62619_row1_col8\" class=\"data row1 col8\" >5</td>\n      <td id=\"T_62619_row1_col9\" class=\"data row1 col9\" >0.8176</td>\n      <td id=\"T_62619_row1_col10\" class=\"data row1 col10\" >7.1</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row2_col0\" class=\"data row2 col0\" >gr4j</td>\n      <td id=\"T_62619_row2_col1\" class=\"data row2 col1\" >cmaes</td>\n      <td id=\"T_62619_row2_col2\" class=\"data row2 col2\" >0.885911</td>\n      <td id=\"T_62619_row2_col3\" class=\"data row2 col3\" >0.885911</td>\n      <td id=\"T_62619_row2_col4\" class=\"data row2 col4\" >2.34e-13</td>\n      <td id=\"T_62619_row2_col5\" class=\"data row2 col5\" >2.80e-14</td>\n      <td id=\"T_62619_row2_col6\" class=\"data row2 col6\" >936</td>\n      <td id=\"T_62619_row2_col7\" class=\"data row2 col7\" >352</td>\n      <td id=\"T_62619_row2_col8\" class=\"data row2 col8\" >5</td>\n      <td id=\"T_62619_row2_col9\" class=\"data row2 col9\" >0.8176</td>\n      <td id=\"T_62619_row2_col10\" class=\"data row2 col10\" >1.4</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row3_col0\" class=\"data row3 col0\" >gr4j</td>\n      <td id=\"T_62619_row3_col1\" class=\"data row3 col1\" >dds</td>\n      <td id=\"T_62619_row3_col2\" class=\"data row3 col2\" >0.885903</td>\n      <td id=\"T_62619_row3_col3\" class=\"data row3 col3\" >0.885894</td>\n      <td id=\"T_62619_row3_col4\" class=\"data row3 col4\" >1.14e-05</td>\n      <td id=\"T_62619_row3_col5\" class=\"data row3 col5\" >7.55e-06</td>\n      <td id=\"T_62619_row3_col6\" class=\"data row3 col6\" >10000</td>\n      <td id=\"T_62619_row3_col7\" class=\"data row3 col7\" >949</td>\n      <td id=\"T_62619_row3_col8\" class=\"data row3 col8\" >5</td>\n      <td id=\"T_62619_row3_col9\" class=\"data row3 col9\" >0.8175</td>\n      <td id=\"T_62619_row3_col10\" class=\"data row3 col10\" >13.8</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row4_col0\" class=\"data row4 col0\" >gr4j</td>\n      <td id=\"T_62619_row4_col1\" class=\"data row4 col1\" >pso</td>\n      <td id=\"T_62619_row4_col2\" class=\"data row4 col2\" >0.885341</td>\n      <td id=\"T_62619_row4_col3\" class=\"data row4 col3\" >0.883675</td>\n      <td id=\"T_62619_row4_col4\" class=\"data row4 col4\" >2.15e-03</td>\n      <td id=\"T_62619_row4_col5\" class=\"data row4 col5\" >5.70e-04</td>\n      <td id=\"T_62619_row4_col6\" class=\"data row4 col6\" >10000</td>\n      <td id=\"T_62619_row4_col7\" class=\"data row4 col7\" >2626</td>\n      <td id=\"T_62619_row4_col8\" class=\"data row4 col8\" >1</td>\n      <td id=\"T_62619_row4_col9\" class=\"data row4 col9\" >0.8134</td>\n      <td id=\"T_62619_row4_col10\" class=\"data row4 col10\" >13.2</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row5_col0\" class=\"data row5 col0\" >gr4j</td>\n      <td id=\"T_62619_row5_col1\" class=\"data row5 col1\" >dual_annealing</td>\n      <td id=\"T_62619_row5_col2\" class=\"data row5 col2\" >0.885911</td>\n      <td id=\"T_62619_row5_col3\" class=\"data row5 col3\" >0.885911</td>\n      <td id=\"T_62619_row5_col4\" class=\"data row5 col4\" >1.57e-12</td>\n      <td id=\"T_62619_row5_col5\" class=\"data row5 col5\" >8.15e-14</td>\n      <td id=\"T_62619_row5_col6\" class=\"data row5 col6\" >10000</td>\n      <td id=\"T_62619_row5_col7\" class=\"data row5 col7\" >674</td>\n      <td id=\"T_62619_row5_col8\" class=\"data row5 col8\" >5</td>\n      <td id=\"T_62619_row5_col9\" class=\"data row5 col9\" >0.8176</td>\n      <td id=\"T_62619_row5_col10\" class=\"data row5 col10\" >13.6</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row6_col0\" class=\"data row6 col0\" >gr4j</td>\n      <td id=\"T_62619_row6_col1\" class=\"data row6 col1\" >nelder_mead</td>\n      <td id=\"T_62619_row6_col2\" class=\"data row6 col2\" >0.885911</td>\n      <td id=\"T_62619_row6_col3\" class=\"data row6 col3\" >0.885911</td>\n      <td id=\"T_62619_row6_col4\" class=\"data row6 col4\" >2.22e-16</td>\n      <td id=\"T_62619_row6_col5\" class=\"data row6 col5\" >2.22e-16</td>\n      <td id=\"T_62619_row6_col6\" class=\"data row6 col6\" >4784</td>\n      <td id=\"T_62619_row6_col7\" class=\"data row6 col7\" >342</td>\n      <td id=\"T_62619_row6_col8\" class=\"data row6 col8\" >5</td>\n      <td id=\"T_62619_row6_col9\" class=\"data row6 col9\" >0.8176</td>\n      <td id=\"T_62619_row6_col10\" class=\"data row6 col10\" >6.2</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row7_col0\" class=\"data row7 col0\" >hbv</td>\n      <td id=\"T_62619_row7_col1\" class=\"data row7 col1\" >sceua</td>\n      <td id=\"T_62619_row7_col2\" class=\"data row7 col2\" >0.919425</td>\n      <td id=\"T_62619_row7_col3\" class=\"data row7 col3\" >0.919385</td>\n      <td id=\"T_62619_row7_col4\" class=\"data row7 col4\" >1.12e-04</td>\n      <td id=\"T_62619_row7_col5\" class=\"data row7 col5\" >1.44e-04</td>\n      <td id=\"T_62619_row7_col6\" class=\"data row7 col6\" >12883</td>\n      <td id=\"T_62619_row7_col7\" class=\"data row7 col7\" >9501</td>\n      <td id=\"T_62619_row7_col8\" class=\"data row7 col8\" >1</td>\n      <td id=\"T_62619_row7_col9\" class=\"data row7 col9\" >0.8546</td>\n      <td id=\"T_62619_row7_col10\" class=\"data row7 col10\" >14.6</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row8_col0\" class=\"data row8 col0\" >hbv</td>\n      <td id=\"T_62619_row8_col1\" class=\"data row8 col1\" >de</td>\n      <td id=\"T_62619_row8_col2\" class=\"data row8 col2\" >0.919463</td>\n      <td id=\"T_62619_row8_col3\" class=\"data row8 col3\" >0.919383</td>\n      <td id=\"T_62619_row8_col4\" class=\"data row8 col4\" >1.04e-04</td>\n      <td id=\"T_62619_row8_col5\" class=\"data row8 col5\" >1.06e-04</td>\n      <td id=\"T_62619_row8_col6\" class=\"data row8 col6\" >20000</td>\n      <td id=\"T_62619_row8_col7\" class=\"data row8 col7\" >19039</td>\n      <td id=\"T_62619_row8_col8\" class=\"data row8 col8\" >1</td>\n      <td id=\"T_62619_row8_col9\" class=\"data row8 col9\" >0.8554</td>\n      <td id=\"T_62619_row8_col10\" class=\"data row8 col10\" >19.4</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row9_col0\" class=\"data row9 col0\" >hbv</td>\n      <td id=\"T_62619_row9_col1\" class=\"data row9 col1\" >cmaes</td>\n      <td id=\"T_62619_row9_col2\" class=\"data row9 col2\" >0.919567</td>\n      <td id=\"T_62619_row9_col3\" class=\"data row9 col3\" >0.919560</td>\n      <td id=\"T_62619_row9_col4\" class=\"data row9 col4\" >8.68e-06</td>\n      <td id=\"T_62619_row9_col5\" class=\"data row9 col5\" >1.35e-06</td>\n      <td id=\"T_62619_row9_col6\" class=\"data row9 col6\" >4510</td>\n      <td id=\"T_62619_row9_col7\" class=\"data row9 col7\" >2740</td>\n      <td id=\"T_62619_row9_col8\" class=\"data row9 col8\" >5</td>\n      <td id=\"T_62619_row9_col9\" class=\"data row9 col9\" >0.8553</td>\n      <td id=\"T_62619_row9_col10\" class=\"data row9 col10\" >4.9</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row10_col0\" class=\"data row10 col0\" >hbv</td>\n      <td id=\"T_62619_row10_col1\" class=\"data row10 col1\" >dds</td>\n      <td id=\"T_62619_row10_col2\" class=\"data row10 col2\" >0.918783</td>\n      <td id=\"T_62619_row10_col3\" class=\"data row10 col3\" >0.917873</td>\n      <td id=\"T_62619_row10_col4\" class=\"data row10 col4\" >1.64e-03</td>\n      <td id=\"T_62619_row10_col5\" class=\"data row10 col5\" >7.86e-04</td>\n      <td id=\"T_62619_row10_col6\" class=\"data row10 col6\" >20000</td>\n      <td id=\"T_62619_row10_col7\" class=\"data row10 col7\" >9474</td>\n      <td id=\"T_62619_row10_col8\" class=\"data row10 col8\" >1</td>\n      <td id=\"T_62619_row10_col9\" class=\"data row10 col9\" >0.8533</td>\n      <td id=\"T_62619_row10_col10\" class=\"data row10 col10\" >19.4</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row11_col0\" class=\"data row11 col0\" >hbv</td>\n      <td id=\"T_62619_row11_col1\" class=\"data row11 col1\" >pso</td>\n      <td id=\"T_62619_row11_col2\" class=\"data row11 col2\" >0.917371</td>\n      <td id=\"T_62619_row11_col3\" class=\"data row11 col3\" >0.916953</td>\n      <td id=\"T_62619_row11_col4\" class=\"data row11 col4\" >1.70e-03</td>\n      <td id=\"T_62619_row11_col5\" class=\"data row11 col5\" >2.20e-03</td>\n      <td id=\"T_62619_row11_col6\" class=\"data row11 col6\" >19980</td>\n      <td id=\"T_62619_row11_col7\" class=\"data row11 col7\" >nan</td>\n      <td id=\"T_62619_row11_col8\" class=\"data row11 col8\" >0</td>\n      <td id=\"T_62619_row11_col9\" class=\"data row11 col9\" >0.8548</td>\n      <td id=\"T_62619_row11_col10\" class=\"data row11 col10\" >18.7</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row12_col0\" class=\"data row12 col0\" >hbv</td>\n      <td id=\"T_62619_row12_col1\" class=\"data row12 col1\" >dual_annealing</td>\n      <td id=\"T_62619_row12_col2\" class=\"data row12 col2\" >0.919522</td>\n      <td id=\"T_62619_row12_col3\" class=\"data row12 col3\" >0.919422</td>\n      <td id=\"T_62619_row12_col4\" class=\"data row12 col4\" >1.32e-04</td>\n      <td id=\"T_62619_row12_col5\" class=\"data row12 col5\" >4.69e-05</td>\n      <td id=\"T_62619_row12_col6\" class=\"data row12 col6\" >20000</td>\n      <td id=\"T_62619_row12_col7\" class=\"data row12 col7\" >7377</td>\n      <td id=\"T_62619_row12_col8\" class=\"data row12 col8\" >4</td>\n      <td id=\"T_62619_row12_col9\" class=\"data row12 col9\" >0.8554</td>\n      <td id=\"T_62619_row12_col10\" class=\"data row12 col10\" >18.5</td>\n    </tr>\n    <tr>\n      <td id=\"T_62619_row13_col0\" class=\"data row13 col0\" >hbv</td>\n      <td id=\"T_62619_row13_col1\" class=\"data row13 col1\" >nelder_mead</td>\n      <td id=\"T_62619_row13_col2\" class=\"data row13 col2\" >0.919400</td>\n      <td id=\"T_62619_row13_col3\" class=\"data row13 col3\" >0.919110</td>\n      <td id=\"T_62619_row13_col4\" class=\"data row13 col4\" >4.29e-04</td>\n      <td id=\"T_62619_row13_col5\" class=\"data row13 col5\" >1.68e-04</td>\n      <td id=\"T_62619_row13_col6\" class=\"data row13 col6\" >20000</td>\n      <td id=\"T_62619_row13_col7\" class=\"data row13 col7\" >17745</td>\n      <td id=\"T_62619_row13_col8\" class=\"data row13 col8\" >1</td>\n      <td id=\"T_62619_row13_col9\" class=\"data row13 col9\" >0.8556</td>\n      <td id=\"T_62619_row13_col10\" class=\"data row13 col10\" >18.5</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n::: {#cell-fig-convergence .cell execution_count=7}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(11, 4.2))\ncols = dict(zip(ALGOS_A, plt.cm.tab10(np.linspace(0, 1, 10))))\nfor ax, m, xmax in zip(axes, [\"gr4j\", \"hbv\"], [10000, 20000]):\n    for a in ALGOS_A:\n        cs = [CURVES[f\"{m}|{a}|{s}\"] for s in SEEDS if f\"{m}|{a}|{s}\" in CURVES]\n        if not cs: continue\n        L = min(len(c) for c in cs); Mx = np.vstack([1 - c[:L] for c in cs])\n        x = np.arange(1, L + 1)\n        ax.plot(x, np.median(Mx, 0), color=cols[a], label=a, lw=1.6)\n        ax.fill_between(x, Mx.min(0), Mx.max(0), color=cols[a], alpha=0.15, lw=0)\n    ax.axhline(BEST[m], ls=\"--\", c=\"k\", lw=0.8)\n    ax.set_xscale(\"log\"); ax.set_xlim(20, xmax)\n    ax.set_ylim(BEST[m] - 0.02, BEST[m] + 0.002)\n    ax.set_xlabel(\"objective evaluations\"); ax.set_ylabel(r\"best-so-far $\\mathcal{O}$\")\n    ax.set_title(f\"{'GR4J (4 par)' if m=='gr4j' else 'HBV-light (9 par, thresholds)'}\")\naxes[0].legend(fontsize=7.5, loc=\"lower right\", ncol=2)\nplt.tight_layout(); plt.savefig(FIG / \"a10_convergence.png\", dpi=150, bbox_inches=\"tight\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Experiment A. Best-so-far objective versus number of objective evaluations; solid line = median over 5 seeds, band = min-max envelope. Left: GR4J (4 parameters). Right: HBV-light (9 parameters, threshold outlet). The dashed line is the best value found by any algorithm.](10_optimization_files/figure-html/fig-convergence-output-1.png){#fig-convergence width=1639 height=619}\n:::\n:::\n\n\n::: {#cell-fig-spread .cell execution_count=8}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(11, 4.2))\nax = axes[0]\norder = EA[EA.model == \"hbv\"].sort_values(\"O median\", ascending=False).algorithm.tolist()\nfor i, a in enumerate(order):\n    for m, mk, off in [(\"gr4j\", \"o\", -0.15), (\"hbv\", \"s\", 0.15)]:\n        d = A_[(A_.model == m) & (A_.algo == a)]\n        ax.scatter(BEST[m] - d.obj_train, np.full(len(d), i + off), marker=mk, s=18,\n                   color=\"tab:blue\" if m == \"gr4j\" else \"tab:red\",\n                   label=None if i else (\"GR4J\" if m == \"gr4j\" else \"HBV\"))\nax.axvspan(1e-9, 1e-4, color=\"grey\", alpha=0.25, label=\"within 1e-4\")\nax.set_yticks(range(len(order))); ax.set_yticklabels(order)\nax.set_xscale(\"log\"); ax.set_xlabel(r\"shortfall behind the best known $\\mathcal{O}$\")\nax.set_title(\"final objective per seed\"); ax.legend(fontsize=8)\nax = axes[1]\npc = [c for c in A_.columns if c.startswith(\"p_\") and \"decoy\" not in c]\nhb = A_[A_.model == \"hbv\"]\ncv = hb.groupby(\"algo\")[pc].agg(lambda x: np.std(x) / (np.abs(np.mean(x)) + 1e-12)).loc[order]\nim = ax.imshow(cv.to_numpy(), aspect=\"auto\", cmap=\"magma_r\", vmin=0, vmax=0.6)\nax.set_xticks(range(len(pc))); ax.set_xticklabels([c[2:] for c in pc], rotation=45, ha=\"right\")\nax.set_yticks(range(len(order))); ax.set_yticklabels(order)\nax.set_title(\"HBV: across-seed CV of the best parameter values\"); ax.grid(False)\nplt.colorbar(im, ax=ax, shrink=0.85)\nplt.tight_layout(); plt.savefig(FIG / \"a10_algorithm_spread.png\", dpi=150, bbox_inches=\"tight\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Experiment A. Left: final objective of each seed (points) around the algorithm median; the grey band is +/- 1e-4, the practical convergence tolerance. Right: equifinality — the across-seed coefficient of variation of each best parameter value for HBV-light, per algorithm.](10_optimization_files/figure-html/fig-spread-output-1.png){#fig-spread width=1610 height=620}\n:::\n:::\n\n\n**Reading of Experiment A.**\n\n* On **GR4J (4 parameters)** the problem is, in practice, *solved*: SCE-UA, DE, CMA-ES, dual\n  annealing and multi-start Nelder–Mead all land on the same optimum to better than $10^{-6}$\n  objective units, with **zero spread across seeds**. CMA-ES gets there in ≈ 900 evaluations,\n  SCE-UA in ≈ 3,500, DE in ≈ 5,000. Only PSO (default inertia/cognitive settings) misses, by\n  ≈ 0.002 with a seed spread of 0.002 — i.e. PSO is the one algorithm whose *tuning* would itself\n  need tuning.\n* On **HBV-light (9 parameters, threshold outlet)** the ranking separates: CMA-ES reaches the best\n  value with a seed spread of $9\\times10^{-6}$, followed by dual annealing, DE, SCE-UA and\n  multi-start Nelder–Mead; DDS and PSO fall short by 0.8–2.2 $\\times10^{-3}$. All differences are,\n  hydrologically, nothing — the worst algorithm is 0.002 objective units behind the best, while\n  a04 measured 0.02–0.06 units of regret between *objective functions* and 0.05–0.08 between\n  calibration periods. **Algorithm choice is a second-order effect; convergence bookkeeping is not.**\n* The right-hand panel shows the real story: parameter values scatter across seeds far more than the\n  objective does (equifinality). For the algorithms with the largest objective spread (DDS, PSO) the\n  parameter CV reaches 0.3–0.6 — the same objective is reached from very different parameter sets.\n  This is why a11–a15 must report the **across-seed parameter spread**, not only the best set.\n* Transfer to the internal-validation window is flat across algorithms (column *O validation*):\n  a better calibration objective did **not** buy a better out-of-sample objective beyond the\n  third decimal. Squeezing the last $10^{-4}$ out of the search is not where the score comes from.\n\n## Experiment B — how many SCE-UA complexes? {#sec-exp-b}\n\n::: {#tbl-expb .cell tbl-cap='Experiment B. SCE-UA on HBV-light (n = 9): effect of the number of complexes `ngs`. Budget cap 20,000 evaluations, 5 seeds.' execution_count=9}\n``` {.python .cell-code}\nBb = B[B.exp == \"B\"].copy()\nBb[\"ngs\"] = Bb.tag.str.replace(\"ngs=\", \"\").astype(int)\nEB = Bb.groupby(\"ngs\").agg(**{\"O median\": (\"obj_train\", \"median\"), \"O worst\": (\"obj_train\", \"min\"),\n                              \"seed spread\": (\"obj_train\", lambda x: x.max() - x.min()),\n                              \"evals (med)\": (\"n_eval\", \"median\"),\n                              \"wall s (med)\": (\"wall_s\", \"median\"),\n                              \"O validation\": (\"obj_valid\", \"median\")})\nEB[\"gap to best\"] = BEST[\"hbv\"] - EB[\"O median\"]\nEB.round(6)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>O median</th>\n      <th>O worst</th>\n      <th>seed spread</th>\n      <th>evals (med)</th>\n      <th>wall s (med)</th>\n      <th>O validation</th>\n      <th>gap to best</th>\n    </tr>\n    <tr>\n      <th>ngs</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>5</th>\n      <td>0.919439</td>\n      <td>0.919344</td>\n      <td>0.000210</td>\n      <td>5728.0</td>\n      <td>5.635737</td>\n      <td>0.854835</td>\n      <td>0.000130</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>0.919435</td>\n      <td>0.919370</td>\n      <td>0.000188</td>\n      <td>11156.0</td>\n      <td>10.975362</td>\n      <td>0.853872</td>\n      <td>0.000133</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>0.919425</td>\n      <td>0.919385</td>\n      <td>0.000112</td>\n      <td>12883.0</td>\n      <td>12.667183</td>\n      <td>0.854567</td>\n      <td>0.000144</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>0.919476</td>\n      <td>0.919407</td>\n      <td>0.000144</td>\n      <td>12806.0</td>\n      <td>12.466395</td>\n      <td>0.854802</td>\n      <td>0.000093</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Experiment C — does log-scaling the parameters help? {#sec-exp-c}\n\n::: {#tbl-expc .cell tbl-cap='Experiment C. Linear versus logarithmic mapping of the scale-like parameters (GR4J: x1, x3; HBV: FC, K0, K1, K2), 5 seeds. Positive `delta O (log - linear)` means the log map helps.' execution_count=10}\n``` {.python .cell-code}\nCc = B[B.exp == \"C\"]\nEC = (Cc.groupby([\"model\", \"algo\", \"tag\"])\n        .agg(**{\"O median\": (\"obj_train\", \"median\"), \"seed spread\": (\"obj_train\", lambda x: x.max() - x.min()),\n                \"evals (med)\": (\"n_eval\", \"median\")})\n        .reset_index())\npiv = EC.pivot_table(index=[\"model\", \"algo\"], columns=\"tag\", values=\"O median\")\npiv[\"delta O (log - linear)\"] = piv[\"log\"] - piv[\"linear\"]\nsp = EC.pivot_table(index=[\"model\", \"algo\"], columns=\"tag\", values=\"seed spread\")\npiv[\"seed spread linear\"] = sp[\"linear\"]; piv[\"seed spread log\"] = sp[\"log\"]\npiv.round(6)\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>tag</th>\n      <th>linear</th>\n      <th>log</th>\n      <th>delta O (log - linear)</th>\n      <th>seed spread linear</th>\n      <th>seed spread log</th>\n    </tr>\n    <tr>\n      <th>model</th>\n      <th>algo</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">gr4j</th>\n      <th>cmaes</th>\n      <td>0.885911</td>\n      <td>0.885911</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>de</th>\n      <td>0.885911</td>\n      <td>0.885911</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">hbv</th>\n      <th>cmaes</th>\n      <td>0.919567</td>\n      <td>0.919565</td>\n      <td>-0.000002</td>\n      <td>0.000009</td>\n      <td>0.000093</td>\n    </tr>\n    <tr>\n      <th>de</th>\n      <td>0.919463</td>\n      <td>0.919352</td>\n      <td>-0.000111</td>\n      <td>0.000104</td>\n      <td>0.000406</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Experiment D — cost of dimension (the slot-4 question) {#sec-exp-d}\n\n::: {#fig-dimension .cell execution_count=11}\n``` {.python .cell-code}\nDd = B[B.exp == \"D\"]\nED = Dd.groupby(\"algo\").agg(**{\"O median\": (\"obj_train\", \"median\"),\n                               \"worst\": (\"obj_train\", \"min\"),\n                               \"spread\": (\"obj_train\", lambda x: x.max() - x.min()),\n                               \"evals\": (\"n_eval\", \"median\")})\nbest15 = Dd.obj_train.max()\nEe = B[B.exp == \"E\"]\nfig, axes = plt.subplots(1, 2, figsize=(11, 4.0))\nax = axes[0]\no = ED.sort_values(\"O median\", ascending=False).index.tolist()\nax.barh(range(len(o)), [best15 - ED.loc[a, \"O median\"] for a in o], color=\"tab:blue\", alpha=0.6)\nfor i, a in enumerate(o):\n    d = Dd[Dd.algo == a]\n    ax.scatter(best15 - d.obj_train, np.full(len(d), i), color=\"k\", s=12, zorder=3)\nax.set_yticks(range(len(o))); ax.set_yticklabels(o); ax.invert_yaxis()\nax.set_xscale(\"symlog\", linthresh=1e-6)\nax.set_xlabel(r\"shortfall behind the best 15-d $\\mathcal{O}$\")\nax.set_title(\"Exp. D: 15 search dimensions, 30,000 evaluations\")\nax = axes[1]\nlbl, val = [], []\nfor m in [\"gr4j\", \"hbv\"]:\n    tgt = BEST[m] - 1e-3\n    for a in [\"nelder_mead\", \"powell\", \"lbfgsb\"]:\n        d = Ee[(Ee.model == m) & (Ee.algo == a)]\n        lbl.append(f\"{a}\\n{m}\"); val.append(100.0 * (d.obj_train >= tgt).mean())\nax.bar(range(len(val)), val, color=[\"tab:blue\"] * 3 + [\"tab:red\"] * 3, alpha=0.7)\nax.set_xticks(range(len(lbl))); ax.set_xticklabels(lbl, fontsize=7.5)\nax.set_ylabel(\"% of 15 random starts that found the optimum\"); ax.set_ylim(0, 105)\nax.set_title(\"Exp. E: single-start local search\")\nplt.tight_layout(); plt.savefig(FIG / \"a10_dimension.png\", dpi=150, bbox_inches=\"tight\"); plt.show()\nED.round(6)\n```\n\n::: {.cell-output .cell-output-display}\n![Left: Experiment D — the 9-parameter HBV surface inflated to 15 search dimensions with 6 inactive coordinates; points are the 5 seeds, bars the median shortfall behind the 9-d optimum. Right: Experiment E — 15 independent single-start local searches per method and model; a run counts as 'found' if it comes within 1e-3 objective units of the global best.](10_optimization_files/figure-html/fig-dimension-output-1.png){#fig-dimension-1 width=1639 height=589}\n:::\n\n::: {#fig-dimension-2 .cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>O median</th>\n      <th>worst</th>\n      <th>spread</th>\n      <th>evals</th>\n    </tr>\n    <tr>\n      <th>algo</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>cmaes</th>\n      <td>0.919568</td>\n      <td>0.919475</td>\n      <td>0.000093</td>\n      <td>7080.0</td>\n    </tr>\n    <tr>\n      <th>dds</th>\n      <td>0.918534</td>\n      <td>0.917311</td>\n      <td>0.002248</td>\n      <td>30000.0</td>\n    </tr>\n    <tr>\n      <th>de</th>\n      <td>0.919536</td>\n      <td>0.919511</td>\n      <td>0.000035</td>\n      <td>30000.0</td>\n    </tr>\n    <tr>\n      <th>sceua</th>\n      <td>0.919311</td>\n      <td>0.919270</td>\n      <td>0.000082</td>\n      <td>18716.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Experiment E — is local search enough? {#sec-exp-e}\n\n::: {#tbl-expe .cell tbl-cap='Experiment E. 15 independent single starts per method and model, 2,000 evaluations each. `success` = within 1e-3 objective units of the best known value.' execution_count=12}\n``` {.python .cell-code}\nrows = []\nfor m in [\"gr4j\", \"hbv\"]:\n    tgt = BEST[m] - 1e-3\n    for a in [\"nelder_mead\", \"powell\", \"lbfgsb\"]:\n        d = Ee[(Ee.model == m) & (Ee.algo == a)]\n        rows.append({\"model\": m, \"method\": a, \"success rate\": f\"{100*(d.obj_train>=tgt).mean():.0f} %\",\n                     \"median O\": d.obj_train.median(), \"worst O\": d.obj_train.min(),\n                     \"median evals\": d.n_eval.median()})\npd.DataFrame(rows).round(5).set_index([\"model\", \"method\"])\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>success rate</th>\n      <th>median O</th>\n      <th>worst O</th>\n      <th>median evals</th>\n    </tr>\n    <tr>\n      <th>model</th>\n      <th>method</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"3\" valign=\"top\">gr4j</th>\n      <th>nelder_mead</th>\n      <td>73 %</td>\n      <td>0.88591</td>\n      <td>0.79006</td>\n      <td>476.0</td>\n    </tr>\n    <tr>\n      <th>powell</th>\n      <td>93 %</td>\n      <td>0.88591</td>\n      <td>0.86827</td>\n      <td>998.0</td>\n    </tr>\n    <tr>\n      <th>lbfgsb</th>\n      <td>47 %</td>\n      <td>0.86827</td>\n      <td>0.83746</td>\n      <td>220.0</td>\n    </tr>\n    <tr>\n      <th rowspan=\"3\" valign=\"top\">hbv</th>\n      <th>nelder_mead</th>\n      <td>33 %</td>\n      <td>0.91654</td>\n      <td>0.90460</td>\n      <td>2000.0</td>\n    </tr>\n    <tr>\n      <th>powell</th>\n      <td>7 %</td>\n      <td>0.91600</td>\n      <td>0.90426</td>\n      <td>2000.0</td>\n    </tr>\n    <tr>\n      <th>lbfgsb</th>\n      <td>0 %</td>\n      <td>0.90406</td>\n      <td>0.74160</td>\n      <td>740.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe failure of single-start local search on the 9-parameter threshold surface — and in particular of\nfinite-difference **L-BFGS-B**, whose gradient is meaningless across the `UZL` switch — is the\nquantitative justification for the rule *\"derivative-free global search only for slots 3 and 4\"*.\nNote also that a 4-parameter GR4J is easy enough that even a local method usually succeeds; the\ndanger grows with dimension exactly as @arsenault2014 report for a 10-parameter conceptual model.\n\n## Slot 5: measured LSTM throughput {#sec-lstm-cost}\n\n::: {#tbl-lstm .cell tbl-cap='Measured training throughput of a generic sequence-to-sequence LSTM of the slot-5 shape (torch 2.13.0, device from src.common.data.torch_device()). One epoch = 39 minibatches of 256 windows drawn from the 10,592-day internal-train window + one full-window (13,515 d) inference pass for early stopping. a09/a15 own the real model; this only sizes the budget.' execution_count=13}\n``` {.python .cell-code}\ncache = FIG / \"a10_lstm_timing.json\"\nif cache.exists():\n    LT = json.load(open(cache))\nelse:\n    import torch, torch.nn as nn\n    dev = torch_device(); LT = {\"device\": dev, \"torch\": torch.__version__}\n    for (hid, lay, seq, bs, nin) in [(64, 1, 365, 256, 14), (128, 2, 365, 256, 14), (32, 1, 180, 128, 4)]:\n        torch.manual_seed(SEED)\n        lstm = nn.LSTM(nin, hid, num_layers=lay, batch_first=True,\n                       dropout=0.0 if lay == 1 else 0.4).to(dev)\n        head = nn.Linear(hid, 1).to(dev)\n        opt = torch.optim.AdamW(list(lstm.parameters()) + list(head.parameters()), lr=1e-3)\n        X = torch.randn(bs, seq, nin, device=dev); y = torch.randn(bs, seq, 1, device=dev)\n        nb = max(1, (int(TRAIN.sum()) - seq) // bs)\n        def step():\n            o, _ = lstm(X); l = ((head(o) - y) ** 2).mean()\n            opt.zero_grad(); l.backward(); opt.step()\n        for _ in range(3): step()\n        if dev == \"mps\": torch.mps.synchronize()\n        t0 = time.perf_counter()\n        for _ in range(10): step()\n        if dev == \"mps\": torch.mps.synchronize()\n        per_batch = (time.perf_counter() - t0) / 10\n        Xf = torch.randn(1, len(FRAME), nin, device=dev)\n        with torch.no_grad():\n            lstm(Xf)\n            if dev == \"mps\": torch.mps.synchronize()\n            t0 = time.perf_counter(); o, _ = lstm(Xf); head(o)\n            if dev == \"mps\": torch.mps.synchronize()\n            t_inf = time.perf_counter() - t0\n        npar = sum(p.numel() for p in lstm.parameters()) + sum(p.numel() for p in head.parameters())\n        LT[f\"hidden {hid}, {lay} layer(s), seq {seq}, batch {bs}, {nin} inputs\"] = {\n            \"weights\": npar, \"batches/epoch\": nb, \"s/epoch\": round(per_batch * nb + t_inf, 3),\n            \"min for 200 epochs\": round((per_batch * nb + t_inf) * 200 / 60, 2)}\n    json.dump(LT, open(cache, \"w\"), indent=1)\npd.DataFrame({k: v for k, v in LT.items() if isinstance(v, dict)}).T\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>weights</th>\n      <th>batches/epoch</th>\n      <th>s/epoch</th>\n      <th>min for 200 epochs</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>hidden 64, 1 layer(s), seq 365, batch 256, 14 inputs</th>\n      <td>20545.0</td>\n      <td>39.0</td>\n      <td>2.800</td>\n      <td>9.33</td>\n    </tr>\n    <tr>\n      <th>hidden 128, 2 layer(s), seq 365, batch 256, 14 inputs</th>\n      <td>205953.0</td>\n      <td>39.0</td>\n      <td>8.082</td>\n      <td>26.94</td>\n    </tr>\n    <tr>\n      <th>hidden 32, 1 layer(s), seq 180, batch 128, 4 inputs</th>\n      <td>4897.0</td>\n      <td>81.0</td>\n      <td>1.311</td>\n      <td>4.37</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#fig-budget .cell execution_count=14}\n``` {.python .cell-code}\nper_eval_ms = {1: float(COST.ms.iloc[-1]) if np.isfinite(COST.ms.iloc[-1]) else 25.4,\n               2: float(COST[COST.item.str.contains(\"runner evaluation, GR4J\")].ms.iloc[0]),\n               3: float(COST[COST.item.str.contains(\"runner evaluation, HBV\")].ms.iloc[0]),\n               4: 5.0}\ntot = {int(b[\"slot\"]): b.get(\"total_evaluations\", 0) for b in OCFG[\"per_model\"].values()}\nnames = {1: \"1 arx_api_ridge\", 2: \"2 gr4j\", 3: \"3 hbv_light\", 4: \"4 sacsma\", 5: \"5 lstm_seq2seq\"}\nh_worst = {s: tot[s] * per_eval_ms[s] / 3.6e6 for s in [1, 2, 3, 4]}\nh_worst[5] = OCFG[\"per_model\"][\"5_lstm_seq2seq\"][\"hard_limit_min\"] / 60\nh_exp = {s: OCFG[\"per_model\"][k][\"expected_wall_time_min\"] / 60\n         for k, b in OCFG[\"per_model\"].items() for s in [b[\"slot\"]]}\nfig, ax = plt.subplots(figsize=(8.5, 3.6))\nx = np.arange(5)\nax.bar(x - 0.2, [h_worst[s] for s in range(1, 6)], 0.38, label=\"worst case (budget cap, 1 core)\")\nax.bar(x + 0.2, [h_exp[s] for s in range(1, 6)], 0.38, label=\"expected (observed early stopping)\")\nax.axhline(3, ls=\"--\", c=\"crimson\"); ax.text(4.1, 3.08, \"3 h limit\", color=\"crimson\", fontsize=8)\nax.set_xticks(x); ax.set_xticklabels([names[s] for s in range(1, 6)], fontsize=8)\nax.set_ylabel(\"wall time [h]\"); ax.legend(fontsize=8); ax.set_title(\"Calibration budget per slot\")\nplt.tight_layout(); plt.savefig(FIG / \"a10_budget.png\", dpi=150, bbox_inches=\"tight\"); plt.show()\npd.DataFrame({\"per-eval ms\": {names[s]: per_eval_ms.get(s, np.nan) for s in range(1, 6)},\n              \"total evaluations\": {names[s]: tot.get(s, np.nan) for s in range(1, 6)},\n              \"worst-case h\": {names[s]: round(h_worst[s], 2) for s in range(1, 6)},\n              \"expected h\": {names[s]: round(h_exp[s], 2) for s in range(1, 6)}}).round(2)\n```\n\n::: {.cell-output .cell-output-display}\n![Wall-clock budget of the recommended recipes against the 3 h per-optimizer limit of config/project.yaml (dashed red). Slots 1-4 use the measured per-evaluation costs of @tbl-cost and the total evaluation counts of config/optimization.yaml; slot 5 uses the measured LSTM throughput (90 min hyperparameter cap + 5 members).](10_optimization_files/figure-html/fig-budget-output-1.png){#fig-budget-1 width=1265 height=529}\n:::\n\n::: {#fig-budget-2 .cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>per-eval ms</th>\n      <th>total evaluations</th>\n      <th>worst-case h</th>\n      <th>expected h</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1 arx_api_ridge</th>\n      <td>7.33</td>\n      <td>20000</td>\n      <td>0.04</td>\n      <td>0.15</td>\n    </tr>\n    <tr>\n      <th>2 gr4j</th>\n      <td>1.26</td>\n      <td>300000</td>\n      <td>0.10</td>\n      <td>0.12</td>\n    </tr>\n    <tr>\n      <th>3 hbv_light</th>\n      <td>0.86</td>\n      <td>500000</td>\n      <td>0.12</td>\n      <td>0.20</td>\n    </tr>\n    <tr>\n      <th>4 sacsma</th>\n      <td>5.00</td>\n      <td>1400000</td>\n      <td>1.94</td>\n      <td>1.50</td>\n    </tr>\n    <tr>\n      <th>5 lstm_seq2seq</th>\n      <td>NaN</td>\n      <td>0</td>\n      <td>3.00</td>\n      <td>1.67</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n# Recommendation per slot {#sec-reco}\n\nThe full machine-readable specification is `config/optimization.yaml`; this section gives the\nreasoning. In every slot the search happens on the **unit cube** and the bounds come from\n`config/models.yaml`.\n\n## Slot 1 — `arx_api_ridge` (7 hyperparameters + 21 closed-form coefficients)\n\n* **Algorithm: Optuna TPE** [@bergstra2011; @akiba2019], 256 Sobol' start-up trials + 744 TPE trials,\n  `multivariate=True`, × 5 seeds (42–46); **cross-check** with DE (3,000 evaluations) and the pure\n  Sobol' sample as a noise reference. TPE is chosen because the outer problem is *mixed*: six\n  continuous hyperparameters plus the integer `n_lag`, over which the objective is piecewise\n  constant — exactly the structure a density-ratio sampler handles and a Gaussian assumption does not.\n* **Inner estimator**: the ridge solve is closed form [@hoerl1970], so each trial costs one fit\n  (measured 25 ms) — 1,000 trials × 5 seeds ≈ 2 min.\n* **Windows**: coefficients on internal train, hyperparameters selected on internal validation\n  (a03/a04), then a **closed-form refit on the full calibration metric window** with the selected\n  hyperparameters. The refitted object is the artefact that goes to a16.\n* **Parsimony rule** (over-fitting guard, 7 hyperparameters selected on 2,557 days): among all\n  configurations within 0.002 objective units of the best validation score, take the one with the\n  smallest `n_lag` and the largest `log10_ridge_alpha`. Report train *and* validation objective; a\n  gap larger than 0.03 is a flag.\n* **Transforms**: `lam_slow` and `lam_pet` are sampled uniformly in $\\log(1-\\lambda)$ (i.e. uniform\n  in log memory $1/(1-\\lambda)$). Their bounds 0.95–0.999 and 0.80–0.999 correspond to memories of\n  20–1,000 d and 5–1,000 d; a uniform-in-$\\lambda$ sample would put half of its points in the\n  20–40 d band and explore the intended decade-wide range with a handful of trials.\n\n## Slot 2 — `gr4j` (4 parameters)\n\n* **Algorithm: SCE-UA**, `ngs = 2n+1 = 9`, `kstop = 10`, `pcento = 1e-4`, `peps = 1e-6`,\n  budget cap 30,000, **10 seeds** (42–51); **cross-check** CMA-ES and DE with the same cap;\n  finally a 2,000-evaluation Nelder–Mead polish from the overall best point.\n* **Why SCE-UA and not the (slightly faster) CMA-ES?** On this slot every global method finds the\n  same optimum (Exp. A), so speed is irrelevant — 10 SCE-UA seeds cost ≈ 45 s. SCE-UA was developed\n  by @duan1992 **on the Leaf River daily record** and is the method every reader of this basin's\n  literature expects; using it here and cross-checking with two structurally different algorithms is\n  the more defensible choice. The cross-check is what actually certifies convergence.\n* **Expected outcome**: seed spread $< 10^{-6}$, ≈ 100,000 evaluations in total, ≈ 7 min wall time.\n\n## Slot 3 — `hbv_light` (9 parameters, non-smooth)\n\n* **Algorithm: CMA-ES**, `sigma0 = 0.25` on the unit cube, default population\n  $4+\\lfloor 3\\ln d\\rfloor$, `tolfun = 1e-10`, cap 50,000, **10 seeds**; **cross-check** SCE-UA\n  (`ngs = 19`) and DE; Nelder–Mead polish.\n* **Why CMA-ES?** It won Experiment A on this exact structure — best median objective, the smallest\n  seed spread ($9\\times10^{-6}$) and the fewest evaluations (≈ 4,500 median). Its covariance\n  adaptation is what handles the strong `K1`–`PERC`–`UZL` interaction; the unit-cube mapping is what\n  makes a single step size legitimate across parameters spanning 0.0005–1,000 in raw units.\n* **Forbidden**: L-BFGS-B and any finite-difference gradient (Exp. E: 0 of 15 single starts succeeded\n  on this surface; @kavetski2007). **Transforms**: linear — Exp. C shows the log map buys nothing here.\n* **Watch**: a bound-active `K1` or `K2` at the optimum is a message about the bounds in\n  `config/models.yaml`, to be reported as an ISSUE, *not* silently widened.\n\n## Slot 4 — `sacsma` (15 parameters, non-smooth, integer sub-stepping)\n\n* **Algorithm: SCE-UA** with `ngs = 15`, cap 100,000 per seed, **10 seeds**; **cross-check** CMA-ES\n  (10 seeds, cap 60,000) and DDS (5 seeds, cap 60,000).\n* **Why this budget?** Experiment D inflates the same threshold surface from 9 to 15 search\n  dimensions: the evaluation count needed by CMA-ES and SCE-UA grows by roughly a factor 3, and no\n  algorithm needed more than ≈ 30,000 evaluations to stop improving. A 100,000 cap is therefore\n  ≈ 3× the measured requirement, and it still costs only ≈ 8 min per seed at 5 ms/evaluation.\n  @duan1994 recommend `ngs` of the order of $n$ for problems of this size, and @sorooshian1993\n  calibrated SAC-SMA on *this* record with SCE-UA. Experiment B confirms that the result is insensitive\n  to `ngs` (5, 10, 19 and 20 complexes agree to $5\\times10^{-5}$ on the 9-parameter surface; fewer\n  complexes simply stop earlier).\n* **Honest caveat**: in Experiment D it is *CMA-ES*, not SCE-UA, that reaches the best 15-dimensional\n  value (0.919568 in ≈ 7,100 evaluations versus 0.919311 for SCE-UA). SCE-UA is kept as the declared\n  primary for continuity with this basin's literature, but the two are treated as equal partners: step 7\n  of the protocol selects the best set over all seeds **and** all cross-check algorithms.\n* **DDS in the portfolio** because it is the method designed for a fixed, comparatively small\n  budget [@tolson2007] and it degrades most gracefully in dimension; it is the safety net if the real\n  SAC-SMA turns out to be 4× more expensive than estimated.\n* **Diagnostics**: report the KGE decomposition at the optimum, the across-seed spread of every\n  parameter (LZPK/LZFPM equifinality is expected), and the warm-up sensitivity check described in\n  `config/optimization.yaml` (a03 asks for 730 warm-up days; only 366 exist inside the calibration\n  window and only 92 before the evaluation metric window — see @sec-limits).\n\n## Slot 5 — `lstm_seq2seq` (10 hyperparameters + ≈ 20,500 weights)\n\n* **Inner**: AdamW [@loshchilov2019] with gradient-norm clipping at 1.0, the per-window NSE\\* loss of\n  @kratzert2019 with the first `warmup_steps` masked, learning-rate halving at epochs 60/120,\n  **early stopping with patience 20** on the composite objective of the *full* internal-validation\n  simulation [@prechelt1998] — never a per-minibatch efficiency (`config/metrics.yaml`).\n* **Outer**: Optuna TPE with `MedianPruner(n_startup_trials=5, n_warmup_steps=15, interval_steps=5)`,\n  **25 trials** (the a03 cap), ≤ 60 epochs per trial, and a **hard 90 min study timeout**.\n* **Final**: 5 members with seeds 42–46, ≤ 200 epochs each, per-member wall cap 20 min; the slot-5\n  prediction is their arithmetic mean (a03). No refit on the full calibration window — the validation\n  window is the only over-fitting guard (a03 decision).\n* **Budget arithmetic** (@tbl-lstm): the default architecture costs ≈ 1.8 s/epoch, so 200 epochs take\n  6 min; the largest admissible architecture (hidden 128, 2 layers) costs 5.9 s/epoch → 20 min.\n  Worst case 90 min (HP stage, capped) + 5 × 20 min (members) = 3.2 h, which is why the per-member\n  cap and the study timeout are *mandatory*, not advisory. Expected case ≈ 1.5 h.\n* If MPS results are not bit-reproducible between runs, fall back to CPU and record the deviation.\n\n# Parameter-space handling {#sec-space}\n\n**Unit cube.** Every algorithm searches $u\\in[0,1]^d$ and the runner maps $u\\mapsto x$. This is not\ncosmetic: CMA-ES uses a single step size $\\sigma$ for all coordinates and PSO a single velocity\nclamp, so a raw-space search over parameters spanning $0.0005$ to $1{,}500$ would be dominated by the\nlargest-range coordinate.\n\n**Log scaling.** Experiment C compared the linear map against a logarithmic map of the scale-like\nparameters. The rule adopted in `config/optimization.yaml` is:\n\n> log-scale a coordinate only if (i) its bounds span ≥ 1.5 decades **and** (ii) the model response is\n> approximately scale-invariant in it (rate constants, residence times, penalties) — **not** for\n> storage capacities whose lower bound is merely a numerical floor.\n\nThe second half of the rule matters for SAC-SMA: `LZFPM` is bounded 1–1,000 mm, but a lower zone of\n1–30 mm is physically absurd for a basin with ≈ 227 mm of plant-available storage (a01); a log map\nwould spend half of its samples there. Experiment C then settles the empirical question: the log map is **neutral** on GR4J (identical optimum\nto six decimals for both DE and CMA-ES) and, on HBV-light, neutral for CMA-ES but $1.1\\times10^{-4}$\n*worse* for DE. The declared default in `config/optimization.yaml` is therefore the **linear** map for\nslots 2, 3 and 4 — the rule above survives as the criterion a14 should use if it wants to test\n`{LZPK: log, LZSK: log}` as a variant, not as an unverified default. The one place where a transform is\nkept is slot 1, whose recession coefficients approach 1: `lam_slow` (0.95–0.999) and `lam_pet`\n(0.80–0.999) use the `log_memory` map, uniform in $\\log(1-\\lambda)$, because a uniform-in-$\\lambda$\nsample puts half of its points into the shortest 5 % of the intended memory range.\n\n**Integer parameters.** `n_lag` (slot 1), the LSTM's `hidden_size`, `n_layers`, `seq_len`,\n`warmup_steps`, `batch_size`, `use_antecedent_features` (slot 5) and SAC-SMA's internal `NINC` are\nrounded **inside the models** (a03), so the objective is piecewise constant along those coordinates.\nThree consequences, encoded in the config: never report an un-rounded integer as \"the optimum\";\nuse a genuine integer distribution (Optuna) where the inner fit is expensive; never let a local\npolish move along an integer coordinate.\n\n**Non-rectangular constraints** (HBV's $K_0\\ge K_1 > K_2$) are likewise enforced inside the model, so\nthe optimizer box stays rectangular — but a11–a15 must report raw *and* effective values, otherwise\nthe constraint becomes invisible and the reported `K2` may not be the `K2` the model used.\n\n# Convergence, non-convergence and reproducibility {#sec-convergence}\n\n**Practical tolerance: $\\Delta\\mathcal{O}=10^{-4}$.** Anything below that is hydrologically\nmeaningless: a04 measured 0.02–0.06 objective units of regret between *objective functions* and\nthis report measures 0.000–0.002 between *algorithms*. Optimising past $10^{-4}$ is not wrong, it is\nsimply not where the score is decided.\n\nA calibration counts as converged when **all four** hold:\n\n1. **seed spread** $\\max_k\\mathcal{O}^\\ast_k-\\min_k\\mathcal{O}^\\ast_k \\le 10^{-4}$ over the\n   independent seeds;\n2. **tail improvement** of the best-so-far over the last 20 % of the evaluations $< 10^{-5}$;\n3. the algorithm's **internal criterion** fired before the budget cap (SCE-UA `pcento`/`peps`,\n   DE `tol`, CMA-ES `tolfun`/`tolx`) — if the run stopped because it ran out of budget, it is\n   budget-limited by definition;\n4. a **second, structurally different algorithm** reproduces $\\mathcal{O}^\\ast$ within $10^{-4}$.\n\nFailure modes and the prescribed response:\n\n| Symptom | Diagnosis | Action |\n|---|---|---|\n| seed spread $> 10^{-4}$ | not converged | double `max_evals`, rerun the failing seeds; only then change algorithm |\n| tail improvement $\\ge 10^{-5}$ at the cap | budget-limited | raise the cap (it is cheap) |\n| best point on a bound | the box, not the search, is limiting | report it; raise an ISSUE against `config/models.yaml`; do **not** widen bounds unilaterally |\n| large parameter spread, identical $\\mathcal{O}$ | equifinality [@beven1992] | report the spread, keep the best set, spend nothing more |\n| many `n_failed` evaluations | model instability | report the count; investigate the model, not the optimizer |\n\n**Reproducibility contract.** `seed_k = 42 + k`: seeds 42–51 for the conceptual slots, 42–46 for the\ntrainable ones. Every stochastic component is seeded from that number\n(`scipy seed=`, `cma {'seed': seed+1}`, `spotpy random_state=`, `np.random.seed` for pyswarms,\n`default_rng(seed)` for DDS/local starts, `TPESampler(seed=)`, `torch.manual_seed`). Runs are\nindependent, so parallel (joblib over `LR_N_JOBS`) and sequential execution give identical numbers;\nworkers must run single-threaded (`OMP_NUM_THREADS=1`) because five agents share two cores.\nEach result records the library versions and the platform.\n\n# What every optimizer agent must save {#sec-artefacts}\n\nWritten by `runner.calibrate()` into `results/calibration/<model_id>/`:\n\n| File | Content |\n|---|---|\n| `trace_<stage>_seed<seed>.csv` | **every** evaluation: `eval, elapsed_s, cost, objective, best_so_far, <one column per parameter>` |\n| `best_<stage>_seed<seed>.json` | best parameters, best objective, `n_eval`, `n_failed`, `wall_s`, `s_per_eval`, `time_to_best_s`, convergence block, metrics on train / validation / full calibration incl. the five acceptance checks, the full settings block, environment and seed |\n| `summary_<stage>.csv` | one row per seed × algorithm |\n| `best.json` | **the** parameter set handed to a16, plus `seed_spread_objective` and `converged_across_seeds` |\n| `sim_calibration.csv` | `date, Q_sim, Q_obs` over the whole 13,515-day calibration run window — **required** for the ensemble weights (@sec-ensembles) |\n| `model_<model_id>.<ext>` | `model.save()` artefact (coefficients / weights / parameters + frozen scaling constants) |\n| `convergence_<model_id>.png` | best-so-far objective versus evaluations, all seeds |\n\n: Mandatory artefacts {#tbl-artefacts}\n\nMinimum reporting in each a11–a15 handoff: objective, KGE and NSE on the full calibration metric\nwindow **and** on the internal-validation window; the five acceptance checks of `config/metrics.yaml`\n(|PBIAS| ≤ 10 %, β ∈ [0.90,1.10], α ∈ [0.85,1.15], |FHV| ≤ 25 %, |ΔBFI| ≤ 0.15); evaluations, wall\ntime and across-seed spread; library versions; the seed list.\n\n# Protocol for a11–a15 {#sec-protocol}\n\n1. **Read** `config/optimization.yaml` (this agent), `config/models.yaml` (bounds), and\n   `config/metrics.yaml` (objective). Never hard-code a bound, a date or a metric.\n2. **Smoke test** the model: default parameters, one simulation, mass balance, and the measured cost\n   per evaluation. Record `s_per_eval`; if it is more than 2× the value in\n   `config/optimization.yaml`, re-scale the budget and say so.\n3. **Screening stage** (`--stage screen`): search with the recommended algorithm on the\n   *internal-train* window, 5 seeds. Report the objective on train **and** on internal validation.\n   This stage exists to detect over-fitting and optimizer pathologies; it does **not** produce the\n   delivered parameters.\n4. **Final stage** (`--stage final`): repeat the identical search with the objective on the **full\n   calibration metric window** (1952-10-01..1988-09-30, 13,149 d), 10 seeds for conceptual slots.\n   Run the cross-check algorithm(s) with the same budget and seeds.\n5. **Polish** (conceptual slots): Nelder–Mead, 2,000 evaluations, started from the best point of\n   step 4, integer coordinates held fixed. Keep the result only if it improves $\\mathcal{O}$.\n6. **Convergence check** (@sec-convergence). If it fails, act as in the table, then repeat step 4.\n7. **Select** the parameter set with the highest $\\mathcal{O}$ on the full calibration metric window\n   over all seeds and cross-check algorithms. **This set — and only this set — goes to a16.**\n   Write it to `best.json` and to the model artefact.\n8. **Report** the acceptance checks and the full metric block; flag every violation, never\n   \"correct\" for it.\n9. **Save** `sim_calibration.csv` (the ensembles need it) and the convergence figure.\n\nTrainable slots deviate exactly as a03/a04 prescribe: slot 1 fits coefficients on internal train,\nselects hyperparameters on internal validation and then **refits in closed form on the full\ncalibration metric window**; slot 5 fits on internal train, early-stops and selects on internal\nvalidation and is **not** refitted.\n\n# Ensembles: weights without touching the evaluation window {#sec-ensembles}\n\nThe five ensembles were pre-declared by a03 before any calibration result existed. Their weights are\nfixed as follows — every number comes from calibration data only:\n\n| Ensemble | Weights | Where they come from |\n|---|---|---|\n| `ens_mean_all5` | 0.2 each | fixed a priori, nothing fitted |\n| `ens_mean_conceptual` | 1/3 over slots 2,3,4 | fixed a priori |\n| `ens_physics_plus_ml` | 1/3 over slots 2,4,5 | fixed a priori |\n| `ens_nnls_calibration` | non-negative least squares | fitted on the **internal-validation window 1981-10-01..1988-09-30** (2,557 d) using the calibrated simulations of all five slots, then rescaled to sum 1 [@lawson1995] |\n| `ens_best_conceptual_plus_lstm` | [0.5, 0.5] | member = argmax KGE over slots 2,3,4 on the **full calibration metric window**; weights fixed a priori |\n\n: Ensemble weight protocol {#tbl-ensembles}\n\nMechanically: each of a11–a15 saves `sim_calibration.csv` over the whole calibration run window;\na16 assembles the $2{,}557\\times5$ matrix $A$ of simulations on 1981-10-01..1988-09-30, solves\n$\\min_{w\\ge 0}\\lVert Aw-y\\rVert_2$ with `scipy.optimize.nnls`, rescales $w$ to sum 1, stores the raw\nand rescaled weights together with the condition number of $A$ and the residual — and **freezes**\nthem before a single evaluation-window value is computed. Re-fitting or re-selecting any weight or\nmember after an evaluation number is known would invalidate the study (CLAUDE.md rule 3).\n\nNote the deliberate asymmetry: the NNLS weights use the validation window (2,557 d) so that they are\nnot fitted on the same days the conceptual slots were calibrated on, while the member *choice* of\n`ens_best_conceptual_plus_lstm` uses the full calibration window because it needs the most reliable\npossible ranking and only spends one bit of information.\n\n# The shared runner {#sec-runner}\n\n`src/optimization/runner.py` is the single entry point:\n\n```python\nfrom src.optimization.runner import calibrate, build_model, slot_settings\n\nres = calibrate(build_model(2), \"sceua\",\n                {**slot_settings(2, \"final\"), \"stage\": \"final\"}, seed=42)\nres[\"best_params\"], res[\"metrics\"][\"calibration\"][\"KGE\"], res[\"convergence\"]\n```\n\nor from the shell, in the `leafriver` environment, from the repository root:\n\n```bash\npython -m src.optimization.runner --slot 2 --seeds 42-51 --stage final\npython -m src.optimization.runner --slot 3 --algorithm cmaes --budget 50000 --stage screen\n```\n\nIt (i) loads data only through `src/common/data.py` and refuses to run with `LR_AGENT=a16`;\n(ii) maps every algorithm onto the unit cube with the configured per-parameter transform;\n(iii) traces every evaluation; (iv) maps non-finite costs to $10^6$; (v) enforces a hard evaluation\nbudget; (vi) scores the best set on internal train, internal validation and the full calibration\nwindow including the acceptance checks; and (vii) runs seeds in parallel and writes\n`summary_<stage>.csv` and `best.json`. Registered algorithms: `sceua, de, cmaes, dds, pso,\ndual_annealing, nelder_mead, lbfgsb, powell, optuna_tpe, sobol`.\n\n::: {#runner-demo .cell execution_count=15}\n``` {.python .cell-code code-fold=\"false\"}\ndemo = R.calibrate(SurrGR4J(), \"cmaes\",\n                   {\"max_evals\": 1200, \"score_window\": \"train\", \"stage\": \"demo\",\n                    \"out_dir\": str(FIG.parent / \"build\" / \"a10_demo\"), \"trace\": True},\n                   seed=42)\nprint(f\"O(train) {demo['metrics']['train']['objective']:.6f}   \"\n      f\"O(validation) {demo['metrics']['validation']['objective']:.6f}   \"\n      f\"KGE(cal) {demo['metrics']['calibration']['KGE']:.4f}   \"\n      f\"NSE(cal) {demo['metrics']['calibration']['NSE']:.4f}\")\nprint(f\"evaluations {demo['n_eval']}, wall {demo['wall_s']:.1f} s, \"\n      f\"tail improvement {demo['convergence']['improvement_tail']:.2e}, \"\n      f\"acceptance {demo['metrics']['calibration']['acceptance']['passes']}\")\nprint({k: round(v, 4) for k, v in demo[\"best_params\"].items()})\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nO(train) 0.885911   O(validation) 0.817573   KGE(cal) 0.9122   NSE(cal) 0.8511\nevaluations 904, wall 2.2 s, tail improvement 2.70e-11, acceptance True\n{'x1': 258.4901, 'x2': -0.8994, 'x3': 41.3321, 'x4': 3.5218}\n```\n:::\n:::\n\n\n`tests/test_runner.py` covers the transform round-trip (linear / log / log-memory), the budget guard,\nthe non-finite → $10^6$ mapping, the period masks (10,592 / 2,557 / 13,149 d), artefact writing,\ndeterminism under a fixed seed, the `LR_AGENT=a16` refusal and the completeness of\n`config/optimization.yaml`.\n\n# Limitations and open points {#sec-limits}\n\n* The benchmark uses **surrogates** of slots 2 and 3, not the deliverable models (a05–a09 were\n  building them concurrently). The surrogates follow the same equations and the same bounds, but a\n  small implementation difference could change the surface. Slot 4 (15 parameters) was extrapolated\n  from a *dimension-inflated* 9-parameter surface plus the literature [@duan1994; @arsenault2014];\n  a14 must verify the measured cost per evaluation and the seed spread against the numbers here, and\n  raise an ISSUE if either is off by more than a factor 2.\n* The benchmark measures the *internal-train* optimum. It cannot say which algorithm gives a better\n  **evaluation-period** score, and by construction nobody may find out before a16.\n* **Warm-up tension (slot 4)**: a03 asks for 730 warm-up days, but only 366 exist before the\n  calibration metric window and only 92 before the evaluation metric window. Nothing can be simulated\n  before 1951-10-01 without touching evaluation data. The prescribed handling is a *diagnostic*\n  (re-score the best set with the first 365 metric days dropped) and an ISSUE if the effect exceeds\n  0.005 objective units — not a change of the run window. Logged in `context/ISSUES.md`.\n* PSO was used with textbook settings (`w = 0.72`, `c1 = c2 = 1.5`). A tuned PSO would probably close\n  most of its 0.002 gap; it is not recommended here because an algorithm that needs tuning to match\n  an untuned competitor is the wrong tool for a five-slot comparison.\n* Uncertainty estimation (GLUE, DREAM) is deliberately out of scope: the study ranks deterministic\n  models. The equifinality shown in @fig-spread is the reason a13/a14 should *report* parameter\n  spread rather than claim a unique optimum.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "10_optimization_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}