{
  "hash": "76272c7ec56dfe8d381892113ed45f88",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Final evaluation on the held-out window: five calibrated models, five pre-declared ensembles, one winner\"\nsubtitle: \"Agent 16 (a16-evaluator) — phase P6\"\nauthor: \"a16-evaluator\"\ndate: 2026-09-16\njupyter: leafriver\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    fig-dpi: 150\n    tbl-cap-location: top\nbibliography: references.bib\n---\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport os, sys, json, warnings\nfrom pathlib import Path\n\nROOT = Path.cwd()\nwhile not (ROOT / \"config\" / \"project.yaml\").exists():\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT)); os.chdir(ROOT)\nos.environ[\"LR_AGENT\"] = \"a16\"          # this document IS agent 16\n\nimport numpy as np, pandas as pd, yaml\nimport matplotlib as mpl, matplotlib.pyplot as plt\nfrom IPython.display import Markdown, Image\nwarnings.filterwarnings(\"ignore\")\nmpl.rcParams.update({\"axes.grid\": True, \"grid.alpha\": 0.3, \"font.size\": 9})\n\nfrom src.common.data import load_data, load_config, slice_run, metric_mask, internal_mask\nfrom src.common.metrics import kge, nse, kge_components     # CANONICAL — never re-implemented\n\nEV   = ROOT / \"results\" / \"evaluation\"\nFIG  = ROOT / \"results\" / \"figures\"\nmet  = pd.read_csv(EV / \"metrics.csv\").set_index(\"id\")\nboot = pd.read_csv(EV / \"bootstrap.csv\").set_index(\"id\")\nblk  = pd.read_csv(EV / \"metrics_blocks.csv\")\nsel  = json.loads((EV / \"selection.json\").read_text())\nhyp  = json.loads((EV / \"hypotheses.json\").read_text())\nhypA = json.loads((EV / \"hypotheses_addendum.json\").read_text())\nwts  = json.loads((EV / \"ensemble_weights.json\").read_text())\ndiag = json.loads((EV / \"diagnostics.json\").read_text())\npw   = pd.read_csv(EV / \"paired_bootstrap_vs_winner.csv\").set_index(\"other\")\nsims = pd.read_parquet(EV / \"simulations.parquet\").set_index(\"date\")\n\nSLOT_ID = {1: \"arx_api_ridge\", 2: \"gr4j\", 3: \"hbv_light\", 4: \"sacsma\", 5: \"lstm_seq2seq_fast\"}\nLABEL = {\"arx_api_ridge\": \"1 · ARX-API ridge\", \"gr4j\": \"2 · GR4J\", \"hbv_light\": \"3 · HBV-light\",\n         \"sacsma\": \"4 · SAC-SMA\", \"lstm_seq2seq_fast\": \"5 · LSTM seq2seq (3 seeds)\",\n         \"ens_mean_all5\": \"E1 · ens_mean_all5\", \"ens_mean_conceptual\": \"E2 · ens_mean_conceptual\",\n         \"ens_physics_plus_ml\": \"E3 · ens_physics_plus_ml\",\n         \"ens_nnls_calibration\": \"E4 · ens_nnls_calibration\",\n         \"ens_best_conceptual_plus_lstm\": \"E5 · ens_best_conceptual_plus_lstm\"}\nCAND = list(LABEL)\nWIN = sel[\"best_model_id\"]\ndef f(x, n=4): return f\"{x:.{n}f}\"\ndef K(i): return float(met.loc[i, \"KGE\"])\ndef N(i): return float(met.loc[i, \"NSE\"])\n```\n:::\n\n\n# Executive summary {#sec-summary}\n\n``` {.python .cell-code}\nlo, hi = sel[\"KGE_95CI\"]; nlo, nhi = sel[\"NSE_95CI\"]\nbest_single = sel[\"best_single_model_id\"]\nspread_all = max(K(c) for c in CAND) - min(K(c) for c in CAND)\nMarkdown(f\"\"\"\n**Winner: `{WIN}` — KGE {f(sel['KGE'])} (95 % CI {f(lo,3)} … {f(hi,3)}),\nNSE {f(sel['NSE'])} (95 % CI {f(nlo,3)} … {f(nhi,3)})** on the evaluation metric window\n**1949-01-01 … 1951-09-30 ({sel['metric_days']} days)**, an equal-weight mean of all five\ncalibrated slots.\n\nThe margin is small and should not be oversold. `{sel['runner_up']}` has the *highest* KGE\n({f(sel['runner_up_KGE'])}), only {f(sel['top2_KGE_gap'])} above the winner, and the declared\ntie-break (§ @sec-rule) — top-2 KGE gap < 0.02 **and** paired-bootstrap\nP(top > second) = {f(sel['P_topKGE_better_than_second_KGE'],3)} < 0.8 — moved the decision to NSE, where\n`{WIN}` leads by {f(sel['NSE'] - sel['runner_up_NSE'])}. A paired 30-day moving-block bootstrap gives\nP(`{WIN}` better than `{sel['runner_up']}` in KGE) = {f(pw.loc[sel['runner_up'], 'P_winner_better_KGE'],3)}\n— i.e. **a coin flip**. For scale: the 95 % CI of the winner's own KGE is\n{f(hi - lo,3)} wide, about {int(round((hi - lo) / sel['top2_KGE_gap']))}× the gap it won by, and the whole\nfield of ten candidates spans only {f(spread_all,3)} KGE units.\n\nThe best **single** model on KGE is `{best_single}` ({f(sel['best_single_model_KGE'])}); the best single\nmodel on **NSE** is `arx_api_ridge` ({f(N('arx_api_ridge'))}), which is also the highest NSE of any\ncandidate, ensembles included. The worst single model is the LSTM\n(KGE {f(K('lstm_seq2seq_fast'))}) — the model that had been the best on calibration.\n\nPre-registered hypothesis **H1 is falsified in its first clause**: the 19-coefficient ARX-API ridge\nregression does not sit at the bottom of the complexity gradient, it reaches\nNSE {f(hyp['H1']['NSE_slot1'])} against GR4J's {f(hyp['H1']['NSE_slot2'])} and SAC-SMA's\n{f(hyp['H1']['NSE_slot4'])}. Details and the other seven hypotheses in @sec-hypotheses.\n\"\"\")\n```\n\n**Winner: `ens_mean_all5` — KGE 0.9018 (95 % CI 0.811 … 0.944),\nNSE 0.8932 (95 % CI 0.856 … 0.950)** on the evaluation metric window\n**1949-01-01 … 1951-09-30 (1003 days)**, an equal-weight mean of all five\ncalibrated slots.\n\nThe margin is small and should not be oversold. `ens_mean_conceptual` has the *highest* KGE\n(0.9058), only 0.0040 above the winner, and the declared\ntie-break (§ @sec-rule) — top-2 KGE gap < 0.02 **and** paired-bootstrap\nP(top > second) = 0.339 < 0.8 — moved the decision to NSE, where\n`ens_mean_all5` leads by 0.0294. A paired 30-day moving-block bootstrap gives\nP(`ens_mean_all5` better than `ens_mean_conceptual` in KGE) = 0.661\n— i.e. **a coin flip**. For scale: the 95 % CI of the winner's own KGE is\n0.133 wide, about 33× the gap it won by, and the whole\nfield of ten candidates spans only 0.109 KGE units.\n\nThe best **single** model on KGE is `gr4j` (0.8941); the best single\nmodel on **NSE** is `arx_api_ridge` (0.9183), which is also the highest NSE of any\ncandidate, ensembles included. The worst single model is the LSTM\n(KGE 0.7971) — the model that had been the best on calibration.\n\nPre-registered hypothesis **H1 is falsified in its first clause**: the 19-coefficient ARX-API ridge\nregression does not sit at the bottom of the complexity gradient, it reaches\nNSE 0.9183 against GR4J's 0.8287 and SAC-SMA's\n0.8635. Details and the other seven hypotheses in @sec-hypotheses.\n\n\n\n# Protocol {#sec-protocol}\n\n## Periods\n\n::: {#tbl-periods .cell tbl-cap='Windows actually used, read live from config/project.yaml (periods.definition = dates, ISSUE-001 resolved). Row indices are 0-based half-open positions in data/raw/LeafRiverDaily.txt.' execution_count=3}\n``` {.python .cell-code}\ndf = load_data()\nev = slice_run(df, \"evaluation\", allow_evaluation=True)\nm_ev = metric_mask(ev, \"evaluation\")\ncal = slice_run(df, \"calibration\"); m_cal = metric_mask(cal, \"calibration\")\nm_val = internal_mask(cal, \"validation\")\nassert len(ev) == 1095 and int(m_ev.sum()) == 1003\nrows = [\n (\"evaluation run (all models simulated here)\", ev.index[0], ev.index[-1], len(ev), \"0:1095\"),\n (\"evaluation warm-up (discarded)\", ev.index[0], ev.index[~m_ev][-1], int((~m_ev).sum()), \"0:92\"),\n (\"EVALUATION METRIC (every score below)\", ev.index[m_ev][0], ev.index[m_ev][-1], int(m_ev.sum()), \"92:1095\"),\n (\"calibration metric (reference only)\", cal.index[m_cal][0], cal.index[m_cal][-1], int(m_cal.sum()), \"1461:14610\"),\n (\"calibration internal validation (ensemble weights)\", cal.index[m_val][0], cal.index[m_val][-1], int(m_val.sum()), \"12053:14610\"),\n]\npd.DataFrame(rows, columns=[\"window\", \"start\", \"end\", \"days\", \"raw rows\"]).assign(\n    start=lambda d: d[\"start\"].dt.date.astype(str), end=lambda d: d[\"end\"].dt.date.astype(str)\n).set_index(\"window\")\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>start</th>\n      <th>end</th>\n      <th>days</th>\n      <th>raw rows</th>\n    </tr>\n    <tr>\n      <th>window</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>evaluation run (all models simulated here)</th>\n      <td>1948-10-01</td>\n      <td>1951-09-30</td>\n      <td>1095</td>\n      <td>0:1095</td>\n    </tr>\n    <tr>\n      <th>evaluation warm-up (discarded)</th>\n      <td>1948-10-01</td>\n      <td>1948-12-31</td>\n      <td>92</td>\n      <td>0:92</td>\n    </tr>\n    <tr>\n      <th>EVALUATION METRIC (every score below)</th>\n      <td>1949-01-01</td>\n      <td>1951-09-30</td>\n      <td>1003</td>\n      <td>92:1095</td>\n    </tr>\n    <tr>\n      <th>calibration metric (reference only)</th>\n      <td>1952-10-01</td>\n      <td>1988-09-30</td>\n      <td>13149</td>\n      <td>1461:14610</td>\n    </tr>\n    <tr>\n      <th>calibration internal validation (ensemble weights)</th>\n      <td>1981-10-01</td>\n      <td>1988-09-30</td>\n      <td>2557</td>\n      <td>12053:14610</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEvery model was run **once**, continuously, over the 1,095-day evaluation run window with its final\ncalibrated parameters and its own parameter-derived initial states (a03 decision 3). The first 92 days\n(Oct–Dec 1948) are warm-up and enter no metric. There was **no re-calibration, no parameter tweak and no\nmodel change** after the evaluation observations were read; the pipeline\n(`results/evaluation/run_evaluation.py`) was executed once in its final form, and the two edits made to\nit before the final run (a wrong `aux` accessor for slot 4, a wrong `runner_up` field, and a corrected\nparameter count for slot 5) are bookkeeping, not scoring.\n\nSAC-SMA (slot 4) runs with its **cyclic warm-up spin-up** active (ISSUE-005). On the evaluation window\nits 92 warm-up days were replayed **9\ntimes** (residual 0\\.00)\nusing **P and PET only**, never observed Q, before the run window started. The calibration window needed\n6 cycles. This is by design and was not\ndisabled.\n\n## Metrics\n\nOnly two metrics are reported, both taken verbatim from `src/common/metrics.py`\n[@gupta2009; @nash1970]:\n\n$$\\mathrm{KGE} = 1 - \\sqrt{(r-1)^2 + (\\alpha-1)^2 + (\\beta-1)^2},\\qquad\n\\alpha = \\frac{\\sigma_s}{\\sigma_o},\\quad \\beta = \\frac{\\mu_s}{\\mu_o}$$\n\n$$\\mathrm{NSE} = 1 - \\frac{\\sum_t (s_t-o_t)^2}{\\sum_t (o_t-\\bar o)^2}$$\n\n`config/project.yaml → evaluation_protocol.final_report_metrics_only: true`, so **KGE and NSE are the only\nperformance metrics in this report**. The KGE components $r$, $\\alpha$, $\\beta$ appear once, in\n@sec-hypotheses, because hypothesis **H5 is stated in terms of $\\alpha$ and $\\beta$** and cannot be\nadjudicated without them; they are not used to rank anything. Likewise the sub-period and log-space\nfigures in H2/H3 are the pre-registered test statistics of those hypotheses, not performance claims.\n\n## Uncertainty\n\n95 % confidence intervals come from a **moving-block bootstrap** [@kunsch1989; @politis1994; @efron1994]:\n30-day blocks, 2,000 resamples, `numpy.random.default_rng(42)`, block starts drawn uniformly from the\n1,003-day metric window and concatenated to length 1,003. The *same* 2,000 index matrices are applied to\nevery candidate, so differences between models are **paired** and their bootstrap distribution is a\nlegitimate significance statement about the ranking. A 30-day block comfortably exceeds the basin's\n9–11 day recession time scale (a01/a02), so within-block serial correlation is preserved.\n\n## Selection rule (declared before the numbers were looked at) {#sec-rule}\n\nVerbatim from `.claude/skills/a16-evaluator/SKILL.md` § Step 4:\n\n1. Primary: highest **KGE** on the evaluation metric window.\n2. If the top-2 KGE difference < 0.02 **and** paired-bootstrap P(top > second) < 0.8 → tie-break by\n   highest **NSE**; if still tied, prefer fewer fitted quantities (parsimony).\n3. Disqualify a model that produced NaN or negative flows — report it anyway.\n\n``` {.python .cell-code}\ndq = sel[\"disqualified_nan_or_negative\"]\nMarkdown(f\"**Applied:** {sel['rule_applied']}  \\n\"\n         f\"**Rule 3:** {'no candidate produced a NaN or a negative flow' if not dq else 'disqualified: ' + ', '.join(dq)} \"\n         f\"(minimum simulated flow over all ten candidates: \"\n         f\"{f(met.loc[CAND,'min_sim'].min(),4)} mm/d, at `{met.loc[CAND,'min_sim'].idxmin()}`).\")\n```\n**Applied:** Rule 2 applied: top-2 KGE gap 0.0040 < 0.02 AND P(top>second | paired block bootstrap) = 0.339 < 0.8 -> tie-break on NSE.  \n**Rule 3:** no candidate produced a NaN or a negative flow (minimum simulated flow over all ten candidates: 0.0222 mm/d, at `sacsma`).\n\n\n## Ensembles: where every weight came from {#sec-weights}\n\nThis is the single largest leakage risk in the study, so it is documented exhaustively. All five\nensembles were built and frozen by `results/evaluation/freeze_weights.py` **before**\n`run_evaluation.py` was ever executed, and the freeze was committed as git tag\n`backup/a16-evaluator-20260916-171945`. The script imports `slice_run(df, \"calibration\")` only; no\nevaluation row, observation or simulation enters `results/evaluation/ensemble_weights.json`.\n\n::: {#tbl-weights .cell tbl-cap='The five pre-declared ensembles (config/models.yaml -> ensembles) with the rows their weights came from.' execution_count=5}\n``` {.python .cell-code}\nrows = []\nfor eid, e in wts[\"ensembles\"].items():\n    rows.append({\"ensemble\": eid,\n                 \"members (slots)\": \" + \".join(str(m) for m in e[\"members\"]),\n                 \"weights\": \", \".join(f\"{w:.3f}\" for w in e[\"weights\"]),\n                 \"weight source\": e[\"weight_source\"]})\npd.DataFrame(rows).set_index(\"ensemble\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>members (slots)</th>\n      <th>weights</th>\n      <th>weight source</th>\n    </tr>\n    <tr>\n      <th>ensemble</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>ens_mean_all5</th>\n      <td>1 + 2 + 3 + 4 + 5</td>\n      <td>0.200, 0.200, 0.200, 0.200, 0.200</td>\n      <td>pre-declared equal weights (config/models.yaml)</td>\n    </tr>\n    <tr>\n      <th>ens_mean_conceptual</th>\n      <td>2 + 3 + 4</td>\n      <td>0.333, 0.333, 0.333</td>\n      <td>pre-declared equal weights (config/models.yaml)</td>\n    </tr>\n    <tr>\n      <th>ens_physics_plus_ml</th>\n      <td>2 + 4 + 5</td>\n      <td>0.333, 0.333, 0.333</td>\n      <td>pre-declared equal weights (config/models.yaml)</td>\n    </tr>\n    <tr>\n      <th>ens_nnls_calibration</th>\n      <td>1 + 2 + 3 + 4 + 5</td>\n      <td>0.169, 0.000, 0.312, 0.000, 0.519</td>\n      <td>scipy.optimize.nnls on calibration_internal.va...</td>\n    </tr>\n    <tr>\n      <th>ens_best_conceptual_plus_lstm</th>\n      <td>4 + 5</td>\n      <td>0.500, 0.500</td>\n      <td>pre-declared 0.5/0.5; conceptual member = argm...</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n* **E1–E3** carry weights that were fixed *a priori* in `config/models.yaml` by a03 (equal weights); no\n  data of any kind was used to set them.\n* **E4 `ens_nnls_calibration`** is the only ensemble with *fitted* weights. `scipy.optimize.nnls`\n  [@lawson1995] was run on the member simulations over\n  **calibration\\_internal\\.validation 1981\\-10\\-01\\.\\.1988\\-09\\-30** — raw file rows\n  12053:14610,\n  2557 days — the calibration internal-validation block prescribed by a04.\n  Raw coefficients\n  0\\.1640\\, 0\\.0000\\, 0\\.3026\\, 0\\.0000\\, 0\\.5029\n  (slots 1…5) sum to 0\\.9695 and were rescaled to sum 1 as the\n  specification requires. NNLS drove slots 2 and 4 to exactly zero: the fitted ensemble is\n  **17 % ridge + 31 % HBV-light + 52 % LSTM**. This is stacking in the sense of @breiman1996 and it is\n  the classical place where an ensemble over-fits its fitting window — see H6.\n* **E5 `ens_best_conceptual_plus_lstm`** needed a *member choice*. The specification says\n  “argmax KGE over slots 2, 3, 4 on the calibration metric window”. Those KGEs are\n  slot 2 0\\.9139\\, slot 3 0\\.9445\\, slot 4 0\\.9500\n  → **slot 4 (SAC-SMA)**, chosen from calibration data alone.\n\n## Calibration reproducibility check {#sec-repro-check}\n\nBefore any evaluation simulation, each slot was re-run over the full calibration window with the\nparameters in `results/calibration/<model_id>/best.json` and compared with the optimizer's own stored\nsimulation and metrics.\n\n::: {#tbl-repro .cell tbl-cap='Step-1 precondition: every slot reproduces its stored calibration simulation and its stored KGE/NSE. Max |difference| is over the 13,515-day calibration run window.' execution_count=6}\n``` {.python .cell-code}\nrep = pd.DataFrame([\n (\"1 arx_api_ridge\", \"optuna_tpe / 48\", 1.42e-14, 0.9097694993, 0.8209703239),\n (\"2 gr4j\",          \"sceua / 43\",      7.11e-15, 0.9138580212, 0.8557921600),\n (\"3 hbv_light\",     \"cmaes / 49\",      3.55e-15, 0.9445209913, 0.8930725037),\n (\"4 sacsma\",        \"sceua / 42\",      3.55e-15, 0.9499605552, 0.9016840016),\n (\"5 lstm_seq2seq_fast\", \"a15b TPE / 42,43,44\", 3.55e-15, 0.9257933340, 0.9510177262),\n], columns=[\"slot\", \"algorithm / seed\", \"max |Δ Q_sim| (mm/d)\", \"KGE_cal reproduced\", \"NSE_cal reproduced\"])\nrep.set_index(\"slot\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>algorithm / seed</th>\n      <th>max |Δ Q_sim| (mm/d)</th>\n      <th>KGE_cal reproduced</th>\n      <th>NSE_cal reproduced</th>\n    </tr>\n    <tr>\n      <th>slot</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1 arx_api_ridge</th>\n      <td>optuna_tpe / 48</td>\n      <td>1.420000e-14</td>\n      <td>0.909769</td>\n      <td>0.820970</td>\n    </tr>\n    <tr>\n      <th>2 gr4j</th>\n      <td>sceua / 43</td>\n      <td>7.110000e-15</td>\n      <td>0.913858</td>\n      <td>0.855792</td>\n    </tr>\n    <tr>\n      <th>3 hbv_light</th>\n      <td>cmaes / 49</td>\n      <td>3.550000e-15</td>\n      <td>0.944521</td>\n      <td>0.893073</td>\n    </tr>\n    <tr>\n      <th>4 sacsma</th>\n      <td>sceua / 42</td>\n      <td>3.550000e-15</td>\n      <td>0.949961</td>\n      <td>0.901684</td>\n    </tr>\n    <tr>\n      <th>5 lstm_seq2seq_fast</th>\n      <td>a15b TPE / 42,43,44</td>\n      <td>3.550000e-15</td>\n      <td>0.925793</td>\n      <td>0.951018</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAll five agree with the stored values far inside the 1e-9 tolerance the skill demands (reproduced KGE and\nNSE are bit-identical to the ones in `best.json` at 10 decimals). Slot 5's frozen artefact\n`model_5_fast_ensemble.pt` was restored with `Model5().load()`, which also restores a02's frozen scaling\nconstants; nothing was refitted and no scaling statistic was recomputed at predict time.\n\nTwo protocol notes, both decided **before** the evaluation numbers were seen:\n\n* **Slot 1** is `kind: trainable`. The artefact handed over by the calibration phase fits the closed-form\n  ridge coefficients on `calibration_internal.train` (1952-10-01…1981-09-30) and reports the resulting\n  calibration-window scores; that is what `best.json` contains and what is used as the headline slot-1\n  model here. a03's `fit_protocol.final_refit` prescribes an additional refit on the full calibration\n  metric window; that variant was also evaluated and is reported as a **sensitivity row only**\n  (`arx_api_ridge_refit_metricwindow`), never in the ranking.\n* **Slot 5** uses a15b's budgeted 3-seed ensemble. The full a15 run (pid 31743) had been executing for\n  6 h 49 min at evaluation time and had written no artefact; it was not waited for. a15b's own handoff\n  states its score is a **lower bound** for the LSTM slot.\n\n# Main results {#sec-results}\n\n::: {#tbl-main .cell tbl-cap='THE RESULT. Evaluation metric window 1949-01-01..1951-09-30, 1,003 days. Sorted by KGE (primary selection metric). 95 % CI from a 30-day moving-block bootstrap (2,000 resamples, seed 42). cal KGE / cal NSE are on the calibration metric window 1952-10-01..1988-09-30 (13,149 d) and are quoted only so that the degradation can be read off.' execution_count=7}\n``` {.python .cell-code}\nt = met.loc[CAND].copy()\nt[\"model\"] = [LABEL[i] for i in t.index]\nt[\"KGE 95 % CI\"] = [f\"[{boot.loc[i,'KGE_lo']:.3f}, {boot.loc[i,'KGE_hi']:.3f}]\" for i in t.index]\nt[\"NSE 95 % CI\"] = [f\"[{boot.loc[i,'NSE_lo']:.3f}, {boot.loc[i,'NSE_hi']:.3f}]\" for i in t.index]\nout = (t.reset_index()[[\"model\", \"n_fitted\", \"KGE\", \"KGE 95 % CI\", \"NSE\", \"NSE 95 % CI\",\n                        \"KGE_cal\", \"NSE_cal\"]]\n       .rename(columns={\"n_fitted\": \"# fitted quantities\", \"KGE_cal\": \"cal KGE\", \"NSE_cal\": \"cal NSE\"})\n       .sort_values(\"KGE\", ascending=False).round(4).set_index(\"model\"))\nout\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th># fitted quantities</th>\n      <th>KGE</th>\n      <th>KGE 95 % CI</th>\n      <th>NSE</th>\n      <th>NSE 95 % CI</th>\n      <th>cal KGE</th>\n      <th>cal NSE</th>\n    </tr>\n    <tr>\n      <th>model</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>E2 · ens_mean_conceptual</th>\n      <td>28.0</td>\n      <td>0.9058</td>\n      <td>[0.786, 0.943]</td>\n      <td>0.8638</td>\n      <td>[0.818, 0.928]</td>\n      <td>0.9428</td>\n      <td>0.9078</td>\n    </tr>\n    <tr>\n      <th>E1 · ens_mean_all5</th>\n      <td>30855.0</td>\n      <td>0.9018</td>\n      <td>[0.811, 0.944]</td>\n      <td>0.8932</td>\n      <td>[0.856, 0.950]</td>\n      <td>0.9430</td>\n      <td>0.9318</td>\n    </tr>\n    <tr>\n      <th>2 · GR4J</th>\n      <td>4.0</td>\n      <td>0.8941</td>\n      <td>[0.781, 0.932]</td>\n      <td>0.8287</td>\n      <td>[0.771, 0.877]</td>\n      <td>0.9139</td>\n      <td>0.8558</td>\n    </tr>\n    <tr>\n      <th>1 · ARX-API ridge</th>\n      <td>26.0</td>\n      <td>0.8893</td>\n      <td>[0.829, 0.936]</td>\n      <td>0.9183</td>\n      <td>[0.878, 0.949]</td>\n      <td>0.9098</td>\n      <td>0.8210</td>\n    </tr>\n    <tr>\n      <th>E3 · ens_physics_plus_ml</th>\n      <td>30820.0</td>\n      <td>0.8890</td>\n      <td>[0.780, 0.940]</td>\n      <td>0.8790</td>\n      <td>[0.836, 0.937]</td>\n      <td>0.9376</td>\n      <td>0.9311</td>\n    </tr>\n    <tr>\n      <th>3 · HBV-light</th>\n      <td>9.0</td>\n      <td>0.8822</td>\n      <td>[0.721, 0.930]</td>\n      <td>0.8290</td>\n      <td>[0.772, 0.925]</td>\n      <td>0.9445</td>\n      <td>0.8931</td>\n    </tr>\n    <tr>\n      <th>4 · SAC-SMA</th>\n      <td>15.0</td>\n      <td>0.8753</td>\n      <td>[0.748, 0.940]</td>\n      <td>0.8635</td>\n      <td>[0.811, 0.923]</td>\n      <td>0.9500</td>\n      <td>0.9017</td>\n    </tr>\n    <tr>\n      <th>E4 · ens_nnls_calibration</th>\n      <td>30855.0</td>\n      <td>0.8681</td>\n      <td>[0.757, 0.925]</td>\n      <td>0.8819</td>\n      <td>[0.835, 0.949]</td>\n      <td>0.9398</td>\n      <td>0.9479</td>\n    </tr>\n    <tr>\n      <th>E5 · ens_best_conceptual_plus_lstm</th>\n      <td>30816.0</td>\n      <td>0.8422</td>\n      <td>[0.705, 0.926]</td>\n      <td>0.8721</td>\n      <td>[0.819, 0.938]</td>\n      <td>0.9466</td>\n      <td>0.9420</td>\n    </tr>\n    <tr>\n      <th>5 · LSTM seq2seq (3 seeds)</th>\n      <td>30801.0</td>\n      <td>0.7971</td>\n      <td>[0.635, 0.913]</td>\n      <td>0.8460</td>\n      <td>[0.759, 0.930]</td>\n      <td>0.9258</td>\n      <td>0.9510</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-bench .cell tbl-cap='Context benchmarks on the SAME evaluation metric window. The first two are built from calibration-period observations only. The third uses yesterday\\'s observed flow and is therefore not a rainfall-runoff model at all - it is the bar a04 said any useful model must clear.' execution_count=8}\n``` {.python .cell-code}\nb = met.loc[[\"bench_mean_calibration_flow\", \"bench_doy_climatology_cal\", \"bench_persistence_1day\"],\n            [\"KGE\", \"NSE\"]].round(4)\nb.index = [\"mean calibration flow (1.353 mm/d)\", \"day-of-year climatology of calibration\",\n           \"one-day persistence (uses observed Q)\"]\nb\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>KGE</th>\n      <th>NSE</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>mean calibration flow (1.353 mm/d)</th>\n      <td>-0.4322</td>\n      <td>-0.0118</td>\n    </tr>\n    <tr>\n      <th>day-of-year climatology of calibration</th>\n      <td>0.0580</td>\n      <td>0.1395</td>\n    </tr>\n    <tr>\n      <th>one-day persistence (uses observed Q)</th>\n      <td>0.8646</td>\n      <td>0.7293</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n``` {.python .cell-code}\nMarkdown(f\"\"\"\nEvery one of the ten candidates beats the mean-flow benchmark\n(KGE {f(K('bench_mean_calibration_flow'),3)}, the Knoben et al. [-@knoben2019] reference) and the\nday-of-year climatology (KGE {f(K('bench_doy_climatology_cal'),3)}) by a wide margin. Eight of the ten\nalso beat one-day persistence on KGE ({f(K('bench_persistence_1day'),3)}) — the two that do not are\n`ens_best_conceptual_plus_lstm` ({f(K('ens_best_conceptual_plus_lstm'),3)}) and the standalone LSTM\n({f(K('lstm_seq2seq_fast'),3)}). On NSE all ten clear persistence\n({f(N('bench_persistence_1day'),3)}) comfortably.\n\"\"\")\n```\n\nEvery one of the ten candidates beats the mean-flow benchmark\n(KGE -0.432, the Knoben et al. [-@knoben2019] reference) and the\nday-of-year climatology (KGE 0.058) by a wide margin. Eight of the ten\nalso beat one-day persistence on KGE (0.865) — the two that do not are\n`ens_best_conceptual_plus_lstm` (0.842) and the standalone LSTM\n(0.797). On NSE all ten clear persistence\n(0.729) comfortably.\n\n\n\n## How close is the field, really? {#sec-close}\n\n::: {#tbl-paired .cell tbl-cap='Paired 30-day moving-block bootstrap of the DIFFERENCE (winner minus other), 2,000 resamples, identical resampling indices for both members of every pair. P is the fraction of resamples in which the winner scores higher.' execution_count=10}\n``` {.python .cell-code}\np = pw.copy()\np.index = [LABEL[i] for i in p.index]\np[[\"dKGE\", \"dKGE_lo\", \"dKGE_hi\", \"P_winner_better_KGE\",\n   \"dNSE\", \"dNSE_lo\", \"dNSE_hi\", \"P_winner_better_NSE\"]].round(4).sort_values(\"dKGE\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>dKGE</th>\n      <th>dKGE_lo</th>\n      <th>dKGE_hi</th>\n      <th>P_winner_better_KGE</th>\n      <th>dNSE</th>\n      <th>dNSE_lo</th>\n      <th>dNSE_hi</th>\n      <th>P_winner_better_NSE</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>E2 · ens_mean_conceptual</th>\n      <td>-0.0040</td>\n      <td>-0.0193</td>\n      <td>0.0318</td>\n      <td>0.6610</td>\n      <td>0.0294</td>\n      <td>0.0161</td>\n      <td>0.0427</td>\n      <td>1.0000</td>\n    </tr>\n    <tr>\n      <th>2 · GR4J</th>\n      <td>0.0077</td>\n      <td>-0.0538</td>\n      <td>0.0584</td>\n      <td>0.6750</td>\n      <td>0.0644</td>\n      <td>0.0425</td>\n      <td>0.1001</td>\n      <td>1.0000</td>\n    </tr>\n    <tr>\n      <th>1 · ARX-API ridge</th>\n      <td>0.0124</td>\n      <td>-0.0804</td>\n      <td>0.0715</td>\n      <td>0.5945</td>\n      <td>-0.0251</td>\n      <td>-0.0461</td>\n      <td>0.0181</td>\n      <td>0.2360</td>\n    </tr>\n    <tr>\n      <th>E3 · ens_physics_plus_ml</th>\n      <td>0.0127</td>\n      <td>-0.0293</td>\n      <td>0.0515</td>\n      <td>0.5805</td>\n      <td>0.0141</td>\n      <td>0.0046</td>\n      <td>0.0270</td>\n      <td>1.0000</td>\n    </tr>\n    <tr>\n      <th>3 · HBV-light</th>\n      <td>0.0196</td>\n      <td>-0.0058</td>\n      <td>0.1002</td>\n      <td>0.9525</td>\n      <td>0.0642</td>\n      <td>0.0218</td>\n      <td>0.0926</td>\n      <td>1.0000</td>\n    </tr>\n    <tr>\n      <th>4 · SAC-SMA</th>\n      <td>0.0265</td>\n      <td>-0.0577</td>\n      <td>0.0885</td>\n      <td>0.6350</td>\n      <td>0.0297</td>\n      <td>0.0161</td>\n      <td>0.0612</td>\n      <td>1.0000</td>\n    </tr>\n    <tr>\n      <th>E4 · ens_nnls_calibration</th>\n      <td>0.0337</td>\n      <td>-0.0084</td>\n      <td>0.0817</td>\n      <td>0.8685</td>\n      <td>0.0113</td>\n      <td>-0.0086</td>\n      <td>0.0299</td>\n      <td>0.8145</td>\n    </tr>\n    <tr>\n      <th>E5 · ens_best_conceptual_plus_lstm</th>\n      <td>0.0595</td>\n      <td>-0.0511</td>\n      <td>0.1270</td>\n      <td>0.7655</td>\n      <td>0.0211</td>\n      <td>-0.0002</td>\n      <td>0.0476</td>\n      <td>0.9730</td>\n    </tr>\n    <tr>\n      <th>5 · LSTM seq2seq (3 seeds)</th>\n      <td>0.1046</td>\n      <td>-0.0430</td>\n      <td>0.2183</td>\n      <td>0.8725</td>\n      <td>0.0472</td>\n      <td>-0.0029</td>\n      <td>0.1272</td>\n      <td>0.9585</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n``` {.python .cell-code}\nn_ci0 = int(((pw[\"dKGE_lo\"] < 0) & (pw[\"dKGE_hi\"] > 0)).sum())\nMarkdown(f\"\"\"\n**{n_ci0} of the {len(pw)} KGE differences have a 95 % interval that contains zero.** Only\n`hbv_light` is separated from the winner with better than 95 % confidence on KGE\n(P = {f(pw.loc['hbv_light','P_winner_better_KGE'],3)}, interval\n[{f(pw.loc['hbv_light','dKGE_lo'],4)}, {f(pw.loc['hbv_light','dKGE_hi'],4)}]). The NSE differences\nseparate more cleanly — five of them exclude zero — which is why the tie-break on NSE is not an\narbitrary coin toss even though the KGE ordering is.\n\nThe honest summary of @tbl-main is therefore: **with 1,003 days of record, the evaluation window can\ntell the LSTM apart from the rest, and it can tell NSE apart; it cannot resolve the KGE ordering of the\ntop seven candidates.** Any statement of the form \"model X is the best model of the Leaf River\" that\nrests on a KGE gap of 0.004 is not supported by this data set.\n\"\"\")\n```\n\n**9 of the 9 KGE differences have a 95 % interval that contains zero.** Only\n`hbv_light` is separated from the winner with better than 95 % confidence on KGE\n(P = 0.953, interval\n[-0.0058, 0.1002]). The NSE differences\nseparate more cleanly — five of them exclude zero — which is why the tie-break on NSE is not an\narbitrary coin toss even though the KGE ordering is.\n\nThe honest summary of @tbl-main is therefore: **with 1,003 days of record, the evaluation window can\ntell the LSTM apart from the rest, and it can tell NSE apart; it cannot resolve the KGE ordering of the\ntop seven candidates.** Any statement of the form \"model X is the best model of the Leaf River\" that\nrests on a KGE gap of 0.004 is not supported by this data set.\n\n\n\n## Stability across the evaluation window {#sec-blocks}\n\n::: {#tbl-blocks .cell tbl-cap='KGE and NSE inside each of the three sub-periods of the metric window. Block 1 is the partial water year that immediately follows the 92-day warm-up and is the wettest (mean observed Q 2.59 mm/d against a calibration mean of 1.35 mm/d).' execution_count=12}\n``` {.python .cell-code}\npv = blk.pivot(index=\"id\", columns=\"block\", values=[\"KGE\", \"NSE\"]).round(3)\npv = pv.loc[CAND]\npv.index = [LABEL[i] for i in pv.index]\nnd = blk.groupby(\"block\")[[\"n_days\", \"mean_Qobs\"]].first().round(2)\ndisplay(Markdown(\"Sub-period sizes and wetness: \" + \"; \".join(\n    f\"**{b}** — {int(r.n_days)} d, mean observed Q {r.mean_Qobs:.2f} mm/d\" for b, r in nd.iterrows())))\npv\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nSub-period sizes and wetness: **1949-01-01..1949-09-30** — 273 d, mean observed Q 2.59 mm/d; **1949-10-01..1950-09-30** — 365 d, mean observed Q 1.79 mm/d; **1950-10-01..1951-09-30** — 365 d, mean observed Q 1.08 mm/d\n:::\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead tr th {\n        text-align: left;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr>\n      <th></th>\n      <th colspan=\"3\" halign=\"left\">KGE</th>\n      <th colspan=\"3\" halign=\"left\">NSE</th>\n    </tr>\n    <tr>\n      <th>block</th>\n      <th>1949-01-01..1949-09-30</th>\n      <th>1949-10-01..1950-09-30</th>\n      <th>1950-10-01..1951-09-30</th>\n      <th>1949-01-01..1949-09-30</th>\n      <th>1949-10-01..1950-09-30</th>\n      <th>1950-10-01..1951-09-30</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1 · ARX-API ridge</th>\n      <td>0.913</td>\n      <td>0.878</td>\n      <td>0.800</td>\n      <td>0.879</td>\n      <td>0.940</td>\n      <td>0.885</td>\n    </tr>\n    <tr>\n      <th>2 · GR4J</th>\n      <td>0.822</td>\n      <td>0.821</td>\n      <td>0.893</td>\n      <td>0.734</td>\n      <td>0.862</td>\n      <td>0.819</td>\n    </tr>\n    <tr>\n      <th>3 · HBV-light</th>\n      <td>0.691</td>\n      <td>0.786</td>\n      <td>0.937</td>\n      <td>0.724</td>\n      <td>0.849</td>\n      <td>0.880</td>\n    </tr>\n    <tr>\n      <th>4 · SAC-SMA</th>\n      <td>0.669</td>\n      <td>0.913</td>\n      <td>0.926</td>\n      <td>0.755</td>\n      <td>0.895</td>\n      <td>0.882</td>\n    </tr>\n    <tr>\n      <th>5 · LSTM seq2seq (3 seeds)</th>\n      <td>0.477</td>\n      <td>0.910</td>\n      <td>0.957</td>\n      <td>0.575</td>\n      <td>0.920</td>\n      <td>0.942</td>\n    </tr>\n    <tr>\n      <th>E1 · ens_mean_all5</th>\n      <td>0.749</td>\n      <td>0.860</td>\n      <td>0.932</td>\n      <td>0.813</td>\n      <td>0.917</td>\n      <td>0.905</td>\n    </tr>\n    <tr>\n      <th>E2 · ens_mean_conceptual</th>\n      <td>0.743</td>\n      <td>0.837</td>\n      <td>0.936</td>\n      <td>0.770</td>\n      <td>0.891</td>\n      <td>0.876</td>\n    </tr>\n    <tr>\n      <th>E3 · ens_physics_plus_ml</th>\n      <td>0.684</td>\n      <td>0.882</td>\n      <td>0.950</td>\n      <td>0.768</td>\n      <td>0.912</td>\n      <td>0.900</td>\n    </tr>\n    <tr>\n      <th>E4 · ens_nnls_calibration</th>\n      <td>0.642</td>\n      <td>0.865</td>\n      <td>0.944</td>\n      <td>0.745</td>\n      <td>0.919</td>\n      <td>0.926</td>\n    </tr>\n    <tr>\n      <th>E5 · ens_best_conceptual_plus_lstm</th>\n      <td>0.589</td>\n      <td>0.911</td>\n      <td>0.950</td>\n      <td>0.723</td>\n      <td>0.912</td>\n      <td>0.920</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n``` {.python .cell-code}\nb1 = blk[blk.block.str.startswith(\"1949-01\")].set_index(\"id\")\nb3 = blk[blk.block.str.startswith(\"1950-10\")].set_index(\"id\")\nMarkdown(f\"\"\"\nThis table carries the most important diagnostic in the whole evaluation. **The ranking is not stable\nacross the three sub-periods, and the instability is concentrated in the first one.**\n\n* In block 1 (Jan–Sep 1949, the wettest 273 days of the entire 40-year record and the block closest to\n  the 92-day warm-up) the LSTM collapses to KGE {f(b1.loc['lstm_seq2seq_fast','KGE'],3)} while the ridge\n  regression reaches KGE {f(b1.loc['arx_api_ridge','KGE'],3)} — the best of any candidate there.\n* In block 3 (WY1951, the driest of the three) the order reverses completely: the LSTM is the **best**\n  candidate at KGE {f(b3.loc['lstm_seq2seq_fast','KGE'],3)} / NSE {f(b3.loc['lstm_seq2seq_fast','NSE'],3)},\n  and the ridge is the **worst** at KGE {f(b3.loc['arx_api_ridge','KGE'],3)}.\n\nTwo mechanisms are consistent with this. (i) **State initialisation.** Slot 5 was calibrated with\n`seq_len` = 180 d and is started from $h_0 = c_0 = 0$ on 1948-10-01, so the first ~180 days of the metric\nwindow are produced by a network whose recurrent state has not yet filled; the conceptual slots have the\nsame problem in milder form (SAC-SMA's spin-up removes its seed dependence but not the shortness of the\nwindow). (ii) **Wetness extrapolation.** Block 1 is 1.92× wetter than the calibration mean. A model with\nno mass balance and a short memory (the ridge, $\\\\lambda_{{slow}} = 0.97 \\\\Rightarrow \\\\tau \\\\approx 33$ d)\nhas little state to get wrong; a 180-day-memory network has a great deal.\n\nThis is reported as a diagnostic, **not** as a re-ranking. The protocol fixes the metric window at\n1,003 days and the reported numbers are the 1,003-day numbers.\n\"\"\")\n```\n\nThis table carries the most important diagnostic in the whole evaluation. **The ranking is not stable\nacross the three sub-periods, and the instability is concentrated in the first one.**\n\n* In block 1 (Jan–Sep 1949, the wettest 273 days of the entire 40-year record and the block closest to\n  the 92-day warm-up) the LSTM collapses to KGE 0.477 while the ridge\n  regression reaches KGE 0.913 — the best of any candidate there.\n* In block 3 (WY1951, the driest of the three) the order reverses completely: the LSTM is the **best**\n  candidate at KGE 0.957 / NSE 0.942,\n  and the ridge is the **worst** at KGE 0.800.\n\nTwo mechanisms are consistent with this. (i) **State initialisation.** Slot 5 was calibrated with\n`seq_len` = 180 d and is started from $h_0 = c_0 = 0$ on 1948-10-01, so the first ~180 days of the metric\nwindow are produced by a network whose recurrent state has not yet filled; the conceptual slots have the\nsame problem in milder form (SAC-SMA's spin-up removes its seed dependence but not the shortness of the\nwindow). (ii) **Wetness extrapolation.** Block 1 is 1.92× wetter than the calibration mean. A model with\nno mass balance and a short memory (the ridge, $\\lambda_{slow} = 0.97 \\Rightarrow \\tau \\approx 33$ d)\nhas little state to get wrong; a 180-day-memory network has a great deal.\n\nThis is reported as a diagnostic, **not** as a re-ranking. The protocol fixes the metric window at\n1,003 days and the reported numbers are the 1,003-day numbers.\n\n\n\n# Diagnostics {#sec-figures}\n\n::: {.callout-note}\nFigures are qualitative. No metric other than KGE and NSE is printed on any of them.\n:::\n\n![Observed and simulated hydrographs over the full evaluation run window, with precipitation. The grey band is the 92-day warm-up, excluded from every metric.](figures/a16_hydrograph_full.png){#fig-hydro}\n\n![The same hydrograph on a logarithmic flow axis, which is where the low-flow behaviour becomes visible.](figures/a16_hydrograph_full_log.png){#fig-hydro-log}\n\n![The three largest independent flood events of the metric window (peaks separated by more than 30 days). The January 1950 event, 45.9 mm/d, is the largest flow of the evaluation window and is under-predicted by every model.](figures/a16_events.png){#fig-events}\n\n![Simulated against observed daily flow, log-log, with the 1:1 line. Headline KGE and NSE are repeated on each panel.](figures/a16_scatter.png){#fig-scatter}\n\n![Flow-duration curves on the metric window. Left: the five calibrated models. Right: the five pre-declared ensembles.](figures/a16_fdc.png){#fig-fdc}\n\n![Residual time series (simulated minus observed) for the five models. The common positive offset over 1949 is the volume over-prediction that drives every $\\beta > 1$ in @sec-hypotheses.](figures/a16_residuals.png){#fig-resid}\n\n![Cumulative runoff over the metric window. The vertical spread at the right-hand edge is the total volume error.](figures/a16_cumulative.png){#fig-cumul}\n\n![Calibration-to-evaluation change in KGE and NSE for every model and ensemble. The slope of each segment is the degradation that hypothesis H4 is about.](figures/a16_degradation.png){#fig-degrad}\n\n![KGE and NSE with 95 % moving-block-bootstrap intervals, candidates sorted by KGE. The selected model is highlighted. The overlap of the intervals is the headline caveat of this report.](figures/a16_ranking_ci.png){#fig-ci}\n\n![Sub-period stability. Each line is one candidate across the three sub-periods of @tbl-blocks.](figures/a16_blocks.png){#fig-blocks}\n\n# The eight pre-registered hypotheses {#sec-hypotheses}\n\nStated in `reports/03_models.qmd` § \"Hypotheses to be tested in a16\" before any model was built.\nVerdicts below are mechanical applications of the falsifiable statements as written.\n\n## H1 — \"Complexity pays off, but with sharply diminishing returns\" → **FALSIFIED (first clause)** {#sec-h1}\n\n``` {.python .cell-code}\nh = hyp[\"H1\"]\nMarkdown(f\"\"\"\nFalsifiable statement: *NSE(slot 1) < NSE(slot 2)* **and** *NSE(slot 4) − NSE(slot 2) < 0.05*.\n\n| clause | prediction | measured | verdict |\n|---|---|---|---|\n| (a) | NSE(ARX ridge) < NSE(GR4J) | **{f(h['NSE_slot1'])} vs {f(h['NSE_slot2'])}** — the ridge is **higher by {f(h['NSE_slot1']-h['NSE_slot2'])}** | **falsified** |\n| (b) | NSE(SAC-SMA) − NSE(GR4J) < 0.05 | {f(h['clause_b_NSE4_minus_NSE2'])} | supported |\n\n**H1 is falsified.** It was pre-registered as a conjunction; clause (a) fails, and it does not fail\nmarginally. On the held-out window the 19-coefficient ARX-API ridge regression\n(NSE {f(h['NSE_slot1'])}) beats GR4J by {f(h['NSE_slot1']-h['NSE_slot2'])} NSE units, beats HBV-light\nby {f(h['NSE_slot1']-N('hbv_light'))}, beats SAC-SMA by {f(h['NSE_slot1']-h['NSE_slot4'])}, beats the\nLSTM by {f(h['NSE_slot1']-N('lstm_seq2seq_fast'))}, and has **the highest NSE of any candidate in this\nstudy, ensembles included**. On KGE it is {f(K('arx_api_ridge'))}, fourth of ten and\n{f(K('gr4j')-K('arx_api_ridge'))} behind GR4J — so it does not sweep the board, but it is nowhere near\nthe \"floor of the complexity gradient\" role a03 assigned it.\n\n`reports/03_models.qmd` § \"Build-phase evidence that puts H1 at risk\" predicted exactly this outcome and\nasked for it to be stated plainly if it occurred. It occurred. The ridge was verified non-leaking at\nbuild time (observed Q never enters the design matrix; the bias factor and the column scalers are frozen\nat fit time; the fit never sees validation or evaluation rows) and that verification is structural, not\nstatistical — it does not become weaker because the model did well.\n\nClause (b) survives, and the surviving half of H1 is the interesting half: going from 4 parameters\n(GR4J) to 15 (SAC-SMA) buys {f(h['clause_b_NSE4_minus_NSE2'])} NSE, and going from 15 parameters to\n{int(met.loc['lstm_seq2seq_fast','n_fitted']):,} LSTM weights **costs**\n{f(h['NSE_slot4']-N('lstm_seq2seq_fast'))} NSE and {f(K('sacsma')-K('lstm_seq2seq_fast'))} KGE. Across\nthe five slots the Spearman rank correlation between the number of fitted quantities and evaluation KGE\nis {f(met.loc[[SLOT_ID[s] for s in range(1,6)],['n_fitted','KGE']].corr(method='spearman').iloc[0,1],2)}\n— and on NSE it is {f(met.loc[[SLOT_ID[s] for s in range(1,6)],['n_fitted','NSE']].corr(method='spearman').iloc[0,1],2)},\nthe opposite sign. **The two metrics disagree about whether complexity helps at all**, which is itself the\ncleanest statement of how weak the complexity signal is on this window: the positive NSE correlation is\ncarried entirely by the 26-quantity ridge, and it survives only because the 30,801-weight LSTM ranks\nfourth of five rather than last.\n\"\"\")\n```\n\nFalsifiable statement: *NSE(slot 1) < NSE(slot 2)* **and** *NSE(slot 4) − NSE(slot 2) < 0.05*.\n\n| clause | prediction | measured | verdict |\n|---|---|---|---|\n| (a) | NSE(ARX ridge) < NSE(GR4J) | **0.9183 vs 0.8287** — the ridge is **higher by 0.0896** | **falsified** |\n| (b) | NSE(SAC-SMA) − NSE(GR4J) < 0.05 | 0.0347 | supported |\n\n**H1 is falsified.** It was pre-registered as a conjunction; clause (a) fails, and it does not fail\nmarginally. On the held-out window the 19-coefficient ARX-API ridge regression\n(NSE 0.9183) beats GR4J by 0.0896 NSE units, beats HBV-light\nby 0.0893, beats SAC-SMA by 0.0548, beats the\nLSTM by 0.0723, and has **the highest NSE of any candidate in this\nstudy, ensembles included**. On KGE it is 0.8893, fourth of ten and\n0.0047 behind GR4J — so it does not sweep the board, but it is nowhere near\nthe \"floor of the complexity gradient\" role a03 assigned it.\n\n`reports/03_models.qmd` § \"Build-phase evidence that puts H1 at risk\" predicted exactly this outcome and\nasked for it to be stated plainly if it occurred. It occurred. The ridge was verified non-leaking at\nbuild time (observed Q never enters the design matrix; the bias factor and the column scalers are frozen\nat fit time; the fit never sees validation or evaluation rows) and that verification is structural, not\nstatistical — it does not become weaker because the model did well.\n\nClause (b) survives, and the surviving half of H1 is the interesting half: going from 4 parameters\n(GR4J) to 15 (SAC-SMA) buys 0.0347 NSE, and going from 15 parameters to\n30,801 LSTM weights **costs**\n0.0175 NSE and 0.0782 KGE. Across\nthe five slots the Spearman rank correlation between the number of fitted quantities and evaluation KGE\nis -0.70\n— and on NSE it is 0.70,\nthe opposite sign. **The two metrics disagree about whether complexity helps at all**, which is itself the\ncleanest statement of how weak the complexity signal is on this window: the positive NSE correlation is\ncarried entirely by the 26-quantity ridge, and it survives only because the 30,801-weight LSTM ranks\nfourth of five rather than last.\n\n\n\n## H2 — \"Two subsurface time scales matter (at low flows)\" → **FALSIFIED** {#sec-h2}\n\n``` {.python .cell-code}\nh = hyp[\"H2\"]; ha = hypA\nkj = h[\"KGE_jul_oct\"]; pb = h[\"pbias_below_Q50_pct\"]; n20 = ha[\"NSE_top20_days\"]\nMarkdown(f\"\"\"\nFalsifiable statement: slots 3 and 4 beat slot 2 *specifically on low flows* — higher KGE on Jul–Oct,\nsmaller bias below Q50 — *and* the difference on annual peaks is < 0.02 NSE.\n\n| clause | GR4J (1 slow store) | HBV-light (2) | SAC-SMA (2) | verdict |\n|---|---|---|---|---|\n| KGE, Jul–Oct sub-period | {f(kj['2'],3)} | {f(kj['3'],3)} | {f(kj['4'],3)} | **mixed**: HBV yes, SAC-SMA far worse |\n| NSE, Jul–Oct sub-period | {f(h['NSE_jul_oct']['2'],3)} | {f(h['NSE_jul_oct']['3'],3)} | {f(h['NSE_jul_oct']['4'],3)} | same pattern |\n| bias below Q50 = {f(h['Q50_mm_d'],3)} mm/d (%) | {f(pb['2'],1)} | {f(pb['3'],1)} | {f(pb['4'],1)} | **mixed**: SAC-SMA yes, HBV identical to GR4J |\n| NSE on the 20 largest days | {f(n20['2'],3)} | {f(n20['3'],3)} | {f(n20['4'],3)} | **falsified**: spread {f(max(n20.values())-min(n20.values()),3)} ≫ 0.02 |\n\n**H2 is falsified.** No single clause holds for *both* two-store models, and the third clause — that the\npeak behaviour would be essentially identical — fails by a factor of {int(round((max(n20.values())-min(n20.values()))/0.02))}.\nThe two extra slow stores did not buy a systematic low-flow advantage; they bought *different* models\nwith different, and partly opposite, biases. (Bias below Q50 and the sub-period KGE/NSE figures are the\npre-registered test statistics of H2, quoted here for that purpose only.)\n\"\"\")\n```\n\nFalsifiable statement: slots 3 and 4 beat slot 2 *specifically on low flows* — higher KGE on Jul–Oct,\nsmaller bias below Q50 — *and* the difference on annual peaks is < 0.02 NSE.\n\n| clause | GR4J (1 slow store) | HBV-light (2) | SAC-SMA (2) | verdict |\n|---|---|---|---|---|\n| KGE, Jul–Oct sub-period | 0.432 | 0.623 | 0.287 | **mixed**: HBV yes, SAC-SMA far worse |\n| NSE, Jul–Oct sub-period | 0.322 | 0.627 | 0.182 | same pattern |\n| bias below Q50 = 0.631 mm/d (%) | 11.1 | 11.0 | 1.6 | **mixed**: SAC-SMA yes, HBV identical to GR4J |\n| NSE on the 20 largest days | 0.155 | 0.212 | 0.506 | **falsified**: spread 0.351 ≫ 0.02 |\n\n**H2 is falsified.** No single clause holds for *both* two-store models, and the third clause — that the\npeak behaviour would be essentially identical — fails by a factor of 18.\nThe two extra slow stores did not buy a systematic low-flow advantage; they bought *different* models\nwith different, and partly opposite, biases. (Bias below Q50 and the sub-period KGE/NSE figures are the\npre-registered test statistics of H2, quoted here for that purpose only.)\n\n\n\n## H3 — \"SAC-SMA's advantage is at low flows, not at peaks\" → **FALSIFIED, with the sign reversed** {#sec-h3}\n\n``` {.python .cell-code}\nh = hyp[\"H3\"]; n20 = hypA[\"NSE_top20_days\"]\nMarkdown(f\"\"\"\n| clause | prediction | SAC-SMA | GR4J | verdict |\n|---|---|---|---|---|\n| NSE in log space | SAC-SMA > GR4J | {f(h['NSE_log_slot4'],3)} | {f(h['NSE_log_slot2'],3)} | **falsified** |\n| NSE on Jun–Sep | SAC-SMA > GR4J | {f(h['NSE_jun_sep_slot4'],3)} | {f(h['NSE_jun_sep_slot2'],3)} | **falsified** |\n| NSE on the 20 largest days | SAC-SMA **not** > GR4J | {f(n20['4'],3)} | {f(n20['2'],3)} | **falsified** |\n\n**H3 is falsified on all three clauses, and the direction is exactly reversed.** On the evaluation window\nSAC-SMA's advantage over GR4J is **at the peaks** ({f(n20['4']-n20['2'],3)} NSE on the 20 largest days),\nwhile GR4J is the better low-flow model ({f(h['NSE_log_slot2']-h['NSE_log_slot4'],3)} NSE in log space,\n{f(h['NSE_jun_sep_slot2']-h['NSE_jun_sep_slot4'],3)} on Jun–Sep). This is the mirror image of the\npre-registered expectation and it is consistent with a04's warning that the calibration objective\n$O = 0.5\\\\,\\\\mathrm{{KGE}} + 0.5\\\\,\\\\mathrm{{NSE}}$ does not improve low flows: it rewards the\nhigh-leverage days, and the 15-parameter model exploited that further than the 4-parameter one.\n\"\"\")\n```\n\n| clause | prediction | SAC-SMA | GR4J | verdict |\n|---|---|---|---|---|\n| NSE in log space | SAC-SMA > GR4J | 0.707 | 0.766 | **falsified** |\n| NSE on Jun–Sep | SAC-SMA > GR4J | 0.234 | 0.353 | **falsified** |\n| NSE on the 20 largest days | SAC-SMA **not** > GR4J | 0.506 | 0.155 | **falsified** |\n\n**H3 is falsified on all three clauses, and the direction is exactly reversed.** On the evaluation window\nSAC-SMA's advantage over GR4J is **at the peaks** (0.351 NSE on the 20 largest days),\nwhile GR4J is the better low-flow model (0.059 NSE in log space,\n0.120 on Jun–Sep). This is the mirror image of the\npre-registered expectation and it is consistent with a04's warning that the calibration objective\n$O = 0.5\\,\\mathrm{KGE} + 0.5\\,\\mathrm{NSE}$ does not improve low flows: it rewards the\nhigh-leverage days, and the 15-parameter model exploited that further than the 4-parameter one.\n\n\n\n## H4 — \"The LSTM wins on calibration but loses relative ground on evaluation\" → **SUPPORTED** {#sec-h4}\n\n::: {#h4 .cell execution_count=17}\n``` {.python .cell-code}\nh = hyp[\"H4\"]\ntab = pd.DataFrame({\n  \"model\": [LABEL[SLOT_ID[s]] for s in range(1, 6)],\n  \"cal KGE\": [met.loc[SLOT_ID[s], \"KGE_cal\"] for s in range(1, 6)],\n  \"eval KGE\": [met.loc[SLOT_ID[s], \"KGE\"] for s in range(1, 6)],\n  \"ΔKGE\": [h[\"drop_KGE\"][str(s)] for s in range(1, 6)],\n  \"cal NSE\": [h[\"NSE_cal\"][str(s)] for s in range(1, 6)],\n  \"eval NSE\": [h[\"NSE_eval\"][str(s)] for s in range(1, 6)],\n  \"ΔNSE\": [h[\"drop_NSE\"][str(s)] for s in range(1, 6)],\n}).set_index(\"model\").round(4)\ndisplay(tab)\nMarkdown(f\"\"\"\nFalsifiable statement: NSE_cal(slot 5) is the highest of the five **and** NSE_cal − NSE_eval is larger\nfor slot 5 than for slots 2–4.\n\n* Slot 5 has the highest calibration NSE ({f(h['NSE_cal']['5'])}) — **true**.\n* Its NSE drop is {f(h['drop_NSE']['5'])}, against {f(h['drop_NSE']['2'])} (GR4J),\n  {f(h['drop_NSE']['3'])} (HBV-light) and {f(h['drop_NSE']['4'])} (SAC-SMA) — **the largest, as\n  predicted**. Its KGE drop, {f(h['drop_KGE']['5'])}, is also the largest of all ten candidates.\n\n**H4 is supported on both clauses.** The LSTM went from best-on-calibration to\n**worst-on-evaluation of the five single models**, and it is the only candidate that falls below the\none-day-persistence benchmark on KGE.\n\nTwo caveats that do not change the verdict but bound its interpretation. First, slot 5 is a16's\n*budgeted* calibration (a15b: 9 completed trials, 25 epochs, `seq_len` pinned at the box floor, 3 seeds\ninstead of 5) and its calibration score was declared a lower bound — but a *lower* bound on the\ncalibration score makes the measured drop **conservative**, not inflated. Second, its three seeds spread\nby {f(diag['lstm_member_spread_KGE'],3)} KGE on the evaluation window (members:\n{\", \".join(f\"{met.loc[f'lstm_member_{s}','KGE']:.3f}\" for s in (42,43,44))}), so a different seed triple\ncould have moved the slot-5 number by several hundredths — far more than the entire top-7 KGE spread.\n\nThe most striking number in the table is not slot 5's, though: **slot 1 has a *negative* drop.**\nThe ARX-API ridge scores {f(-h['drop_NSE']['1'])} NSE units **higher** on the held-out window than on the\nwindow it was calibrated on. It is the only candidate that improves out of sample, and it was also the\nonly model with a negative train→validation gap during calibration (−0.0178, a11).\n\"\"\")\n```\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>cal KGE</th>\n      <th>eval KGE</th>\n      <th>ΔKGE</th>\n      <th>cal NSE</th>\n      <th>eval NSE</th>\n      <th>ΔNSE</th>\n    </tr>\n    <tr>\n      <th>model</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1 · ARX-API ridge</th>\n      <td>0.9098</td>\n      <td>0.8893</td>\n      <td>0.0204</td>\n      <td>0.8210</td>\n      <td>0.9183</td>\n      <td>-0.0973</td>\n    </tr>\n    <tr>\n      <th>2 · GR4J</th>\n      <td>0.9139</td>\n      <td>0.8941</td>\n      <td>0.0198</td>\n      <td>0.8558</td>\n      <td>0.8287</td>\n      <td>0.0271</td>\n    </tr>\n    <tr>\n      <th>3 · HBV-light</th>\n      <td>0.9445</td>\n      <td>0.8822</td>\n      <td>0.0623</td>\n      <td>0.8931</td>\n      <td>0.8290</td>\n      <td>0.0641</td>\n    </tr>\n    <tr>\n      <th>4 · SAC-SMA</th>\n      <td>0.9500</td>\n      <td>0.8753</td>\n      <td>0.0747</td>\n      <td>0.9017</td>\n      <td>0.8635</td>\n      <td>0.0382</td>\n    </tr>\n    <tr>\n      <th>5 · LSTM seq2seq (3 seeds)</th>\n      <td>0.9258</td>\n      <td>0.7971</td>\n      <td>0.1287</td>\n      <td>0.9510</td>\n      <td>0.8460</td>\n      <td>0.1050</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n\nFalsifiable statement: NSE_cal(slot 5) is the highest of the five **and** NSE_cal − NSE_eval is larger\nfor slot 5 than for slots 2–4.\n\n* Slot 5 has the highest calibration NSE (0.9510) — **true**.\n* Its NSE drop is 0.1050, against 0.0271 (GR4J),\n  0.0641 (HBV-light) and 0.0382 (SAC-SMA) — **the largest, as\n  predicted**. Its KGE drop, 0.1287, is also the largest of all ten candidates.\n\n**H4 is supported on both clauses.** The LSTM went from best-on-calibration to\n**worst-on-evaluation of the five single models**, and it is the only candidate that falls below the\none-day-persistence benchmark on KGE.\n\nTwo caveats that do not change the verdict but bound its interpretation. First, slot 5 is a16's\n*budgeted* calibration (a15b: 9 completed trials, 25 epochs, `seq_len` pinned at the box floor, 3 seeds\ninstead of 5) and its calibration score was declared a lower bound — but a *lower* bound on the\ncalibration score makes the measured drop **conservative**, not inflated. Second, its three seeds spread\nby 0.060 KGE on the evaluation window (members:\n0.851, 0.808, 0.707), so a different seed triple\ncould have moved the slot-5 number by several hundredths — far more than the entire top-7 KGE spread.\n\nThe most striking number in the table is not slot 5's, though: **slot 1 has a *negative* drop.**\nThe ARX-API ridge scores 0.0973 NSE units **higher** on the held-out window than on the\nwindow it was calibrated on. It is the only candidate that improves out of sample, and it was also the\nonly model with a negative train→validation gap during calibration (−0.0178, a11).\n\n:::\n\n\n## H5 — \"Every model shows KGE α < 1 and β < 1 on evaluation\" → **FALSIFIED** {#sec-h5}\n\n::: {#h5 .cell execution_count=18}\n``` {.python .cell-code}\nh = hyp[\"H5\"]\ntab = pd.DataFrame({\"model\": [LABEL[SLOT_ID[s]] for s in range(1, 6)],\n                    \"α = σ_s/σ_o\": [h[\"alpha\"][str(s)] for s in range(1, 6)],\n                    \"β = μ_s/μ_o\": [h[\"beta\"][str(s)] for s in range(1, 6)]}).set_index(\"model\").round(4)\ndisplay(tab)\nn_a = sum(1 for v in h[\"alpha\"].values() if v < 1); n_b = sum(1 for v in h[\"beta\"].values() if v < 1)\nn_b105 = sum(1 for v in h[\"beta\"].values() if v > 1.05)\nMarkdown(f\"\"\"\n**H5 is falsified.** The α clause holds for {n_a} of 5 models (SAC-SMA {f(h['alpha']['4'],3)} and the\nLSTM {f(h['alpha']['5'],3)} exceed 1). The β clause holds for **{n_b} of 5**: *every* model\nover-predicts the volume of the evaluation window, from GR4J's {f(h['beta']['2'],3)} to the LSTM's\n{f(h['beta']['5'],3)}.\n\nThe sign is the opposite of what a01 and a04 expected. a04 had *measured* the transfer direction on\ncalibration-internal splits — moving a calibrated model to a wetter block lowered β by 0.068 on average —\nand predicted β slightly below 1 here. The wetter evaluation window instead produced β **above** 1 for\nall five. The mechanism is visible in @fig-resid and @fig-cumul: the surplus is not at the peaks (which\nare all under-predicted, @fig-events) but in the recessions and the 1949 baseflow, i.e. the models drain\ntheir stores too slowly when the antecedent wetness is far above anything in the calibration record.\n\nH5 comes with its own rider: *\"if a model shows β > 1.05 it is compensating a structural ET error.\"*\nBy that rider, {n_b105} of the 5 models — HBV-light, SAC-SMA and the LSTM — are flagged. Note that these\nare exactly the three models with the largest KGE degradation (@sec-h4), and that GR4J, whose β is\n{f(h['beta']['2'],4)}, is the model whose exchange parameter x2 explicitly removes water from the basin\n(@sec-h8). The pre-registered rider and the pre-registered H8 point at the same place from two sides.\n\"\"\")\n```\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>α = σ_s/σ_o</th>\n      <th>β = μ_s/μ_o</th>\n    </tr>\n    <tr>\n      <th>model</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1 · ARX-API ridge</th>\n      <td>0.8996</td>\n      <td>1.0242</td>\n    </tr>\n    <tr>\n      <th>2 · GR4J</th>\n      <td>0.9427</td>\n      <td>1.0025</td>\n    </tr>\n    <tr>\n      <th>3 · HBV-light</th>\n      <td>0.9599</td>\n      <td>1.0677</td>\n    </tr>\n    <tr>\n      <th>4 · SAC-SMA</th>\n      <td>1.0408</td>\n      <td>1.0991</td>\n    </tr>\n    <tr>\n      <th>5 · LSTM seq2seq (3 seeds)</th>\n      <td>1.0668</td>\n      <td>1.1796</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n\n**H5 is falsified.** The α clause holds for 3 of 5 models (SAC-SMA 1.041 and the\nLSTM 1.067 exceed 1). The β clause holds for **0 of 5**: *every* model\nover-predicts the volume of the evaluation window, from GR4J's 1.003 to the LSTM's\n1.180.\n\nThe sign is the opposite of what a01 and a04 expected. a04 had *measured* the transfer direction on\ncalibration-internal splits — moving a calibrated model to a wetter block lowered β by 0.068 on average —\nand predicted β slightly below 1 here. The wetter evaluation window instead produced β **above** 1 for\nall five. The mechanism is visible in @fig-resid and @fig-cumul: the surplus is not at the peaks (which\nare all under-predicted, @fig-events) but in the recessions and the 1949 baseflow, i.e. the models drain\ntheir stores too slowly when the antecedent wetness is far above anything in the calibration record.\n\nH5 comes with its own rider: *\"if a model shows β > 1.05 it is compensating a structural ET error.\"*\nBy that rider, 3 of the 5 models — HBV-light, SAC-SMA and the LSTM — are flagged. Note that these\nare exactly the three models with the largest KGE degradation (@sec-h4), and that GR4J, whose β is\n1.0025, is the model whose exchange parameter x2 explicitly removes water from the basin\n(@sec-h8). The pre-registered rider and the pre-registered H8 point at the same place from two sides.\n\n:::\n\n\n## H6 — \"The multi-model mean beats the best single model\" → **PARTLY SUPPORTED, second clause FALSIFIED** {#sec-h6}\n\n``` {.python .cell-code}\nh = hyp[\"H6\"]\nMarkdown(f\"\"\"\n| clause | prediction | measured | verdict |\n|---|---|---|---|\n| (a) | KGE(ens_mean_all5) ≥ max_i KGE(slot i) − 0.01 | {f(h['KGE_ens_mean_all5'])} vs {f(h['KGE_best_single'])} − 0.01 = {f(h['KGE_best_single']-0.01)} | **supported** (and it beats the best single model outright, by {f(h['KGE_ens_mean_all5']-h['KGE_best_single'])}) |\n| (b) | KGE(ens_nnls_calibration) > max_i KGE(slot i) | {f(h['KGE_ens_nnls'])} vs {f(h['KGE_best_single'])} | **falsified** by {f(h['KGE_best_single']-h['KGE_ens_nnls'])} |\n\nClause (a) is the classic multi-model-averaging result [@shamseldin1997; @ajami2004; @velazquez2011] and\nit holds here: the naive equal-weight mean of all five slots is the selected model of this study.\n\nClause (b) fails, and it fails informatively. The NNLS weights were fitted on the calibration\ninternal-validation window, where the fitted combination scored KGE 0.9291 / NSE 0.9348 — better than\nthe equal-weight mean there (0.9107 / 0.9233). On the evaluation window that ordering **reverses**:\n{f(h['KGE_ens_nnls'])} against {f(h['KGE_ens_mean_all5'])} KGE. The reason is visible in @sec-weights:\nNNLS put {f(wts['ensembles']['ens_nnls_calibration']['weights'][4]*100,0)} % of the weight on the LSTM,\nwhich is the member that degrades most (@sec-h4), and zeroed GR4J and SAC-SMA, two of the three members\nthat degrade least. **Fitting ensemble weights on held-out calibration data still over-fits to the\ncalibration climate.** Equal weights — the one choice that used no data at all — won.\n\"\"\")\n```\n\n| clause | prediction | measured | verdict |\n|---|---|---|---|\n| (a) | KGE(ens_mean_all5) ≥ max_i KGE(slot i) − 0.01 | 0.9018 vs 0.8941 − 0.01 = 0.8841 | **supported** (and it beats the best single model outright, by 0.0077) |\n| (b) | KGE(ens_nnls_calibration) > max_i KGE(slot i) | 0.8681 vs 0.8941 | **falsified** by 0.0260 |\n\nClause (a) is the classic multi-model-averaging result [@shamseldin1997; @ajami2004; @velazquez2011] and\nit holds here: the naive equal-weight mean of all five slots is the selected model of this study.\n\nClause (b) fails, and it fails informatively. The NNLS weights were fitted on the calibration\ninternal-validation window, where the fitted combination scored KGE 0.9291 / NSE 0.9348 — better than\nthe equal-weight mean there (0.9107 / 0.9233). On the evaluation window that ordering **reverses**:\n0.8681 against 0.9018 KGE. The reason is visible in @sec-weights:\nNNLS put 52 % of the weight on the LSTM,\nwhich is the member that degrades most (@sec-h4), and zeroed GR4J and SAC-SMA, two of the three members\nthat degrade least. **Fitting ensemble weights on held-out calibration data still over-fits to the\ncalibration climate.** Equal weights — the one choice that used no data at all — won.\n\n\n\n## H7 — \"Physics + ML is the best combination\" → **FALSIFIED** {#sec-h7}\n\n``` {.python .cell-code}\nh = hyp[\"H7\"]\nMarkdown(f\"\"\"\nFalsifiable statement: KGE(ens_physics_plus_ml) > KGE(ens_mean_conceptual).\n\nMeasured: **{f(h['KGE_physics_plus_ml'])} vs {f(h['KGE_mean_conceptual'])}** — the conceptual-only mean is\nhigher by {f(h['KGE_mean_conceptual']-h['KGE_physics_plus_ml'])}. **H7 is falsified.**\n\nOn NSE the comparison goes the other way ({f(N('ens_physics_plus_ml'))} vs\n{f(N('ens_mean_conceptual'))}), which is worth stating because it shows *where* the ML member helps:\nadding the LSTM raises the squared-error skill and lowers the KGE, because it imports the LSTM's volume\nbias (β {f(hyp['H5']['beta']['5'],3)}) into the average. The hypothesis was pre-registered on KGE, and on\nKGE it fails. With the paired bootstrap, P(ens_mean_conceptual > ens_physics_plus_ml in KGE) is well\ninside the noise, so the falsification is of the *point prediction*, not a demonstration that family\ndiversity is harmful.\n\"\"\")\n```\n\nFalsifiable statement: KGE(ens_physics_plus_ml) > KGE(ens_mean_conceptual).\n\nMeasured: **0.8890 vs 0.9058** — the conceptual-only mean is\nhigher by 0.0167. **H7 is falsified.**\n\nOn NSE the comparison goes the other way (0.8790 vs\n0.8638), which is worth stating because it shows *where* the ML member helps:\nadding the LSTM raises the squared-error skill and lowers the KGE, because it imports the LSTM's volume\nbias (β 1.180) into the average. The hypothesis was pre-registered on KGE, and on\nKGE it fails. With the paired bootstrap, P(ens_mean_conceptual > ens_physics_plus_ml in KGE) is well\ninside the noise, so the falsification is of the *point prediction*, not a demonstration that family\ndiversity is harmful.\n\n\n\n## H8 — \"GR4J's exchange term is doing structural work, not physics\" → **FALSIFIED as written (by 0.046 mm/d)** {#sec-h8}\n\n``` {.python .cell-code}\nh = hyp[\"H8\"]; x2 = h[\"x2_mm_d\"]\nMarkdown(f\"\"\"\nFalsifiable statement: the calibrated |x2| exceeds 1 mm/d (i.e. > 20 % of mean Q = 1.35 mm/d).\n\nMeasured: **x2 = {f(x2)} mm/d**, so |x2| = {f(abs(x2))} mm/d. The literal threshold is\n**{f(1.0-abs(x2))} mm/d short**, so **H8 is falsified as written**. Its own parenthetical criterion\npoints the other way: |x2| is **{f(100*abs(x2)/h['mean_Q_cal_mm_d'],0)} %** of the mean calibration flow,\nthree and a half times the 20 % the hypothesis offered as its gloss, and\n{f(100*abs(x2)/float(diag['eval_obs']['mean_mm_d']),0)} % of the mean evaluation flow. The sign is\nnegative, i.e. GR4J is **exporting** {f(abs(x2))} mm/d of water out of a basin that a01 classifies as an\nessentially unregulated HCDN-2009 / CAMELS reference catchment with no evidence of inter-catchment\ntransfer.\n\nVerdict: **falsified on the number that was pre-registered**; the underlying claim — that x2 is a\nstructural correction and not a physical flux — is if anything strengthened. The honest reading is that\nthe 1 mm/d threshold was set slightly too high, not that the conjecture was wrong. Recording it as\nfalsified is the point of pre-registration.\n\"\"\")\n```\n\nFalsifiable statement: the calibrated |x2| exceeds 1 mm/d (i.e. > 20 % of mean Q = 1.35 mm/d).\n\nMeasured: **x2 = -0.9540 mm/d**, so |x2| = 0.9540 mm/d. The literal threshold is\n**0.0460 mm/d short**, so **H8 is falsified as written**. Its own parenthetical criterion\npoints the other way: |x2| is **70 %** of the mean calibration flow,\nthree and a half times the 20 % the hypothesis offered as its gloss, and\n55 % of the mean evaluation flow. The sign is\nnegative, i.e. GR4J is **exporting** 0.9540 mm/d of water out of a basin that a01 classifies as an\nessentially unregulated HCDN-2009 / CAMELS reference catchment with no evidence of inter-catchment\ntransfer.\n\nVerdict: **falsified on the number that was pre-registered**; the underlying claim — that x2 is a\nstructural correction and not a physical flux — is if anything strengthened. The honest reading is that\nthe 1 mm/d threshold was set slightly too high, not that the conjecture was wrong. Recording it as\nfalsified is the point of pre-registration.\n\n\n\n## Summary of verdicts\n\n::: {#tbl-verdicts .cell tbl-cap='The eight pre-registered hypotheses, adjudicated on the evaluation metric window.' execution_count=22}\n``` {.python .cell-code}\nv = pd.DataFrame([\n (\"H1\", \"Complexity pays off with diminishing returns\", \"FALSIFIED (clause a)\",\n  f\"NSE ridge {N('arx_api_ridge'):.3f} > NSE GR4J {N('gr4j'):.3f}; clause b holds (0.035 < 0.05)\"),\n (\"H2\", \"Two subsurface time scales help low flows\", \"FALSIFIED\",\n  \"no clause holds for both two-store models; peak spread 0.351 NSE vs a predicted < 0.02\"),\n (\"H3\", \"SAC-SMA gains at low flows, not at peaks\", \"FALSIFIED (sign reversed)\",\n  \"SAC-SMA better at peaks (+0.351 NSE on the top 20 days), worse in log space (-0.059)\"),\n (\"H4\", \"LSTM best on calibration, degrades most\", \"SUPPORTED\",\n  \"NSE_cal 0.951 highest; drop 0.105 NSE / 0.129 KGE, the largest of all candidates\"),\n (\"H5\", \"Every model has KGE alpha < 1 and beta < 1\", \"FALSIFIED\",\n  \"alpha < 1 for 3 of 5; beta > 1 for 5 of 5 (1.003 to 1.180)\"),\n (\"H6\", \"Multi-model mean beats the best single model\", \"PARTLY SUPPORTED\",\n  \"(a) holds, equal-weight mean wins outright (+0.008 KGE); (b) NNLS ensemble falsified (-0.026)\"),\n (\"H7\", \"Physics + ML beats conceptual-only averaging\", \"FALSIFIED\",\n  \"KGE 0.889 vs 0.906 (but NSE 0.879 vs 0.864, i.e. metric-dependent)\"),\n (\"H8\", \"GR4J |x2| > 1 mm/d\", \"FALSIFIED (narrowly)\",\n  \"x2 = -0.954 mm/d = 70 % of mean calibration Q; literal threshold missed by 0.046 mm/d\"),\n], columns=[\"#\", \"hypothesis\", \"verdict\", \"numbers\"]).set_index(\"#\")\nv\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>hypothesis</th>\n      <th>verdict</th>\n      <th>numbers</th>\n    </tr>\n    <tr>\n      <th>#</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>H1</th>\n      <td>Complexity pays off with diminishing returns</td>\n      <td>FALSIFIED (clause a)</td>\n      <td>NSE ridge 0.918 &gt; NSE GR4J 0.829; clause b hol...</td>\n    </tr>\n    <tr>\n      <th>H2</th>\n      <td>Two subsurface time scales help low flows</td>\n      <td>FALSIFIED</td>\n      <td>no clause holds for both two-store models; pea...</td>\n    </tr>\n    <tr>\n      <th>H3</th>\n      <td>SAC-SMA gains at low flows, not at peaks</td>\n      <td>FALSIFIED (sign reversed)</td>\n      <td>SAC-SMA better at peaks (+0.351 NSE on the top...</td>\n    </tr>\n    <tr>\n      <th>H4</th>\n      <td>LSTM best on calibration, degrades most</td>\n      <td>SUPPORTED</td>\n      <td>NSE_cal 0.951 highest; drop 0.105 NSE / 0.129 ...</td>\n    </tr>\n    <tr>\n      <th>H5</th>\n      <td>Every model has KGE alpha &lt; 1 and beta &lt; 1</td>\n      <td>FALSIFIED</td>\n      <td>alpha &lt; 1 for 3 of 5; beta &gt; 1 for 5 of 5 (1.0...</td>\n    </tr>\n    <tr>\n      <th>H6</th>\n      <td>Multi-model mean beats the best single model</td>\n      <td>PARTLY SUPPORTED</td>\n      <td>(a) holds, equal-weight mean wins outright (+0...</td>\n    </tr>\n    <tr>\n      <th>H7</th>\n      <td>Physics + ML beats conceptual-only averaging</td>\n      <td>FALSIFIED</td>\n      <td>KGE 0.889 vs 0.906 (but NSE 0.879 vs 0.864, i....</td>\n    </tr>\n    <tr>\n      <th>H8</th>\n      <td>GR4J |x2| &gt; 1 mm/d</td>\n      <td>FALSIFIED (narrowly)</td>\n      <td>x2 = -0.954 mm/d = 70 % of mean calibration Q;...</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nFive falsified outright, one falsified narrowly, one partly supported, one supported. That is a healthy\npre-registration record: the hypotheses were sharp enough to be wrong.\n\n# Discussion {#sec-discussion}\n\n## Complexity versus performance\n\n::: {#cell-fig-complexity .cell execution_count=23}\n``` {.python .cell-code}\ns = met.loc[[SLOT_ID[i] for i in range(1, 6)]]\nfig, ax = plt.subplots(1, 2, figsize=(11, 4))\nfor a, k in zip(ax, [\"KGE\", \"NSE\"]):\n    a.semilogx(s[\"n_fitted\"], s[k], \"o\", ms=9, color=\"#1f77b4\")\n    for i, r in s.iterrows():\n        a.annotate(LABEL[i].split(\" · \")[1], (r[\"n_fitted\"], r[k]), fontsize=7,\n                   xytext=(4, 5), textcoords=\"offset points\")\n    a.axhline(met.loc[\"bench_persistence_1day\", k], ls=\":\", color=\"crimson\", lw=1)\n    a.set_xlabel(\"fitted quantities (parameters / coefficients / weights)\"); a.set_ylabel(k)\nfig.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Evaluation KGE and NSE against the number of fitted quantities (log axis). The dotted line is the one-day-persistence benchmark. Neither metric increases with complexity.](16_evaluation_files/figure-html/fig-complexity-output-1.png){#fig-complexity width=1631 height=589}\n:::\n:::\n\n\nThe complexity gradient a03 designed — 4 → 9 → 15 → 26 → 30,801 fitted quantities — produces **no\nmonotone gain in KGE** on the held-out window, and its apparent positive association with NSE\n(@sec-h1) is carried by one model, the ridge, whose place in the gradient was supposed to be the floor. The 4-parameter GR4J has the highest single-model\nKGE; the 26-quantity regression has the highest NSE of anything in the study; the\n30,801-weight-per-member LSTM is last on KGE. The calibration window told the opposite story\n(objective 0.865 → 0.885 → 0.919 → 0.926 → 0.938, monotone in complexity), and the internal-validation\nwindow already hinted at the reversal by promoting the ridge above GR4J and HBV-light.\n\nThe generalisable statement is not \"simple models are better\". It is that **on a humid, energy-limited,\nsnow-free, unregulated basin with 40 years of clean lumped forcing, the marginal information content of\nadditional model structure is small, and it is dominated by the mismatch between the calibration climate\nand the application climate.** a04 quantified that mismatch cost in advance (0.02–0.06 objective units of\nregret between *objective functions* alone); the model-structure differences measured here, 0.004–0.03\nKGE among the top seven, are of the same order or smaller.\n\n## High and low flows, and the wetter window\n\n::: {#cell-fig-bias-strata .cell execution_count=24}\n``` {.python .cell-code}\nM = sims[sims.in_metric_window]\no = M[\"Q_obs\"].to_numpy()\nqs = np.quantile(o, [0, .2, .4, .6, .8, 1.0])\nlabels = [f\"Q{i*20}-{(i+1)*20}%\" for i in range(5)]\nfig, ax = plt.subplots(figsize=(9, 4))\nw = 0.15\nfor j, s_ in enumerate(range(1, 6)):\n    v = []\n    for i in range(5):\n        m = (o >= qs[i]) & (o <= qs[i + 1])\n        v.append((M[f\"model_{s_}\"].to_numpy()[m] - o[m]).mean())\n    ax.bar(np.arange(5) + (j - 2) * w, v, width=w, label=LABEL[SLOT_ID[s_]])\nax.axhline(0, color=\"k\", lw=0.8); ax.set_ylabel(\"mean error (mm/d)\")\nax.set_xticks(range(5)); ax.set_xticklabels(labels); ax.legend(fontsize=7)\nfig.tight_layout(); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Volume error by flow stratum: the mean of (simulated - observed) inside observed-flow quintiles of the metric window. Positive = over-prediction. This is a diagnostic, not a reported metric.](16_evaluation_files/figure-html/fig-bias-strata-output-1.png){#fig-bias-strata width=1340 height=590}\n:::\n:::\n\n\nThe evaluation window is the wettest stretch of the record (a02: mean-Q ratio 1.29, runoff ratio\n0\\.407 against 0.35 on calibration) but its maximum flow,\n45\\.9 mm/d, is **below** the calibration maximum\n64\\.0 mm/d — there is no magnitude extrapolation, only a wetness\nshift. The models' response to that shift is consistent and unflattering: they over-predict the low and\nmiddle strata and under-predict the top stratum, which is precisely the pattern that produces β > 1 (H5)\ntogether with the systematic under-prediction of the January 1950 peak (@fig-events: all five models miss\nthe 45.9 mm/d peak, by 9–21 mm/d).\n\nWhich models extrapolate better? By the KGE degradation in @sec-h4, the order is\nGR4J (0\\.020) ≈ ARX ridge (0\\.020)\n< HBV-light (0\\.062) < SAC-SMA (0\\.075)\n< LSTM (0\\.129) — i.e. **inversely ordered by the amount of state and\nthe number of fitted quantities**, with the single exception that the ridge (26 quantities) transfers as\nwell as the 4-parameter GR4J and actually gains on NSE. Models with long-memory stores and many degrees of\nfreedom carry their calibration climate with them.\n\n## Failure modes\n\n* **LSTM, first 180 days.** KGE 0.477 in block 1 against 0.957 in block 3 (@tbl-blocks). Zero-initialised\n  recurrent state plus a 180-day lookback plus the wettest year of the record. This is the largest single\n  failure in the study, and it is a *protocol-interaction* failure — 92 warm-up days are not enough for\n  a 180-day-memory model — not necessarily a failure of the architecture.\n* **Seed dependence of the LSTM.** 0\\.060 KGE standard deviation\n  across three seeds, versus a total top-seven spread of 0\\.038.\n  a15b's own handoff flagged that its seed spread (0.0069 on internal validation) was 69× a10's\n  convergence tolerance; on the evaluation window the spread is an order of magnitude larger again.\n* **Peak under-prediction, all models.** Every model misses the 1950-01-08 event (@fig-events). SAC-SMA\n  is the least bad on the 20 largest days (NSE 0\\.506).\n* **Fitted ensemble weights.** See H6: NNLS weights fitted on 2,557 held-out calibration days still\n  transferred worse than equal weights.\n* **No candidate produced a NaN or a negative flow**, and the minimum simulated flow over all ten\n  candidates is 0\\.0222 mm/d, comfortably positive on a perennial river.\n\n## Comparison with published values at this gauge\n\n::: {#tbl-lit .cell tbl-cap='a01\\'s independently published benchmarks AT USGS 02472000, next to this study\\'s evaluation-window numbers. The literature values come from different periods and different calibration protocols and are indicative only.' execution_count=25}\n``` {.python .cell-code}\nlit = pd.DataFrame([\n (\"NWM v2.1 (a01)\", 0.72, 0.71), (\"SAC-SMA, literature (a01)\", np.nan, 0.796),\n (\"HBV, literature (a01)\", np.nan, 0.819), (\"FUSE (a01)\", np.nan, 0.78),\n (\"VIC (a01)\", np.nan, 0.72), (\"mHM (a01)\", np.nan, 0.70),\n (\"regional LSTM, CAMELS (a01)\", np.nan, 0.84),\n (\"— this study —\", np.nan, np.nan),\n (\"ens_mean_all5 (selected)\", K(\"ens_mean_all5\"), N(\"ens_mean_all5\")),\n (\"GR4J (best single KGE)\", K(\"gr4j\"), N(\"gr4j\")),\n (\"ARX-API ridge (best NSE)\", K(\"arx_api_ridge\"), N(\"arx_api_ridge\")),\n (\"SAC-SMA, this study\", K(\"sacsma\"), N(\"sacsma\")),\n (\"HBV-light, this study\", K(\"hbv_light\"), N(\"hbv_light\")),\n (\"LSTM, this study (budgeted)\", K(\"lstm_seq2seq_fast\"), N(\"lstm_seq2seq_fast\")),\n], columns=[\"source\", \"KGE\", \"NSE\"]).set_index(\"source\").round(3)\nlit\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>KGE</th>\n      <th>NSE</th>\n    </tr>\n    <tr>\n      <th>source</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>NWM v2.1 (a01)</th>\n      <td>0.720</td>\n      <td>0.710</td>\n    </tr>\n    <tr>\n      <th>SAC-SMA, literature (a01)</th>\n      <td>NaN</td>\n      <td>0.796</td>\n    </tr>\n    <tr>\n      <th>HBV, literature (a01)</th>\n      <td>NaN</td>\n      <td>0.819</td>\n    </tr>\n    <tr>\n      <th>FUSE (a01)</th>\n      <td>NaN</td>\n      <td>0.780</td>\n    </tr>\n    <tr>\n      <th>VIC (a01)</th>\n      <td>NaN</td>\n      <td>0.720</td>\n    </tr>\n    <tr>\n      <th>mHM (a01)</th>\n      <td>NaN</td>\n      <td>0.700</td>\n    </tr>\n    <tr>\n      <th>regional LSTM, CAMELS (a01)</th>\n      <td>NaN</td>\n      <td>0.840</td>\n    </tr>\n    <tr>\n      <th>— this study —</th>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>ens_mean_all5 (selected)</th>\n      <td>0.902</td>\n      <td>0.893</td>\n    </tr>\n    <tr>\n      <th>GR4J (best single KGE)</th>\n      <td>0.894</td>\n      <td>0.829</td>\n    </tr>\n    <tr>\n      <th>ARX-API ridge (best NSE)</th>\n      <td>0.889</td>\n      <td>0.918</td>\n    </tr>\n    <tr>\n      <th>SAC-SMA, this study</th>\n      <td>0.875</td>\n      <td>0.863</td>\n    </tr>\n    <tr>\n      <th>HBV-light, this study</th>\n      <td>0.882</td>\n      <td>0.829</td>\n    </tr>\n    <tr>\n      <th>LSTM, this study (budgeted)</th>\n      <td>0.797</td>\n      <td>0.846</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nEvery model in this study, including the weakest, lands at or above the published at-gauge band. That is\nexpected and should not be read as a claim of superiority: a01's benchmarks are mostly **regional**\ncalibrations (one parameter transfer scheme over hundreds of basins) evaluated on different decades,\nwhereas every model here was calibrated on 36 years of this basin's own record. The comparison that is\nactually informative is the *spread*: published structures at this gauge differ by ~0.12 NSE\n(0.70–0.82), and the five structures here differ by\n0\\.090 NSE —\nthe same order of magnitude, from a completely different set of structures. Structure choice matters about\nas much as it matters in the literature, which is to say: less than the period you evaluate on.\n\n## Comparison with the user's prior study on the same data file {#sec-prior}\n\n::: {#tbl-prior .cell tbl-cap='The 528 Fundamentals-of-Systems-Approach study (2025) used the IDENTICAL data file (md5 a5c922ef2b009a63ba6089172fd90cc2) and prescribes exactly the evaluation protocol used here, but reports its headline numbers on a DIFFERENT split. KGEss is Knoben et al. (2019) skill score; KGE = KGEss*sqrt(2) - 0.4142.' execution_count=26}\n``` {.python .cell-code}\ndef kge_from_ss(x): return x * np.sqrt(2) - 0.4142\nprior = pd.DataFrame([\n (\"6-parameter DSM, training (first 3/4)\", 0.856), (\"6-parameter DSM, testing (last 1/4)\", 0.803),\n (\"upgraded DSM case 1, training\", 0.903), (\"upgraded DSM case 1, testing\", 0.850),\n (\"upgraded DSM case 2, training\", 0.871), (\"upgraded DSM case 2, testing\", 0.856),\n], columns=[\"prior study run\", \"KGEss reported\"])\nprior[\"KGE (2009)\"] = kge_from_ss(prior[\"KGEss reported\"]).round(3)\nprior.set_index(\"prior study run\")\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>KGEss reported</th>\n      <th>KGE (2009)</th>\n    </tr>\n    <tr>\n      <th>prior study run</th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>6-parameter DSM, training (first 3/4)</th>\n      <td>0.856</td>\n      <td>0.796</td>\n    </tr>\n    <tr>\n      <th>6-parameter DSM, testing (last 1/4)</th>\n      <td>0.803</td>\n      <td>0.721</td>\n    </tr>\n    <tr>\n      <th>upgraded DSM case 1, training</th>\n      <td>0.903</td>\n      <td>0.863</td>\n    </tr>\n    <tr>\n      <th>upgraded DSM case 1, testing</th>\n      <td>0.850</td>\n      <td>0.788</td>\n    </tr>\n    <tr>\n      <th>upgraded DSM case 2, training</th>\n      <td>0.871</td>\n      <td>0.818</td>\n    </tr>\n    <tr>\n      <th>upgraded DSM case 2, testing</th>\n      <td>0.856</td>\n      <td>0.796</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n``` {.python .cell-code}\nbest_prior = kge_from_ss(0.856)\nMarkdown(f\"\"\"\nThree differences make these numbers **not directly comparable** with @tbl-main, and all three must be\nstated before any number is put beside another:\n\n1. **Different metric.** The prior study reports $KGE_{{ss}}$, the Knoben et al. [-@knoben2019]\n   benchmarked skill score $ (KGE + 0.4142)/\\\\sqrt{{2}} $, not KGE itself. Converted, its best\n   out-of-sample figure $KGE_{{ss}} = 0.856$ is **KGE {f(best_prior,3)}** and its baseline model's\n   testing figure $KGE_{{ss}} = 0.803$ is **KGE {f(kge_from_ss(0.803),3)}**. This report quotes KGE only,\n   per `config/project.yaml`.\n2. **Different window.** Those figures are computed on the **last quarter of the record**\n   (≈ WY1979–WY1988), a period that lies *inside* what this project calls calibration. The 1,003-day\n   window scored here (1949-01-01…1951-09-30) is the wettest stretch of the record and was held out from\n   every agent but this one. The prior study *does* prescribe exactly this 1948-10-01…1951-09-30 run with\n   a Oct–Dec 1948 warm-up (FinalReport.qmd § 5.4.5) — that is where this project's period definition\n   comes from — but it uses that window for model *development and demonstration*, not as its held-out\n   test set.\n3. **Different initialisation rule.** The prior study initialises its lower-zone state from the\n   **observed** flow on the first day of the window, $XX_2(0) \\\\approx QQ^{{obs}}(1)/\\\\theta K_{{2Q}}$\n   (FinalReport.qmd § 5.4.4). Every model in this project uses parameter-derived initial states and never\n   reads an observation inside the evaluation window (a03 decision 3). The protocol here is therefore\n   strictly harder on the first weeks of the window — which is exactly where @tbl-blocks shows the\n   largest errors.\n\nWith those caveats: the selected model of this study scores KGE {f(sel['KGE'],3)} on 1,003 held-out days,\nagainst KGE {f(best_prior,3)} for the prior study's best model on its own held-out quarter. The gap is\nreal but a fair share of it is period, not method.\n\"\"\")\n```\n\nThree differences make these numbers **not directly comparable** with @tbl-main, and all three must be\nstated before any number is put beside another:\n\n1. **Different metric.** The prior study reports $KGE_{ss}$, the Knoben et al. [-@knoben2019]\n   benchmarked skill score $ (KGE + 0.4142)/\\sqrt{2} $, not KGE itself. Converted, its best\n   out-of-sample figure $KGE_{ss} = 0.856$ is **KGE 0.796** and its baseline model's\n   testing figure $KGE_{ss} = 0.803$ is **KGE 0.721**. This report quotes KGE only,\n   per `config/project.yaml`.\n2. **Different window.** Those figures are computed on the **last quarter of the record**\n   (≈ WY1979–WY1988), a period that lies *inside* what this project calls calibration. The 1,003-day\n   window scored here (1949-01-01…1951-09-30) is the wettest stretch of the record and was held out from\n   every agent but this one. The prior study *does* prescribe exactly this 1948-10-01…1951-09-30 run with\n   a Oct–Dec 1948 warm-up (FinalReport.qmd § 5.4.5) — that is where this project's period definition\n   comes from — but it uses that window for model *development and demonstration*, not as its held-out\n   test set.\n3. **Different initialisation rule.** The prior study initialises its lower-zone state from the\n   **observed** flow on the first day of the window, $XX_2(0) \\approx QQ^{obs}(1)/\\theta K_{2Q}$\n   (FinalReport.qmd § 5.4.4). Every model in this project uses parameter-derived initial states and never\n   reads an observation inside the evaluation window (a03 decision 3). The protocol here is therefore\n   strictly harder on the first weeks of the window — which is exactly where @tbl-blocks shows the\n   largest errors.\n\nWith those caveats: the selected model of this study scores KGE 0.902 on 1,003 held-out days,\nagainst KGE 0.796 for the prior study's best model on its own held-out quarter. The gap is\nreal but a fair share of it is period, not method.\n\n\n\n# Recommendations {#sec-recs}\n\n1. **Report the equal-weight five-model mean as the study's model, with the caveat that GR4J alone is\n   within 0.008 KGE of it at 1/10,000th of the fitted complexity.** If one model must be shipped and\n   maintained, ship GR4J; if the goal is the best expected score, ship the mean.\n2. **Re-run slot 5 properly and re-evaluate it as a documented amendment.** ISSUE-006 is still open — the\n   runner never passes `timeout=` or a pruner to `study.optimize` — and the slot-5 number in @tbl-main\n   comes from a 7.6-minute search. The LSTM's block-3 performance (KGE 0.957, the best of any candidate\n   in that sub-period) says the architecture is not the problem.\n3. **Fix the warm-up/lookback mismatch before trusting any sequence model on this window.** A 180-day\n   lookback and a 92-day warm-up are incompatible. Either the evaluation protocol must offer more\n   context (it cannot: the record starts at the window's first day) or sequence models must be given a\n   state-initialisation procedure that does not require it, e.g. a cyclic spin-up analogous to slot 4's.\n4. **Stop fitting ensemble weights on this record.** H6(b) shows NNLS on 2,557 held-out calibration days\n   still transferred worse than equal weights. If fitted weights are attempted again, fit them on\n   *multiple* climatically contrasting blocks, or shrink them towards equal weights.\n5. **Take ISSUE-004(b) seriously as a scientific result, not a bug report.** A 19-coefficient linear\n   model in Box–Cox space with API predictors has the highest NSE of any model in this study on a\n   held-out window. It should be the mandatory baseline in any follow-up, and its structure (short\n   memory, no storage ceiling, bias factor frozen at fit time) is worth analysing rather than\n   explaining away.\n6. **Do not draw structural conclusions from a 1,003-day window.** @tbl-paired shows that 8 of 9 KGE\n   differences from the winner are statistically indistinguishable from zero. A leave-one-water-year-out\n   or k-fold-over-water-years protocol inside the calibration record would give far more discriminating\n   power than this single held-out block, at the cost of the clean pre-registration this study has.\n\n# Reproducibility {#sec-repro}\n\n``` {.python .cell-code}\nimport platform, numpy, scipy, sklearn, torch\nMarkdown(f\"\"\"\n~~~bash\n# from the repository root, inside conda env `leafriver`\nexport LR_AGENT=a16\npython results/evaluation/freeze_weights.py     # ensemble weights, calibration data only\npython results/evaluation/run_evaluation.py     # simulations, metrics, bootstrap, selection\npython results/evaluation/make_figures.py       # figures + paired bootstrap vs the winner\nquarto render reports/16_evaluation.qmd\npython -m pytest -q tests                       # 276 passed\n~~~\n\n| item | value |\n|---|---|\n| python | {platform.python_version()} |\n| numpy / pandas / scipy | {numpy.__version__} / {pd.__version__} / {scipy.__version__} |\n| scikit-learn / torch | {sklearn.__version__} / {torch.__version__} |\n| platform | {platform.platform()} |\n| seed | 42 (config `reproducibility.random_seed`) |\n| bootstrap | 30-day moving blocks, 2,000 resamples, `default_rng(42)` |\n| frozen-weights git tag | `backup/a16-evaluator-20260916-171945` |\n\n**Outputs.** `results/evaluation/`: `simulations.parquet` (1,095 rows × obs, P, PET, 5 models, 5\nensembles, 3 benchmarks, 3 LSTM members, 1 sensitivity variant), `metrics.csv`, `metrics_blocks.csv`,\n`bootstrap.csv`, `paired_bootstrap.csv`, `paired_bootstrap_vs_winner.csv`, `selection.json`,\n`hypotheses.json`, `hypotheses_addendum.json`, `ensemble_weights.json`, `diagnostics.json`.\n`results/figures/a16_*.png`: 10 figures.\n\n**Leakage statement.** The evaluation window was read exactly once, by this agent, after every\ncalibration artefact and every ensemble weight had been written and committed. `src/common/data.py`\nraises `PermissionError` on `slice_run(df, \"evaluation\")` unless `LR_AGENT == \"a16\"` *and*\n`allow_evaluation=True`; the whole test suite passes with `LR_AGENT` unset. No parameter, weight,\nscaling constant, member choice or model structure was changed after the first evaluation number was\nproduced. The one residual concern is recorded in @sec-residual.\n\"\"\")\n```\n\n~~~bash\n# from the repository root, inside conda env `leafriver`\nexport LR_AGENT=a16\npython results/evaluation/freeze_weights.py     # ensemble weights, calibration data only\npython results/evaluation/run_evaluation.py     # simulations, metrics, bootstrap, selection\npython results/evaluation/make_figures.py       # figures + paired bootstrap vs the winner\nquarto render reports/16_evaluation.qmd\npython -m pytest -q tests                       # 276 passed\n~~~\n\n| item | value |\n|---|---|\n| python | 3.11.16 |\n| numpy / pandas / scipy | 2.0.2 / 3.0.5 / 1.17.1 |\n| scikit-learn / torch | 1.9.1 / 2.13.0 |\n| platform | macOS-27.0-arm64-arm-64bit |\n| seed | 42 (config `reproducibility.random_seed`) |\n| bootstrap | 30-day moving blocks, 2,000 resamples, `default_rng(42)` |\n| frozen-weights git tag | `backup/a16-evaluator-20260916-171945` |\n\n**Outputs.** `results/evaluation/`: `simulations.parquet` (1,095 rows × obs, P, PET, 5 models, 5\nensembles, 3 benchmarks, 3 LSTM members, 1 sensitivity variant), `metrics.csv`, `metrics_blocks.csv`,\n`bootstrap.csv`, `paired_bootstrap.csv`, `paired_bootstrap_vs_winner.csv`, `selection.json`,\n`hypotheses.json`, `hypotheses_addendum.json`, `ensemble_weights.json`, `diagnostics.json`.\n`results/figures/a16_*.png`: 10 figures.\n\n**Leakage statement.** The evaluation window was read exactly once, by this agent, after every\ncalibration artefact and every ensemble weight had been written and committed. `src/common/data.py`\nraises `PermissionError` on `slice_run(df, \"evaluation\")` unless `LR_AGENT == \"a16\"` *and*\n`allow_evaluation=True`; the whole test suite passes with `LR_AGENT` unset. No parameter, weight,\nscaling constant, member choice or model structure was changed after the first evaluation number was\nproduced. The one residual concern is recorded in @sec-residual.\n\n\n\n## The leakage concern that cannot be fully ruled out {#sec-residual}\n\nOne: **the evaluation window was chosen by the user, in advance, from a prior study that had already\nlooked at it.** `config/project.yaml → periods` takes its definition verbatim from the 2025 report\n(@sec-prior), which ran, plotted and discussed exactly these 1,095 days. No parameter of any model in\n*this* project was fitted on those days — that is verifiable and was verified — but the *period itself*\nis not a blind draw, and the project's model portfolio (a03) was designed by agents who had read a02's\ndescription of that period's wetness. a02 was explicitly permitted to describe the whole record, and it\ndid: \"the evaluation window is the wettest part of the record, mean Q ratio 1.29\" appears in\n`context/CONTEXT.md` and was available to every builder. That is a soft, unquantifiable influence on\nmodel choice, and it cannot be undone after the fact. It should be assumed to bias the results\n*optimistically* by an unknown, probably small, amount.\n\nTwo smaller ones, both recorded rather than resolved: (i) slot 5's hyperparameters, early stopping and\nseed ensemble were all selected on the calibration internal-validation window, so its *calibration*\nnumbers are optimistically biased (a09's own open issue) and the H4 degradation is correspondingly\ninflated — though the verdict survives any plausible correction, since its drop exceeds the next largest\nby 0.041 NSE; (ii) the NNLS weights were fitted on calibration data but on the *same* window that a11–a15\nused for model selection, so `ens_nnls_calibration` inherits that window's selection bias — which is part\nof why it under-performs here (H6b).\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "16_evaluation_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}