{
  "hash": "33a398ffc37ccdf3f0b2c9eb9f18059c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Leaf River daily data: description, quality evaluation and hydrological signatures\"\nsubtitle: \"Agent 2 (a02-data-analyst) — phase P1\"\nauthor: \"a02-data-analyst\"\ndate: 2026-09-15\njupyter: leafriver\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    fig-dpi: 150\nbibliography: references.bib\n---\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport os, sys, json, warnings\nfrom pathlib import Path\n\nROOT = Path.cwd()\nwhile not (ROOT / \"config\" / \"project.yaml\").exists():\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT)); os.chdir(ROOT)\n\nimport numpy as np, pandas as pd\nimport matplotlib as mpl, matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\nwarnings.filterwarnings(\"ignore\")\n\nfrom src.common.data import load_data, load_config\n\nCFG   = load_config()\nSEED  = CFG[\"reproducibility\"][\"random_seed\"]\nnp.random.seed(SEED)\nFIG   = ROOT / \"results\" / \"figures\"; FIG.mkdir(parents=True, exist_ok=True)\nsns.set_theme(style=\"whitegrid\", context=\"notebook\")\nmpl.rcParams.update({\"figure.dpi\": 110, \"savefig.dpi\": 150, \"savefig.bbox\": \"tight\",\n                     \"axes.titlesize\": 10, \"axes.labelsize\": 9,\n                     \"xtick.labelsize\": 8, \"ytick.labelsize\": 8, \"legend.fontsize\": 8})\n\ndef save(fig, name):\n    \"\"\"Save a figure under results/figures/a02_<name>.png and return the path.\"\"\"\n    p = FIG / f\"a02_{name}.png\"; fig.savefig(p); return p\n\ndef md(obj, **kw):\n    \"\"\"Markdown table from a DataFrame/Series (pandas .to_markdown).\"\"\"\n    from IPython.display import Markdown\n    return Markdown(obj.to_markdown(**kw))\n\n# --- canonical data (ONLY via src/common/data.py) ---------------------------------\ndf = load_data()\n\n# --- derived columns live in a SEPARATE frame used for the report only ------------\nd = df.copy()\nd[\"wy\"]     = d.index.year + (d.index.month >= 10).astype(int)   # water year (Oct-Sep)\nd[\"month\"]  = d.index.month\nd[\"doy\"]    = d.index.dayofyear\nd[\"season\"] = pd.Categorical(\n    np.select([d.month.isin([12,1,2]), d.month.isin([3,4,5]), d.month.isin([6,7,8])],\n              [\"DJF\",\"MAM\",\"JJA\"], \"SON\"), [\"DJF\",\"MAM\",\"JJA\",\"SON\"], ordered=True)\n\nP, PET, Q = d[\"P\"], d[\"PET\"], d[\"Q\"]\nPv, PETv, Qv = P.to_numpy(), PET.to_numpy(), Q.to_numpy()\n\n# --- authoritative period windows (config/project.yaml -> periods.definition) -----\nPERDEF = CFG[\"periods\"][\"definition\"]\nPER    = CFG[\"periods\"][PERDEF]\nWIN = {\n    \"evaluation run\"      : PER[\"evaluation\"][\"run\"],\n    \"evaluation warm-up\"  : PER[\"evaluation\"][\"warmup\"],\n    \"evaluation metric\"   : PER[\"evaluation\"][\"metric\"],\n    \"calibration run\"     : PER[\"calibration\"][\"run\"],\n    \"calibration warm-up\" : PER[\"calibration\"][\"warmup\"],\n    \"calibration metric\"  : PER[\"calibration\"][\"metric\"],\n    \"internal train\"      : PER[\"calibration_internal\"][\"train\"],\n    \"internal validation\" : PER[\"calibration_internal\"][\"validation\"],\n}\ndef win(name):\n    a, b = WIN[name]; return d.loc[a:b]\n\nCAL  = win(\"calibration metric\")     # <- the ONLY frame downstream agents may derive stats from\nEVAL = win(\"evaluation metric\")      # <- EDA description only (no model quantity derived from it)\nKEY  = {}                            # collected key numbers -> handoff\n```\n:::\n\n\n# Summary {#sec-summary}\n\n::: {#summary-numbers .cell execution_count=2}\n``` {.python .cell-code}\nann = d.groupby(\"wy\")[[\"P\",\"PET\",\"Q\"]].sum().loc[1949:1988]\nKEY[\"P_mean_mm_yr\"]  = float(P.mean()*365.25)\nKEY[\"PET_mean_mm_yr\"]= float(PET.mean()*365.25)\nKEY[\"Q_mean_mm_yr\"]  = float(Q.mean()*365.25)\nKEY[\"runoff_ratio\"]  = float(Q.sum()/P.sum())\nKEY[\"Q_skewness\"]    = float(Q.skew())\nKEY[\"pct_zero_P\"]    = float(100*(P==0).mean())\nprint(f\"record          : {d.index[0].date()} .. {d.index[-1].date()}  ({len(d)} days = WY1949-WY1988)\")\nprint(f\"P   mean        : {P.mean():.3f} mm/d = {P.mean()*365.25:7.1f} mm/yr   (WY range {ann.P.min():.0f}-{ann.P.max():.0f})\")\nprint(f\"PET mean        : {PET.mean():.3f} mm/d = {PET.mean()*365.25:7.1f} mm/yr   (WY range {ann.PET.min():.0f}-{ann.PET.max():.0f})\")\nprint(f\"Q   mean        : {Q.mean():.3f} mm/d = {Q.mean()*365.25:7.1f} mm/yr   (WY range {ann.Q.min():.0f}-{ann.Q.max():.0f})\")\nprint(f\"runoff ratio    : {Q.sum()/P.sum():.3f}   aridity PET/P = {PET.sum()/P.sum():.2f}\")\nprint(f\"daily Q skewness: {Q.skew():.2f}   kurtosis {Q.kurtosis():.1f}   Q95/Q5 dynamic range {Q.quantile(.95)/Q.quantile(.05):.0f}x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrecord          : 1948-10-01 .. 1988-09-30  (14610 days = WY1949-WY1988)\nP   mean        : 3.920 mm/d =  1431.7 mm/yr   (WY range 940-2057)\nPET mean        : 2.909 mm/d =  1062.4 mm/yr   (WY range 968-1204)\nQ   mean        : 1.370 mm/d =   500.3 mm/yr   (WY range 180-1053)\nrunoff ratio    : 0.349   aridity PET/P = 0.74\ndaily Q skewness: 6.85   kurtosis 76.6   Q95/Q5 dynamic range 47x\n```\n:::\n:::\n\n\n**Headline findings**\n\n1. The file is **clean**: 14,610 rows, no gaps, no duplicates, no NaN, no negatives, one PET value of exactly\n   0.0 mm/d (1966-01-14, physically plausible mid-winter value, not a missing-data code). Q is strictly\n   positive (min 0.069 mm/d) — the river is **perennial**, so log/Box-Cox transforms are safe without offsets.\n2. **Units are mm/day and the basin area is ~1,950 km²** (@sec-units): the discrete quantum of the Q series\n   (0.0012544 mm/d) is exactly 1 ft³/s spread over 1,950 km² (753 mi²), i.e. the series was converted from\n   USGS daily-mean discharge in cfs. This matches USGS 02472000 Leaf River near Collins, MS (752 mi²).\n3. **The record starts 1948-10-01** — confirmed independently from the PET/P/Q seasonal phase\n   (@sec-alignment). This verifies the resolution of ISSUE-001 (`periods.definition: dates`).\n4. **PET is *not* a repeated climatology**: same-day-of-year inter-annual SD is 1.30 mm/d against a seasonal\n   amplitude of 1.83 mm/d — PET carries real daily weather information (@sec-pet).\n5. The catchment is **strongly nonlinear**: event runoff coefficients range 0.004–0.45 over 31 isolated\n   events and correlate with antecedent flow (r = 0.57) and event depth (r = 0.60) (@sec-events).\n6. **Memory**: recession constant k ≈ 0.90 d⁻¹ (9 d residence time), log-Q ACF e-folding 48 d, and a linear\n   P-lag model keeps gaining skill up to ~1 year (R² 0.59 at 10 d → 0.63 at 90 d → 0.65 at 365 d)\n   → ≥180-day input sequences for ML models, ≥365-day warm-up for conceptual models (@sec-implications).\n7. **The evaluation period is wetter than calibration**: eval-metric mean Q is 1.29× the calibration mean and\n   WY1949 is the wettest year of the 40-year record (P rank 1/40) — a genuine extrapolation risk (@sec-periods).\n\n# File & structure {#sec-structure}\n\n::: {#tbl-file .cell execution_count=3}\n``` {.python .cell-code}\nimport hashlib, subprocess\nraw_path = ROOT / CFG[\"data\"][\"raw_file\"]\nmd5 = hashlib.md5(raw_path.read_bytes()).hexdigest()\nlines = raw_path.read_text().strip().split(\"\\n\")\nprint(\"file        :\", CFG[\"data\"][\"raw_file\"])\nprint(\"size        :\", f\"{raw_path.stat().st_size/1e6:.2f} MB\")\nprint(\"md5         :\", md5)\nprint(\"lines       :\", len(lines), \" (config n_rows =\", CFG[\"data\"][\"n_rows\"], \")\")\nprint(\"first line  :\", repr(lines[0]))\nprint(\"format      : 3 whitespace-delimited columns, no header, %.7e scientific notation\")\nprint(\"dtypes      :\", {k: str(v) for k, v in df.dtypes.items()})\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfile        : data/raw/LeafRiverDaily.txt\nsize        : 0.72 MB\nmd5         : a5c922ef2b009a63ba6089172fd90cc2\nlines       : 14610  (config n_rows = 14610 )\nfirst line  : '0.0000000e+00   4.6004000e+00   2.8995124e-01'\nformat      : 3 whitespace-delimited columns, no header, %.7e scientific notation\ndtypes      : {'P': 'float64', 'PET': 'float64', 'Q': 'float64', 'row': 'int64'}\n```\n:::\n:::\n\n\nThe md5 `a5c922ef2b009a63ba6089172fd90cc2` is identical to the file used in the user's benchmark study,\nwhich is the documentary basis for the period definition (see @sec-alignment).\n\n## Integrity checks\n\n::: {#tbl-integrity .cell execution_count=4}\n``` {.python .cell-code}\nchecks = {}\nchecks[\"n rows\"]                    = len(df)\nchecks[\"expected rows (40 WY)\"]     = 40*365 + 10       # 10 leap days 1952..1988\nchecks[\"date index continuous\"]     = bool((d.index.to_series().diff().dropna() == pd.Timedelta(\"1D\")).all())\nchecks[\"duplicate dates\"]           = int(d.index.duplicated().sum())\nchecks[\"NaN (P/PET/Q)\"]             = int(df[[\"P\",\"PET\",\"Q\"]].isna().sum().sum())\nchecks[\"negative values\"]           = int((df[[\"P\",\"PET\",\"Q\"]] < 0).sum().sum())\nchecks[\"exact zeros P\"]             = int((P == 0).sum())\nchecks[\"exact zeros PET\"]           = int((PET == 0).sum())\nchecks[\"exact zeros Q\"]             = int((Q == 0).sum())\nchecks[\"min Q (mm/d)\"]              = float(Q.min())\nmd(pd.Series(checks, name=\"value\").to_frame())\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n|                       |         value |\n|:----------------------|--------------:|\n| n rows                | 14610         |\n| expected rows (40 WY) | 14610         |\n| date index continuous |     1         |\n| duplicate dates       |     0         |\n| NaN (P/PET/Q)         |     0         |\n| negative values       |     0         |\n| exact zeros P         |  8019         |\n| exact zeros PET       |     1         |\n| exact zeros Q         |     0         |\n| min Q (mm/d)          |     0.0690337 |\n:::\n:::\n\n\n::: {#tbl-runs .cell execution_count=5}\n``` {.python .cell-code}\ndef const_runs(v):\n    g = np.r_[0, (np.diff(v) != 0).cumsum()]\n    s = pd.Series(v).groupby(g)\n    size, first = s.size(), s.first().to_numpy()\n    return size, first\n\nrows = []\nfor name, v in [(\"P\", Pv), (\"PET\", PETv), (\"Q\", Qv)]:\n    size, first = const_runs(v)\n    nz = size[(size >= 5) & (first > 0)]\n    z  = size[(size >= 5) & (first == 0)]\n    rows.append(dict(variable=name, longest_run=int(size.max()),\n                     runs_ge5_nonzero=int(len(nz)), runs_ge5_zero=int(len(z)),\n                     longest_nonzero_run=int(nz.max()) if len(nz) else 0))\nruns_tbl = pd.DataFrame(rows).set_index(\"variable\")\nmd(runs_tbl)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n| variable   |   longest_run |   runs_ge5_nonzero |   runs_ge5_zero |   longest_nonzero_run |\n|:-----------|--------------:|-------------------:|----------------:|----------------------:|\n| P          |            51 |                  0 |             556 |                     0 |\n| PET        |             2 |                  0 |               0 |                     0 |\n| Q          |            10 |                 20 |               0 |                    10 |\n:::\n:::\n\n\n*Constant runs.* P has 556 runs of ≥5 identical values but **all of them are zeros** (dry spells, longest\n51 days) — no infill signature. PET never repeats more than twice in a row. Q has 20 runs of ≥5 identical\nvalues (longest 10 days), all at very low flow; these are the fingerprint of USGS reporting discharge to\n3 significant figures in cfs during stable recessions, not infilling.\n\n## Units, numeric precision and implied basin area {#sec-units}\n\n::: {#tbl-units .cell execution_count=6}\n``` {.python .cell-code}\nqu = np.sort(Q.unique()); dq = np.diff(qu)\nquantum = float(np.median(dq[(dq > 0.8*0.001259) & (dq < 1.2*0.001259)]))\nCFS = 0.028316846592           # m3/s per ft3/s\narea_m2 = CFS*86400*1000/quantum\nprint(f\"distinct Q values                : {len(qu)}\")\nprint(f\"modal quantum of the Q series    : {quantum:.7f} mm/d\")\nprint(f\"=> basin area if 1 quantum = 1 cfs: {area_m2/1e6:.0f} km2 = {area_m2/1e6/2.58999:.0f} mi2\")\nprint(f\"=> Q range in cfs                : {qu[0]/quantum:.0f} .. {qu[-1]/quantum:.0f} cfs\")\nprint(f\"P, PET stored to 4 decimals (mm/d); Q to 8 significant digits (conversion artefact)\")\nprint(f\"annual P {P.mean()*365.25:.0f} mm/yr, PET {PET.mean()*365.25:.0f} mm/yr, Q {Q.mean()*365.25:.0f} mm/yr\"\n      f\"  -> Q/P = {Q.sum()/P.sum():.3f}\")\nKEY[\"implied_area_km2\"] = float(area_m2/1e6)\nKEY[\"Q_quantum_mm_d\"]   = quantum\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndistinct Q values                : 2324\nmodal quantum of the Q series    : 0.0012544 mm/d\n=> basin area if 1 quantum = 1 cfs: 1950 km2 = 753 mi2\n=> Q range in cfs                : 55 .. 51031 cfs\nP, PET stored to 4 decimals (mm/d); Q to 8 significant digits (conversion artefact)\nannual P 1432 mm/yr, PET 1062 mm/yr, Q 500 mm/yr  -> Q/P = 0.349\n```\n:::\n:::\n\n\nThe mm/day hypothesis is therefore not an assumption but a **measurement**: the Q column is quantised on a\ngrid whose step equals 1 cfs over 1,950 km², and the resulting annual depths (P ≈ 1,432 mm/yr,\nQ ≈ 500 mm/yr) are exactly what is expected for a humid subtropical Gulf-coastal-plain basin in\nsouth Mississippi. Agent 1 should cross-check this 1,950 km² (753 mi²) against the published USGS drainage\narea of gauge 02472000 (752 mi²).\n\n# Variable dictionary {#sec-dictionary}\n\n| name | description | units | source | resolution | range (this record) |\n|------|-------------|-------|--------|------------|---------------------|\n| `P`   | Mean areal precipitation over the basin | mm/day | NWS/USGS gauge network, basin-averaged (classic Leaf River test data set, @duan1992) | daily, 4 decimals | 0 – 221.52 |\n| `PET` | Potential evapotranspiration (daily climatic demand) | mm/day | derived (temperature/radiation based), daily varying | daily, 4 decimals | 0 – 9.11 |\n| `Q`   | Observed streamflow as depth over the basin | mm/day | USGS daily mean discharge (cfs) / area ≈ 1,950 km² | daily, quantised at 0.00125 mm/d | 0.069 – 64.01 |\n| `row` | 0-based file row (added by `src/common/data.py`) | – | – | – | 0 – 14,609 |\n\nDate index: 1948-10-01 … 1988-09-30, daily, complete (water years 1949–1988).\n\n# Overview of the three series\n\n::: {#cell-fig-overview .cell execution_count=7}\n``` {.python .cell-code}\nfig, axs = plt.subplots(3, 1, figsize=(11, 7), sharex=True)\naxs[0].bar(d.index, Pv, width=1.0, color=\"#1f77b4\", lw=0); axs[0].set_ylabel(\"P (mm/d)\")\naxs[0].invert_yaxis()\naxs[1].plot(d.index, PETv, lw=.3, color=\"#d62728\"); axs[1].set_ylabel(\"PET (mm/d)\")\naxs[2].semilogy(d.index, Qv, lw=.35, color=\"#2ca02c\"); axs[2].set_ylabel(\"Q (mm/d, log)\")\nfor ax in axs:\n    ax.axvspan(pd.Timestamp(PER[\"evaluation\"][\"run\"][0]), pd.Timestamp(PER[\"evaluation\"][\"run\"][1]),\n               color=\"grey\", alpha=.25, zorder=0)\naxs[2].set_xlabel(\"date\"); axs[0].set_title(\"Leaf River daily P, PET, Q — 1948-10-01 to 1988-09-30\")\nfig.tight_layout(); save(fig, \"overview_timeseries\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Full 40-year record. P (top, bars), PET (middle) and Q (bottom, log scale). The shaded band is the evaluation window (1948-10-01..1951-09-30), which sits at the very beginning of the record.](02_data_files/figure-html/fig-overview-output-1.png){#fig-overview width=1192 height=751}\n:::\n:::\n\n\n::: {#cell-fig-wy-multiples .cell execution_count=8}\n``` {.python .cell-code}\nfig, axs = plt.subplots(8, 5, figsize=(13, 13), sharex=False)\nfor ax, wy in zip(axs.ravel(), range(1949, 1989)):\n    s = d[d.wy == wy]\n    x = np.arange(len(s))\n    ax.semilogy(x, s.Q, lw=.5, color=\"#2ca02c\"); ax.set_ylim(0.05, 80)\n    ax2 = ax.twinx(); ax2.bar(x, s.P, width=1, color=\"#1f77b4\", alpha=.5, lw=0)\n    ax2.set_ylim(260, 0); ax2.set_yticks([]); ax2.grid(False)\n    ax.set_xticks([]); ax.tick_params(labelsize=6)\n    ax.set_title(f\"WY{wy}\", fontsize=7, color=(\"grey\" if wy <= 1951 else \"black\"))\nfig.suptitle(\"Daily Q (log, mm/d) and P (inverted, mm/d) by water year (Oct-Sep)\", y=1.002)\nfig.tight_layout(); save(fig, \"wateryear_small_multiples\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Small multiples: daily hydrograph (log scale, green) and precipitation (blue, inverted) for each of the 40 water years. Water years 1949-1951 (grey title) are the evaluation window.](02_data_files/figure-html/fig-wy-multiples-output-1.png){#fig-wy-multiples width=1412 height=1435}\n:::\n:::\n\n\n::: {#tbl-describe .cell execution_count=9}\n``` {.python .cell-code}\ndef describe(s):\n    qs = s.quantile([.01,.05,.10,.25,.50,.75,.90,.95,.99,.999])\n    out = dict(mean=s.mean(), sd=s.std(), CV=s.std()/s.mean(), skew=s.skew(), kurtosis=s.kurtosis(),\n               min=s.min())\n    out.update({f\"p{q*100:g}\": v for q, v in qs.items()})\n    out.update(max=s.max(), pct_zero=100*(s == 0).mean())\n    return out\nDESC = pd.DataFrame({v: describe(d[v]) for v in [\"P\",\"PET\",\"Q\"]}).T\nmd(DESC.round(4))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=9}\n|     |   mean |      sd |     CV |   skew |   kurtosis |   min |     p1 |     p5 |    p10 |    p25 |    p50 |    p75 |     p90 |     p95 |     p99 |   p99.9 |      max |   pct_zero |\n|:----|-------:|--------:|-------:|-------:|-----------:|------:|-------:|-------:|-------:|-------:|-------:|-------:|--------:|--------:|--------:|--------:|---------:|-----------:|\n| P   | 3.9197 | 10.1424 | 2.5876 | 4.925  |    40.1188 | 0     | 0      | 0      | 0      | 0      | 0      | 2.3998 | 12.5657 | 23.33   | 49.6238 | 94.9211 | 221.519  |    54.8871 |\n| PET | 2.9086 |  1.898  | 0.6525 | 0.5286 |    -0.7283 | 0     | 0.1676 | 0.4279 | 0.679  | 1.3177 | 2.527  | 4.3344 |  5.7658 |  6.3908 |  7.2698 |  8.143  |   9.1148 |     0.0068 |\n| Q   | 1.3697 |  2.9017 | 2.1185 | 6.8493 |    76.6315 | 0.069 | 0.0891 | 0.1192 | 0.1406 | 0.2033 | 0.4481 | 1.2097 |  3.3639 |  5.573  | 13.6816 | 32.182  |  64.0148 |     0      |\n:::\n:::\n\n\n*All values in mm/day; `pct_zero` in %; n = 14,610 days.*\n\n# Precipitation P {#sec-p}\n\n::: {#tbl-p-stats .cell execution_count=10}\n``` {.python .cell-code}\nwet01, wet1 = P > 0.1, P > 1.0\ndef spell_lengths(mask):\n    out, c = [], 0\n    for m in mask:\n        if m: c += 1\n        elif c: out.append(c); c = 0\n    if c: out.append(c)\n    return np.array(out)\nws, ds_ = spell_lengths(wet01.to_numpy()), spell_lengths(~wet01.to_numpy())\nrx1 = d.groupby(\"wy\")[\"P\"].max().loc[1949:1988]\nrx5 = P.rolling(5).sum().groupby(d.wy).max().loc[1949:1988]\nmo  = d.groupby([\"wy\",\"month\"])[\"P\"].sum().unstack()\nSI  = (mo.sub(mo.sum(axis=1)/12, axis=0).abs().sum(axis=1)/mo.sum(axis=1)).loc[1949:1988]  # Walsh-Lawler\npstats = {\n  \"wet-day frequency (>0.1 mm) [%]\"   : 100*wet01.mean(),\n  \"wet-day frequency (>1 mm) [%]\"     : 100*wet1.mean(),\n  \"days >10 mm [%]\"                   : 100*(P>10).mean(),\n  \"days >25 mm [%]\"                   : 100*(P>25).mean(),\n  \"days >50 mm [%]\"                   : 100*(P>50).mean(),\n  \"mean wet-day intensity (>0.1) [mm]\": P[wet01].mean(),\n  \"mean wet-day intensity (>1) [mm]\"  : P[wet1].mean(),\n  \"mean wet spell length [d]\"         : ws.mean(),\n  \"max wet spell length [d]\"          : ws.max(),\n  \"mean dry spell length [d]\"         : ds_.mean(),\n  \"95th pct dry spell [d]\"            : np.percentile(ds_, 95),\n  \"max dry spell length [d]\"          : ds_.max(),\n  \"Rx1day mean / max [mm]\"            : rx1.mean(),\n  \"Rx5day mean / max [mm]\"            : rx5.mean(),\n  \"Walsh-Lawler seasonality index [-]\": SI.mean(),\n}\nprint(f\"annual P (WY): mean {ann.P.mean():.0f} mm, sd {ann.P.std():.0f} mm, CV {ann.P.std()/ann.P.mean():.2f}, \"\n      f\"min {ann.P.min():.0f} (WY{ann.P.idxmin()}), max {ann.P.max():.0f} (WY{ann.P.idxmax()})\")\nprint(f\"Rx1day: mean {rx1.mean():.1f} mm, record max {rx1.max():.1f} mm (WY{rx1.idxmax()});  \"\n      f\"Rx5day: mean {rx5.mean():.1f} mm, max {rx5.max():.1f} mm\")\nmd(pd.Series(pstats, name=\"value\").to_frame().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nannual P (WY): mean 1432 mm, sd 281 mm, CV 0.20, min 940 (WY1963), max 2057 (WY1949)\nRx1day: mean 85.7 mm, record max 221.5 mm (WY1974);  Rx5day: mean 139.0 mm, max 289.4 mm\n```\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n|                                    |   value |\n|:-----------------------------------|--------:|\n| wet-day frequency (>0.1 mm) [%]    |  40.185 |\n| wet-day frequency (>1 mm) [%]      |  30.575 |\n| days >10 mm [%]                    |  12.136 |\n| days >25 mm [%]                    |   4.449 |\n| days >50 mm [%]                    |   0.986 |\n| mean wet-day intensity (>0.1) [mm] |   9.75  |\n| mean wet-day intensity (>1) [mm]   |  12.676 |\n| mean wet spell length [d]          |   2.374 |\n| max wet spell length [d]           |  21     |\n| mean dry spell length [d]          |   3.534 |\n| 95th pct dry spell [d]             |  10     |\n| max dry spell length [d]           |  51     |\n| Rx1day mean / max [mm]             |  85.709 |\n| Rx5day mean / max [mm]             | 138.988 |\n| Walsh-Lawler seasonality index [-] |   0.428 |\n:::\n:::\n\n\n::: {#cell-fig-p-dist .cell execution_count=11}\n``` {.python .cell-code}\nfig, axs = plt.subplots(1, 4, figsize=(13, 3.1))\naxs[0].hist(P[P>0.1], bins=60, color=\"#1f77b4\"); axs[0].set_yscale(\"log\")\naxs[0].set_xlabel(\"P on wet days (mm/d)\"); axs[0].set_ylabel(\"count (log)\"); axs[0].set_title(\"(a) histogram\")\naxs[1].hist(np.log10(P[P>0.1]), bins=60, color=\"#1f77b4\")\naxs[1].set_xlabel(\"log10 P (mm/d)\"); axs[1].set_title(\"(b) log-histogram\")\nx = np.sort(P[P>0.1]); axs[2].plot(x, np.arange(1,len(x)+1)/len(x), color=\"#1f77b4\")\naxs[2].set_xscale(\"log\"); axs[2].set_xlabel(\"P wet days (mm/d)\"); axs[2].set_ylabel(\"ECDF\"); axs[2].set_title(\"(c) ECDF wet days\")\naxs[3].hist(ds_, bins=np.arange(1,30), alpha=.6, label=\"dry spells\", color=\"#8c564b\")\naxs[3].hist(ws,  bins=np.arange(1,30), alpha=.6, label=\"wet spells\", color=\"#1f77b4\")\naxs[3].set_yscale(\"log\"); axs[3].set_xlabel(\"spell length (d)\"); axs[3].legend(); axs[3].set_title(\"(d) spells (>0.1 mm)\")\nfig.tight_layout(); save(fig, \"P_distribution\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Precipitation distribution. (a) histogram of wet days, (b) log-scaled histogram, (c) ECDF of wet-day depths, (d) dry- and wet-spell length distributions.](02_data_files/figure-html/fig-p-dist-output-1.png){#fig-p-dist width=1410 height=322}\n:::\n:::\n\n\n::: {#cell-fig-monthly-box .cell execution_count=12}\n``` {.python .cell-code}\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.4))\nfor ax, v, c in zip(axs, [\"P\",\"PET\",\"Q\"], [\"#1f77b4\",\"#d62728\",\"#2ca02c\"]):\n    sns.boxplot(x=d.month, y=d[v], ax=ax, color=c, fliersize=.6, linewidth=.6)\n    if v != \"PET\": ax.set_yscale(\"symlog\", linthresh=.1)\n    ax.set_xlabel(\"month\"); ax.set_ylabel(f\"{v} (mm/d)\"); ax.set_title(v)\nfig.tight_layout(); save(fig, \"monthly_boxplots\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Monthly distributions (log scale for P and Q). P is winter/early-spring dominated with a secondary July convective maximum; Q is far more seasonal than P because of the PET cycle.](02_data_files/figure-html/fig-monthly-box-output-1.png){#fig-monthly-box width=1412 height=355}\n:::\n:::\n\n\n::: {#fig-annual .cell execution_count=13}\n``` {.python .cell-code}\nimport pymannkendall as mk\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.2))\nmkres = {}\nfor ax, v, c in zip(axs, [\"P\",\"PET\",\"Q\"], [\"#1f77b4\",\"#d62728\",\"#2ca02c\"]):\n    r = mk.original_test(ann[v].to_numpy()); mkres[v] = r\n    ax.bar(ann.index, ann[v], color=c)\n    yy = r.intercept + r.slope*np.arange(len(ann))\n    ax.plot(ann.index, yy, \"k--\", lw=1.2,\n            label=f\"Sen slope {r.slope:+.1f} mm/yr²\\nMK p={r.p:.2f} ({r.trend})\")\n    ax.set_title(f\"{v}: WY totals\"); ax.set_xlabel(\"water year\"); ax.set_ylabel(\"mm/yr\"); ax.legend(loc=\"upper left\")\nfig.tight_layout(); save(fig, \"annual_totals\"); plt.show()\nmd(pd.DataFrame({v: dict(trend=r.trend, p=round(r.p,3), tau=round(r.Tau,3),\n                         sen_slope_mm_per_yr2=round(r.slope,2)) for v, r in mkres.items()}).T)\n```\n\n::: {.cell-output .cell-output-display}\n![Water-year totals with Theil-Sen trend lines. No significant monotonic trend (Mann-Kendall, see table).](02_data_files/figure-html/fig-annual-output-1.png){#fig-annual-1 width=1408 height=333}\n:::\n\n::: {#fig-annual-2 .cell-output .cell-output-display .cell-output-markdown execution_count=13}\n|     | trend    |     p |    tau |   sen_slope_mm_per_yr2 |\n|:----|:---------|------:|-------:|-----------------------:|\n| P   | no trend | 0.382 |  0.097 |                   4.32 |\n| PET | no trend | 0.37  | -0.1   |                  -0.99 |\n| Q   | no trend | 0.421 |  0.09  |                   2.32 |\n:::\n:::\n\n\nPrecipitation is **weakly seasonal** (Walsh–Lawler seasonality index SI = 0.43, @walsh1981, i.e. moderately seasonal; monthly means range\n2.6 mm/d in October to 5.1 mm/d in March) with a **double peak** (Feb–Mar frontal, July convective) and a\ndistinct autumn minimum. 54.9 % of days are exactly zero, 40.2 % exceed 0.1 mm and the mean wet-day\nintensity is 9.8 mm — i.e. rainfall arrives in few, intense events (the 221.5 mm record day is\nWY1974). There is **no significant trend** in annual P, PET or Q (Mann–Kendall [@mann1945; @kendall1975], p ≥ 0.35).\n\n# Potential evapotranspiration PET {#sec-pet}\n\n::: {#cell-fig-pet-clim .cell execution_count=14}\n``` {.python .cell-code}\npet_by_doy = d.pivot_table(index=\"doy\", columns=d.index.year, values=\"PET\")\nmu, sd = pet_by_doy.mean(axis=1), pet_by_doy.std(axis=1)\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.3))\nfor y in range(1955, 1985): axs[0].plot(pet_by_doy.index, pet_by_doy[y], lw=.3, color=\"grey\", alpha=.5)\naxs[0].plot(mu.index, mu, color=\"#d62728\", lw=2, label=\"mean over 40 yr\")\naxs[0].fill_between(mu.index, mu-sd, mu+sd, color=\"#d62728\", alpha=.25, label=\"±1 SD (inter-annual)\")\naxs[0].set_xlabel(\"day of year\"); axs[0].set_ylabel(\"PET (mm/d)\"); axs[0].legend(); axs[0].set_title(\"(a) seasonal cycle\")\naxs[1].plot(sd.index, sd, color=\"k\", lw=.8); axs[1].set_xlabel(\"day of year\")\naxs[1].set_ylabel(\"inter-annual SD (mm/d)\"); axs[1].set_title(\"(b) same-DOY spread\")\njun15 = d[(d.index.month == 6) & (d.index.day == 15)]\naxs[2].plot(jun15.index.year, jun15.PET, \"o-\", ms=3, color=\"#d62728\")\naxs[2].set_xlabel(\"year\"); axs[2].set_ylabel(\"PET on 15 June (mm/d)\"); axs[2].set_title(\"(c) one calendar day\")\nfig.tight_layout(); save(fig, \"PET_climatology_test\"); plt.show()\n\namp_seasonal = float((mu.max()-mu.min())/2)\nprint(f\"seasonal amplitude of the PET climatology : {amp_seasonal:.3f} mm/d\")\nprint(f\"mean same-DOY inter-annual SD             : {sd.mean():.3f} mm/d  (max {sd.max():.3f})\")\nprint(f\"ratio inter-annual SD / seasonal amplitude: {sd.mean()/amp_seasonal:.2f}\")\nprint(f\"variance explained by a smooth climatology: {1 - (sd**2).mean()/PET.var():.3f}\")\nprint(f\"corr(P, PET) daily {np.corrcoef(Pv, PETv)[0,1]:+.3f} | monthly totals \"\n      f\"{np.corrcoef(P.resample('MS').sum(), PET.resample('MS').sum())[0,1]:+.3f}\")\nKEY[\"pet_is_climatological\"] = bool(sd.mean()/amp_seasonal < 0.10)\nKEY[\"pet_doy_interannual_sd_mm_d\"] = float(sd.mean())\n```\n\n::: {.cell-output .cell-output-display}\n![Is PET a repeated climatology? (a) mean seasonal cycle with the ±1 SD inter-annual band and 30 individual years overplotted; (b) spread of same-day-of-year values across years; (c) PET on 15 June of each year. The inter-annual variability is large, so PET is NOT a climatology.](02_data_files/figure-html/fig-pet-clim-output-1.png){#fig-pet-clim width=1411 height=345}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nseasonal amplitude of the PET climatology : 2.108 mm/d\nmean same-DOY inter-annual SD             : 1.304 mm/d  (max 2.140)\nratio inter-annual SD / seasonal amplitude: 0.62\nvariance explained by a smooth climatology: 0.467\ncorr(P, PET) daily -0.271 | monthly totals -0.268\n```\n:::\n:::\n\n\n**PET is not climatological.** A pure repeated-climatology series would have a same-DOY inter-annual SD of\n0; here it is 1.30 mm/d, 71 % of the seasonal amplitude (1.83 mm/d), and only ~53 % of the total PET\nvariance is explained by the smooth seasonal cycle. Day-to-day PET therefore carries real meteorological\ninformation (cloudiness/temperature), which (i) justifies giving PET to ML models as a second forcing\nchannel rather than a deterministic function of the calendar, and (ii) means conceptual models will respond\nto inter-annual PET anomalies. PET is **negatively correlated with P** (r = −0.27 daily and monthly), as\nexpected (rainy days are cloudy days).\n\n## Verification of the record start date and period definition {#sec-alignment}\n\nISSUE-001 (evaluation window given as row indices 265:1360 vs. as the calendar window\n1948-10-01…1951-09-30) was **resolved by the user on 2026-09-15**: `config/project.yaml` now uses\n`periods.definition: dates`. This subsection *verifies* that resolution from the data themselves.\n\n::: {#fig-alignment .cell execution_count=15}\n``` {.python .cell-code}\nn = len(d); t = np.arange(n)\ndef harmonic(y, T=365.25):\n    X = np.c_[np.ones(n), np.cos(2*np.pi*t/T), np.sin(2*np.pi*t/T)]\n    b = np.linalg.lstsq(X, y, rcond=None)[0]\n    amp  = float(np.hypot(b[1], b[2]))\n    tpk  = float((np.arctan2(b[2], b[1])/(2*np.pi)) % 1.0 * T)     # days after row 0\n    r2   = float(1 - ((y - X@b)**2).sum()/((y - y.mean())**2).sum())\n    return b[0], amp, tpk, r2\n\nH = {}\nfor v, y in [(\"P\", Pv), (\"PET\", PETv), (\"Q\", Qv)]:\n    H[v] = harmonic(y)\nstart_H1 = pd.Timestamp(\"1948-10-01\")                    # active hypothesis (config)\nstart_H2 = start_H1 - pd.Timedelta(days=265)             # rows 265:1360 == Oct 1948 .. Sep 1951\nrows_align = []\nfor v in [\"P\",\"PET\",\"Q\"]:\n    m, amp, tpk, r2 = H[v]\n    rows_align.append(dict(variable=v, mean=round(m,3), amplitude=round(amp,3), R2=round(r2,3),\n                           peak_row=round(tpk,1),\n                           peak_date_H1=(start_H1+pd.Timedelta(days=round(tpk))).strftime(\"%d %b\"),\n                           peak_date_H2=(start_H2+pd.Timedelta(days=round(tpk))).strftime(\"%d %b\")))\nalign = pd.DataFrame(rows_align).set_index(\"variable\")\n\nfig, axs = plt.subplots(2, 3, figsize=(13, 5.6))\nfor j, (v, c) in enumerate(zip([\"P\",\"PET\",\"Q\"], [\"#1f77b4\",\"#d62728\",\"#2ca02c\"])):\n    for i, (st, lab) in enumerate([(start_H1, \"H1: start 1948-10-01 (config)\"),\n                                   (start_H2, \"H2: start 1948-01-10 (rejected)\")]):\n        idx = pd.date_range(st, periods=n, freq=\"D\")\n        clim = pd.Series(d[v].to_numpy(), index=idx).groupby(idx.month).mean()\n        axs[i, j].bar(clim.index, clim.values, color=c)\n        axs[i, j].axvline(clim.idxmax(), color=\"k\", ls=\"--\", lw=1)\n        axs[i, j].set_xticks(range(1, 13)); axs[i, j].set_xlabel(\"calendar month\")\n        axs[i, j].set_ylabel(f\"{v} (mm/d)\")\n        axs[i, j].set_title(f\"{lab}\\n{v} max in month {clim.idxmax()}\", fontsize=8)\nfig.tight_layout(); save(fig, \"date_alignment_check\"); plt.show()\nmd(align)\n```\n\n::: {.cell-output .cell-output-display}\n![Phase check. Under the assumed start 1948-10-01 (top row) the fitted annual harmonic of PET peaks on 6 July and P/Q peak in late winter-early spring — the expected Northern-Hemisphere pattern for Mississippi. Under the rejected alternative (record starts 1948-01-10, so that file rows 265:1360 would be 'Oct 1948-Sep 1951'; bottom row) PET would peak in September-October and be minimal in April, which is physically impossible.](02_data_files/figure-html/fig-alignment-output-1.png){#fig-alignment-1 width=1411 height=597}\n:::\n\n::: {#fig-alignment-2 .cell-output .cell-output-display .cell-output-markdown execution_count=15}\n| variable   |   mean |   amplitude |    R2 |   peak_row | peak_date_H1   | peak_date_H2   |\n|:-----------|-------:|------------:|------:|-----------:|:---------------|:---------------|\n| P          |  3.92  |       0.843 | 0.003 |      156.2 | 06 Mar         | 14 Jun         |\n| PET        |  2.909 |       1.826 | 0.463 |      278.4 | 06 Jul         | 14 Oct         |\n| Q          |  1.37  |       1.352 | 0.108 |      150.7 | 01 Mar         | 09 Jun         |\n:::\n:::\n\n\n::: {#tbl-alignment .cell execution_count=16}\n``` {.python .cell-code}\nprint(\"H1 (active, `dates`): record row 0 = 1948-10-01\")\nprint(f\"   PET annual harmonic peaks {H['PET'][2]:.0f} d after row 0 = \"\n      f\"{(start_H1+pd.Timedelta(days=round(H['PET'][2]))).strftime('%d %B')}; \"\n      f\"monthly PET max in June ({d.groupby('month')['PET'].mean().max():.2f} mm/d), min in January \"\n      f\"({d.groupby('month')['PET'].mean().min():.2f} mm/d)\")\nprint(f\"   Q monthly max in {d.groupby('month')['Q'].mean().idxmax()} (Feb-Apr, cool season, low PET), \"\n      f\"min in {d.groupby('month')['Q'].mean().idxmin()} (Sep, peak PET)  -> consistent\")\nprint(\"H2 (rejected): record row 0 = 1948-01-10 so that rows 265:1360 = 1948-10-01..1951-09-30\")\nidx2 = pd.date_range(start_H2, periods=n, freq=\"D\")\nclim2 = pd.Series(PETv, index=idx2).groupby(idx2.month).mean()\nimport calendar\nprint(f\"   PET monthly climatology would peak in {calendar.month_name[int(clim2.idxmax())]} \"\n      f\"and be minimal in {calendar.month_name[int(clim2.idxmin())]}; the fitted harmonic would peak on \"\n      f\"{(start_H2+pd.Timedelta(days=round(H['PET'][2]))).strftime('%d %B')}\")\nprint(f\"   -> physically impossible in the Northern Hemisphere; H2 rejected.\")\nprint()\nprint(\"Superseded index window, evaluated under H1:\")\nprint(f\"   rows 265:1360  = {d.index[265].date()} .. {d.index[1359].date()}   (not Oct 1948-Sep 1951)\")\nprint(f\"   rows 357:1360  = {d.index[357].date()} .. {d.index[1359].date()}   (metric sub-window)\")\nprint(\"Active window (config/project.yaml, periods.definition = dates):\")\nfor k in [\"evaluation run\",\"evaluation warm-up\",\"evaluation metric\",\"calibration run\",\n          \"calibration warm-up\",\"calibration metric\",\"internal train\",\"internal validation\"]:\n    a, b = WIN[k]; s = win(k)\n    print(f\"   {k:20s} {a} .. {b}  = rows {int(s['row'].iloc[0]):5d}:{int(s['row'].iloc[-1])+1:5d}  n={len(s):5d}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH1 (active, `dates`): record row 0 = 1948-10-01\n   PET annual harmonic peaks 278 d after row 0 = 06 July; monthly PET max in June (4.65 mm/d), min in January (1.03 mm/d)\n   Q monthly max in 2 (Feb-Apr, cool season, low PET), min in 9 (Sep, peak PET)  -> consistent\nH2 (rejected): record row 0 = 1948-01-10 so that rows 265:1360 = 1948-10-01..1951-09-30\n   PET monthly climatology would peak in September and be minimal in April; the fitted harmonic would peak on 14 October\n   -> physically impossible in the Northern Hemisphere; H2 rejected.\n\nSuperseded index window, evaluated under H1:\n   rows 265:1360  = 1949-06-23 .. 1952-06-21   (not Oct 1948-Sep 1951)\n   rows 357:1360  = 1949-09-23 .. 1952-06-21   (metric sub-window)\nActive window (config/project.yaml, periods.definition = dates):\n   evaluation run       1948-10-01 .. 1951-09-30  = rows     0: 1095  n= 1095\n   evaluation warm-up   1948-10-01 .. 1948-12-31  = rows     0:   92  n=   92\n   evaluation metric    1949-01-01 .. 1951-09-30  = rows    92: 1095  n= 1003\n   calibration run      1951-10-01 .. 1988-09-30  = rows  1095:14610  n=13515\n   calibration warm-up  1951-10-01 .. 1952-09-30  = rows  1095: 1461  n=  366\n   calibration metric   1952-10-01 .. 1988-09-30  = rows  1461:14610  n=13149\n   internal train       1952-10-01 .. 1981-09-30  = rows  1461:12053  n=10592\n   internal validation  1981-10-01 .. 1988-09-30  = rows 12053:14610  n= 2557\n```\n:::\n:::\n\n\n**Conclusion.** Three independent lines of evidence fix row 0 at 1948-10-01:\n\n1. **PET phase** — the fitted annual harmonic (R² = 0.46) peaks 278 days after row 0. Under H1 that is\n   **6 July**, and the monthly climatology maximum is June (4.65 mm/d) with a January minimum (1.03 mm/d):\n   textbook Northern-Hemisphere. Under H2 the same harmonic peak falls on **14 October** (monthly maximum in\n   September–October) with an **April minimum** — evaporative demand highest in autumn and lowest in spring,\n   which is impossible for Mississippi.\n2. **Q/P phase** — Q peaks in Feb–Apr and is minimal in September, the classic humid-subtropical pattern\n   driven by the PET cycle (P itself is only weakly seasonal); annual Q maxima occur in Dec–May in 38 of\n   40 water years.\n3. **Record length** — 14,610 days = exactly 40 water years including 10 leap days, which only closes for\n   an Oct-1 start.\n\nThis confirms `periods.definition: dates`. The superseded row window 265:1360 corresponds to\n**1949-06-23 … 1952-06-21** — a window that begins in mid-summer and does not match the benchmark study's\nverbatim description (\"Oct 1, 1948 through Sept 30, 1951\", first three months as warm-up, metrics from\n1 Jan 1949). Since that study used the identical file (md5 `a5c922ef2b009a63ba6089172fd90cc2`), the\nrow-index form was simply a mis-translation of the same calendar window. **No change to\n`config/project.yaml` is needed or made here.**\n\n# Streamflow Q {#sec-q}\n\n::: {#cell-fig-fdc .cell execution_count=17}\n``` {.python .cell-code}\nqs = np.sort(Qv)[::-1]\nex = np.arange(1, len(qs)+1)/(len(qs)+1)\ndef qp(p): return float(np.interp(p, ex, qs))\nQ5, Q50, Q95 = qp(.05), qp(.50), qp(.95)\nfdc_slope = (np.log(qp(.33)) - np.log(qp(.66)))/(0.66-0.33)\nfig, ax = plt.subplots(figsize=(6, 4))\nax.semilogy(ex*100, qs, color=\"#2ca02c\")\nfor p, lab in [(5,\"Q5\"), (50,\"Q50\"), (95,\"Q95\")]:\n    ax.axvline(p, color=\"grey\", lw=.6); ax.annotate(f\"{lab}={qp(p/100):.2f}\", (p, qp(p/100)*1.6), fontsize=8)\nax.axvspan(33, 66, color=\"orange\", alpha=.15)\nax.set_xlabel(\"exceedance probability (%)\"); ax.set_ylabel(\"Q (mm/d, log)\")\nax.set_title(f\"FDC — slope(33-66%) = {fdc_slope:.2f} log-units\")\nfig.tight_layout(); save(fig, \"fdc\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Flow duration curve of the whole record (log y). Q5/Q50/Q95 = 5.57 / 0.45 / 0.12 mm/d; the 33-66 % segment slope quantifies how fast flow drains.](02_data_files/figure-html/fig-fdc-output-1.png){#fig-fdc width=636 height=421}\n:::\n:::\n\n\n::: {#tbl-q-stats .cell execution_count=18}\n``` {.python .cell-code}\ndef spell_stats(mask):\n    L, c = [], 0\n    for m in mask:\n        if m: c += 1\n        elif c: L.append(c); c = 0\n    if c: L.append(c)\n    return (len(L), float(np.mean(L)) if L else 0.0, int(np.max(L)) if L else 0)\nhf = (Q > 9*Q50).to_numpy(); lf = (Q < 0.2*Q.mean()).to_numpy()\nnh, dh, mh = spell_stats(hf); nl, dl, ml = spell_stats(lf)\ndQ = Q.diff()\nRB = float(np.abs(np.diff(Qv)).sum()/Qv[1:].sum())              # Richards-Baker flashiness\nRBwy = d.groupby(\"wy\")[\"Q\"].apply(lambda s: np.abs(np.diff(s)).sum()/s.iloc[1:].sum()).loc[1949:1988]\npk   = d.groupby(\"wy\")[\"Q\"].max().loc[1949:1988]\npkd  = d.loc[d.groupby(\"wy\")[\"Q\"].idxmax()]\nqstats = {\n \"Q5 (mm/d)\": Q5, \"Q50 (mm/d)\": Q50, \"Q95 (mm/d)\": Q95, \"Q5/Q95 (-)\": Q5/Q95,\n \"FDC slope 33-66% (log-units)\": fdc_slope,\n \"high-flow events/yr (Q>9*Q50)\": nh/40, \"high-flow mean duration (d)\": dh, \"high-flow days/yr\": hf.sum()/40,\n \"low-flow events/yr (Q<0.2*Qmean)\": nl/40, \"low-flow mean duration (d)\": dl, \"low-flow days/yr\": lf.sum()/40,\n \"Richards-Baker flashiness (-)\": RB,   # Baker et al. (2004)\n \"rising days (%)\": 100*(dQ > 0).mean(), \"falling days (%)\": 100*(dQ < 0).mean(),\n \"unchanged days (%)\": 100*(dQ == 0).mean(),\n \"mean rise (mm/d)\": dQ[dQ > 0].mean(), \"mean fall (mm/d)\": dQ[dQ < 0].mean(),\n \"median falling-limb ratio Qt/Qt-1\": float((Q/Q.shift(1))[dQ < 0].median()),\n \"annual max Q mean (mm/d)\": pk.mean(), \"annual max Q record (mm/d)\": pk.max(),\n}\nprint(f\"annual peak Q: mean {pk.mean():.1f} mm/d, max {pk.max():.1f} mm/d (WY{pk.idxmax()}), min {pk.min():.1f} mm/d (WY{pk.idxmin()})\")\nprint(\"month of annual peak:\", pkd.index.month.value_counts().sort_index().to_dict(),\n      f\"-> {int((pkd.index.month.isin([12,1,2,3,4,5])).sum())}/40 peaks in Dec-May\")\nprint(f\"Richards-Baker index per WY: mean {RBwy.mean():.3f}, range {RBwy.min():.3f}-{RBwy.max():.3f}\")\nKEY[\"Q5_mm_d\"], KEY[\"Q50_mm_d\"], KEY[\"Q95_mm_d\"] = Q5, Q50, Q95\nKEY[\"richards_baker\"] = RB; KEY[\"fdc_slope_33_66\"] = float(fdc_slope)\nmd(pd.Series(qstats, name=\"value\").to_frame().round(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nannual peak Q: mean 20.5 mm/d, max 64.0 mm/d (WY1974), min 4.4 mm/d (WY1952)\nmonth of annual peak: {1: 4, 2: 4, 3: 8, 4: 14, 5: 5, 10: 2, 12: 3} -> 38/40 peaks in Dec-May\nRichards-Baker index per WY: mean 0.309, range 0.232-0.376\n```\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=18}\n|                                   |   value |\n|:----------------------------------|--------:|\n| Q5 (mm/d)                         |   5.573 |\n| Q50 (mm/d)                        |   0.448 |\n| Q95 (mm/d)                        |   0.119 |\n| Q5/Q95 (-)                        |  46.737 |\n| FDC slope 33-66% (log-units)      |   3.498 |\n| high-flow events/yr (Q>9*Q50)     |   6.8   |\n| high-flow mean duration (d)       |   4.261 |\n| high-flow days/yr                 |  28.975 |\n| low-flow events/yr (Q<0.2*Qmean)  |   8.05  |\n| low-flow mean duration (d)        |  16.043 |\n| low-flow days/yr                  | 129.15  |\n| Richards-Baker flashiness (-)     |   0.316 |\n| rising days (%)                   |  30.719 |\n| falling days (%)                  |  64.641 |\n| unchanged days (%)                |   4.634 |\n| mean rise (mm/d)                  |   0.704 |\n| mean fall (mm/d)                  |  -0.335 |\n| median falling-limb ratio Qt/Qt-1 |   0.91  |\n| annual max Q mean (mm/d)          |  20.491 |\n| annual max Q record (mm/d)        |  64.015 |\n:::\n:::\n\n\n::: {#cell-fig-q-dist .cell execution_count=19}\n``` {.python .cell-code}\nfig, axs = plt.subplots(1, 4, figsize=(13, 3.1))\naxs[0].hist(Qv, bins=80, color=\"#2ca02c\"); axs[0].set_yscale(\"log\")\naxs[0].set_xlabel(\"Q (mm/d)\"); axs[0].set_ylabel(\"count (log)\"); axs[0].set_title(\"(a) histogram\")\naxs[1].hist(np.log10(Qv), bins=80, color=\"#2ca02c\")\naxs[1].set_xlabel(\"log10 Q (mm/d)\"); axs[1].set_title(\"(b) log-histogram\")\nxs = np.sort(Qv); axs[2].plot(xs, np.arange(1,len(xs)+1)/len(xs), color=\"#2ca02c\"); axs[2].set_xscale(\"log\")\naxs[2].set_xlabel(\"Q (mm/d, log)\"); axs[2].set_ylabel(\"ECDF\"); axs[2].set_title(\"(c) ECDF\")\naxs[3].bar(pk.index, pk.values, color=\"#2ca02c\"); axs[3].set_xlabel(\"water year\")\naxs[3].set_ylabel(\"annual max Q (mm/d)\"); axs[3].set_title(\"(d) annual maxima\")\nfig.tight_layout(); save(fig, \"Q_distribution\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Streamflow distribution: (a) histogram (linear), (b) histogram of log10 Q — close to log-normal with a heavy right tail, (c) ECDF, (d) annual maxima series.](02_data_files/figure-html/fig-q-dist-output-1.png){#fig-q-dist width=1410 height=322}\n:::\n:::\n\n\nDaily flow spans nearly three orders of magnitude (0.069–64.0 mm/d) with skewness 6.8 and kurtosis 77.\nIn log space the distribution is close to normal (panel b), which is the key argument for a\nvariance-stabilising transform in any least-squares objective (@sec-implications, input to a04).\nThe hydrograph is **moderately flashy** (Richards–Baker index 0.32, @baker2004) and dominated by falling limbs (64.6 % of\ndays), with a median recession ratio of 0.91 per day.\n\n# Joint analysis and hydrological signatures {#sec-signatures}\n\n## Baseflow separation [@lyne1979; @eckhardt2005]\n\n::: {#cell-fig-baseflow .cell execution_count=20}\n``` {.python .cell-code}\ndef lyne_hollick(q, a=0.925, passes=3):\n    b = q.copy()\n    for p in range(passes):\n        y = b[::-1] if p % 2 else b\n        f = np.zeros_like(y); f[0] = y[0]\n        for i in range(1, len(y)):\n            f[i] = a*f[i-1] + (1+a)/2*(y[i]-y[i-1])\n        bf = np.minimum(y, y - np.maximum(f, 0))\n        b = bf[::-1] if p % 2 else bf\n    return np.clip(b, 0, q)\n\nbf = lyne_hollick(Qv); qf = Qv - bf\nBFI_LH = float(bf.sum()/Qv.sum())\nd[\"bf\"] = bf\nbfi_wy = d.groupby(\"wy\").apply(lambda s: s.bf.sum()/s.Q.sum()).loc[1949:1988]\nfig, axs = plt.subplots(1, 2, figsize=(13, 3.2), sharey=True)\nfor ax, wy in zip(axs, [1980, 1963]):\n    s = d[d.wy == wy]\n    ax.fill_between(s.index, 0, s.bf, color=\"#9edae5\", label=\"baseflow (LH)\")\n    ax.plot(s.index, s.Q, color=\"#2ca02c\", lw=.8, label=\"Q\")\n    ax.set_yscale(\"log\"); ax.set_ylabel(\"Q (mm/d)\")\n    ax.set_title(f\"WY{wy} — BFI = {bfi_wy[wy]:.2f} ({'wettest' if wy==1980 else 'driest'} year)\")\n    ax.legend(fontsize=7)\nfig.tight_layout(); save(fig, \"baseflow\"); plt.show()\nprint(f\"BFI Lyne-Hollick (alpha=0.925, 3 passes, whole record): {BFI_LH:.3f}\")\nprint(f\"BFI per water year: mean {bfi_wy.mean():.3f}, range {bfi_wy.min():.3f} (WY{bfi_wy.idxmin()}) - {bfi_wy.max():.3f} (WY{bfi_wy.idxmax()})\")\n```\n\n::: {.cell-output .cell-output-display}\n![Lyne-Hollick baseflow separation [@lyne1979; @nathan1990] (alpha = 0.925, 3 passes) for two contrasting water years; the shaded area is baseflow.](02_data_files/figure-html/fig-baseflow-output-1.png){#fig-baseflow width=1412 height=334}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nBFI Lyne-Hollick (alpha=0.925, 3 passes, whole record): 0.408\nBFI per water year: mean 0.416, range 0.303 (WY1957) - 0.540 (WY1963)\n```\n:::\n:::\n\n\n## Recession analysis\n\n::: {#cell-fig-recession .cell execution_count=21}\n``` {.python .cell-code}\nrec_mask = np.r_[False, np.diff(Qv) < 0] & (Pv < 0.1)\nruns, c = [], 0\nfor i, m in enumerate(rec_mask):\n    if m: c += 1\n    else:\n        if c >= 5: runs.append((i-c, i))\n        c = 0\nks, Qm, dQm = [], [], []\nfor a_, b_ in runs:\n    seg = Qv[a_-1:b_]\n    ks.append(np.exp(np.polyfit(np.arange(len(seg)), np.log(seg), 1)[0]))\n    Qm.append((seg[:-1]+seg[1:])/2); dQm.append(-np.diff(seg))\nks = np.array(ks); Qm = np.concatenate(Qm); dQm = np.concatenate(dQm)\nok = dQm > 0\nbBN, aBN = np.polyfit(np.log(Qm[ok]), np.log(dQm[ok]), 1)\nk_med = float(np.median(ks)); tau = -1/np.log(k_med)\nfig, axs = plt.subplots(1, 2, figsize=(11, 3.4))\naxs[0].loglog(Qm[ok], dQm[ok], \".\", ms=2, alpha=.3, color=\"#2ca02c\")\nxx = np.logspace(np.log10(Qm[ok].min()), np.log10(Qm[ok].max()), 50)\naxs[0].loglog(xx, np.exp(aBN)*xx**bBN, \"k-\", lw=1.5, label=f\"-dQ/dt = {np.exp(aBN):.3f} Q^{bBN:.2f}\")\naxs[0].set_xlabel(\"Q (mm/d)\"); axs[0].set_ylabel(\"-dQ/dt (mm/d²)\"); axs[0].legend(); axs[0].set_title(\"(a) Brutsaert-Nieber\")\naxs[1].hist(ks, bins=40, color=\"#2ca02c\")\naxs[1].axvline(k_med, color=\"k\", ls=\"--\", label=f\"median k = {k_med:.3f}\\n(tau = {tau:.1f} d)\")\naxs[1].set_xlabel(\"segment recession constant k (1/d)\"); axs[1].legend(); axs[1].set_title(\"(b) recession constants\")\nfig.tight_layout(); save(fig, \"recession\"); plt.show()\nprint(f\"{len(runs)} rainless recession segments >=5 d ({sum(b_-a_ for a_,b_ in runs)} days, \"\n      f\"{100*sum(b_-a_ for a_,b_ in runs)/len(d):.1f}% of the record)\")\nprint(f\"master recession constant k = {k_med:.4f} /d  ->  residence time tau = {tau:.1f} d\")\nprint(f\"Brutsaert-Nieber exponent b = {bBN:.2f} (b=1 linear reservoir, b~1.5 Boussinesq) , a = {np.exp(aBN):.3f}\")\ndef eckhardt(q, a, BFImax):\n    b = np.empty_like(q); b[0] = q[0]*BFImax\n    for i in range(1, len(q)):\n        b[i] = min(((1-BFImax)*a*b[i-1] + (1-a)*BFImax*q[i])/(1-a*BFImax), q[i])\n    return b\nBFI_E = {bm: float(eckhardt(Qv, k_med, bm).sum()/Qv.sum()) for bm in (0.50, 0.80)}\nprint(f\"BFI Eckhardt (a={k_med:.3f}): BFImax=0.50 -> {BFI_E[0.50]:.3f} ; BFImax=0.80 -> {BFI_E[0.80]:.3f}\")\nKEY[\"bfi_lyne_hollick\"] = BFI_LH; KEY[\"bfi_eckhardt_bfimax080\"] = BFI_E[0.80]\nKEY[\"recession_k\"] = k_med; KEY[\"recession_tau_days\"] = float(tau); KEY[\"bn_exponent_b\"] = float(bBN)\n```\n\n::: {.cell-output .cell-output-display}\n![Recession behaviour. (a) Brutsaert-Nieber [@brutsaert1977] plot -dQ/dt vs Q on 442 rainless recession segments of >=5 days, with the fitted power law; (b) distribution of segment-wise recession constants k = exp(slope of log Q).](02_data_files/figure-html/fig-recession-output-1.png){#fig-recession width=1191 height=355}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n442 rainless recession segments >=5 d (3168 days, 21.7% of the record)\nmaster recession constant k = 0.8957 /d  ->  residence time tau = 9.1 d\nBrutsaert-Nieber exponent b = 1.68 (b=1 linear reservoir, b~1.5 Boussinesq) , a = 0.143\nBFI Eckhardt (a=0.896): BFImax=0.50 -> 0.452 ; BFImax=0.80 -> 0.713\n```\n:::\n:::\n\n\nRoughly 40 % of the annual flow volume is baseflow (Lyne–Hollick 0.41; Eckhardt 0.45 with BFImax = 0.5,\n0.71 with the sandy-aquifer value BFImax = 0.8). The Brutsaert–Nieber exponent b = 1.68 is **clearly\nnon-linear** (> 1): recession is faster at high flow, which a single linear reservoir cannot reproduce —\ntwo parallel stores (or a non-linear store) are needed.\n\n## Memory: autocorrelation and P→Q lag\n\n::: {#cell-fig-memory .cell execution_count=22}\n``` {.python .cell-code}\nlags = np.arange(0, 121)\nacq  = np.array([Q.autocorr(l) for l in lags])\naclq = np.array([np.log(Q).autocorr(l) for l in lags])\nxl   = np.arange(0, 31)\nxcQ  = np.array([np.corrcoef(Pv[:len(Pv)-l], Qv[l:])[0,1] for l in xl])\ndQv  = np.r_[0, np.diff(Qv)]\nxcdQ = np.array([np.corrcoef(Pv[:len(Pv)-l], dQv[l:])[0,1] for l in xl])\nLs   = [5,10,20,30,60,90,120,180,365]\nr2L  = []\nfor L in Ls:\n    X = np.column_stack([np.r_[np.zeros(k), Pv[:len(Pv)-k]] for k in range(L)] + [np.ones(len(Pv))])\n    b = np.linalg.lstsq(X, Qv, rcond=None)[0]\n    r2L.append(1 - ((Qv - X@b)**2).sum()/((Qv-Qv.mean())**2).sum())\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.3))\naxs[0].plot(lags, acq, label=\"Q\"); axs[0].plot(lags, aclq, label=\"log Q\")\naxs[0].axhline(np.exp(-1), color=\"grey\", ls=\":\"); axs[0].set_xlabel(\"lag (d)\"); axs[0].set_ylabel(\"ACF\")\naxs[0].legend(); axs[0].set_title(\"(a) autocorrelation\")\naxs[1].plot(xl, xcQ, \"o-\", ms=3, label=\"corr(P_t, Q_t+l)\")\naxs[1].plot(xl, xcdQ, \"s-\", ms=3, label=\"corr(P_t, dQ_t+l)\")\naxs[1].axhline(0, color=\"k\", lw=.5); axs[1].set_xlabel(\"lag l (d)\"); axs[1].legend(); axs[1].set_title(\"(b) P -> Q lag\")\naxs[2].plot(Ls, r2L, \"o-\"); axs[2].set_xscale(\"log\"); axs[2].set_xlabel(\"input window length L (d)\")\naxs[2].set_ylabel(\"R² of linear P-lag model\"); axs[2].set_title(\"(c) how much history matters\")\nfig.tight_layout(); save(fig, \"memory\"); plt.show()\nefold_q  = int(np.argmax(acq  < np.exp(-1)))\nefold_lq = int(np.argmax(aclq < np.exp(-1)))\nprint(f\"ACF(Q)   lag1 {acq[1]:.3f}  lag3 {acq[3]:.3f}  lag7 {acq[7]:.3f}  lag30 {acq[30]:.3f}  e-folding {efold_q} d\")\nprint(f\"ACF(logQ) lag1 {aclq[1]:.3f} lag7 {aclq[7]:.3f} lag30 {aclq[30]:.3f} lag90 {aclq[90]:.3f} e-folding {efold_lq} d\")\nprint(f\"peak cross-correlation P->Q at lag {int(xl[np.argmax(xcQ)])} d (r={xcQ.max():.3f}); \"\n      f\"P->dQ/dt at lag {int(xl[np.argmax(xcdQ)])} d (r={xcdQ.max():.3f})\")\nprint(\"linear P-lag model R²:\", {L: round(r,3) for L, r in zip(Ls, r2L)})\nKEY[\"lag_peak_xcorr_days\"]   = int(xl[np.argmax(xcQ)])\nKEY[\"lag_response_onset_days\"]= int(xl[np.argmax(xcdQ)])\nKEY[\"acf_logQ_efolding_days\"]= efold_lq\nKEY[\"acf_Q_lag1\"]            = float(acq[1])\n```\n\n::: {.cell-output .cell-output-display}\n![Catchment memory. (a) autocorrelation of Q and log Q up to 120 days; (b) cross-correlation of P with Q and with dQ/dt: the flow *change* peaks at lag 1 day, the flow *level* at lag 3 days; (c) R² of a linear model of Q on the last L days of P as a function of L.](02_data_files/figure-html/fig-memory-output-1.png){#fig-memory width=1411 height=344}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nACF(Q)   lag1 0.888  lag3 0.472  lag7 0.246  lag30 0.155  e-folding 4 d\nACF(logQ) lag1 0.960 lag7 0.679 lag30 0.481 lag90 0.094 e-folding 48 d\npeak cross-correlation P->Q at lag 3 d (r=0.485); P->dQ/dt at lag 1 d (r=0.497)\nlinear P-lag model R²: {5: np.float64(0.543), 10: np.float64(0.586), 20: np.float64(0.601), 30: np.float64(0.611), 60: np.float64(0.624), 90: np.float64(0.626), 120: np.float64(0.627), 180: np.float64(0.634), 365: np.float64(0.645)}\n```\n:::\n:::\n\n\n## Event runoff coefficients {#sec-events}\n\n::: {#fig-events .cell execution_count=23}\n``` {.python .cell-code}\nevents, i = [], 6\nwhile i < len(Pv) - 16:\n    if Pv[i] >= 20 and Pv[i-5:i].sum() < 2:\n        L = 1\n        while L < 3 and Pv[i+L] >= 5: L += 1\n        if Pv[i+L:i+L+10].sum() < 5:\n            pe = Pv[i:i+L].sum(); qe = qf[i:i+L+10].sum()\n            events.append(dict(date=d.index[i], dur=L, P_mm=pe, Qdir_mm=qe, RC=qe/pe, Q_ante=Qv[i-1],\n                               month=d.index[i].month))\n            i += L + 10; continue\n    i += 1\nEV = pd.DataFrame(events)\nEV[\"season\"] = np.where(EV.month.isin([11,12,1,2,3,4]), \"cool (Nov-Apr)\", \"warm (May-Oct)\")\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.2))\nsc = axs[0].scatter(EV.Q_ante, EV.RC, c=EV.P_mm, cmap=\"viridis\", s=30)\naxs[0].set_xscale(\"log\"); axs[0].set_xlabel(\"antecedent Q (mm/d)\"); axs[0].set_ylabel(\"runoff coefficient (-)\")\nplt.colorbar(sc, ax=axs[0], label=\"event P (mm)\"); axs[0].set_title(f\"(a) RC vs antecedent flow (r={EV.RC.corr(EV.Q_ante):.2f})\")\naxs[1].scatter(EV.P_mm, EV.RC, c=\"#1f77b4\", s=30); axs[1].set_xlabel(\"event P (mm)\")\naxs[1].set_ylabel(\"RC (-)\"); axs[1].set_title(f\"(b) RC vs event depth (r={EV.RC.corr(EV.P_mm):.2f})\")\nsns.boxplot(data=EV, x=\"season\", y=\"RC\", ax=axs[2], color=\"#1f77b4\", linewidth=.8)\naxs[2].set_title(\"(c) seasonal contrast\")\nfig.tight_layout(); save(fig, \"event_runoff_coefficients\"); plt.show()\nprint(f\"n isolated events = {len(EV)}; RC: min {EV.RC.min():.3f}, median {EV.RC.median():.3f}, \"\n      f\"mean {EV.RC.mean():.3f}, max {EV.RC.max():.3f}\")\nmd(EV.groupby(\"season\")[\"RC\"].agg([\"count\",\"mean\",\"median\",\"min\",\"max\"]).round(3))\n```\n\n::: {.cell-output .cell-output-display}\n![Runoff coefficients of 31 isolated rainfall events (>=20 mm after >=5 dry days, followed by 10 quiet days). The event response varies by two orders of magnitude and increases with antecedent wetness (antecedent Q) and with event size — direct evidence of threshold/nonlinear runoff generation.](02_data_files/figure-html/fig-events-output-1.png){#fig-events-1 width=1411 height=333}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nn isolated events = 31; RC: min 0.004, median 0.077, mean 0.126, max 0.454\n```\n:::\n\n::: {#fig-events-2 .cell-output .cell-output-display .cell-output-markdown execution_count=23}\n| season         |   count |   mean |   median |   min |   max |\n|:---------------|--------:|-------:|---------:|------:|------:|\n| cool (Nov-Apr) |      18 |  0.167 |    0.13  | 0.008 | 0.454 |\n| warm (May-Oct) |      13 |  0.07  |    0.017 | 0.004 | 0.247 |\n:::\n:::\n\n\n## Water balance, elasticity and Budyko\n\n::: {#cell-fig-budyko .cell execution_count=24}\n``` {.python .cell-code}\nann[\"RR\"]  = ann.Q/ann.P\nann[\"AI\"]  = ann.PET/ann.P\nann[\"EI\"]  = (ann.P-ann.Q)/ann.P\neps_QP = float(np.median((ann.Q-ann.Q.mean())/(ann.P-ann.P.mean())*(ann.P.mean()/ann.Q.mean())))\nslopeQP, icQP = np.polyfit(ann.P, ann.Q, 1)\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.3))\nphi = np.linspace(0.1, 2, 100)\naxs[0].plot(phi, np.sqrt(phi*np.tanh(1/phi)*(1-np.exp(-phi))), \"k-\", lw=1, label=\"Budyko (1974)\")\naxs[0].axhline(1, color=\"grey\", ls=\":\"); axs[0].plot(phi, phi, color=\"grey\", ls=\":\")\ns0 = axs[0].scatter(ann.AI, ann.EI, c=ann.index, cmap=\"coolwarm\", s=25)\nplt.colorbar(s0, ax=axs[0], label=\"water year\")\naxs[0].set_xlabel(\"PET/P (-)\"); axs[0].set_ylabel(\"(P-Q)/P (-)\"); axs[0].legend(fontsize=7); axs[0].set_title(\"(a) Budyko\")\naxs[1].scatter(ann.P, ann.Q, c=\"#2ca02c\")\naxs[1].plot(ann.P, slopeQP*ann.P+icQP, \"k--\", label=f\"slope {slopeQP:.2f}, R²={np.corrcoef(ann.P,ann.Q)[0,1]**2:.2f}\")\nfor wy in [1949,1950,1951]:\n    axs[1].annotate(f\"WY{wy}\", (ann.P.loc[wy], ann.Q.loc[wy]), fontsize=7, color=\"red\")\naxs[1].set_xlabel(\"annual P (mm)\"); axs[1].set_ylabel(\"annual Q (mm)\"); axs[1].legend(fontsize=7); axs[1].set_title(\"(b) annual P-Q\")\nsb = d.groupby(\"season\", observed=True)[[\"P\",\"PET\",\"Q\"]].mean()*91.3\nsb.plot.bar(ax=axs[2], color=[\"#1f77b4\",\"#d62728\",\"#2ca02c\"]); axs[2].set_ylabel(\"mm per season\")\naxs[2].set_title(\"(c) seasonal water balance\"); axs[2].tick_params(axis=\"x\", rotation=0)\nfig.tight_layout(); save(fig, \"budyko_waterbalance\"); plt.show()\nprint(f\"long-term runoff ratio {Q.sum()/P.sum():.3f}; per-WY mean {ann.RR.mean():.3f} sd {ann.RR.std():.3f}, \"\n      f\"min {ann.RR.min():.3f} (WY{ann.RR.idxmin()}), max {ann.RR.max():.3f} (WY{ann.RR.idxmax()})\")\nprint(f\"Q-P elasticity (median estimator of Sankarasubramanian et al. 2001): {eps_QP:.2f} \"\n      f\"(1 % more P -> {eps_QP:.2f} % more Q); dQ/dP regression slope {slopeQP:.2f}\")\nprint(f\"aridity index PET/P = {PET.sum()/P.sum():.2f} (energy-limited, humid); evaporative index = {(P.sum()-Q.sum())/P.sum():.2f}\")\nmd(sb.round(0))\nKEY[\"elasticity_Q_P\"] = eps_QP\nKEY[\"aridity_index_PET_over_P\"] = float(PET.sum()/P.sum())\n```\n\n::: {.cell-output .cell-output-display}\n![(a) Budyko [@budyko1974] space: each dot is a water year (aridity index PET/P vs evaporative index (P-Q)/P) with the Budyko curve; (b) annual Q vs annual P; (c) seasonal water balance.](02_data_files/figure-html/fig-budyko-output-1.png){#fig-budyko width=1411 height=345}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nlong-term runoff ratio 0.349; per-WY mean 0.335 sd 0.096, min 0.192 (WY1963), max 0.598 (WY1980)\nQ-P elasticity (median estimator of Sankarasubramanian et al. 2001): 2.07 (1 % more P -> 2.07 % more Q); dQ/dP regression slope 0.75\naridity index PET/P = 0.74 (energy-limited, humid); evaporative index = 0.65\n```\n:::\n:::\n\n\n::: {#cell-fig-storage .cell execution_count=25}\n``` {.python .cell-code}\naet_proxy = PETv/PETv.sum()*(Pv.sum()-Qv.sum())\nS = np.cumsum(Pv - Qv - aet_proxy)\nfig, axs = plt.subplots(1, 2, figsize=(12, 3.2))\naxs[0].plot(d.index, S, color=\"#8c564b\"); axs[0].set_ylabel(\"storage anomaly (mm)\")\naxs[0].set_title(\"(a) cumulative P - Q - AET_proxy\")\nSm = pd.Series(S, index=d.index).groupby(d.index.month).mean() - pd.Series(S).mean()\naxs[1].bar(Sm.index, Sm.values, color=\"#8c564b\"); axs[1].set_xticks(range(1,13))\naxs[1].set_xlabel(\"month\"); axs[1].set_ylabel(\"mean anomaly (mm)\"); axs[1].set_title(\"(b) seasonal storage cycle\")\nfig.tight_layout(); save(fig, \"storage_anomaly\"); plt.show()\nprint(f\"range of the storage anomaly: {S.max()-S.min():.0f} mm (min {S.min():.0f}, max {S.max():.0f})\")\nprint(f\"seasonal amplitude (monthly means): {Sm.max()-Sm.min():.0f} mm, maximum in month {int(Sm.idxmax())}, minimum in month {int(Sm.idxmin())}\")\nprint(f\"linear-reservoir storage implied by k={k_med:.3f} at Q50 and at Qmean: \"\n      f\"{Q50/(1-k_med):.0f} mm and {Q.mean()/(1-k_med):.0f} mm (fast store only)\")\n```\n\n::: {.cell-output .cell-output-display}\n![Cumulative water-balance (dynamic storage) anomaly, S(t) = cumsum(P - Q - AET_proxy), where the AET proxy distributes the long-term AET (P-Q) in proportion to PET. Seasonal drawdown is ~150 mm; multi-year droughts (mid-1950s, early 1960s) accumulate a ~1,000 mm deficit.](02_data_files/figure-html/fig-storage-output-1.png){#fig-storage width=1299 height=333}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nrange of the storage anomaly: 1519 mm (min -1005, max 513)\nseasonal amplitude (monthly means): 153 mm, maximum in month 3, minimum in month 10\nlinear-reservoir storage implied by k=0.896 at Q50 and at Qmean: 4 mm and 13 mm (fast store only)\n```\n:::\n:::\n\n\n# Quality control {#sec-qc}\n\n::: {#cell-fig-doublemass .cell execution_count=26}\n``` {.python .cell-code}\ncp, cq = np.cumsum(Pv), np.cumsum(Qv)\nco = np.polyfit(cp, cq, 1); resid = cq - np.polyval(co, cp)\nhalf = len(cp)//2\nfig, axs = plt.subplots(1, 2, figsize=(11, 3.3))\naxs[0].plot(cp/1000, cq/1000, color=\"#2ca02c\"); axs[0].plot(cp/1000, np.polyval(co, cp)/1000, \"k--\", lw=.8)\naxs[0].set_xlabel(\"cumulative P (m)\"); axs[0].set_ylabel(\"cumulative Q (m)\")\naxs[0].set_title(f\"(a) double mass — slope {co[0]:.3f}\")\naxs[1].plot(d.index, resid, color=\"#8c564b\"); axs[1].axhline(0, color=\"k\", lw=.6)\naxs[1].set_ylabel(\"residual (mm)\"); axs[1].set_title(\"(b) residual from the fitted line\")\nfig.tight_layout(); save(fig, \"double_mass\"); plt.show()\nprint(f\"double-mass slope: whole record {co[0]:.4f} | first half {np.polyfit(cp[:half],cq[:half],1)[0]:.4f} \"\n      f\"| second half {np.polyfit(cp[half:],cq[half:],1)[0]:.4f}\")\nprint(f\"max |residual| {np.abs(resid).max():.0f} mm ({100*np.abs(resid).max()/cq[-1]:.1f} % of total Q) on {d.index[np.abs(resid).argmax()].date()}\")\n```\n\n::: {.cell-output .cell-output-display}\n![Double-mass curve of cumulative Q against cumulative P (a) and its residual from the overall straight line (b). No abrupt break; a gentle S-shape reflects the dry 1950s-60s and the wet 1970s.](02_data_files/figure-html/fig-doublemass-output-1.png){#fig-doublemass width=1188 height=344}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\ndouble-mass slope: whole record 0.3503 | first half 0.3282 | second half 0.3818\nmax |residual| 729 mm (3.6 % of total Q) on 1972-12-20\n```\n:::\n:::\n\n\n::: {#tbl-qc .cell execution_count=27}\n``` {.python .cell-code}\n# 1) physically impossible annual balances\nqc = {}\nqc[\"water years with Q > P\"] = int((ann.Q > ann.P).sum())\nqc[\"water years with runoff ratio > 0.8\"] = int((ann.RR > 0.8).sum())\nqc[\"water years with runoff ratio < 0.15\"] = int((ann.RR < 0.15).sum())\n# 2) flow rises without rain\nrise_noP = (dQv > 0.5) & (P.rolling(3).sum().fillna(0).to_numpy() < 1.0)\nqc[\"days with dQ > 0.5 mm/d and 3-day P < 1 mm\"] = int(rise_noP.sum())\n# 3) large rain without response\nbigP = Pv > 25\nresp = np.array([dQv[i+1:i+4].max() if i+4 < len(dQv) else 0 for i in np.where(bigP)[0]])\nqc[\"days with P > 25 mm\"] = int(bigP.sum())\nqc[\"...of which no response within 3 d (dQ < 0.1 mm/d)\"] = int((resp < 0.1).sum())\n# 4) timing offset diagnostics\nqc[\"corr(P_t, dQ_t)\"]   = float(np.corrcoef(Pv, dQv)[0,1])\nqc[\"corr(P_t, dQ_t+1)\"] = float(np.corrcoef(Pv[:-1], dQv[1:])[0,1])\nqc[\"corr(P_t, dQ_t+2)\"] = float(np.corrcoef(Pv[:-2], dQv[2:])[0,1])\nmd(pd.Series(qc, name=\"value\").to_frame())\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=27}\n|                                                    |      value |\n|:---------------------------------------------------|-----------:|\n| water years with Q > P                             |   0        |\n| water years with runoff ratio > 0.8                |   0        |\n| water years with runoff ratio < 0.15               |   0        |\n| days with dQ > 0.5 mm/d and 3-day P < 1 mm         |  33        |\n| days with P > 25 mm                                | 650        |\n| ...of which no response within 3 d (dQ < 0.1 mm/d) |  32        |\n| corr(P_t, dQ_t)                                    |   0.153186 |\n| corr(P_t, dQ_t+1)                                  |   0.49694  |\n| corr(P_t, dQ_t+2)                                  |   0.251894 |\n:::\n:::\n\n\n::: {#tbl-stationarity .cell execution_count=28}\n``` {.python .cell-code}\ndef pettitt(x):\n    n = len(x); r = np.argsort(np.argsort(x)) + 1\n    U = np.array([2*r[:k].sum() - k*(n+1) for k in range(1, n+1)])\n    K = int(np.abs(U).max()); k = int(np.abs(U).argmax())\n    p = float(min(2*np.exp(-6*K**2/(n**3 + n**2)), 1.0))\n    return k, K, p\nrows = []\nfor v in [\"P\",\"PET\",\"Q\"]:\n    k, K, p = pettitt(ann[v].to_numpy())\n    rows.append(dict(variable=v, change_point_after=f\"WY{ann.index[k]}\", K=K, p_value=round(p,3),\n                     significant_5pct=p < 0.05))\ndec = d.assign(decade=(d.index.year//10)*10).groupby(\"decade\")[[\"P\",\"PET\",\"Q\"]].mean()*365.25\nmd(pd.DataFrame(rows).set_index(\"variable\"))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=28}\n| variable   | change_point_after   |   K |   p_value | significant_5pct   |\n|:-----------|:---------------------|----:|----------:|:-------------------|\n| P          | WY1970               | 134 |     0.387 | False              |\n| PET        | WY1964               | 132 |     0.406 | False              |\n| Q          | WY1970               | 138 |     0.35  | False              |\n:::\n:::\n\n\n::: {#tbl-decades .cell execution_count=29}\n``` {.python .cell-code}\nmd(dec.round(0).rename(columns=lambda c: f\"{c} (mm/yr)\"))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=29}\n|   decade |   P (mm/yr) |   PET (mm/yr) |   Q (mm/yr) |\n|---------:|------------:|--------------:|------------:|\n|     1940 |        1800 |           916 |         798 |\n|     1950 |        1295 |          1087 |         393 |\n|     1960 |        1365 |          1067 |         456 |\n|     1970 |        1575 |          1039 |         604 |\n|     1980 |        1448 |          1076 |         512 |\n:::\n:::\n\n\n**QC verdict.** The record passes every check:\n\n* no year has Q > P; runoff ratios stay within 0.19–0.60, all physically sensible;\n* the 33 days with a rise of >0.5 mm/d and almost no rain in the preceding 3 days were inspected\n  individually — every one of them follows a large multi-day storm 3–6 days earlier (e.g. 1950-05-05 with\n  107 mm in the previous 5 days) and is therefore a **routing delay, not an inconsistency**;\n* 32 of 650 days with P > 25 mm produce no flow response within 3 days; these occur almost exclusively in\n  summer at very low antecedent flow, i.e. they are genuine storage-deficit events, not data errors;\n* the P→Q timing is internally consistent: corr(P_t, dQ_t) = 0.15 but corr(P_t, dQ_{t+1}) = 0.50, so the\n  response starts on the day of the storm and peaks on the following day. **No 1-day offset correction is\n  warranted** (shifting P by one day would degrade the same-day correlation to zero);\n* Pettitt tests [@pettitt1979] find no significant change point in annual P, PET or Q (p ≥ 0.35); the double-mass curve has\n  no break (maximum deviation 729 mm = 3.6 % of cumulative Q, a smooth wet/dry oscillation).\n* Decadal means show the 1950s as the driest decade (P 1,295 mm/yr, Q 393 mm/yr) and the 1970s as the\n  wettest (P 1,574 mm/yr, Q 604 mm/yr) — climate variability, not inhomogeneity.\n\n# Period comparison {#sec-periods}\n\nThe windows below come straight from `config/project.yaml` (`periods.definition = dates`, ISSUE-001\nresolved). The evaluation statistics in this section are **descriptive EDA only**; no quantity derived from\nthe evaluation window is passed downstream. Everything a model may use (scaling, feature choice,\nparameters) must come from the calibration columns.\n\n::: {#tbl-periods .cell execution_count=30}\n``` {.python .cell-code}\ndef period_stats(name):\n    s = win(name)\n    return pd.Series({\n        \"start\": s.index[0].date(), \"end\": s.index[-1].date(),\n        \"rows\": f\"{int(s['row'].iloc[0])}:{int(s['row'].iloc[-1])+1}\", \"n days\": len(s),\n        \"P (mm/yr)\": s.P.mean()*365.25, \"PET (mm/yr)\": s.PET.mean()*365.25, \"Q (mm/yr)\": s.Q.mean()*365.25,\n        \"runoff ratio\": s.Q.sum()/s.P.sum(),\n        \"Q mean\": s.Q.mean(), \"Q median\": s.Q.median(), \"Q p95\": s.Q.quantile(.95),\n        \"Q p99\": s.Q.quantile(.99), \"Q max\": s.Q.max(), \"Q min\": s.Q.min(),\n        \"Q sd\": s.Q.std(), \"Q skew\": s.Q.skew(),\n        \"P zero days (%)\": 100*(s.P == 0).mean(), \"P max\": s.P.max(),\n        \"peaks/yr (Q>9*Q50_all)\": (np.diff(np.r_[0,(s.Q > 9*Q50).astype(int)]) == 1).sum()/(len(s)/365.25),\n    })\nnames = [\"evaluation metric\", \"calibration metric\", \"internal train\", \"internal validation\"]\nPT = pd.DataFrame({n: period_stats(n) for n in names})\nmd(PT.map(lambda v: round(v, 3) if isinstance(v, float) else v))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=30}\n|                        | evaluation metric   | calibration metric   | internal train   | internal validation   |\n|:-----------------------|:--------------------|:---------------------|:-----------------|:----------------------|\n| start                  | 1949-01-01          | 1952-10-01           | 1952-10-01       | 1981-10-01            |\n| end                    | 1951-09-30          | 1988-09-30           | 1981-09-30       | 1988-09-30            |\n| rows                   | 92:1095             | 1461:14610           | 1461:12053       | 12053:14610           |\n| n days                 | 1003                | 13149                | 10592            | 2557                  |\n| P (mm/yr)              | 1570.01             | 1427.333             | 1425.77          | 1433.808              |\n| PET (mm/yr)            | 1104.725            | 1059.374             | 1061.17          | 1051.933              |\n| Q (mm/yr)              | 638.899             | 494.3                | 501.474          | 464.58                |\n| runoff ratio           | 0.407               | 0.346                | 0.352            | 0.324                 |\n| Q mean                 | 1.749               | 1.353                | 1.373            | 1.272                 |\n| Q median               | 0.631               | 0.441                | 0.447            | 0.423                 |\n| Q p95                  | 6.238               | 5.535                | 5.586            | 5.262                 |\n| Q p99                  | 19.822              | 13.37                | 13.693           | 11.839                |\n| Q max                  | 45.94               | 64.015               | 64.015           | 36.401                |\n| Q min                  | 0.119               | 0.069                | 0.069            | 0.098                 |\n| Q sd                   | 3.646               | 2.851                | 2.91             | 2.591                 |\n| Q skew                 | 6.182               | 6.881                | 7.014            | 5.956                 |\n| P zero days (%)        | 49.153              | 55.13                | 55.787           | 52.405                |\n| P max                  | 122.549             | 221.519              | 221.519          | 108.755               |\n| peaks/yr (Q>9*Q50_all) | 6.919               | 6.944                | 6.793            | 7.571                 |\n:::\n:::\n\n\n::: {#cell-fig-periods .cell execution_count=31}\n``` {.python .cell-code}\nfig, axs = plt.subplots(1, 3, figsize=(13, 3.4))\ncols = {\"evaluation metric\": \"crimson\", \"calibration metric\": \"black\",\n        \"internal train\": \"#1f77b4\", \"internal validation\": \"#ff7f0e\"}\nfor n, c in cols.items():\n    s = win(n).Q.to_numpy(); ss = np.sort(s)[::-1]\n    axs[0].semilogy(np.arange(1, len(ss)+1)/(len(ss)+1)*100, ss, color=c, lw=1.2,\n                    ls=\"--\" if \"internal\" in n else \"-\", label=n)\naxs[0].set_xlabel(\"exceedance probability (%)\"); axs[0].set_ylabel(\"Q (mm/d, log)\")\naxs[0].legend(fontsize=7); axs[0].set_title(\"(a) FDC by period\")\nfor n, c in cols.items():\n    s = win(n); axs[1].plot(s.groupby(s.index.month).Q.mean(), color=c, lw=1.2,\n                            ls=\"--\" if \"internal\" in n else \"-\", label=n)\naxs[1].set_xlabel(\"month\"); axs[1].set_ylabel(\"mean Q (mm/d)\"); axs[1].set_title(\"(b) seasonal cycle of Q\")\naxs[2].bar(ann.index, ann.P, color=np.where(ann.index <= 1951, \"crimson\", \"#1f77b4\"), label=\"P\")\naxs[2].bar(ann.index, ann.Q, color=np.where(ann.index <= 1951, \"darkred\", \"#2ca02c\"), label=\"Q\")\naxs[2].set_xlabel(\"water year\"); axs[2].set_ylabel(\"mm/yr\"); axs[2].legend(fontsize=7)\naxs[2].set_title(\"(c) WY totals (red = evaluation years)\")\nfig.tight_layout(); save(fig, \"period_comparison\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Evaluation vs calibration conditions. (a) FDC overlay of the four metric windows; (b) monthly mean Q; (c) water-year totals of P and Q with the evaluation water years highlighted.](02_data_files/figure-html/fig-periods-output-1.png){#fig-periods width=1410 height=355}\n:::\n:::\n\n\n::: {#tbl-extrapolation .cell execution_count=32}\n``` {.python .cell-code}\nex_rows = []\nfor q in [0.90, 0.95, 0.99, 0.999]:\n    th = CAL.Q.quantile(q)\n    ex_rows.append(dict(quantile=f\"Q{q*100:g} of calibration\", threshold_mm_d=round(float(th), 3),\n                        pct_eval_days_above=round(100*float((EVAL.Q > th).mean()), 2),\n                        pct_cal_days_above=round(100*(1-q), 2)))\nprint(f\"eval/calibration ratio of means:  Q {EVAL.Q.mean()/CAL.Q.mean():.3f} | \"\n      f\"P {EVAL.P.mean()/CAL.P.mean():.3f} | PET {EVAL.PET.mean()/CAL.PET.mean():.3f}\")\nprint(f\"largest eval Q {EVAL.Q.max():.1f} mm/d vs largest calibration Q {CAL.Q.max():.1f} mm/d \"\n      f\"(eval max is the {100*(CAL.Q > EVAL.Q.max()).mean():.2f} % quantile of calibration)\")\nprint(f\"largest eval P {EVAL.P.max():.1f} mm vs largest calibration P {CAL.P.max():.1f} mm\")\nprint(f\"WY ranks (1 = highest of 40): P  WY1949 {int(ann.P.rank(ascending=False)[1949])}, \"\n      f\"WY1950 {int(ann.P.rank(ascending=False)[1950])}, WY1951 {int(ann.P.rank(ascending=False)[1951])}\")\nprint(f\"                              Q  WY1949 {int(ann.Q.rank(ascending=False)[1949])}, \"\n      f\"WY1950 {int(ann.Q.rank(ascending=False)[1950])}, WY1951 {int(ann.Q.rank(ascending=False)[1951])}\")\nKEY[\"eval_vs_cal_Q_mean_ratio\"] = float(EVAL.Q.mean()/CAL.Q.mean())\nKEY[\"eval_vs_cal_P_mean_ratio\"] = float(EVAL.P.mean()/CAL.P.mean())\nKEY[\"pct_eval_days_above_cal_Q99\"] = float(100*(EVAL.Q > CAL.Q.quantile(.99)).mean())\nmd(pd.DataFrame(ex_rows).set_index(\"quantile\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\neval/calibration ratio of means:  Q 1.293 | P 1.100 | PET 1.043\nlargest eval Q 45.9 mm/d vs largest calibration Q 64.0 mm/d (eval max is the 0.03 % quantile of calibration)\nlargest eval P 122.5 mm vs largest calibration P 221.5 mm\nWY ranks (1 = highest of 40): P  WY1949 1, WY1950 14, WY1951 32\n                              Q  WY1949 2, WY1950 11, WY1951 25\n```\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=32}\n| quantile             |   threshold_mm_d |   pct_eval_days_above |   pct_cal_days_above |\n|:---------------------|-----------------:|----------------------:|---------------------:|\n| Q90 of calibration   |            3.364 |                 11.96 |                 10   |\n| Q95 of calibration   |            5.535 |                  6.58 |                  5   |\n| Q99 of calibration   |           13.37  |                  1.69 |                  1   |\n| Q99.9 of calibration |           31.984 |                  0.2  |                  0.1 |\n:::\n:::\n\n\n**Reading of the table.** The evaluation window is *inside* the calibration range but in its wet tail:\nthe evaluation metric period has 1.29× the mean flow, 1.10× the mean P and a runoff ratio of 0.41 against\n0.35 for calibration. 1.7 % of evaluation days exceed the calibration Q99 (1.7× the expected 1 %), and\n6.6 % exceed the calibration Q95. No evaluation day exceeds the calibration maximum (45.9 vs 64.0 mm/d),\nso **no strict extrapolation of the flow magnitude is required** — but models that trade high-flow bias for\nlow-flow accuracy during calibration will be penalised on this wetter window. WY1949 is the wettest water\nyear of the entire record (2,057 mm P, rank 1/40; 956 mm Q, rank 2/40).\nInternal train and internal validation are, by contrast, very similar to each other (mean Q 1.373 vs\n1.272 mm/d, runoff ratio 0.352 vs 0.324), so the internal split is a fair early-stopping/ranking device.\n\n## Calibration-only statistics for model scaling {#sec-scaling}\n\n**Downstream agents (in particular the ML builders) must use *only* the numbers in this table** for\nstandardisation, normalisation or any other data-derived constant.\n\n::: {#tbl-scaling .cell execution_count=33}\n``` {.python .cell-code}\nCALRUN = win(\"calibration run\")\nsc = pd.concat({\n    \"calibration metric (1952-10-01..1988-09-30, n=13149)\": CAL[[\"P\",\"PET\",\"Q\"]].agg([\"mean\",\"std\",\"min\",\"max\",\"median\"]).T,\n    \"calibration run incl. warm-up (1951-10-01.., n=13515)\": CALRUN[[\"P\",\"PET\",\"Q\"]].agg([\"mean\",\"std\",\"min\",\"max\",\"median\"]).T,\n})\nextra = pd.DataFrame({\n    \"log(Q) mean\": [float(np.log(CAL.Q).mean())], \"log(Q) sd\": [float(np.log(CAL.Q).std())],\n    \"log1p(Q) mean\": [float(np.log1p(CAL.Q).mean())], \"log1p(Q) sd\": [float(np.log1p(CAL.Q).std())],\n    \"sqrt(Q) mean\": [float(np.sqrt(CAL.Q).mean())], \"sqrt(Q) sd\": [float(np.sqrt(CAL.Q).std())],\n}, index=[\"calibration metric\"])\nKEY[\"cal_scaling\"] = {v: {\"mean\": float(CAL[v].mean()), \"std\": float(CAL[v].std()),\n                          \"min\": float(CAL[v].min()), \"max\": float(CAL[v].max())} for v in [\"P\",\"PET\",\"Q\"]}\nKEY[\"cal_logQ_mean\"] = float(np.log(CAL.Q).mean()); KEY[\"cal_logQ_sd\"] = float(np.log(CAL.Q).std())\nmd(sc.round(4))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=33}\n|                                                                  |   mean |     std |   min |      max |   median |\n|:-----------------------------------------------------------------|-------:|--------:|------:|---------:|---------:|\n| ('calibration metric (1952-10-01..1988-09-30, n=13149)', 'P')    | 3.9078 | 10.1414 | 0     | 221.519  |   0      |\n| ('calibration metric (1952-10-01..1988-09-30, n=13149)', 'PET')  | 2.9004 |  1.889  | 0     |   9.1148 |   2.5224 |\n| ('calibration metric (1952-10-01..1988-09-30, n=13149)', 'Q')    | 1.3533 |  2.8511 | 0.069 |  64.0148 |   0.4406 |\n| ('calibration run incl. warm-up (1951-10-01.., n=13515)', 'P')   | 3.8813 | 10.0823 | 0     | 221.519  |   0      |\n| ('calibration run incl. warm-up (1951-10-01.., n=13515)', 'PET') | 2.9075 |  1.892  | 0     |   9.1148 |   2.5281 |\n| ('calibration run incl. warm-up (1951-10-01.., n=13515)', 'Q')   | 1.3325 |  2.8179 | 0.069 |  64.0148 |   0.4355 |\n:::\n:::\n\n\n::: {#tbl-scaling2 .cell execution_count=34}\n``` {.python .cell-code}\nmd(extra.T.round(4).rename(columns={\"calibration metric\": \"value\"}))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=34}\n|               |   value |\n|:--------------|--------:|\n| log(Q) mean   | -0.5963 |\n| log(Q) sd     |  1.2192 |\n| log1p(Q) mean |  0.5989 |\n| log1p(Q) sd   |  0.5918 |\n| sqrt(Q) mean  |  0.9163 |\n| sqrt(Q) sd    |  0.7168 |\n:::\n:::\n\n\n# Implications for downstream agents {#sec-implications}\n\n**a03 (model proposer) — processes, memory, nonlinearity**\n\n* Two storage time scales are mandatory: a fast one (event response peaks 1–3 d after rain,\n  Richards–Baker 0.32) and a slow one (BFI 0.41, log-Q ACF e-folding 48 d, recession τ ≈ 9 d for the\n  intermediate store and much longer tails).\n* Recession is **non-linear** (Brutsaert–Nieber b = 1.68 ≠ 1): prefer a non-linear lower zone\n  (SAC-SMA/HBV-style) or ≥2 parallel linear reservoirs (HYMOD's quick tanks + slow tank).\n* Runoff generation is strongly **threshold-controlled**: event runoff coefficients span 0.004–0.45 and\n  scale with antecedent flow (r = 0.57) → a saturation-excess / variable-contributing-area formulation\n  (Probability-Distributed soil Moisture, as in HYMOD, or SAC-SMA's tension stores) is the natural choice.\n* Seasonality comes from PET, not P: mean P varies 2.6–5.1 mm/d over the year while mean Q varies\n  0.38–2.88 mm/d. Models must reproduce the summer evaporative shutdown (JJA: P 330 mm, PET 409 mm,\n  Q 42 mm) — no snow processes are needed in south Mississippi.\n* Long memory: a linear model on the last L days of P keeps improving to L ≈ 365 (R² 0.59 → 0.65).\n  **Recommended LSTM sequence length 180–365 days [cf. @kratzert2018] (use 365 if memory allows, 180 as a cheap default);\n  conceptual warm-up ≥ 365 days** — which is what the calibration window already provides\n  (1951-10-01…1952-09-30). Note the evaluation warm-up prescribed by the protocol is only 92 days\n  (Oct–Dec 1948), so models should be initialised from a plausible near-median storage state rather than\n  from empty stores.\n* PET is **not** climatological (same-DOY inter-annual SD 1.30 mm/d): feed the actual PET series, do not\n  replace it with a seasonal curve.\n\n**a04 (metrics advisor) — distribution and objective transformation**\n\n* Daily Q: skewness 6.8, kurtosis 77, Q5/Q95 = 47, log-normal-shaped in log space; the wettest 1 % of\n  days carry 16 % and the wettest 5 % carry 40 % of the total flow volume. Untransformed squared errors (NSE/KGE on Q) are dominated by ~20 flood days\n  per year.\n* Q is **strictly positive** (min 0.069 mm/d) → log, sqrt and Box-Cox transforms need **no offset**;\n  sensible complements to the mandated KGE/NSE during development are KGE on log Q or sqrt Q, or a\n  split KGE / FDC-signature diagnostics [@yilmaz2008]. Final reporting stays KGE + NSE on untransformed Q, per `config/project.yaml`.\n* Calibration-period moments for the KGE β/α terms: mean 1.3533 mm/d, sd 2.8511 mm/d.\n\n**a05–a09 (model builders) — units and practicalities**\n\n* All three series are mm/day; no unit conversion is needed anywhere. Basin area ≈ 1,950 km² if a discharge\n  in m³/s is ever required (1 mm/d = 22.57 m³/s).\n* P has 54.9 % exact zeros; Q has **no** zeros and no NaN → no special missing-value or zero-flow handling.\n* Never derive scaling constants from anything but @sec-scaling.\n\n**a10 (optimisation advisor) — response-surface expectations**\n\n* 13,149 calibration days with a heavy-tailed target: the objective surface for untransformed NSE/KGE is\n  dominated by a handful of flood years (WY1961, WY1974, WY1980) and is therefore rough;\n  global search (SCE-UA/DE) rather than local gradient descent is advised, consistent with the fact that\n  this exact data set is the SCE-UA benchmark [@duan1992].\n* Strong parameter interaction is expected between the fast/slow partition (BFI ≈ 0.41) and the recession\n  constants (k ≈ 0.90).\n\n**a16 (evaluator) — risks**\n\n* The evaluation window is the **wettest** part of the record (Q mean ratio 1.29, WY1949 the wettest year).\n  A model calibrated on 1952–1988 will most likely show a positive α and a slight negative β bias there;\n  report the KGE decomposition, not just the total.\n* The evaluation warm-up is only 92 days — differences between models in initial-state handling will be\n  visible in Jan–Mar 1949. Warm-up rows are not scored (metric starts 1949-01-01).\n\n# Processed data set\n\n::: {#write-parquet .cell execution_count=35}\n``` {.python .cell-code}\nout = ROOT / CFG[\"data\"][\"processed_file\"]\nout.parent.mkdir(parents=True, exist_ok=True)\ndf.to_parquet(out)                       # canonical frame from src/common/data.py (P, PET, Q, row)\nchk = pd.read_parquet(out)\nprint(f\"written : {out.relative_to(ROOT)}  ({out.stat().st_size/1e3:.1f} kB)\")\nprint(f\"shape   : {chk.shape}, columns {list(chk.columns)}, index {chk.index[0].date()}..{chk.index[-1].date()}\")\nprint(f\"identical to load_data(): {chk.equals(df)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nwritten : data/processed/leafriver_daily.parquet  (402.4 kB)\nshape   : (14610, 4), columns ['P', 'PET', 'Q', 'row'], index 1948-10-01..1988-09-30\nidentical to load_data(): True\n```\n:::\n:::\n\n\nThe processed file is a byte-faithful copy of what `src.common.data.load_data()` returns (no derived\ncolumns, no filtering) — it exists so downstream agents can load the record without re-parsing the ASCII\nfile, but **the canonical access path remains `src/common/data.py`**.\n\n# Appendix: key numbers {#sec-appendix}\n\n::: {#key-numbers .cell execution_count=36}\n``` {.python .cell-code}\nKEY[\"qc_flags\"] = [\"no_missing_values\", \"no_negatives\", \"no_zero_flows\", \"perennial_river\",\n                   \"Q_quantised_at_1cfs\", \"one_PET_zero_1966-01-14\",\n                   \"no_significant_trend_MK\", \"no_pettitt_change_point\",\n                   \"no_double_mass_break\", \"no_1day_PQ_offset\",\n                   \"33_rises_without_rain_all_explained_by_routing_delay\",\n                   \"eval_window_wetter_than_calibration\"]\nprint(json.dumps({k: (round(v, 6) if isinstance(v, float) else v) for k, v in KEY.items()\n                  if not isinstance(v, dict)}, indent=1, default=str))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n{\n \"P_mean_mm_yr\": 1431.661065,\n \"PET_mean_mm_yr\": 1062.368195,\n \"Q_mean_mm_yr\": 500.278714,\n \"runoff_ratio\": 0.349439,\n \"Q_skewness\": 6.84934,\n \"pct_zero_P\": 54.887064,\n \"implied_area_km2\": 1950.348402,\n \"Q_quantum_mm_d\": 0.001254,\n \"pet_is_climatological\": false,\n \"pet_doy_interannual_sd_mm_d\": 1.303552,\n \"Q5_mm_d\": 5.57305,\n \"Q50_mm_d\": 0.448103,\n \"Q95_mm_d\": 0.119242,\n \"richards_baker\": 0.315881,\n \"fdc_slope_33_66\": 3.497519,\n \"bfi_lyne_hollick\": 0.408374,\n \"bfi_eckhardt_bfimax080\": 0.71311,\n \"recession_k\": 0.895725,\n \"recession_tau_days\": 9.080812,\n \"bn_exponent_b\": 1.676589,\n \"lag_peak_xcorr_days\": 3,\n \"lag_response_onset_days\": 1,\n \"acf_logQ_efolding_days\": 48,\n \"acf_Q_lag1\": 0.888039,\n \"elasticity_Q_P\": 2.069593,\n \"aridity_index_PET_over_P\": 0.742053,\n \"eval_vs_cal_Q_mean_ratio\": 1.292534,\n \"eval_vs_cal_P_mean_ratio\": 1.09996,\n \"pct_eval_days_above_cal_Q99\": 1.694915,\n \"cal_logQ_mean\": -0.596274,\n \"cal_logQ_sd\": 1.219194,\n \"qc_flags\": [\n  \"no_missing_values\",\n  \"no_negatives\",\n  \"no_zero_flows\",\n  \"perennial_river\",\n  \"Q_quantised_at_1cfs\",\n  \"one_PET_zero_1966-01-14\",\n  \"no_significant_trend_MK\",\n  \"no_pettitt_change_point\",\n  \"no_double_mass_break\",\n  \"no_1day_PQ_offset\",\n  \"33_rises_without_rain_all_explained_by_routing_delay\",\n  \"eval_window_wetter_than_calibration\"\n ]\n}\n```\n:::\n:::\n\n\n::: {#versions .cell execution_count=37}\n``` {.python .cell-code}\nimport platform, pyarrow, matplotlib, statsmodels, scipy\nprint(\"python      \", platform.python_version())\nfor m in [np, pd, scipy, statsmodels, matplotlib, sns, pyarrow, mk]:\n    print(f\"{m.__name__:12s}\", getattr(m, \"__version__\", \"n/a\"))\nprint(\"seed        \", SEED)\nprint(\"figures     \", sorted(p.name for p in FIG.glob(\"a02_*.png\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npython       3.11.16\nnumpy        2.0.2\npandas       3.0.5\nscipy        1.17.1\nstatsmodels  0.15.0\nmatplotlib   3.11.1\nseaborn      0.13.2\npyarrow      25.0.0\npymannkendall 1.4.3\nseed         42\nfigures      ['a02_PET_climatology_test.png', 'a02_P_distribution.png', 'a02_Q_distribution.png', 'a02_annual_totals.png', 'a02_baseflow.png', 'a02_budyko_waterbalance.png', 'a02_date_alignment_check.png', 'a02_double_mass.png', 'a02_event_runoff_coefficients.png', 'a02_fdc.png', 'a02_memory.png', 'a02_monthly_boxplots.png', 'a02_overview_timeseries.png', 'a02_period_comparison.png', 'a02_recession.png', 'a02_storage_anomaly.png', 'a02_wateryear_small_multiples.png']\n```\n:::\n:::\n\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "02_data_files"
    ],
    "filters": [],
    "includes": {}
  }
}