{
  "hash": "127009dc45a3ed1978924de3a25f4d91",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Performance metrics for daily streamflow and the calibration objective for Leaf River\"\nsubtitle: \"Agent 4 (a04-metrics-advisor) — phase P2\"\nauthor: \"a04-metrics-advisor\"\ndate: 2026-09-15\njupyter: leafriver\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    fig-dpi: 150\n    tbl-cap-location: top\nbibliography: references.bib\n---\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\"}\nimport os, sys, json, time, warnings\nfrom pathlib import Path\n\nROOT = Path.cwd()\nwhile not (ROOT / \"config\" / \"project.yaml\").exists():\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT)); os.chdir(ROOT)\n\nimport numpy as np, pandas as pd\nimport matplotlib as mpl, matplotlib.pyplot as plt\nimport seaborn as sns\nwarnings.filterwarnings(\"ignore\")\n\nfrom src.common.data import load_data, load_config, slice_run, metric_mask, internal_mask\nfrom src.common.metrics import kge, nse, kge_components      # CANONICAL - never re-implemented\nimport src.common.metrics_extra as mx                        # Agent 4 extension\n\nCFG  = load_config()\nSEED = CFG[\"reproducibility\"][\"random_seed\"]\nnp.random.seed(SEED)\nFIG  = ROOT / \"results\" / \"figures\"; FIG.mkdir(parents=True, exist_ok=True)\nsns.set_theme(style=\"whitegrid\", context=\"notebook\")\nmpl.rcParams.update({\"figure.dpi\": 110, \"savefig.dpi\": 150, \"savefig.bbox\": \"tight\",\n                     \"axes.titlesize\": 10, \"axes.labelsize\": 9,\n                     \"xtick.labelsize\": 8, \"ytick.labelsize\": 8, \"legend.fontsize\": 8})\n\ndef save(fig, name):\n    p = FIG / f\"a04_{name}.png\"; fig.savefig(p); return p\n\ndef md(obj, **kw):\n    from IPython.display import Markdown\n    return Markdown(obj.to_markdown(**kw))\n\n# ---- data: calibration only. The evaluation window is never touched in this report. ----\ndf   = load_data()\nrun  = slice_run(df, \"calibration\")           # 1951-10-01 .. 1988-09-30 (warm-up included)\nMM   = metric_mask(run, \"calibration\")        # 1952-10-01 .. 1988-09-30, 13 149 d\nTR   = internal_mask(run, \"train\")            # 1952-10-01 .. 1981-09-30, 10 592 d\nVA   = internal_mask(run, \"validation\")       # 1981-10-01 .. 1988-09-30,  2 557 d\nP    = np.ascontiguousarray(run[\"P\"].to_numpy())\nPET  = np.ascontiguousarray(run[\"PET\"].to_numpy())\nOBS  = run[\"Q\"].to_numpy()\nIDX  = run.index\nWY   = IDX.year + (IDX.month >= 10).astype(int)\n\nO    = OBS[MM]\nCV_O = O.std() / O.mean()\nprint(f\"calibration metric window: {IDX[MM][0].date()} .. {IDX[MM][-1].date()}  n = {MM.sum()} d\")\nprint(f\"mean {O.mean():.4f} mm/d | sd {O.std():.4f} mm/d | CV {CV_O:.4f} | \"\n      f\"skew {float(((O-O.mean())**3).mean()/O.std()**3):.2f} | min {O.min():.4f} | max {O.max():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncalibration metric window: 1952-10-01 .. 1988-09-30  n = 13149 d\nmean 1.3533 mm/d | sd 2.8510 mm/d | CV 2.1067 | skew 6.88 | min 0.0690 | max 64.01\n```\n:::\n:::\n\n\n::: {.callout-important}\n## Recommendation in one box\n\n**Calibrate every model slot (a11–a15) by MAXIMISING the equally weighted average of the two\nmetrics that will be reported:**\n\n$$\n\\mathcal{O} \\;=\\; 0.5\\,\\mathrm{KGE}\\!\\left(Q_{\\text{sim}},Q_{\\text{obs}}\\right)\n            \\;+\\; 0.5\\,\\mathrm{NSE}\\!\\left(Q_{\\text{sim}},Q_{\\text{obs}}\\right)\n$$\n\non **untransformed** daily flow (mm/day), KGE as defined by @gupta2009 and NSE by @nash1970\n(the project's canonical `src/common/metrics.py`), evaluated on the **calibration metric window\n1952-10-01 … 1988-09-30 (13 149 days)**, warm-up 1951-10-01 … 1952-09-30 excluded.\nOptimisers that minimise use the cost $1-\\mathcal{O}$ (perfect = 0, unbounded above).\nImplementation: `src.common.metrics_extra.objective` / `objective_cost`; contract:\n`config/metrics.yaml`.\n\n*No transform and therefore no offset $\\varepsilon$ anywhere.* Observed $Q\\ge0.069$ mm/day on all\n14 610 days, so $\\sqrt{\\cdot}$, $\\log$ and Box–Cox **would** be defined without an arbitrary\nconstant (@sec-why) — the point is that they are not needed: a third $\\mathrm{KGE}(\\sqrt{Q})$ term\nwas tested explicitly and changed every out-of-sample number by less than 0.001.\n\n*Why not plain KGE, the ranking metric?* Because @sec-transfer calibrates two surrogate\nrainfall–runoff models under **24 candidate objectives** on **four independent splits inside the\ncalibration period** (three of them 20–46 % wetter than their training years, mimicking the\nevaluation window, which is 29 % wetter than calibration). Result, as mean shortfall behind the\nbest objective of each of the 8 experiments (\"regret\"):\n\n| objective used for calibration | regret in KGE | regret in NSE | worst case KGE | worst case NSE |\n|---|---|---|---|---|\n| **0.5·KGE + 0.5·NSE (recommended)** | 0.026 | 0.017 | **0.056** | **0.047** |\n| KGE alone | **0.020** | 0.047 | 0.039 | 0.162 |\n| NSE alone | 0.052 | **0.003** | 0.107 | 0.010 |\n| KGE(√Q) | 0.024 | 0.019 | 0.067 | 0.063 |\n\nKGE alone and NSE alone each win *their own* metric and lose badly on the other; the 50/50 average\nis the only candidate whose **worst case stays below 0.06 on both metrics simultaneously**. KGE and\nNSE are not redundant on this record — their Spearman rank correlation over behavioural simulations\nis ≈0.7 (@fig-objcorr) — so the average is a genuine compromise rather than a re-weighting.\n\nTrainable models (a09, LSTM) minimise the identical quantity as a **full-batch** loss\n(population standard deviations); a per-mini-batch KGE is a different objective.\n\n**Reported metrics are fixed and are NOT chosen here:** a16 reports **KGE and NSE on untransformed\n$Q$** only, ranked by KGE, per `config/project.yaml`.\n:::\n\n# Scope and constraints {#sec-scope}\n\nThe metrics in the *final* report are fixed by the user and by `config/project.yaml`\n(`evaluation_protocol.required_metrics: [KGE, NSE]`, `primary_selection_metric: KGE`,\n`final_report_metrics_only: true`). Agent 4 therefore does **not** choose the reporting metrics.\nWhat Agent 4 chooses is the **calibration objective**: the scalar that a10's optimisers and\na11–a15's calibration runs drive to its optimum. Objective $\\ne$ reporting metric is a deliberate\nand well-documented distinction [@clark2021; @mizukami2019]: the objective is an *estimator design\nchoice* whose only job is to put parameters where the reported metrics will be good **on data the\ncalibration never saw**.\n\nThree hard boundary conditions frame the choice:\n\n| # | Constraint | Consequence for the objective |\n|---|---|---|\n| 1 | Report = KGE and NSE on raw $Q$; KGE decides the ranking | The objective must be dominated by an untransformed KGE term; an objective built purely on transformed flows optimises the wrong thing |\n| 2 | Evaluation window (1949-01-01…1951-09-30) is the **wettest** stretch of the record: mean $Q$ 1.749 vs 1.353 mm/d (ratio 1.29), runoff ratio 0.41 vs 0.35, 1.7 % of days above the calibration $Q_{99}$, but max 45.9 mm/d **below** the calibration max 64.0 mm/d | No magnitude extrapolation is needed, but the objective must not buy calibration score by over-fitting the few largest floods, and must control the volume ratio $\\beta$, which is what shifts under a wet transfer |\n| 3 | Only 92 warm-up days precede the evaluation metric window | Objectives that depend on long-memory low-flow behaviour (log, $1/Q$) are the most exposed to initial-state error early in 1949 |\n\n: Boundary conditions imposed on the objective choice. {#tbl-constraints}\n\n# Catalogue of metrics {#sec-catalogue}\n\nAll formulas use $s_i$ = simulated and $o_i$ = observed daily flow (mm/day), $i=1\\dots n$ over the\nmetric window, $\\mu$ = mean, $\\sigma$ = standard deviation (population), $r$ = Pearson correlation.\nEvery metric listed here is implemented in `src/common/metrics_extra.py` and registered in\n`mx.METRICS`, with `mx.ORIENTATION` (+1 larger-is-better, −1 smaller-is-better, 0 target-value) and\n`mx.OPTIMUM`. `KGE` and `NSE` themselves are imported from the canonical `src/common/metrics.py`.\n\n## Squared-error family\n\n$$\n\\mathrm{MSE}=\\frac1n\\sum (s_i-o_i)^2,\\qquad \\mathrm{RMSE}=\\sqrt{\\mathrm{MSE}},\\qquad\n\\mathrm{NSE}=1-\\frac{\\sum (s_i-o_i)^2}{\\sum (o_i-\\mu_o)^2}\n$$\n\n$$\n\\mathrm{NSE}_{T}=1-\\frac{\\sum (T(s_i)-T(o_i))^2}{\\sum (T(o_i)-\\mu_{T(o)})^2},\\quad\nT\\in\\{\\sqrt{\\cdot},\\ \\log,\\ 1/\\cdot,\\ \\text{Box–Cox}_\\lambda\\},\\qquad\n\\mathrm{NNSE}=\\frac{1}{2-\\mathrm{NSE}}\n$$\n\n@gupta2009 decomposition, used throughout this report:\n$$\n\\mathrm{NSE}=2\\alpha r-\\alpha^2-\\beta_n^2,\\qquad\n\\alpha=\\frac{\\sigma_s}{\\sigma_o},\\quad \\beta_n=\\frac{\\mu_s-\\mu_o}{\\sigma_o}.\n$$\n\n::: {#tbl-cat-sse .cell tbl-cap='Squared-error family. \\'Sens.\\' = which part of the hydrograph dominates the score.' execution_count=2}\n``` {.python .cell-code}\nrows = [\n (\"MSE / RMSE\", r\"$\\frac1n\\sum(s-o)^2$\", \"[0,∞)\", \"0\", \"mm²/d² / mm/d\", \"high flows (extreme)\", \"simple; RMSE in flow units; identical ranking to NSE and to the Gaussian MLE\", \"not comparable between basins/periods; ~1 % of days dominate\", \"@legates1999\"),\n (\"NSE\", r\"$1-\\frac{\\sum(s-o)^2}{\\sum(o-\\mu_o)^2}$\", \"(−∞,1]\", \"1\", \"–\", \"high flows (extreme)\", \"normalised by observed variance; benchmark = mean flow; required by the project\", \"blind to volume bias when CV is large (@sec-why); biased low for short/skewed samples [@lamontagne2020]\", \"@nash1970\"),\n (\"log-NSE\", r\"$\\mathrm{NSE}$ on $\\log Q$\", \"(−∞,1]\", \"1\", \"–\", \"low flows\", \"recessions and baseflow; near-Gaussian residuals here\", \"hypersensitive to small absolute errors at low flow; needs $\\\\varepsilon$ if $Q=0$ (not here)\", \"@oudin2006\"),\n (\"sqrt-NSE\", r\"$\\mathrm{NSE}$ on $\\sqrt{Q}$\", \"(−∞,1]\", \"1\", \"–\", \"balanced (mid/high)\", \"variance-stabilising for Poisson-like skew; keeps peaks relevant\", \"no closed-form diagnostic split\", \"@oudin2006\"),\n (\"inverse-NSE\", r\"$\\mathrm{NSE}$ on $1/Q$\", \"(−∞,1]\", \"1\", \"–\", \"very low flows\", \"sharpest low-flow criterion\", \"numerically explosive; irrelevant for a perennial humid basin\", \"@pushpalatha2012\"),\n (\"Box–Cox NSE\", r\"$T_\\lambda(Q)=\\frac{Q^\\lambda-1}{\\lambda}$\", \"(−∞,1]\", \"1\", \"–\", \"tunable by $\\\\lambda$\", \"one knob interpolates raw ($\\\\lambda=1$) → log ($\\\\lambda\\\\to0$); $\\\\lambda=0.25$ common\", \"extra parameter to justify\", \"@box1964\"),\n (\"NNSE\", r\"$1/(2-\\mathrm{NSE})$\", \"(0,1]\", \"1\", \"–\", \"as NSE\", \"bounded; convenient for sensitivity analysis\", \"monotone re-scaling only: identical ranking\", \"@nossent2012\"),\n (\"weighted NSE\", r\"$1-\\frac{\\sum w_i(s-o)^2}{\\sum w_i(o-\\bar o_w)^2}$\", \"(−∞,1]\", \"1\", \"–\", \"chosen by $w$\", \"can up-weight seasons/events\", \"weights are arbitrary and hard to defend\", \"@krause2005\"),\n (\"$R^2$\", r\"$r^2$\", \"[0,1]\", \"1\", \"–\", \"high flows\", \"shape only\", \"insensitive to bias and to variance errors — never use alone\", \"@legates1999\"),\n]\nmd(pd.DataFrame(rows, columns=[\"Metric\",\"Formula\",\"Range\",\"Opt.\",\"Units\",\"Sens.\",\"Strengths\",\"Weaknesses\",\"Ref.\"]), index=False)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=2}\n| Metric       | Formula                                            | Range   |   Opt. | Units         | Sens.                | Strengths                                                                            | Weaknesses                                                                                              | Ref.             |\n|:-------------|:---------------------------------------------------|:--------|-------:|:--------------|:---------------------|:-------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------|:-----------------|\n| MSE / RMSE   | $\\frac1n\\sum(s-o)^2$                               | [0,∞)   |      0 | mm²/d² / mm/d | high flows (extreme) | simple; RMSE in flow units; identical ranking to NSE and to the Gaussian MLE         | not comparable between basins/periods; ~1 % of days dominate                                            | @legates1999     |\n| NSE          | $1-\\frac{\\sum(s-o)^2}{\\sum(o-\\mu_o)^2}$            | (−∞,1]  |      1 | –             | high flows (extreme) | normalised by observed variance; benchmark = mean flow; required by the project      | blind to volume bias when CV is large (@sec-why); biased low for short/skewed samples [@lamontagne2020] | @nash1970        |\n| log-NSE      | $\\mathrm{NSE}$ on $\\log Q$                         | (−∞,1]  |      1 | –             | low flows            | recessions and baseflow; near-Gaussian residuals here                                | hypersensitive to small absolute errors at low flow; needs $\\varepsilon$ if $Q=0$ (not here)            | @oudin2006       |\n| sqrt-NSE     | $\\mathrm{NSE}$ on $\\sqrt{Q}$                       | (−∞,1]  |      1 | –             | balanced (mid/high)  | variance-stabilising for Poisson-like skew; keeps peaks relevant                     | no closed-form diagnostic split                                                                         | @oudin2006       |\n| inverse-NSE  | $\\mathrm{NSE}$ on $1/Q$                            | (−∞,1]  |      1 | –             | very low flows       | sharpest low-flow criterion                                                          | numerically explosive; irrelevant for a perennial humid basin                                           | @pushpalatha2012 |\n| Box–Cox NSE  | $T_\\lambda(Q)=\\frac{Q^\\lambda-1}{\\lambda}$         | (−∞,1]  |      1 | –             | tunable by $\\lambda$ | one knob interpolates raw ($\\lambda=1$) → log ($\\lambda\\to0$); $\\lambda=0.25$ common | extra parameter to justify                                                                              | @box1964         |\n| NNSE         | $1/(2-\\mathrm{NSE})$                               | (0,1]   |      1 | –             | as NSE               | bounded; convenient for sensitivity analysis                                         | monotone re-scaling only: identical ranking                                                             | @nossent2012     |\n| weighted NSE | $1-\\frac{\\sum w_i(s-o)^2}{\\sum w_i(o-\\bar o_w)^2}$ | (−∞,1]  |      1 | –             | chosen by $w$        | can up-weight seasons/events                                                         | weights are arbitrary and hard to defend                                                                | @krause2005      |\n| $R^2$        | $r^2$                                              | [0,1]   |      1 | –             | high flows           | shape only                                                                           | insensitive to bias and to variance errors — never use alone                                            | @legates1999     |\n:::\n:::\n\n\n## KGE family\n\n$$\n\\mathrm{KGE}=1-\\sqrt{(r-1)^2+(\\alpha-1)^2+(\\beta-1)^2},\\qquad\n\\alpha=\\frac{\\sigma_s}{\\sigma_o},\\quad \\beta=\\frac{\\mu_s}{\\mu_o}\n$$\n\n::: {#tbl-cat-kge .cell tbl-cap='KGE family. All are +1-oriented with optimum 1 and are dimensionless.' execution_count=3}\n``` {.python .cell-code}\nrows = [\n (\"KGE (2009)\", r\"$1-\\sqrt{(r-1)^2+(\\alpha-1)^2+(\\beta-1)^2}$\", \"(−∞,1]\", \"balanced\", \"explicit, orthogonal control of timing, variability and volume; project ranking metric\", \"mean-flow benchmark is −0.41, not 0 [@knoben2019]\", \"@gupta2009\"),\n (\"KGE′ (2012)\", r\"$\\gamma=\\frac{\\sigma_s/\\mu_s}{\\sigma_o/\\mu_o}$ replaces $\\alpha$\", \"(−∞,1]\", \"balanced\", \"removes the correlation between the $\\\\alpha$ and $\\\\beta$ terms\", \"$\\\\gamma$ is blind to a pure scaling error, so bias is penalised only once\", \"@kling2012\"),\n (\"KGE″ (2021)\", r\"$\\beta_n=\\frac{\\mu_s-\\mu_o}{\\sigma_o}$ replaces $\\beta$\", \"(−∞,1]\", \"balanced\", \"stable when $\\\\mu_o\\\\to0$ (ephemeral rivers)\", \"at CV = 2.11 the bias term almost disappears — becomes NSE-like (@sec-why)\", \"@tang2021\"),\n (\"non-parametric KGE\", r\"Spearman $r_S$, FDC-based $\\alpha_{NP}=1-\\tfrac12\\sum|\\tfrac{s_{(k)}}{n\\mu_s}-\\tfrac{o_{(k)}}{n\\mu_o}|$\", \"(−∞,1]\", \"balanced, robust\", \"insensitive to the extreme tail; compares full FDC shape\", \"loses information on the magnitude of individual events\", \"@pool2018\"),\n (\"KGE on $T(Q)$\", r\"KGE of $\\sqrt{Q}$, $\\log Q$, $1/Q$\", \"(−∞,1]\", \"set by $T$\", \"shifts emphasis while keeping the 3-way decomposition\", \"log-KGE is dominated by the smallest flows; $\\\\beta$ on logs is not a volume ratio [@santos2018]\", \"@santos2018\"),\n (\"components $r,\\\\alpha,\\\\beta$\", r\"see above\", \"$r\\\\in[-1,1]$, $\\\\alpha,\\\\beta>0$\", \"diagnostic\", \"tells *why* a model fails; mandatory diagnostic in this project\", \"not a single ranking number\", \"@gupta2009\"),\n (\"split KGE\", r\"$\\frac1m\\sum_j \\mathrm{KGE}_j$ over sub-periods $j$\", \"(−∞,1]\", \"balanced in time\", \"exposes non-stationary performance; robust to one dominant year\", \"noisy for short windows\", \"@fowler2018\"),\n (\"KGE skill score\", r\"$\\frac{\\mathrm{KGE}-\\mathrm{KGE}_{\\text{bench}}}{1-\\mathrm{KGE}_{\\text{bench}}}$\", \"(−∞,1]\", \"as KGE\", \"puts KGE on a 0 = benchmark scale\", \"benchmark must be declared\", \"@knoben2019; @seibert2001\"),\n (\"DE (2021)\", r\"$1-\\sqrt{\\bar\\delta_B^2+\\delta_A^2+(1-r)^2}$ on relative FDC errors\", \"(−∞,1]\", \"FDC shape\", \"diagnoses constant vs dynamic bias separately\", \"young metric; relative errors blow up at low flow\", \"@schwemmle2021\"),\n]\nmd(pd.DataFrame(rows, columns=[\"Metric\",\"Formula\",\"Range\",\"Sens.\",\"Strengths\",\"Weaknesses\",\"Ref.\"]), index=False)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=3}\n| Metric                      | Formula                                                                                                 | Range                          | Sens.            | Strengths                                                                              | Weaknesses                                                                                      | Ref.                      |\n|:----------------------------|:--------------------------------------------------------------------------------------------------------|:-------------------------------|:-----------------|:---------------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------------|:--------------------------|\n| KGE (2009)                  | $1-\\sqrt{(r-1)^2+(\\alpha-1)^2+(\\beta-1)^2}$                                                             | (−∞,1]                         | balanced         | explicit, orthogonal control of timing, variability and volume; project ranking metric | mean-flow benchmark is −0.41, not 0 [@knoben2019]                                               | @gupta2009                |\n| KGE′ (2012)                 | $\\gamma=\\frac{\\sigma_s/\\mu_s}{\\sigma_o/\\mu_o}$ replaces $\\alpha$                                        | (−∞,1]                         | balanced         | removes the correlation between the $\\alpha$ and $\\beta$ terms                         | $\\gamma$ is blind to a pure scaling error, so bias is penalised only once                       | @kling2012                |\n| KGE″ (2021)                 | $\\beta_n=\\frac{\\mu_s-\\mu_o}{\\sigma_o}$ replaces $\\beta$                                                 | (−∞,1]                         | balanced         | stable when $\\mu_o\\to0$ (ephemeral rivers)                                             | at CV = 2.11 the bias term almost disappears — becomes NSE-like (@sec-why)                      | @tang2021                 |\n| non-parametric KGE          | Spearman $r_S$, FDC-based $\\alpha_{NP}=1-\\tfrac12\\sum|\\tfrac{s_{(k)}}{n\\mu_s}-\\tfrac{o_{(k)}}{n\\mu_o}|$ | (−∞,1]                         | balanced, robust | insensitive to the extreme tail; compares full FDC shape                               | loses information on the magnitude of individual events                                         | @pool2018                 |\n| KGE on $T(Q)$               | KGE of $\\sqrt{Q}$, $\\log Q$, $1/Q$                                                                      | (−∞,1]                         | set by $T$       | shifts emphasis while keeping the 3-way decomposition                                  | log-KGE is dominated by the smallest flows; $\\beta$ on logs is not a volume ratio [@santos2018] | @santos2018               |\n| components $r,\\alpha,\\beta$ | see above                                                                                               | $r\\in[-1,1]$, $\\alpha,\\beta>0$ | diagnostic       | tells *why* a model fails; mandatory diagnostic in this project                        | not a single ranking number                                                                     | @gupta2009                |\n| split KGE                   | $\\frac1m\\sum_j \\mathrm{KGE}_j$ over sub-periods $j$                                                     | (−∞,1]                         | balanced in time | exposes non-stationary performance; robust to one dominant year                        | noisy for short windows                                                                         | @fowler2018               |\n| KGE skill score             | $\\frac{\\mathrm{KGE}-\\mathrm{KGE}_{\\text{bench}}}{1-\\mathrm{KGE}_{\\text{bench}}}$                        | (−∞,1]                         | as KGE           | puts KGE on a 0 = benchmark scale                                                      | benchmark must be declared                                                                      | @knoben2019; @seibert2001 |\n| DE (2021)                   | $1-\\sqrt{\\bar\\delta_B^2+\\delta_A^2+(1-r)^2}$ on relative FDC errors                                     | (−∞,1]                         | FDC shape        | diagnoses constant vs dynamic bias separately                                          | young metric; relative errors blow up at low flow                                               | @schwemmle2021            |\n:::\n:::\n\n\n## Absolute-error, bias and agreement\n\n::: {#tbl-cat-bias .cell tbl-cap='Absolute-error / bias / agreement metrics.' execution_count=4}\n``` {.python .cell-code}\nrows = [\n (\"MAE\", r\"$\\frac1n\\sum|s-o|$\", \"[0,∞)\", \"0\", \"mm/d\", \"mid/low flows\", \"robust to outliers; flow units\", \"insensitive to peak errors; not normalised\", \"@legates1999\"),\n (\"PBIAS\", r\"$100\\frac{\\sum(s-o)}{\\sum o}$\", \"(−100,∞)\", \"0\", \"%\", \"volume\", \"direct water-balance check; **here positive = over-prediction**, the negative of the @moriasi2007 sign\", \"says nothing about dynamics\", \"@moriasi2007\"),\n (\"VE\", r\"$\\frac{\\sum s}{\\sum o}-1=\\beta-1$\", \"(−1,∞)\", \"0\", \"–\", \"volume\", \"identical information to KGE's $\\\\beta$\", \"as PBIAS\", \"@moriasi2007\"),\n (\"MARE\", r\"$\\frac1n\\sum\\frac{|s-o|}{o}$\", \"[0,∞)\", \"0\", \"–\", \"low flows\", \"scale free\", \"explodes at small $o$; asymmetric\", \"@legates1999\"),\n (\"Pearson $r$\", r\"$\\mathrm{corr}(s,o)$\", \"[−1,1]\", \"1\", \"–\", \"high flows/timing\", \"component of KGE\", \"blind to bias and amplitude\", \"@legates1999\"),\n (\"Spearman $\\\\rho$\", r\"corr of ranks\", \"[−1,1]\", \"1\", \"–\", \"shape, robust\", \"insensitive to the heavy tail\", \"loses magnitude\", \"@pool2018\"),\n (\"Willmott $d$\", r\"$1-\\frac{\\sum(s-o)^2}{\\sum(|s-\\mu_o|+|o-\\mu_o|)^2}$\", \"[0,1]\", \"1\", \"–\", \"high flows\", \"bounded; sensitive to additive and proportional differences\", \"compresses differences near 1; hard to interpret\", \"@willmott1981\"),\n (\"$d_1$, $d_r$\", r\"absolute-error versions\", \"[0,1] / [−1,1]\", \"1\", \"–\", \"mid flows\", \"$d_r$ is the bounded MAE-based analogue of NSE\", \"rarely reported in hydrology\", \"@willmott2012\"),\n]\nmd(pd.DataFrame(rows, columns=[\"Metric\",\"Formula\",\"Range\",\"Opt.\",\"Units\",\"Sens.\",\"Strengths\",\"Weaknesses\",\"Ref.\"]), index=False)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=4}\n| Metric          | Formula                                             | Range          |   Opt. | Units   | Sens.             | Strengths                                                                                              | Weaknesses                                       | Ref.          |\n|:----------------|:----------------------------------------------------|:---------------|-------:|:--------|:------------------|:-------------------------------------------------------------------------------------------------------|:-------------------------------------------------|:--------------|\n| MAE             | $\\frac1n\\sum|s-o|$                                  | [0,∞)          |      0 | mm/d    | mid/low flows     | robust to outliers; flow units                                                                         | insensitive to peak errors; not normalised       | @legates1999  |\n| PBIAS           | $100\\frac{\\sum(s-o)}{\\sum o}$                       | (−100,∞)       |      0 | %       | volume            | direct water-balance check; **here positive = over-prediction**, the negative of the @moriasi2007 sign | says nothing about dynamics                      | @moriasi2007  |\n| VE              | $\\frac{\\sum s}{\\sum o}-1=\\beta-1$                   | (−1,∞)         |      0 | –       | volume            | identical information to KGE's $\\beta$                                                                 | as PBIAS                                         | @moriasi2007  |\n| MARE            | $\\frac1n\\sum\\frac{|s-o|}{o}$                        | [0,∞)          |      0 | –       | low flows         | scale free                                                                                             | explodes at small $o$; asymmetric                | @legates1999  |\n| Pearson $r$     | $\\mathrm{corr}(s,o)$                                | [−1,1]         |      1 | –       | high flows/timing | component of KGE                                                                                       | blind to bias and amplitude                      | @legates1999  |\n| Spearman $\\rho$ | corr of ranks                                       | [−1,1]         |      1 | –       | shape, robust     | insensitive to the heavy tail                                                                          | loses magnitude                                  | @pool2018     |\n| Willmott $d$    | $1-\\frac{\\sum(s-o)^2}{\\sum(|s-\\mu_o|+|o-\\mu_o|)^2}$ | [0,1]          |      1 | –       | high flows        | bounded; sensitive to additive and proportional differences                                            | compresses differences near 1; hard to interpret | @willmott1981 |\n| $d_1$, $d_r$    | absolute-error versions                             | [0,1] / [−1,1] |      1 | –       | mid flows         | $d_r$ is the bounded MAE-based analogue of NSE                                                         | rarely reported in hydrology                     | @willmott2012 |\n:::\n:::\n\n\n## Likelihood-based criteria\n\nRelevant only if a10 recommends a Bayesian sampler (DREAM). They are *objective functions with a\nprobabilistic interpretation*, so they can be maximised exactly like KGE.\n\n::: {#tbl-cat-lik .cell tbl-cap='Likelihood functions implemented in metrics_extra (log-likelihoods, maximise).' execution_count=5}\n``` {.python .cell-code}\nrows = [\n (\"Gaussian i.i.d.\", r\"$-\\frac n2\\left[\\log\\frac{2\\pi\\,\\mathrm{SSE}}{n}+1\\right]$ (σ profiled out)\", \"closed form, no nuisance parameter\", \"monotone in SSE ⇒ **identical argmax to NSE/RMSE**; inherits all their high-flow leverage\", \"@sorooshian1993\"),\n (\"Box–Cox / log-sinh\", r\"Gaussian on $T_\\lambda(Q)$ + Jacobian $(\\lambda-1)\\sum\\log o_i$\", \"handles heteroscedasticity explicitly; $\\\\lambda$ can be inferred\", \"the Jacobian makes the value non-comparable across $\\\\lambda$\", \"@schoups2010\"),\n (\"AR(1) residuals\", r\"$e_t-\\phi e_{t-1}$ whitened Gaussian\", \"accounts for the strong serial correlation of daily residuals (ACF$_1(Q)=0.888$)\", \"$\\\\phi$ is a nuisance parameter; can mask structural error\", \"@sorooshian1980\"),\n (\"Generalized likelihood (GL)\", r\"skew exponential power errors, $\\sigma_t=\\sigma_0+\\sigma_1 s_t$, AR(1)\", \"most defensible error model; gives calibrated predictive uncertainty\", \"4–5 extra parameters; ≥10× the sampling cost; overkill for a deterministic ranking\", \"@schoups2010\"),\n]\nmd(pd.DataFrame(rows, columns=[\"Criterion\",\"Formula\",\"Strengths\",\"Weaknesses\",\"Ref.\"]), index=False)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n| Criterion                   | Formula                                                                     | Strengths                                                                        | Weaknesses                                                                                | Ref.            |\n|:----------------------------|:----------------------------------------------------------------------------|:---------------------------------------------------------------------------------|:------------------------------------------------------------------------------------------|:----------------|\n| Gaussian i.i.d.             | $-\\frac n2\\left[\\log\\frac{2\\pi\\,\\mathrm{SSE}}{n}+1\\right]$ (σ profiled out) | closed form, no nuisance parameter                                               | monotone in SSE ⇒ **identical argmax to NSE/RMSE**; inherits all their high-flow leverage | @sorooshian1993 |\n| Box–Cox / log-sinh          | Gaussian on $T_\\lambda(Q)$ + Jacobian $(\\lambda-1)\\sum\\log o_i$             | handles heteroscedasticity explicitly; $\\lambda$ can be inferred                 | the Jacobian makes the value non-comparable across $\\lambda$                              | @schoups2010    |\n| AR(1) residuals             | $e_t-\\phi e_{t-1}$ whitened Gaussian                                        | accounts for the strong serial correlation of daily residuals (ACF$_1(Q)=0.888$) | $\\phi$ is a nuisance parameter; can mask structural error                                 | @sorooshian1980 |\n| Generalized likelihood (GL) | skew exponential power errors, $\\sigma_t=\\sigma_0+\\sigma_1 s_t$, AR(1)      | most defensible error model; gives calibrated predictive uncertainty             | 4–5 extra parameters; ≥10× the sampling cost; overkill for a deterministic ranking        | @schoups2010    |\n:::\n:::\n\n\n## Event / peak, FDC-segment and signature metrics\n\nThese are **diagnostics**, never the objective here (they are not differentiable, not smooth, and\nseveral are undefined for poor simulations). They are used in @sec-transfer to explain *why* an\nobjective transfers well or badly.\n\n::: {#tbl-cat-sig .cell tbl-cap='Event, FDC-segment and signature metrics (all target value 0 unless stated).' execution_count=6}\n``` {.python .cell-code}\nrows = [\n (\"FHV\", r\"$100\\frac{\\sum_{h}(s_{(h)}-o_{(h)})}{\\sum_h o_{(h)}}$, top 2 % of the FDC\", \"%\", \"high-flow volume bias\", \"@yilmaz2008\"),\n (\"FLV\", r\"$100\\frac{[\\sum(\\log s_{(l)}-\\log s_{\\min})]-[\\sum(\\log o_{(l)}-\\log o_{\\min})]}{\\sum(\\log o_{(l)}-\\log o_{\\min})}$, lowest 30 %\", \"%\", \"low-flow (baseflow) bias\", \"@yilmaz2008\"),\n (\"FMS\", r\"$100\\frac{m_s-m_o}{m_o}$, $m=\\frac{\\log Q_{20\\%}-\\log Q_{70\\%}}{0.5}$\", \"%\", \"mid-segment FDC slope = flow variability / storage\", \"@yilmaz2008\"),\n (\"peak error\", r\"$\\frac1k\\sum_{j=1}^{k}\\frac{s_j-o_j}{o_j}$ over the $k$ largest observed days\", \"–\", \"flood magnitude\", \"@mizukami2019\"),\n (\"peak timing\", r\"mean $|\\arg\\max_{\\pm w} s - t_{\\text{peak},o}|$\", \"days\", \"routing/response time\", \"@kratzert2021\"),\n (\"BFI error\", r\"$\\mathrm{BFI}(s)-\\mathrm{BFI}(o)$, Lyne–Hollick $\\alpha=0.925$, 3 passes\", \"–\", \"flow-path partition (obs 0.41)\", \"@lyne1979; @nathan1990\"),\n (\"recession error\", r\"median $Q_{t+1}/Q_t$ on falling limbs $\\ge5$ d\", \"1/d\", \"storage–discharge relation (obs $k=0.896$)\", \"@brutsaert1977\"),\n (\"flashiness error\", r\"$\\frac{\\sum|Q_t-Q_{t-1}|}{\\sum Q_t}$ difference (obs 0.316)\", \"–\", \"event response\", \"@baker2004\"),\n (\"ACF(1) error\", r\"$\\rho_1(s)-\\rho_1(o)$ (obs 0.888)\", \"–\", \"memory / over-smoothing\", \"a02 EDA\"),\n (\"FDC slope error\", r\"$\\frac{\\log Q_{33\\%}-\\log Q_{66\\%}}{0.33}$ difference (obs 3.50)\", \"–\", \"flow-duration shape\", \"@sawicz2011\"),\n (\"FDC $W_1$ (log)\", r\"$\\frac1n\\sum_k|\\log q^{s}_{(k)}-\\log q^{o}_{(k)}|$\", \"log mm/d\", \"1-Wasserstein distance between flow distributions (ignores timing entirely)\", \"@pool2018\"),\n]\nmd(pd.DataFrame(rows, columns=[\"Metric\",\"Formula\",\"Units\",\"What it diagnoses\",\"Ref.\"]), index=False)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=6}\n| Metric           | Formula                                                                                                                          | Units    | What it diagnoses                                                           | Ref.                   |\n|:-----------------|:---------------------------------------------------------------------------------------------------------------------------------|:---------|:----------------------------------------------------------------------------|:-----------------------|\n| FHV              | $100\\frac{\\sum_{h}(s_{(h)}-o_{(h)})}{\\sum_h o_{(h)}}$, top 2 % of the FDC                                                        | %        | high-flow volume bias                                                       | @yilmaz2008            |\n| FLV              | $100\\frac{[\\sum(\\log s_{(l)}-\\log s_{\\min})]-[\\sum(\\log o_{(l)}-\\log o_{\\min})]}{\\sum(\\log o_{(l)}-\\log o_{\\min})}$, lowest 30 % | %        | low-flow (baseflow) bias                                                    | @yilmaz2008            |\n| FMS              | $100\\frac{m_s-m_o}{m_o}$, $m=\\frac{\\log Q_{20\\%}-\\log Q_{70\\%}}{0.5}$                                                            | %        | mid-segment FDC slope = flow variability / storage                          | @yilmaz2008            |\n| peak error       | $\\frac1k\\sum_{j=1}^{k}\\frac{s_j-o_j}{o_j}$ over the $k$ largest observed days                                                    | –        | flood magnitude                                                             | @mizukami2019          |\n| peak timing      | mean $|\\arg\\max_{\\pm w} s - t_{\\text{peak},o}|$                                                                                  | days     | routing/response time                                                       | @kratzert2021          |\n| BFI error        | $\\mathrm{BFI}(s)-\\mathrm{BFI}(o)$, Lyne–Hollick $\\alpha=0.925$, 3 passes                                                         | –        | flow-path partition (obs 0.41)                                              | @lyne1979; @nathan1990 |\n| recession error  | median $Q_{t+1}/Q_t$ on falling limbs $\\ge5$ d                                                                                   | 1/d      | storage–discharge relation (obs $k=0.896$)                                  | @brutsaert1977         |\n| flashiness error | $\\frac{\\sum|Q_t-Q_{t-1}|}{\\sum Q_t}$ difference (obs 0.316)                                                                      | –        | event response                                                              | @baker2004             |\n| ACF(1) error     | $\\rho_1(s)-\\rho_1(o)$ (obs 0.888)                                                                                                | –        | memory / over-smoothing                                                     | a02 EDA                |\n| FDC slope error  | $\\frac{\\log Q_{33\\%}-\\log Q_{66\\%}}{0.33}$ difference (obs 3.50)                                                                 | –        | flow-duration shape                                                         | @sawicz2011            |\n| FDC $W_1$ (log)  | $\\frac1n\\sum_k|\\log q^{s}_{(k)}-\\log q^{o}_{(k)}|$                                                                               | log mm/d | 1-Wasserstein distance between flow distributions (ignores timing entirely) | @pool2018              |\n:::\n:::\n\n\n::: {.callout-note}\n## Information-theoretic and probabilistic scores\nMutual information $I(s;o)$, CRPS and Wasserstein distances were considered. CRPS requires a\npredictive *distribution*; all five model slots are deterministic and the final ranking is\ndeterministic, so CRPS is only meaningful if an ensemble is submitted — it is therefore not part of\nthe objective and not part of the report. The 1-Wasserstein distance between FDCs **is** implemented\n(`FDC_W1_log`) because it is a pure distribution-shape diagnostic: a model can have $W_1=0$ and\n$r=0$, which makes it a clean complement to KGE's $r$ term. Mutual information was rejected as an\nobjective: on 13 149 daily values it needs binning/KDE choices that are themselves tuning\nparameters, and it is invariant to any monotone transform — including a 50 % volume bias.\n:::\n\n# Why this particular data set constrains the choice {#sec-why}\n\n::: {#fig-leverage .cell execution_count=7}\n``` {.python .cell-code}\ns_sorted = np.sort(O)[::-1]\nfrac = np.arange(1, len(O) + 1) / len(O)\ncum_vol = np.cumsum(s_sorted) / s_sorted.sum()\nd2 = (s_sorted - O.mean()) ** 2\ncum_ss = np.cumsum(d2) / d2.sum()\n\nlev = {}\nfor nm, x in ((\"$Q$\", O), (\"$\\\\sqrt{Q}$\", np.sqrt(O)), (\"$\\\\log Q$\", np.log(O))):\n    xs = np.sort(x)[::-1]; dd = (xs - x.mean()) ** 2\n    lev[nm] = np.cumsum(dd) / dd.sum()\n\nfig, ax = plt.subplots(1, 2, figsize=(9.5, 3.4))\nax[0].plot(100 * frac, 100 * cum_vol, label=\"share of total volume\")\nax[0].plot(100 * frac, 100 * cum_ss, label=r\"share of $\\sum(o-\\mu_o)^2$ (NSE denominator)\")\nax[0].set_xscale(\"log\"); ax[0].set_xlim(0.05, 100); ax[0].set_xlabel(\"wettest x % of days\")\nax[0].set_ylabel(\"cumulative share (%)\"); ax[0].legend(loc=\"lower right\")\nax[0].axvline(1, color=\"0.5\", lw=0.8, ls=\":\"); ax[0].axvline(5, color=\"0.5\", lw=0.8, ls=\":\")\nax[0].set_title(\"Volume vs squared-error leverage\")\nfor nm, v in lev.items():\n    ax[1].plot(100 * frac, 100 * v, label=nm)\nax[1].set_xscale(\"log\"); ax[1].set_xlim(0.05, 100); ax[1].set_xlabel(\"wettest x % of days\")\nax[1].set_ylabel(\"share of $\\\\sum(T(o)-\\\\mu)^2$ (%)\"); ax[1].legend(title=\"transform\")\nax[1].axvline(1, color=\"0.5\", lw=0.8, ls=\":\"); ax[1].axvline(5, color=\"0.5\", lw=0.8, ls=\":\")\nax[1].set_title(\"Effect of the transform on leverage\")\nsave(fig, \"leverage\"); plt.show()\n\ntbl = []\nfor p in (0.01, 0.02, 0.05, 0.10):\n    k = int(p * len(O))\n    row = {\"wettest % of days\": 100 * p, \"% of volume\": 100 * s_sorted[:k].sum() / s_sorted.sum()}\n    for nm, x in ((\"Q\", O), (\"sqrt Q\", np.sqrt(O)), (\"log Q\", np.log(O))):\n        xs = np.sort(x)[::-1]; dd = (xs - x.mean()) ** 2\n        row[f\"% of SS ({nm})\"] = 100 * dd[:k].sum() / dd.sum()\n    tbl.append(row)\nLEVERAGE = pd.DataFrame(tbl)\nmd(LEVERAGE.round(1), index=False)\n```\n\n::: {.cell-output .cell-output-display}\n![Leverage of the largest flows. Left: share of total volume and of the NSE denominator $\\sum(o-\\mu_o)^2$ carried by the wettest days (calibration metric window). Right: the same share of the squared-error 'gradient mass' under three transforms.](04_metrics_files/figure-html/fig-leverage-output-1.png){#fig-leverage-1 width=894 height=378}\n:::\n\n::: {#fig-leverage-2 .cell-output .cell-output-display .cell-output-markdown execution_count=7}\n|   wettest % of days |   % of volume |   % of SS (Q) |   % of SS (sqrt Q) |   % of SS (log Q) |\n|--------------------:|--------------:|--------------:|-------------------:|------------------:|\n|                   1 |          15.7 |          58.3 |               26.8 |               8.7 |\n|                   2 |          24   |          70.6 |               38.4 |              14.8 |\n|                   5 |          39.9 |          83.6 |               56.6 |              28.1 |\n|                  10 |          55.9 |          89.3 |               69.9 |              42.3 |\n:::\n:::\n\n\n**Fact 1 — one per cent of the days own the squared-error criterion.** In the calibration metric\nwindow the wettest 1 % of days (131 of 13 149) carry 15.7 % of the volume but **58.3 %** of\n$\\sum(o-\\mu_o)^2$; the wettest 5 % carry 83.6 %. Any SSE-based objective (MSE, RMSE, NSE, Gaussian\nlikelihood — all with the same argmax) is therefore, in effect, fitted to ~130 flood days.\nThe $\\sqrt{\\cdot}$ transform reduces the 1 % share to 26.8 % and $\\log$ to 8.7 %: these numbers,\nnot a preference, are what \"balancing high and low flows\" means here.\n\n**Fact 2 — NSE is nearly blind to volume bias at this CV, KGE is not.** For a simulation with the\nright shape but a volume ratio $\\beta=c$ ($r=1$, $\\alpha=c$),\n\n$$\n\\mathrm{KGE}=1-\\sqrt2\\,|c-1| \\quad\\text{(both } \\alpha \\text{ and } \\beta \\text{ terms)},\\qquad\n\\mathrm{NSE}=1-\\Big(\\tfrac{c-1}{\\mathrm{CV}_o}\\Big)^2\\ \\text{if only the mean is wrong},\n$$\n\nand $\\mathrm{CV}_o=2.107$ here.\n\n::: {#tbl-bias-sens .cell tbl-cap='Penalty of a pure volume error at the Leaf River calibration CV = 2.107. \\'KGE (β only)\\' isolates the volume term; \\'NSE (mean only)\\' is the corresponding NSE loss. The last column is how many times harder KGE punishes the same water-balance error.' execution_count=8}\n``` {.python .cell-code}\nrows = []\nfor c in (0.85, 0.90, 0.95, 1.05, 1.10, 1.20, 1.30):\n    dk = abs(c - 1.0)                      # KGE loss from the beta term alone\n    dn = ((c - 1.0) / CV_O) ** 2           # NSE loss from the mean alone\n    dk_full = np.sqrt(2) * abs(c - 1.0)    # KGE loss when alpha scales too\n    rows.append({\"β = Q_sim/Q_obs\": c, \"ΔKGE (β term only)\": dk,\n                 \"ΔKGE (α and β, sim = c·obs)\": dk_full,\n                 \"ΔNSE (mean only)\": dn, \"ratio ΔKGE/ΔNSE\": dk / dn})\nBIAS = pd.DataFrame(rows)\nmd(BIAS.round({\"β = Q_sim/Q_obs\": 2, \"ΔKGE (β term only)\": 4, \"ΔKGE (α and β, sim = c·obs)\": 4,\n               \"ΔNSE (mean only)\": 5, \"ratio ΔKGE/ΔNSE\": 1}), index=False)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=8}\n|   β = Q_sim/Q_obs |   ΔKGE (β term only) |   ΔKGE (α and β, sim = c·obs) |   ΔNSE (mean only) |   ratio ΔKGE/ΔNSE |\n|------------------:|---------------------:|------------------------------:|-------------------:|------------------:|\n|              0.85 |                 0.15 |                        0.2121 |            0.00507 |              29.6 |\n|              0.9  |                 0.1  |                        0.1414 |            0.00225 |              44.4 |\n|              0.95 |                 0.05 |                        0.0707 |            0.00056 |              88.8 |\n|              1.05 |                 0.05 |                        0.0707 |            0.00056 |              88.8 |\n|              1.1  |                 0.1  |                        0.1414 |            0.00225 |              44.4 |\n|              1.2  |                 0.2  |                        0.2828 |            0.00901 |              22.2 |\n|              1.3  |                 0.3  |                        0.4243 |            0.02028 |              14.8 |\n:::\n:::\n\n\nA model that is 10 % too wet loses **0.100 KGE but only 0.0023 NSE** — a factor 44. This is the\nsingle most important asymmetry for this project: calibrating on NSE lets the optimiser trade\nwater balance for a slightly better fit to floods almost for free, and that debt is paid in full in\nthe KGE ranking — *and it is paid on a period 29 % wetter than the one the trade was made on.*\nThe same algebra explains why KGE″ [@tang2021], whose bias term is $\\beta_n=(\\mu_s-\\mu_o)/\\sigma_o$,\nbehaves almost like NSE here: at CV = 2.107 it divides the bias by 2.1 before squaring it.\n\n**Fact 3 — no offset $\\varepsilon$ is needed.** a02 verified $Q>0$ on all 14 610 days\n(min 0.069 mm/day, quantised at 1 ft³/s over 1 949 km²). Every $\\log$, $\\sqrt{}$, $1/Q$ and Box–Cox\nstatistic in this report is therefore computed with $\\varepsilon=0$, which removes the usual\narbitrary-constant problem [@pushpalatha2012; @santos2018]: an $\\varepsilon$ is a hidden tuning\nparameter that silently sets *which* low flows the objective can see. Only simulated flows are\nfloored (at $10^{-12}$ mm/day) so that a degenerate model cannot return $-\\infty$.\n\n::: {#cell-fig-transform .cell execution_count=9}\n``` {.python .cell-code}\nfig, ax = plt.subplots(1, 4, figsize=(11, 2.6))\nfor a, (nm, x) in zip(ax, [(\"$Q$\", O), (\"$\\\\sqrt{Q}$\", np.sqrt(O)),\n                           (\"Box–Cox $\\\\lambda=0.25$\", mx.t_boxcox(O, 0.25)), (\"$\\\\log Q$\", np.log(O))]):\n    a.hist(x, bins=60, color=\"steelblue\")\n    sk = float(((x - x.mean()) ** 3).mean() / x.std() ** 3)\n    a.set_title(f\"{nm}\\nskew = {sk:.2f}\"); a.set_yticks([])\nsave(fig, \"transforms\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Distribution of observed daily Q in the calibration metric window under the four candidate transforms (no offset needed: min Q = 0.069 mm/day).](04_metrics_files/figure-html/fig-transform-output-1.png){#fig-transform width=959 height=312}\n:::\n:::\n\n\n# Benchmarks {#sec-benchmarks}\n\n::: {#tbl-benchmarks .cell tbl-cap='Reference points on the calibration metric window (1952-10-01…1988-09-30). A model is only skilful above these.' execution_count=10}\n``` {.python .cell-code}\nbench = {}\nbench[\"mean flow (constant)\"] = mx.benchmark_mean_flow(O)\nbench[\"day-of-year climatology (15-d smoothed)\"] = mx.benchmark_climatology(O, IDX[MM], smooth=15)\nbench[\"day-of-year climatology (raw)\"] = mx.benchmark_climatology(O, IDX[MM], smooth=1)\npers = np.r_[O[0], O[:-1]]\nbench[\"persistence Q(t) = Q(t-1)\"] = {\"NSE\": nse(pers, O), \"KGE\": kge(pers, O),\n                                      **{k: v for k, v in kge_components(pers, O).items() if k != \"KGE\"}}\nlh = mx._lyne_hollick(O)\nbench[\"baseflow only (Lyne–Hollick)\"] = {\"NSE\": nse(lh, O), \"KGE\": kge(lh, O),\n                                         **{k: v for k, v in kge_components(lh, O).items() if k != \"KGE\"}}\nBENCH = pd.DataFrame(bench).T[[\"KGE\", \"NSE\", \"r\", \"alpha\", \"beta\"]]\nmd(BENCH.round(3))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n|                                         |    KGE |   NSE |     r |   alpha |   beta |\n|:----------------------------------------|-------:|------:|------:|--------:|-------:|\n| mean flow (constant)                    | -0.414 | 0     | 0     |   0     |  1     |\n| day-of-year climatology (15-d smoothed) |  0.089 | 0.127 | 0.357 |   0.354 |  1     |\n| day-of-year climatology (raw)           |  0.125 | 0.145 | 0.381 |   0.381 |  1     |\n| persistence Q(t) = Q(t-1)               |  0.89  | 0.78  | 0.89  |   1     |  1     |\n| baseflow only (Lyne–Hollick)            | -0.06  | 0.136 | 0.629 |   0.204 |  0.406 |\n:::\n:::\n\n\nThe mean-flow benchmark is the reference every reader mis-remembers: **NSE = 0 but KGE = $1-\\sqrt2$\n= −0.414**, not 0 [@knoben2019]. KGE = 0 is already a *non-trivial* model. A day-of-year climatology\n— which uses no forcing at all — reaches KGE ≈ 0.08 / NSE ≈ 0.13 here, and one-day persistence\nreaches KGE 0.89 / NSE 0.78 because ACF$_1$ = 0.888. Persistence is the benchmark a16 should keep in\nmind: a rainfall–runoff model that cannot beat NSE 0.78 has added nothing over \"tomorrow = today\".\nPublished values at this gauge (a01): NWM v2.1 KGE 0.72/NSE 0.71, SAC-SMA 0.80, HBV 0.82,\nregional LSTM 0.84–0.86.\n\n# Experiment 1 — how the candidate metrics react to known errors {#sec-synthetic}\n\nFifteen synthetic \"simulations\" are built **from the observed calibration series only**, each\ncarrying one controlled, hydrologically meaningful defect. Every metric is then computed on the\ncalibration metric window. This is the standard way to read a metric's fingerprint\n[@krause2005; @schwemmle2021]: it shows which metric can *see* which error.\n\n::: {#synthetic-build .cell execution_count=11}\n``` {.python .cell-code}\ndef mav(x, k):\n    return pd.Series(x).rolling(k, center=True, min_periods=1).mean().to_numpy()\n\nrng = np.random.default_rng(SEED)\ndoy = IDX[MM].dayofyear.to_numpy()\nclim = mav(pd.Series(O).groupby(doy).transform(\"mean\").to_numpy(), 15)\n\nSIMS = {\n    \"volume ×0.8\":              0.8 * O,\n    \"volume ×1.2\":              1.2 * O,\n    \"+1 d late\":                np.r_[O[0], O[:-1]],\n    \"−1 d early\":               np.r_[O[1:], O[-1]],\n    \"7-d over-smoothed\":        mav(O, 7),\n    \"baseflow only\":            mx._lyne_hollick(O),\n    \"day-of-year climatology\":  clim,\n    \"mean flow\":                np.full_like(O, O.mean()),\n    \"peaks −30 % (top 2 %)\":    np.where(O >= np.quantile(O, 0.98), 0.7 * O, O),\n    \"low flows ×2 (bot. 30 %)\": np.where(O <= np.quantile(O, 0.30), 2.0 * O, O),\n    \"log-variance ×0.7\":        np.exp(np.log(O).mean() + 0.7 * (np.log(O) - np.log(O).mean())),\n    \"log-variance ×1.3\":        np.exp(np.log(O).mean() + 1.3 * (np.log(O) - np.log(O).mean())),\n    \"multiplicative noise 30 %\": O * np.exp(rng.normal(0, 0.3, len(O))),\n    \"additive noise 0.3 mm/d\":  np.maximum(O + rng.normal(0, 0.3, len(O)), 1e-3),\n    \"perfect\":                  O.copy(),\n}\nNAMES = [\"KGE\", \"NSE\", \"NSE_sqrt\", \"NSE_log\", \"NSE_inv\", \"KGE_sqrt\", \"KGE_log\",\n         \"KGE_2012\", \"KGE_2021\", \"KGE_np\", \"DE\", \"KGE_mix_sqrt\",\n         \"KGE_r\", \"KGE_alpha\", \"KGE_beta\", \"RMSE\", \"MAE\", \"PBIAS\", \"rho\", \"d\",\n         \"FHV\", \"FLV\", \"FMS\", \"peak_timing\", \"BFI_err\", \"FDC_W1_log\"]\nSYN = pd.DataFrame({k: mx.evaluate_all(v, O, NAMES) for k, v in SIMS.items()}).T\n```\n:::\n\n\n::: {#cell-fig-heatmap .cell execution_count=12}\n``` {.python .cell-code}\neff = [\"KGE\", \"NSE\", \"NSE_sqrt\", \"NSE_log\", \"NSE_inv\", \"KGE_sqrt\", \"KGE_log\",\n       \"KGE_2012\", \"KGE_2021\", \"KGE_np\", \"DE\", \"KGE_mix_sqrt\", \"KGE_r\", \"d\", \"rho\"]\nH = SYN[eff].astype(float)\nfig, ax = plt.subplots(figsize=(11, 5.2))\nsns.heatmap(H.clip(lower=-1), annot=H.round(2), fmt=\"\", cmap=\"RdYlGn\", vmin=-1, vmax=1,\n            linewidths=.4, cbar_kws={\"label\": \"value (clipped at −1)\"}, annot_kws={\"size\": 7}, ax=ax)\nax.set_title(\"Experiment 1: sensitivity of efficiency metrics to controlled defects\")\nplt.xticks(rotation=45, ha=\"right\"); save(fig, \"synthetic_heatmap\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Metric fingerprint of 15 controlled defects (calibration metric window, 13 149 d). Cells show the metric value; colour = loss relative to the perfect value, clipped at −1 for readability. Bounded, +1-oriented efficiency metrics only.](04_metrics_files/figure-html/fig-heatmap-output-1.png){#fig-heatmap width=1048 height=559}\n:::\n:::\n\n\n::: {#tbl-synthetic-diag .cell tbl-cap='The same experiment for the diagnostic (non-efficiency) metrics. Target value is 0 for all of them except KGE_alpha/KGE_beta (target 1) and peak_timing (days, target 0).' execution_count=13}\n``` {.python .cell-code}\nmd(SYN[[\"KGE_alpha\", \"KGE_beta\", \"RMSE\", \"MAE\", \"PBIAS\", \"FHV\", \"FLV\", \"FMS\",\n        \"peak_timing\", \"BFI_err\", \"FDC_W1_log\"]].astype(float).round(2))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=13}\n|                           |   KGE_alpha |   KGE_beta |   RMSE |   MAE |   PBIAS |    FHV |     FLV |     FMS |   peak_timing |   BFI_err |   FDC_W1_log |\n|:--------------------------|------------:|-----------:|-------:|------:|--------:|-------:|--------:|--------:|--------------:|----------:|-------------:|\n| volume ×0.8               |        0.8  |       0.8  |   0.63 |  0.27 |  -20    | -20    |    0    |   -0    |          0    |     -0    |         0.22 |\n| volume ×1.2               |        1.2  |       1.2  |   0.63 |  0.27 |   20    |  20    |    0    |   -0    |          0    |     -0    |         0.18 |\n| +1 d late                 |        1    |       1    |   1.34 |  0.43 |   -0    |   0    |   -0.03 |    0    |          1    |     -0    |         0    |\n| −1 d early                |        1    |       1    |   1.34 |  0.43 |    0    |   0    |    0.03 |    0    |          1.2  |      0    |         0    |\n| 7-d over-smoothed         |        0.81 |       1    |   1.27 |  0.45 |   -0    | -20.22 |    0.64 |    4    |          1    |      0.07 |         0.1  |\n| baseflow only             |        0.2  |       0.41 |   2.65 |  0.8  |  -59.4  | -81.44 |  -11.1  |  -24.26 |          3.15 |      0.29 |         0.41 |\n| day-of-year climatology   |        0.35 |       1    |   2.66 |  1.21 |   -0    | -78.13 |  -83.38 |  -13.94 |          3.65 |      0.38 |         0.73 |\n| mean flow                 |        0    |       1    |   2.85 |  1.45 |   -0    | -91.69 | -100    | -100    |          5    |      0.59 |         1.32 |\n| peaks −30 % (top 2 %)     |        0.79 |       0.93 |   0.77 |  0.1  |   -7.22 | -27.3  |    0    |    0    |          0    |      0.03 |         0.01 |\n| low flows ×2 (bot. 30 %)  |        0.99 |       1.04 |   0.09 |  0.05 |    3.54 |   0    |  -17.48 |  -20.08 |          0    |      0.03 |         0.21 |\n| log-variance ×0.7         |        0.36 |       0.62 |   1.93 |  0.58 |  -37.6  | -64.48 |  -30    |  -30    |          0    |      0.17 |         0.3  |\n| log-variance ×1.3         |        2.97 |       1.88 |   5.85 |  1.24 |   88.23 | 187.09 |   30    |   30    |          0    |     -0.13 |         0.3  |\n| multiplicative noise 30 % |        1.12 |       1.04 |   1.03 |  0.33 |    4.47 |  10.98 |   58.16 |   -0.51 |          0.35 |     -0.02 |         0.03 |\n| additive noise 0.3 mm/d   |        1    |       1.02 |   0.27 |  0.22 |    2.29 |   0.22 |  258.88 |   -7.53 |          0    |     -0.04 |         0.75 |\n| perfect                   |        1    |       1    |   0    |  0    |    0    |   0    |    0    |    0    |          0    |      0    |         0    |\n:::\n:::\n\n\nWhat the fingerprint says, in the order that matters for the decision:\n\n1. **Volume bias.** ±20 % volume costs KGE 0.283 but NSE only 0.049 — the algebra of @tbl-bias-sens\n   confirmed empirically. log-NSE (0.97) and sqrt-NSE (0.97) are even blinder. Only the KGE family,\n   PBIAS/VE and FHV react properly.\n2. **Timing.** A one-day shift costs NSE 0.220 but KGE only 0.110 (KGE loses only through $r$).\n   NSE is the stronger timing criterion; KGE is the stronger water-balance criterion. They are\n   complementary, which is exactly why the project reports both.\n3. **Variance errors.** Inflating the variance in log space by 30 % gives KGE −1.17 and NSE −3.27\n   while **log-NSE stays at 0.910 and KGE_log at 0.700**. A log-based objective literally cannot see\n   a catastrophic error in the raw-flow variance — a decisive argument against calibrating on\n   $\\log Q$ when the report is on raw $Q$ [@santos2018].\n4. **Low-flow instability.** Adding 0.3 mm/d of white noise (a trivial error at flood flows) leaves\n   KGE at 0.976 but drives log-NSE to −1.50 and inverse-NSE to −15 554. Inverse and log objectives\n   are numerically dominated by the smallest flows of a perennial river; they are unusable as a\n   primary objective here and are kept only as diagnostics.\n5. **Over-smoothing** (7-day moving average, i.e. a model with too much storage) is punished by\n   KGE (0.785 via $\\alpha$ = 0.81) and by FHV (−20 %) but barely by log-NSE (0.913) — another\n   transform-blindness.\n6. **Peak truncation** (top 2 % cut by 30 %) costs KGE 0.229 and NSE 0.074 but *improves* log-NSE\n   and inverse-NSE to ≈1.00. FHV = −27.6 % detects it cleanly, which is why FHV is retained as the\n   mandatory high-flow diagnostic.\n\n# Experiment 2 — which objective transfers best to an independent, wetter period? {#sec-transfer}\n\nThis is the decision-relevant experiment. @sec-synthetic shows what a metric *sees*; it does not\nshow what happens when a metric is *optimised*. Here two surrogate rainfall–runoff models are\ncalibrated with 24 candidate objectives and the resulting parameter sets are scored with the\n**reported** metrics (KGE, NSE on raw $Q$) on data withheld from that calibration.\n\n::: {.callout-warning}\n## Lane and leakage statement\nThe two models below are **experimental surrogates internal to this report**, not project model\nslots (those are a03/a05–a09's outputs; nothing is written to `src/models/`). Every split used here\nlives strictly inside the calibration window; `src.common.data.slice_run(df, \"evaluation\")` is never\ncalled and `LR_AGENT` is never set. The evaluation window contributes nothing — not even a summary\nstatistic — to the objective choice.\n:::\n\n## Design\n\n* **Surrogate 1 — HyMOD** (5 parameters: $C_{max}$, $b_{exp}$, $\\alpha$, $R_s$, $R_q$): a PDM\n  storage [@moore1985] feeding one slow and three quick linear reservoirs. HyMOD *is* the classic\n  Leaf River model [@boyle2000; @vrugt2003], which makes it the most defensible surrogate available.\n* **Surrogate 2 — NLRes** (5 parameters: $S_{max}$, $\\beta$, $d$, $k_f$, $k_s$): HBV-style power-law\n  saturation runoff, a linear fast reservoir and a **non-linear** slow reservoir $q=k_sS^{1.5}$,\n  chosen because a02 found a non-linear recession (Brutsaert–Nieber $b=1.68$). Two structurally\n  different surrogates guard against a conclusion that is an artefact of one model.\n* **Optimiser:** SciPy `differential_evolution`, seed 42, popsize 15, maxiter 150, tol $10^{-8}$,\n  polish — identical budget for every objective, so differences are attributable to the objective.\n* **Splits (all inside calibration):**\n\n::: {#cell-exp2-setup .cell execution_count=14}\n``` {.python .cell-code}\nfrom numba import njit, prange\n\n@njit(cache=True, fastmath=True)\ndef _hymod(P, E, cmax, bexp, alpha, Rs, Rq):\n    n = P.shape[0]; Q = np.empty(n)\n    x_loss = 0.0; x_slow = 2.3503 / (Rs * 22.5); x_q1 = x_q2 = x_q3 = 0.0\n    b1 = bexp + 1.0; cm_b = cmax / b1\n    for t in range(n):\n        Pval = P[t]; PETval = E[t]; xn_prev = x_loss\n        arg = 1.0 - b1 * xn_prev / cmax\n        if arg < 0.0: arg = 0.0\n        ct_prev = cmax * (1.0 - arg ** (1.0 / b1))\n        UT1 = Pval - cmax + ct_prev\n        if UT1 < 0.0: UT1 = 0.0\n        Pval = Pval - UT1\n        dummy = (ct_prev + Pval) / cmax\n        if dummy > 1.0: dummy = 1.0\n        xn = cm_b * (1.0 - (1.0 - dummy) ** b1)\n        UT2 = Pval - (xn - xn_prev)\n        if UT2 < 0.0: UT2 = 0.0\n        evap = (1.0 - (cm_b - xn) / cm_b) * PETval\n        if evap > xn: evap = xn\n        x_loss = xn - evap\n        UQ = alpha * (UT1 + UT2); US = (1.0 - alpha) * (UT1 + UT2)\n        x_slow = (1.0 - Rs) * x_slow + (1.0 - Rs) * US; QS = (Rs / (1.0 - Rs)) * x_slow\n        x_q1 = (1.0 - Rq) * x_q1 + (1.0 - Rq) * UQ;  o1 = (Rq / (1.0 - Rq)) * x_q1\n        x_q2 = (1.0 - Rq) * x_q2 + (1.0 - Rq) * o1;  o2 = (Rq / (1.0 - Rq)) * x_q2\n        x_q3 = (1.0 - Rq) * x_q3 + (1.0 - Rq) * o2;  o3 = (Rq / (1.0 - Rq)) * x_q3\n        q = QS + o3\n        Q[t] = q if q > 1e-9 else 1e-9\n    return Q\n\n@njit(cache=True, fastmath=True)\ndef _nlres(P, E, Smax, beta, d, kf, ks):\n    n = P.shape[0]; Q = np.empty(n)\n    S = 0.5 * Smax; Sf = 0.0; Ss = 10.0\n    for t in range(n):\n        p = P[t]; ratio = S / Smax\n        if ratio > 1.0: ratio = 1.0\n        r = p * ratio ** beta\n        S = S + p - r\n        ea = E[t] * (S / Smax)\n        if ea > S: ea = S\n        S = S - ea\n        if S > Smax:\n            r += S - Smax; S = Smax\n        Sf = Sf + d * r; qf = kf * Sf; Sf = Sf - qf\n        Ss = Ss + (1.0 - d) * r; qs = ks * Ss ** 1.5\n        if qs > Ss: qs = Ss\n        Ss = Ss - qs\n        q = qf + qs\n        Q[t] = q if q > 1e-9 else 1e-9\n    return Q\n\n@njit(parallel=True, cache=True)\ndef simulate_batch(P, E, theta, which):\n    ns = theta.shape[0]; nt = P.shape[0]; out = np.empty((ns, nt))\n    for i in prange(ns):\n        if which == 0:\n            out[i] = _hymod(P, E, theta[i, 0], theta[i, 1], theta[i, 2], theta[i, 3], theta[i, 4])\n        else:\n            out[i] = _nlres(P, E, theta[i, 0], theta[i, 1], theta[i, 2], theta[i, 3], theta[i, 4])\n    return out\n\nBOUNDS = {0: np.array([[1.0, 500.0], [0.1, 2.0], [0.10, 0.99], [0.0005, 0.15], [0.10, 0.95]]),\n          1: np.array([[50.0, 800.0], [0.5, 6.0], [0.05, 0.95], [0.05, 0.90], [0.001, 0.20]])}\nPNAMES = {0: [\"cmax\", \"bexp\", \"alpha\", \"Rs\", \"Rq\"], 1: [\"Smax\", \"beta\", \"d\", \"kf\", \"ks\"]}\n\nCANDIDATES = {\n    \"NSE\": mx.nse, \"KGE\": kge, \"KGE_2012\": mx.kge_2012, \"KGE_2021\": mx.kge_2021,\n    \"KGE_np\": mx.kge_np, \"NSE_sqrt\": mx.nse_sqrt, \"NSE_log\": mx.nse_log, \"NSE_inv\": mx.nse_inv,\n    \"NSE_bc025\": lambda s, o: mx.nse_boxcox(s, o, lam=0.25),\n    \"KGE_sqrt\": mx.kge_sqrt, \"KGE_log\": mx.kge_log,\n    \"KGEmix_sqrt50\": lambda s, o: mx.kge_mix(s, o, w=0.50, transform=\"sqrt\"),\n    \"KGEmix_sqrt75\": lambda s, o: mx.kge_mix(s, o, w=0.75, transform=\"sqrt\"),\n    \"KGEmix_log50\":  lambda s, o: mx.kge_mix(s, o, w=0.50, transform=\"log\"),\n    \"NSEmix_log50\":  lambda s, o: mx.nse_mix(s, o, w=0.50, transform=\"log\"),\n    \"KGE_NSE_50\":    lambda s, o: mx.kge_nse_mix(s, o, w=0.50),\n    \"negMAE\": lambda s, o: -mx.mae(s, o), \"DE\": mx.de_metric,\n    # three post-hoc variants used to check whether a transformed third term adds anything\n    \"KNS_333\": lambda s, o: (kge(s, o) + mx.nse(s, o) + mx.kge_sqrt(s, o)) / 3.0,\n    \"KNS_442\": lambda s, o: 0.4 * kge(s, o) + 0.4 * mx.nse(s, o) + 0.2 * mx.kge_sqrt(s, o),\n    \"KN_7030\": lambda s, o: 0.7 * kge(s, o) + 0.3 * mx.nse(s, o),\n    \"negFDC_W1\": lambda s, o: -mx.fdc_wasserstein(s, o),\n    \"LL_bc025\": lambda s, o: mx.loglik_boxcox(s, o, lam=0.25) / 1e4,\n    \"Willmott_d\": mx.willmott_d,\n}\n# objectives carried through ALL four splits (the expensive part); the remaining candidates are\n# screened on the temporal split only. KGE_np and NSE_log are screened only (KGE_np costs ~4x).\nCORE = [\"NSE\", \"KGE\", \"KGE_2012\", \"NSE_sqrt\", \"KGE_sqrt\", \"KGE_log\",\n        \"KGEmix_sqrt50\", \"KGEmix_sqrt75\", \"KGE_NSE_50\", \"negMAE\",\n        \"KNS_333\", \"KNS_442\", \"KN_7030\"]\nWETBLOCKS = [(1971, 1973), (1979, 1981), (1961, 1963)]\n\nSPLITS = {\"temporal (WY1982–88, drier)\": (TR, VA)}\nfor a, b in WETBLOCKS:\n    blk = np.arange(a, b + 1)\n    SPLITS[f\"wet WY{a}–{b}\"] = (MM & ~np.isin(WY, blk), MM & np.isin(WY, blk))\n\nSPLIT_INFO = pd.DataFrame({k: dict(n_train=int(tr.sum()), n_test=int(te.sum()),\n                                   meanQ_train=OBS[tr].mean(), meanQ_test=OBS[te].mean(),\n                                   ratio=OBS[te].mean() / OBS[tr].mean(),\n                                   maxQ_train=OBS[tr].max(), maxQ_test=OBS[te].max())\n                           for k, (tr, te) in SPLITS.items()}).T\nmd(SPLIT_INFO.round(3))\n```\n\n::: {#exp2-setup .cell-output .cell-output-display .cell-output-markdown execution_count=14}\n|                             |   n_train |   n_test |   meanQ_train |   meanQ_test |   ratio |   maxQ_train |   maxQ_test |\n|:----------------------------|----------:|---------:|--------------:|-------------:|--------:|-------------:|------------:|\n| temporal (WY1982–88, drier) |     10592 |     2557 |         1.373 |        1.272 |   0.926 |       64.015 |      36.401 |\n| wet WY1971–1973             |     12053 |     1096 |         1.32  |        1.72  |   1.303 |       64.015 |      25.104 |\n| wet WY1979–1981             |     12053 |     1096 |         1.303 |        1.905 |   1.462 |       64.015 |      38.66  |\n| wet WY1961–1963             |     12054 |     1095 |         1.331 |        1.599 |   1.202 |       64.015 |      58.241 |\n:::\n:::\n\n\nThe evaluation window has mean-$Q$ ratio **1.29** relative to calibration and a maximum\n(45.9 mm/d) **below** the calibration maximum (64.0). The three \"wet\" splits reproduce exactly that\nsituation inside calibration — ratio 1.20–1.46, test maximum always below the training maximum — so\na model must extrapolate in *wetness* but not in *magnitude*. The temporal split is the useful\nmirror image (test 6 % drier than train): an objective that is robust must survive both directions.\n\n## Results\n\n::: {#exp2-run .cell execution_count=15}\n``` {.python .cell-code}\nfrom scipy.optimize import differential_evolution\n\ndef optimise(mask, which, fobj, seed=SEED, maxiter=150, popsize=15):\n    b = BOUNDS[which]; o = OBS[mask]\n    def cost(th):\n        s = simulate_batch(P, PET, np.atleast_2d(th), which)[0]\n        v = fobj(s[mask], o)\n        return -v if np.isfinite(v) else 1e6\n    res = differential_evolution(cost, list(map(tuple, b)), seed=seed, maxiter=maxiter,\n                                 popsize=popsize, tol=1e-8, mutation=(0.3, 1.0),\n                                 recombination=0.9, polish=True, init=\"sobol\", workers=1)\n    return res.x, -res.fun\n\nt0 = time.time(); rows = []\nfor which, mname in ((0, \"HyMOD\"), (1, \"NLRes\")):\n    for sname, (mtr, mte) in SPLITS.items():\n        names = list(CANDIDATES) if sname.startswith(\"temporal\") else CORE\n        for cname in names:\n            th, val = optimise(mtr, which, CANDIDATES[cname])\n            s = simulate_batch(P, PET, np.atleast_2d(th), which)[0]\n            rows.append(dict(model=mname, split=sname, objective=cname, obj_train=val,\n                             KGE_train=kge(s[mtr], OBS[mtr]), NSE_train=nse(s[mtr], OBS[mtr]),\n                             KGE_test=kge(s[mte], OBS[mte]), NSE_test=nse(s[mte], OBS[mte]),\n                             r_test=mx.kge_r(s[mte], OBS[mte]), a_test=mx.kge_alpha(s[mte], OBS[mte]),\n                             b_test=mx.kge_beta(s[mte], OBS[mte]),\n                             a_train=mx.kge_alpha(s[mtr], OBS[mtr]), b_train=mx.kge_beta(s[mtr], OBS[mtr]),\n                             logNSE_test=mx.nse_log(s[mte], OBS[mte]),\n                             FHV_test=mx.fhv(s[mte], OBS[mte]), FLV_test=mx.flv(s[mte], OBS[mte]),\n                             PBIAS_test=mx.pbias(s[mte], OBS[mte]),\n                             **{f\"p_{k}\": float(v) for k, v in zip(PNAMES[which], th)}))\nR = pd.DataFrame(rows)\nprint(f\"{len(R)} calibrations in {time.time()-t0:.0f} s \"\n      f\"({R.model.nunique()} surrogates x {R.split.nunique()} splits x up to {len(CANDIDATES)} objectives)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n126 calibrations in 2500 s (2 surrogates x 4 splits x up to 24 objectives)\n```\n:::\n:::\n\n\n::: {#tbl-transfer-temporal .cell tbl-cap='Temporal split: calibrate on WY1953–1981 (10 592 d), test on WY1982–1988 (2 557 d, 6 % drier). All 24 candidate objectives. Sorted by mean test KGE over the two surrogates.' execution_count=16}\n``` {.python .cell-code}\nT = R[R.split.str.startswith(\"temporal\")]\npiv = (T.pivot_table(index=\"objective\", columns=\"model\",\n                     values=[\"KGE_test\", \"NSE_test\", \"b_test\", \"a_test\"]))\npiv.columns = [f\"{m}_{v.split('_')[0]}\" for v, m in piv.columns]\npiv[\"mean_KGE\"] = T.groupby(\"objective\").KGE_test.mean()\npiv[\"mean_NSE\"] = T.groupby(\"objective\").NSE_test.mean()\npiv = piv.sort_values(\"mean_KGE\", ascending=False)\nmd(piv.round(3))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=16}\n| objective     |   HyMOD_KGE |   NLRes_KGE |   HyMOD_NSE |   NLRes_NSE |   HyMOD_a |   NLRes_a |   HyMOD_b |   NLRes_b |   mean_KGE |   mean_NSE |\n|:--------------|------------:|------------:|------------:|------------:|----------:|----------:|----------:|----------:|-----------:|-----------:|\n| negMAE        |       0.782 |       0.654 |       0.788 |       0.61  |     1     |     0.928 |     1.192 |     1.275 |      0.718 |      0.699 |\n| KGE_sqrt      |       0.78  |       0.651 |       0.78  |       0.598 |     1.034 |     0.963 |     1.193 |     1.284 |      0.715 |      0.689 |\n| NSE_sqrt      |       0.782 |       0.648 |       0.791 |       0.626 |     0.982 |     0.897 |     1.192 |     1.276 |      0.715 |      0.709 |\n| KNS_333       |       0.774 |       0.648 |       0.774 |       0.606 |     1.061 |     0.957 |     1.193 |     1.291 |      0.711 |      0.69  |\n| KNS_442       |       0.773 |       0.647 |       0.772 |       0.607 |     1.067 |     0.956 |     1.193 |     1.291 |      0.71  |      0.689 |\n| KGEmix_sqrt50 |       0.771 |       0.647 |       0.77  |       0.568 |     1.071 |     0.996 |     1.193 |     1.286 |      0.709 |      0.669 |\n| KGE_NSE_50    |       0.768 |       0.646 |       0.766 |       0.607 |     1.081 |     0.956 |     1.193 |     1.293 |      0.707 |      0.687 |\n| NSE_bc025     |       0.766 |       0.645 |       0.783 |       0.576 |     0.99  |     0.956 |     1.209 |     1.282 |      0.706 |      0.679 |\n| LL_bc025      |       0.766 |       0.645 |       0.783 |       0.576 |     0.99  |     0.956 |     1.209 |     1.282 |      0.706 |      0.679 |\n| KGEmix_sqrt75 |       0.766 |       0.644 |       0.764 |       0.552 |     1.085 |     1.01  |     1.193 |     1.286 |      0.705 |      0.658 |\n| KN_7030       |       0.763 |       0.646 |       0.761 |       0.588 |     1.093 |     0.981 |     1.193 |     1.292 |      0.704 |      0.675 |\n| NSEmix_log50  |       0.762 |       0.644 |       0.782 |       0.63  |     1.003 |     0.887 |     1.214 |     1.279 |      0.703 |      0.706 |\n| DE            |       0.773 |       0.63  |       0.765 |       0.598 |     0.98  |     0.939 |     1.195 |     1.305 |      0.702 |      0.681 |\n| KGE           |       0.758 |       0.64  |       0.756 |       0.538 |     1.105 |     1.022 |     1.193 |     1.287 |      0.699 |      0.647 |\n| NSE           |       0.743 |       0.64  |       0.794 |       0.633 |     1     |     0.89  |     1.238 |     1.286 |      0.692 |      0.714 |\n| KGEmix_log50  |       0.758 |       0.622 |       0.755 |       0.453 |     1.094 |     1.056 |     1.197 |     1.279 |      0.69  |      0.604 |\n| NSE_log       |       0.721 |       0.639 |       0.754 |       0.511 |     1.028 |     0.986 |     1.254 |     1.271 |      0.68  |      0.633 |\n| KGE_np        |       0.78  |       0.574 |       0.786 |       0.257 |     0.98  |     1.071 |     1.192 |     1.25  |      0.677 |      0.521 |\n| Willmott_d    |       0.734 |       0.619 |       0.773 |       0.584 |     1.074 |     0.996 |     1.236 |     1.327 |      0.677 |      0.678 |\n| KGE_2021      |       0.758 |       0.591 |       0.756 |       0.513 |     1.105 |     1.076 |     1.193 |     1.342 |      0.675 |      0.634 |\n| KGE_2012      |       0.723 |       0.605 |       0.71  |       0.42  |     1.166 |     1.098 |     1.193 |     1.289 |      0.664 |      0.565 |\n| KGE_log       |       0.749 |       0.338 |       0.735 |      -0.465 |     1.111 |     1.359 |     1.196 |     1.273 |      0.544 |      0.135 |\n| negFDC_W1     |       0.545 |       0.239 |       0.204 |      -0.84  |     1.291 |     1.343 |     1.221 |     1.238 |      0.392 |     -0.318 |\n| NSE_inv       |       0.502 |       0.037 |       0.572 |      -0.822 |     1.148 |     1.588 |     1.449 |     1.627 |      0.27  |     -0.125 |\n:::\n:::\n\n\n::: {#tbl-transfer-wet .cell tbl-cap='Wet-shift splits: calibrate on all calibration water years except one wet 3-year block, test on that block (20–46 % wetter than the training years). Mean over the three blocks and the two surrogates; ΔKGE = test − train.' execution_count=17}\n``` {.python .cell-code}\nW = R[~R.split.str.startswith(\"temporal\")]\nagg = (W.groupby(\"objective\")\n         .agg(KGE_test=(\"KGE_test\", \"mean\"), NSE_test=(\"NSE_test\", \"mean\"),\n              KGE_train=(\"KGE_train\", \"mean\"), NSE_train=(\"NSE_train\", \"mean\"),\n              beta_test=(\"b_test\", \"mean\"), alpha_test=(\"a_test\", \"mean\"),\n              PBIAS_test=(\"PBIAS_test\", \"mean\"), FHV_test=(\"FHV_test\", \"mean\"),\n              KGE_test_min=(\"KGE_test\", \"min\"), KGE_test_sd=(\"KGE_test\", \"std\")))\nagg[\"dKGE\"] = agg.KGE_test - agg.KGE_train\nagg[\"dNSE\"] = agg.NSE_test - agg.NSE_train\nagg = agg.sort_values(\"KGE_test\", ascending=False)\nmd(agg[[\"KGE_test\", \"NSE_test\", \"KGE_test_min\", \"KGE_test_sd\", \"dKGE\", \"dNSE\",\n        \"beta_test\", \"alpha_test\", \"PBIAS_test\", \"FHV_test\"]].round(3))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=17}\n| objective     |   KGE_test |   NSE_test |   KGE_test_min |   KGE_test_sd |   dKGE |   dNSE |   beta_test |   alpha_test |   PBIAS_test |   FHV_test |\n|:--------------|-----------:|-----------:|---------------:|--------------:|-------:|-------:|------------:|-------------:|-------------:|-----------:|\n| KGE           |      0.783 |      0.697 |          0.647 |         0.085 |  0.007 | -0.005 |       1.087 |        0.929 |        8.675 |    -12.307 |\n| KGE_2012      |      0.782 |      0.63  |          0.592 |         0.116 |  0.027 | -0.004 |       1.088 |        1.003 |        8.836 |     -3.966 |\n| KGEmix_sqrt75 |      0.782 |      0.702 |          0.653 |         0.081 |  0.006 | -0.005 |       1.087 |        0.918 |        8.673 |    -13.24  |\n| KGEmix_sqrt50 |      0.78  |      0.708 |          0.659 |         0.077 |  0.005 | -0.005 |       1.087 |        0.909 |        8.698 |    -14.215 |\n| KN_7030       |      0.779 |      0.718 |          0.667 |         0.078 |  0.006 | -0.004 |       1.089 |        0.905 |        8.897 |    -15.126 |\n| KNS_333       |      0.773 |      0.725 |          0.673 |         0.074 |  0.005 | -0.003 |       1.089 |        0.887 |        8.882 |    -16.971 |\n| KNS_442       |      0.773 |      0.725 |          0.673 |         0.074 |  0.005 | -0.003 |       1.089 |        0.887 |        8.899 |    -16.954 |\n| KGE_NSE_50    |      0.773 |      0.725 |          0.674 |         0.075 |  0.005 | -0.003 |       1.089 |        0.889 |        8.931 |    -16.894 |\n| KGE_sqrt      |      0.773 |      0.721 |          0.672 |         0.068 |  0.005 | -0.002 |       1.087 |        0.885 |        8.731 |    -16.929 |\n| negMAE        |      0.761 |      0.718 |          0.669 |         0.061 |  0.002 | -0.007 |       1.085 |        0.864 |        8.532 |    -17.961 |\n| NSE_sqrt      |      0.752 |      0.726 |          0.671 |         0.06  |  0.003 | -0.005 |       1.086 |        0.845 |        8.618 |    -20.178 |\n| NSE           |      0.743 |      0.734 |          0.674 |         0.062 |  0.013 | -0.003 |       1.103 |        0.837 |       10.296 |    -20.634 |\n| KGE_log       |      0.621 |      0.159 |          0.281 |         0.264 |  0.003 | -0.046 |       1.085 |        1.144 |        8.519 |     13.647 |\n:::\n:::\n\n\n::: {#cell-fig-transfer .cell execution_count=18}\n``` {.python .cell-code}\norder = agg.index.tolist()\nfig, axs = plt.subplots(1, 2, figsize=(12, 4.6), sharey=True)\nfor ax, (sub, ttl) in zip(axs, [(W, \"wet-shift splits (3 blocks × 2 surrogates)\"),\n                                (T[T.objective.isin(order)], \"temporal split (2 surrogates)\")]):\n    m = sub.groupby(\"objective\")[[\"KGE_test\", \"NSE_test\"]].mean().reindex(order)\n    y = np.arange(len(order))\n    ax.barh(y - 0.2, m.KGE_test, height=0.38, label=\"KGE (test)\", color=\"#1f77b4\")\n    ax.barh(y + 0.2, m.NSE_test, height=0.38, label=\"NSE (test)\", color=\"#ff7f0e\")\n    for j, ob in enumerate(order):\n        d = sub[sub.objective == ob]\n        ax.plot(d.KGE_test, np.full(len(d), j - 0.2), \"k.\", ms=3, alpha=.7)\n        ax.plot(d.NSE_test, np.full(len(d), j + 0.2), \"k.\", ms=3, alpha=.7)\n    ax.set_yticks(y); ax.set_yticklabels(order); ax.set_xlim(0.2, 0.9)\n    ax.set_xlabel(\"out-of-sample efficiency\"); ax.set_title(ttl); ax.legend(loc=\"lower right\")\naxs[0].invert_yaxis()\nsave(fig, \"objective_transfer\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Out-of-sample KGE and NSE by calibration objective. Left: the three wet-shift splits (test 20–46 % wetter than training) — this is the analogue of the real evaluation window. Right: the temporal split (test slightly drier). Points are individual surrogate×split results, bars the mean.](04_metrics_files/figure-html/fig-transfer-output-1.png){#fig-transfer width=1151 height=477}\n:::\n:::\n\n\n::: {#cell-fig-tradeoff .cell execution_count=19}\n``` {.python .cell-code}\nfig, ax = plt.subplots(1, 2, figsize=(10, 4.2))\nfor a, met in zip(ax, [\"KGE\", \"NSE\"]):\n    g = W.groupby(\"objective\")[[f\"{met}_train\", f\"{met}_test\"]].mean()\n    a.plot([0.5, 0.95], [0.5, 0.95], \"k--\", lw=0.8)\n    a.scatter(g[f\"{met}_train\"], g[f\"{met}_test\"], s=28, c=\"#1f77b4\")\n    for ob, r_ in g.iterrows():\n        a.annotate(ob, (r_[f\"{met}_train\"], r_[f\"{met}_test\"]), fontsize=6.5,\n                   xytext=(3, 2), textcoords=\"offset points\")\n    a.set_xlabel(f\"{met} on the training years\"); a.set_ylabel(f\"{met} on the wetter test block\")\n    a.set_title(f\"{met}: calibration vs wet-shift transfer\")\nsave(fig, \"transfer_tradeoff\"); plt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Calibration score vs out-of-sample score for the wet-shift splits. Points below the 1:1 line lose performance when transferred to a wetter period; the vertical distance is the transfer loss. Objectives that win in calibration are not the ones that win out of sample.](04_metrics_files/figure-html/fig-tradeoff-output-1.png){#fig-tradeoff width=924 height=443}\n:::\n:::\n\n\n::: {#tbl-regret .cell tbl-cap='Overall ranking. \\'Regret\\' = mean shortfall of the objective behind the best objective of each individual surrogate×split experiment, averaged over all 8 experiments (4 splits × 2 surrogates), separately for KGE and NSE; 0 = always the best choice. \\'worst case\\' = largest single-experiment shortfall in KGE.' execution_count=20}\n``` {.python .cell-code}\ncommon = R.groupby(\"objective\").size()\ncommon = common[common == R.groupby(\"objective\").size().max()].index\nbest = R.groupby([\"model\", \"split\"])[[\"KGE_test\", \"NSE_test\"]].transform(\"max\")\nRg = R.assign(regret_KGE=best.KGE_test - R.KGE_test, regret_NSE=best.NSE_test - R.NSE_test)\nRg = Rg[Rg.objective.isin(common)]\nREG = (Rg.groupby(\"objective\")\n         .agg(regret_KGE=(\"regret_KGE\", \"mean\"), regret_NSE=(\"regret_NSE\", \"mean\"),\n              worst_case_KGE=(\"regret_KGE\", \"max\"), n=(\"regret_KGE\", \"size\")))\nREG[\"regret_mean\"] = 0.5 * (REG.regret_KGE + REG.regret_NSE)\nREG = REG.sort_values(\"regret_mean\")\nmd(REG.round(4))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=20}\n| objective     |   regret_KGE |   regret_NSE |   worst_case_KGE |   n |   regret_mean |\n|:--------------|-------------:|-------------:|-----------------:|----:|--------------:|\n| KNS_333       |       0.0247 |       0.0158 |           0.0583 |   8 |        0.0202 |\n| KNS_442       |       0.025  |       0.0158 |           0.0571 |   8 |        0.0204 |\n| KGE_NSE_50    |       0.0259 |       0.0165 |           0.0558 |   8 |        0.0212 |\n| KGE_sqrt      |       0.024  |       0.0187 |           0.0672 |   8 |        0.0213 |\n| KN_7030       |       0.0222 |       0.0248 |           0.0473 |   8 |        0.0235 |\n| NSE_sqrt      |       0.0401 |       0.0102 |           0.1029 |   8 |        0.0252 |\n| negMAE        |       0.0324 |       0.0181 |           0.0905 |   8 |        0.0252 |\n| KGEmix_sqrt50 |       0.0205 |       0.0333 |           0.0508 |   8 |        0.0269 |\n| NSE           |       0.0521 |       0.0028 |           0.1068 |   8 |        0.0274 |\n| KGEmix_sqrt75 |       0.0201 |       0.0403 |           0.0453 |   8 |        0.0302 |\n| KGE           |       0.0203 |       0.0472 |           0.0394 |   8 |        0.0337 |\n| KGE_2012      |       0.0299 |       0.1176 |           0.0823 |   8 |        0.0738 |\n| KGE_log       |       0.1812 |       0.5788 |           0.3925 |   8 |        0.38   |\n:::\n:::\n\n\n::: {#cell-fig-objcorr .cell execution_count=21}\n``` {.python .cell-code}\ndef lhs(n, bounds, seed=SEED):\n    r = np.random.default_rng(seed); d = bounds.shape[0]; u = np.empty((n, d))\n    for j in range(d):\n        u[:, j] = (r.permutation(n) + r.random(n)) / n\n    return bounds[:, 0] + u * (bounds[:, 1] - bounds[:, 0])\n\nTH = lhs(6000, BOUNDS[0])\nSB = simulate_batch(P, PET, TH, 0)\nvals = {}\nfor cname, f in CANDIDATES.items():\n    vals[cname] = np.array([f(SB[i][MM], O) for i in range(len(TH))])\nV = pd.DataFrame(vals).replace([np.inf, -np.inf], np.nan)\nbeh = V[\"KGE\"] > 0.0\nC = V[beh].rank().corr(method=\"pearson\")\nfig, ax = plt.subplots(figsize=(8.4, 7))\nsns.heatmap(C, cmap=\"viridis\", vmin=0, vmax=1, annot=True, fmt=\".2f\", annot_kws={\"size\": 6},\n            linewidths=.3, ax=ax, cbar_kws={\"label\": \"Spearman ρ\"})\nax.set_title(f\"Objective redundancy over {int(beh.sum())} behavioural HyMOD simulations\")\nsave(fig, \"objective_correlation\"); plt.show()\nprint(\"Spearman rho with KGE:\",\n      C[\"KGE\"].drop(\"KGE\").sort_values(ascending=False).round(3).to_dict())\n```\n\n::: {.cell-output .cell-output-display}\n![Redundancy of the candidate objectives. Spearman rank correlation between objective values over an ensemble of 6 000 Latin-hypercube HyMOD parameter sets (calibration metric window), restricted to the 'behavioural' subset with KGE > 0. Blocks of near-1 correlation are objectives that would select essentially the same parameter set.](04_metrics_files/figure-html/fig-objcorr-output-1.png){#fig-objcorr width=808 height=733}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nSpearman rho with KGE: {'KGEmix_sqrt75': 0.996, 'KGEmix_sqrt50': 0.98, 'negMAE': 0.949, 'LL_bc025': 0.948, 'NSE_bc025': 0.948, 'KN_7030': 0.928, 'NSE_sqrt': 0.927, 'KNS_333': 0.904, 'KGE_sqrt': 0.899, 'DE': 0.897, 'KGE_2012': 0.889, 'KNS_442': 0.885, 'NSEmix_log50': 0.868, 'NSE_log': 0.858, 'KGE_NSE_50': 0.855, 'KGE_np': 0.849, 'KGE_2021': 0.808, 'KGEmix_log50': 0.701, 'NSE': 0.681, 'Willmott_d': 0.653, 'negFDC_W1': 0.567, 'KGE_log': 0.536, 'NSE_inv': -0.165}\n```\n:::\n:::\n\n\n# Recommendation {#sec-recommendation}\n\n::: {#decide .cell execution_count=22}\n``` {.python .cell-code}\nREC = \"KGE_NSE_50\"\nprint(\"best mean test KGE on the wet-shift splits :\", agg.index[0])\nprint(\"best mean test KGE on the temporal split   :\", piv.index[0])\nprint(\"lowest combined regret over all 8 experiments:\", REG.index[0])\nprint(\"\\nrecommended objective:\", REC, \"=\", mx.OBJECTIVE_NAME, \"in src/common/metrics_extra.py\")\nprint(\"\\nOut-of-sample performance on the three wetter blocks (mean of 6 experiments):\")\nprint(agg.reindex([REC, \"KGE\", \"NSE\", \"KGE_sqrt\", \"NSE_sqrt\", \"KNS_333\"])[\n      [\"KGE_test\", \"NSE_test\", \"dKGE\", \"dNSE\", \"beta_test\", \"alpha_test\"]].dropna(how=\"all\").round(4))\nprint(\"\\nRegret over all 8 experiments (mean shortfall behind the best objective of each):\")\nprint(REG.reindex([REC, \"KGE\", \"NSE\", \"KGE_sqrt\", \"NSE_sqrt\", \"KNS_333\", \"KNS_442\",\n                   \"KN_7030\", \"KGEmix_sqrt50\"]).dropna(how=\"all\").round(4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbest mean test KGE on the wet-shift splits : KGE\nbest mean test KGE on the temporal split   : negMAE\nlowest combined regret over all 8 experiments: KNS_333\n\nrecommended objective: KGE_NSE_50 = KGE_NSE_50 in src/common/metrics_extra.py\n\nOut-of-sample performance on the three wetter blocks (mean of 6 experiments):\n            KGE_test  NSE_test    dKGE    dNSE  beta_test  alpha_test\nobjective                                                            \nKGE_NSE_50    0.7730    0.7246  0.0045 -0.0033     1.0893      0.8885\nKGE           0.7831    0.6969  0.0073 -0.0047     1.0867      0.9286\nNSE           0.7432    0.7340  0.0135 -0.0033     1.1030      0.8371\nKGE_sqrt      0.7728    0.7210  0.0047 -0.0020     1.0873      0.8854\nNSE_sqrt      0.7515    0.7257  0.0034 -0.0052     1.0862      0.8448\nKNS_333       0.7733    0.7245  0.0049 -0.0029     1.0888      0.8866\n\nRegret over all 8 experiments (mean shortfall behind the best objective of each):\n               regret_KGE  regret_NSE  worst_case_KGE  n  regret_mean\nobjective                                                            \nKGE_NSE_50         0.0259      0.0165          0.0558  8       0.0212\nKGE                0.0203      0.0472          0.0394  8       0.0337\nNSE                0.0521      0.0028          0.1068  8       0.0274\nKGE_sqrt           0.0240      0.0187          0.0672  8       0.0213\nNSE_sqrt           0.0401      0.0102          0.1029  8       0.0252\nKNS_333            0.0247      0.0158          0.0583  8       0.0202\nKNS_442            0.0250      0.0158          0.0571  8       0.0204\nKN_7030            0.0222      0.0248          0.0473  8       0.0235\nKGEmix_sqrt50      0.0205      0.0333          0.0508  8       0.0269\n```\n:::\n:::\n\n\n## The decision\n\n**Calibrate on $\\mathcal{O}=0.5\\,\\mathrm{KGE}(Q)+0.5\\,\\mathrm{NSE}(Q)$ — maximise — on\n1952-10-01…1988-09-30; equivalently minimise $1-\\mathcal{O}$.**\n\nThis is *not* the answer the catalogue alone would have suggested (a KGE + $\\sqrt{Q}$ composite);\nit is what @sec-transfer produced. The decisive numbers:\n\n| Criterion | Evidence |\n|---|---|\n| **Alignment with the reported metrics** | The objective *is* the unweighted average of the two reported metrics on untransformed $Q$ — nothing is optimised that is not reported, and nothing reported is left out. No transform, no $\\varepsilon$, no tuning constant other than the 50/50 weight. |\n| **The two terms are not redundant** | Over 6 000 behavioural HyMOD simulations the Spearman rank correlation between KGE and NSE is only ≈0.7 (@fig-objcorr): KGE and NSE genuinely disagree about which parameter set is better on this record, so averaging them is a real multi-criteria compromise, not a re-scaling. |\n| **Robustness to the skew and to volume bias** | KGE's $\\beta$ term supplies the water-balance control that NSE lacks at CV = 2.107 (factor 14–89, @tbl-bias-sens), while NSE's stronger timing sensitivity (@sec-synthetic item 2) compensates KGE's weaker one. The pair covers each other's blind spots. |\n| **Transfer to a wetter period** | @tbl-regret: worst-case regret 0.056 (KGE) and 0.047 (NSE) — the only candidate of the 24 that keeps **both** below 0.06. KGE-only calibration has a worst case of 0.162 in NSE, NSE-only 0.107 in KGE. On the wet blocks the recommendation reaches mean KGE 0.773 / NSE 0.725 against 0.783/0.697 (KGE-only) and 0.743/0.734 (NSE-only): it gives up ≈0.010 KGE to gain ≈0.028 NSE. |\n| **Parsimony** | Three further variants were run through all 8 experiments: $(\\mathrm{KGE}+\\mathrm{NSE}+\\mathrm{KGE}(\\sqrt Q))/3$, $0.4/0.4/0.2$ and $0.7\\,\\mathrm{KGE}+0.3\\,\\mathrm{NSE}$. The first two are indistinguishable from the recommendation (all out-of-sample means differ by < 0.001); the 70/30 weighting trades 0.004 KGE for 0.008 NSE and doubles the worst case. The simplest member of the tied group wins. |\n| **Optimiser and ML compatibility** | Smooth, bounded above by 1, ~0.9 ms per evaluation on 13 149 days, and differentiable everywhere — a10's global searches, a11–a15's calibrations and a09's gradient training all use the *same* scalar. |\n\n::: {.callout-note}\n## Honest limitation\nThe recommendation does **not** improve low flows: out-of-sample log-NSE on the wet blocks is 0.666\nfor the recommendation against 0.761 for sqrt-NSE and 0.591 for KGE-only, and the high-flow bias FHV\nis −16.9 % against −12.3 % for KGE-only. Balancing the hydrograph and maximising the two reported\nmetrics are different goals, and `config/project.yaml` asks for the second. The low-flow and\nhigh-flow behaviour is therefore controlled through the *acceptance checks* in\n`config/metrics.yaml` (`|PBIAS| ≤ 10 %`, $\\beta\\in[0.90,1.10]$, $\\alpha\\in[0.85,1.15]$,\n$|\\mathrm{FHV}| \\le 25$ %, $|\\Delta\\mathrm{BFI}|\\le0.15$), which a11–a15 must report, not through\nthe objective. A slot that passes the acceptance checks *and* maximises $\\mathcal{O}$ is both\nhydrologically sound and competitive in the ranking.\n:::\n\n## Why not each alternative\n\n* **Plain KGE (2009).** The ranking metric, and the declared fallback. It gives the best\n  out-of-sample KGE (regret 0.020 vs 0.026) — but the worst NSE of the whole KGE family\n  (regret 0.047, worst case 0.162, wet-block NSE 0.697). Since NSE is reported too, paying\n  0.006 KGE to remove that exposure is the better bet.\n* **NSE.** Nearly blind to volume bias at CV = 2.107 (@tbl-bias-sens): a 10 % volume error costs\n  0.0023 NSE and 0.100 KGE. NSE-only calibrations produced the largest $|\\beta-1|$ on every wet\n  test block (mean $\\beta$ = 1.103 vs 1.089) and the largest KGE regret (0.052). Never alone.\n* **RMSE / MSE / Gaussian likelihood.** Monotone transformations of each other and of NSE for a\n  fixed observation window — identical argmax, identical weakness. Not separate options.\n  (`LL_bc025` and `NSE_bc025` returned bit-identical parameter sets in @tbl-transfer-temporal,\n  which is the empirical demonstration of that equivalence.)\n* **KGE′ (2012).** $\\gamma=\\mathrm{CV}_s/\\mathrm{CV}_o$ cancels a pure scaling error, so a uniformly\n  biased model is penalised once instead of twice. It wins single wet blocks (KGE 0.909 on\n  WY1961–63) but has the worst NSE regret of the KGE family (0.118) and out-of-sample log-NSE 0.11:\n  it buys KGE by wrecking the low-flow end.\n* **KGE″ (2021).** Built for $\\mu_o\\to0$ (ephemeral rivers). At CV = 2.107 it divides the bias by\n  2.1 before squaring and degenerates towards NSE; on the temporal split it was strictly worse than\n  KGE for both surrogates. Leaf River is perennial — there is nothing to fix.\n* **Non-parametric KGE.** Robust and FDC-based, and the best objective for HyMOD on the temporal\n  split, but it collapsed for the second surrogate (test NSE 0.257) because it optimises ranks and\n  FDC shape rather than event magnitudes. Mean KGE regret 0.077. Retained as a diagnostic.\n* **log-NSE / log-KGE / inverse-NSE.** @sec-synthetic items 3–4: they cannot see a 30 % raw-variance\n  error and they explode on 0.3 mm/d of low-flow noise. In the transfer experiment KGE_log was the\n  worst objective tested (mean KGE regret 0.181, NSE regret 0.579; test NSE −0.47 for one surrogate)\n  and inverse-NSE was second worst. With only 92 warm-up days before the evaluation metric window,\n  an objective dominated by the slowest store is also the most exposed to initial-state error.\n* **MAE.** A genuinely strong performer (best mean test KGE on the temporal split) and robust to the\n  tail, but it is not one of the reported metrics, it has no diagnostic decomposition, and its\n  worst-case KGE regret (0.091) is 1.6× the recommendation's.\n* **Formal likelihoods (GL, AR(1)).** Only justified if a10 chooses DREAM *and* the deliverable were\n  predictive uncertainty. They add 3–5 nuisance parameters and, in the Gaussian case, reduce to NSE.\n* **Signature / Pareto multi-objective.** A Pareto front cannot be handed to a11–a15 as a single\n  number and the final ranking is single-objective by construction. Signatures are used as\n  acceptance checks instead (@sec-a16).\n\n## Per-slot guidance\n\n| Slot | Model kind | Objective | Notes |\n|---|---|---|---|\n| 1–5, conceptual (`kind = \"conceptual\"`) | global search (a10) | maximise `mx.objective` $=0.5\\,\\mathrm{KGE}(Q)+0.5\\,\\mathrm{NSE}(Q)$, equivalently minimise `mx.objective_cost` | identical for every slot — otherwise a comparison between slots is not a comparison of models. Map non-finite costs to $10^6$. |\n| trainable / ML (`kind = \"trainable\"`, e.g. LSTM) | gradient descent | minimise `1 - objective` as a **full-batch** loss on the training mask, in torch with population sd (`unbiased=False`); the mini-batch NSE\\* of @kratzert2019 may be used as the *inner* loss for stability, but early stopping and model selection use the composite on the internal-validation mask | KGE needs the whole batch: $\\mu$, $\\sigma$ and $r$ are not additive over mini-batches |\n| ensembles / hybrids | weights fitted on calibration only | same objective; weights fitted on the internal-validation mask (1981-10-01…1988-09-30) and then frozen | `config/project.yaml`: ensemble weights must never see evaluation data |\n\nFallback if a slot's optimiser cannot handle the composite (a11–a15 must log this in their handoff):\nuse plain **KGE (2009)** and report the difference. Do **not** fall back to NSE alone.\n\n# How Agent 16 must report {#sec-a16}\n\n::: {#tbl-a16-drift .cell tbl-cap='Transfer behaviour measured in Experiment 2 (13 core objectives, 2 surrogates). Deltas are test minus training window. The three wet blocks are the analogue of the real evaluation window; the temporal split is the opposite (drier) direction.' execution_count=23}\n``` {.python .cell-code}\ncore = [c for c in CORE]\nD = R[R.objective.isin(core)].copy()\nD[\"wet\"] = np.where(D.split.str.startswith(\"temporal\"), \"temporal (drier test)\", \"wet blocks (wetter test)\")\ndrift = D.groupby(\"wet\").agg(dKGE=(\"KGE_test\", \"mean\"), dNSE=(\"NSE_test\", \"mean\"),\n                             beta_train=(\"b_train\", \"mean\"), beta_test=(\"b_test\", \"mean\"),\n                             alpha_train=(\"a_train\", \"mean\"), alpha_test=(\"a_test\", \"mean\"))\ndrift[\"dKGE\"] = D.groupby(\"wet\").apply(lambda g: (g.KGE_test - g.KGE_train).mean())\ndrift[\"dNSE\"] = D.groupby(\"wet\").apply(lambda g: (g.NSE_test - g.NSE_train).mean())\ndrift[\"dbeta\"] = drift.beta_test - drift.beta_train\ndrift[\"dalpha\"] = drift.alpha_test - drift.alpha_train\nmd(drift[[\"dKGE\", \"dNSE\", \"dbeta\", \"dalpha\", \"beta_train\", \"beta_test\"]].round(4))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=23}\n| wet                      |    dKGE |    dNSE |   dbeta |   dalpha |   beta_train |   beta_test |\n|:-------------------------|--------:|--------:|--------:|---------:|-------------:|------------:|\n| temporal (drier test)    | -0.0766 | -0.0541 |  0.1082 |   0.1041 |       1.1327 |      1.2409 |\n| wet blocks (wetter test) |  0.0071 | -0.0073 | -0.0676 |  -0.0234 |       1.1562 |      1.0886 |\n:::\n:::\n\n\n1. **Only KGE and NSE**, both on untransformed $Q$ in mm/day, both from `src/common/metrics.py`,\n   both on the evaluation metric window 1949-01-01…1951-09-30 (1 003 days; warm-up\n   1948-10-01…1948-12-31 excluded). No transformed variant and no diagnostic appears in the\n   ranking table (`final_report_metrics_only: true`).\n2. **Rank by KGE**, ties broken by NSE (`config/project.yaml: primary_selection_metric: KGE`).\n3. **Quote the benchmarks** of @tbl-benchmarks so the numbers are interpretable: the mean-flow\n   benchmark gives NSE 0.000 and **KGE −0.414** [@knoben2019] — KGE = 0 is already a non-trivial\n   model, and a KGE of 0.7 is *not* \"70 % of perfect\". One-day persistence gives NSE 0.78 /\n   KGE 0.89 on calibration: a rainfall–runoff model that does not beat that has added nothing.\n4. **Report the calibration-window KGE and NSE next to the evaluation values** so the transfer is\n   visible. Experiment 2 gives the quantitative expectation (@tbl-a16-drift): moving a calibrated\n   model to a **wetter** period of similar length changed KGE by **+0.007 on average**\n   (range −0.05…+0.05 across blocks) and NSE by **−0.007** — i.e. a wetter evaluation period is\n   *not* intrinsically harder. The damaging direction is the opposite one: moving to a 6 % *drier*\n   period cost ΔKGE −0.077 and ΔNSE −0.054. A large drop on the evaluation window should therefore\n   be read as over-fitting or a warm-up artefact, not as \"the evaluation period is wetter\".\n5. **Expect the volume ratio to fall.** Across the three wet blocks $\\beta$ dropped by\n   **−0.068** relative to its value on the training years (and rose by +0.108 in the dry\n   direction), with $\\alpha$ moving the same way. On a 29 %-wetter evaluation window a $\\beta$\n   of 0.93–1.00 for a model calibrated to $\\beta\\approx1.03$ is the *expected* outcome. This is a\n   prediction to be checked, **not** a correction: no model may be re-tuned for it, and no\n   statistic of the evaluation window may enter any calibration.\n6. **Only 92 warm-up days** precede the evaluation metric window (against 366 in calibration), so\n   the initial-state choice is visible in Jan–Mar 1949. a16 should state the initialisation used\n   and, as a robustness check, report KGE/NSE with the first 30 metric days dropped — as a\n   *footnote*, never as the headline number.\n7. Diagnostics ($r,\\alpha,\\beta$, PBIAS, FHV, FLV, log-NSE, BFI) may be computed for the discussion\n   but must be visually separated from the ranking table.\n\n# Machine-readable specification\n\n`config/metrics.yaml` is the contract for a10 and a11–a15; `tests/test_metrics_extra.py`\nasserts that it and `src/common/metrics_extra.py` agree.\n\n::: {#show-config .cell execution_count=24}\n``` {.python .cell-code}\nprint(open(ROOT / \"config\" / \"metrics.yaml\").read())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# ===================================================================================\n# Calibration objective and metric contract — written by Agent 4 (a04-metrics-advisor).\n# Authoritative for a10 (optimiser design) and a11–a15 (calibration).\n# Rationale, formulas and the supporting experiments: reports/04_metrics.qmd\n# Implementation: src/common/metrics_extra.py   (canonical KGE/NSE: src/common/metrics.py)\n# Tests that this file and the code agree: tests/test_metrics_extra.py\n# ===================================================================================\nschema_version: 1\nwritten_by: a04-metrics-advisor\nwritten_at: \"2026-09-15\"\n\n# -----------------------------------------------------------------------------------\n# 1. What the FINAL report shows. Fixed by the user / config/project.yaml — not Agent 4's choice.\n# -----------------------------------------------------------------------------------\nreporting_metrics: [KGE, NSE]         # the ONLY metrics in reports/16_*.qmd (a16)\nprimary_selection_metric: KGE         # ties broken by NSE\nreporting_transform: none             # KGE and NSE are computed on untransformed Q (mm/day)\nreporting_implementation: src/common/metrics.py    # kge(), nse() — never re-implement\nreporting_period: evaluation_metric   # 1949-01-01..1951-09-30, 1003 d (a16 only)\n\n# -----------------------------------------------------------------------------------\n# 2. THE CALIBRATION OBJECTIVE  (this is what a10/a11–a15 must optimise)\n# -----------------------------------------------------------------------------------\nrecommended_objective: KGE_NSE_50\n\nobjective:\n  id: KGE_NSE_50\n  name: \"Equally weighted average of the two reported efficiencies on untransformed daily flow\"\n  formula_latex: \"\\\\mathcal{O} = 0.5\\\\,KGE(Q_{sim},Q_{obs}) + 0.5\\\\,NSE(Q_{sim},Q_{obs})\"\n  formula_python: \"0.5*kge(sim, obs) + 0.5*nse(sim, obs)\"\n  kge_variant: \"Gupta et al. (2009): 1 - sqrt((r-1)^2 + (alpha-1)^2 + (beta-1)^2), alpha = sd_sim/sd_obs, beta = mean_sim/mean_obs\"\n  nse_variant: \"Nash & Sutcliffe (1970): 1 - sum((sim-obs)^2)/sum((obs-mean_obs)^2)\"\n  weights: {KGE: 0.5, NSE: 0.5}\n  transform:\n    name: identity                 # NO transform is applied to sim or obs\n    epsilon: 0.0                   # would not be needed anyway: observed Q >= 0.069 mm/day\n    epsilon_justification: >\n      a02 verified Q > 0 on all 14,610 days (quantised at 0.0012544 mm/day = 1 cfs over\n      1,949 km2), so sqrt/log/Box-Cox would be defined without an arbitrary constant. A\n      sqrt-KGE third term was nevertheless TESTED (variants KNS_333 and KNS_442 in\n      reports/04_metrics.qmd Experiment 2) and changed every out-of-sample number by < 0.001,\n      so it was dropped on parsimony grounds. Simulated flows are floored at 1e-12 mm/day only\n      to keep diagnostics finite.\n  # ---- sign convention -------------------------------------------------------------\n  maximise: true                   # the objective is a SCORE: larger is better\n  optimum: 1.0                     # perfect simulation\n  minimised_quantity: \"1 - objective\"    # what SCE-UA / DE / Nelder-Mead / L-BFGS must minimise\n  minimised_optimum: 0.0\n  unbounded_below: true            # can go to -inf\n  nan_policy: \"non-finite objective -> return cost 1e6 (never NaN) so the optimiser keeps moving\"\n  # ---- implementation --------------------------------------------------------------\n  python:\n    module: src.common.metrics_extra\n    score: \"objective(sim, obs)\"          # maximise this\n    cost:  \"objective_cost(sim, obs)\"     # == 1 - objective(sim, obs); minimise this\n    constants: {OBJECTIVE_W: 0.5, OBJECTIVE_TRANSFORM: identity, OBJECTIVE_NAME: KGE_NSE_50}\n  # ---- period mask -----------------------------------------------------------------\n  period:\n    which: calibration\n    run_window:    [\"1951-10-01\", \"1988-09-30\"]   # simulate from here (warm-up included)\n    warmup_window: [\"1951-10-01\", \"1952-09-30\"]   # 366 d, EXCLUDED from the objective\n    metric_window: [\"1952-10-01\", \"1988-09-30\"]   # 13,149 d: the objective is computed on THIS\n    how: >\n      run = src.common.data.slice_run(df, \"calibration\");\n      mask = src.common.data.metric_mask(run, \"calibration\");\n      score = src.common.metrics_extra.objective(sim[mask], obs[mask])\n    never_use: \"evaluation window 1948-10-01..1951-09-30 (a16 only; LR_AGENT=a16)\"\n  # ---- internal split (model selection WITHOUT touching evaluation) -----------------\n  internal_split:\n    train:      [\"1952-10-01\", \"1981-09-30\"]   # 10,592 d - hyperparameters, early stopping\n    validation: [\"1981-10-01\", \"1988-09-30\"]   # 2,557 d - model/ensemble selection, ensemble weights\n    usage: >\n      Conceptual models: calibrate on the FULL calibration metric window (13,149 d) for the final\n      parameter set; use train/validation only to check for over-fitting and to report a transfer\n      number. Trainable models: fit on train, early-stop and select on validation, then optionally\n      refit on the full window with the selected hyperparameters. Ensemble weights: fit on\n      validation only, then freeze.\n  cost_note: \"~0.9 ms per evaluation on 13,149 days (one KGE + one NSE, pure NumPy)\"\n  # ---- evidence --------------------------------------------------------------------\n  evidence:\n    experiment: \"reports/04_metrics.qmd Experiment 2: 2 surrogate models (HyMOD, NLRes) x 4 independent splits inside calibration x 24 candidate objectives, identical DE budget (seed 42)\"\n    mean_regret_KGE: 0.0259     # mean shortfall behind the best objective of each experiment\n    mean_regret_NSE: 0.0165\n    worst_case_regret_KGE: 0.0558\n    worst_case_regret_NSE: 0.0468\n    comparison:\n      KGE_only:  {mean_regret_KGE: 0.0203, mean_regret_NSE: 0.0472, worst_case_NSE: 0.1617}\n      NSE_only:  {mean_regret_KGE: 0.0521, mean_regret_NSE: 0.0028, worst_case_KGE: 0.1068}\n      KGE_sqrt:  {mean_regret_KGE: 0.0240, mean_regret_NSE: 0.0187, worst_case_KGE: 0.0672}\n    wet_shift_performance: {KGE_test: 0.773, NSE_test: 0.725, beta: 1.089, alpha: 0.889, FHV_pct: -16.9}\n    note: \"the three wet-shift splits reproduce the evaluation window's situation (test period 20-46 % wetter than training, test maximum below the training maximum)\"\n\n# -----------------------------------------------------------------------------------\n# 3. Loss for trainable / ML models (a09 LSTM and any gradient-trained slot)\n# -----------------------------------------------------------------------------------\ntrainable_loss:\n  id: KGE_NSE_50_loss\n  formula: \"1 - [0.5*KGE(Q_sim, Q_obs) + 0.5*NSE(Q_sim, Q_obs)]\"\n  minimise: true\n  optimum: 0.0\n  batching: full_window           # KGE needs mu, sigma and r over the WHOLE scored window\n  reference_numpy: \"src.common.metrics_extra.trainable_loss_numpy(sim, obs)\"\n  torch_notes: >\n    Use torch.std(..., unbiased=False) (population sd) to match numpy exactly; build the KGE and\n    NSE terms once on the concatenated prediction of the whole scored window (13,149 daily values\n    is small) rather than averaging per-mini-batch efficiencies - a per-mini-batch KGE is a\n    DIFFERENT objective and must never be used for early stopping or model selection.\n  inner_loss_allowed: >\n    Where the training scheme cannot produce a full-window prediction per step (a03 slot 5 trains\n    on random 365-day windows with the first 60 days masked), use a per-window loss for the\n    gradient steps - the basin-averaged NSE* of Kratzert et al. (2019),\n    sum((s-o)^2 / (sd_obs + 0.1)^2), is the recommended inner loss - but compute the composite\n    objective on the FULL internal-validation simulation for early stopping, hyperparameter\n    selection and every reported training curve.\n  standardisation: >\n    Input scaling uses calibration-window statistics ONLY (a02): P 3.9078/10.1414,\n    PET 2.9004/1.8890, Q 1.3533/2.8511, log Q -0.5963/1.2192 (mean/sd).\n\n# -----------------------------------------------------------------------------------\n# 3b. Per-slot application (slot definitions from a03 / config/models.yaml)\n# -----------------------------------------------------------------------------------\nper_slot:\n  \"1_arx_api_ridge\":\n    kind: trainable\n    inner_fit: \"closed-form ridge on the Box-Cox transformed target (NOT the project objective) - this is the estimator, not the model-selection criterion\"\n    selection_objective: \"objective() on the internal-validation window; refit the coefficients on the full calibration metric window with the selected hyperparameters and report objective(), KGE and NSE there\"\n    note: \"back-transform to mm/day BEFORE computing any metric; the objective is never evaluated in Box-Cox space\"\n  \"2_gr4j\":       {kind: conceptual, objective: objective(), search: \"global (a10), full calibration metric window\"}\n  \"3_hbv_light\":  {kind: conceptual, objective: objective(), search: \"global (a10), full calibration metric window\"}\n  \"4_sacsma\":     {kind: conceptual, objective: objective(), search: \"global (a10), full calibration metric window; warm-up 730 d - exclude it from the objective as usual\"}\n  \"5_lstm_seq2seq\":\n    kind: trainable\n    inner_loss: \"per-window NSE* (Kratzert et al. 2019) with the first 60 warm-up steps masked\"\n    selection_objective: \"objective() on the full internal-validation simulation (early stopping, Optuna trials, seed-ensemble averaging)\"\n  ensembles:\n    objective: \"objective() on the internal-validation window 1981-10-01..1988-09-30\"\n    note: \"ens_nnls_calibration weights come from non-negative least squares on that window; report objective(), KGE and NSE of every ensemble on the full calibration metric window before freezing\"\n\n# -----------------------------------------------------------------------------------\n# 4. Fallbacks and forbidden objectives\n# -----------------------------------------------------------------------------------\nfallback_objective:\n  id: KGE\n  when: \"a slot's optimiser cannot handle the composite (e.g. an unstable or non-smooth model)\"\n  action: \"use plain KGE (2009), never NSE alone, and record the deviation in the slot's handoff JSON\"\n\nrejected_objectives:      # tested in reports/04_metrics.qmd Experiment 2 and rejected\n  - id: NSE_alone\n    why: >\n      At CV(Q) = 2.107 a 10 % volume error costs 0.0023 NSE but 0.100 KGE (factor 44). NSE-only\n      calibrations carried the largest |beta-1| into every out-of-sample test (mean KGE regret\n      0.052, worst case 0.107). NSE is fine as HALF of the recommended objective, never alone.\n  - id: [MSE, RMSE, LL_gauss]\n    why: \"monotone transformations of NSE for a fixed observation window: identical argmax, identical weakness\"\n  - id: [NSE_log, KGE_log, NSE_inv]\n    why: >\n      Blind to raw-flow variance errors (log-NSE stays at 0.91 while KGE falls to -1.17 for a\n      30 % log-variance inflation) and numerically unstable at low flow (inverse-NSE = -1.6e4 for\n      0.3 mm/d of white noise). KGE_log had by far the worst transfer (mean KGE regret 0.18).\n  - id: KGE_2012\n    why: \"gamma = CV_sim/CV_obs cancels a pure scaling error; worst NSE transfer of the KGE family (regret 0.118)\"\n  - id: KGE_2021\n    why: \"designed for mu_obs -> 0 (ephemeral rivers); at CV 2.107 it divides the bias by 2.1 before squaring and degenerates towards NSE\"\n  - id: KGE_np\n    why: \"optimises ranks and FDC shape, not event magnitudes; mean KGE regret 0.077. Kept as a diagnostic.\"\n  - id: [KNS_333, KNS_442]\n    why: \"3-term variants adding a sqrt-KGE term to the recommendation; tested, differences < 0.001 - rejected on parsimony\"\n  - id: \"any objective computed on the evaluation window\"\n    why: \"CLAUDE.md rule 3 - invalidates the study\"\n\n# -----------------------------------------------------------------------------------\n# 5. Diagnostics (development only — NEVER in the final report)\n# -----------------------------------------------------------------------------------\nsecondary_diagnostics: [KGE_r, KGE_alpha, KGE_beta, NSE_log, NSE_sqrt, PBIAS, FHV, FLV, FMS,\n                        BFI_err, recession_err, peak_timing, FDC_slope_err, KGE_np]\ndiagnostic_targets:        # observed values on the calibration metric window (a02)\n  KGE_r: 1.0\n  KGE_alpha: 1.0\n  KGE_beta: 1.0\n  PBIAS_pct: 0.0\n  FHV_pct: 0.0\n  FLV_pct: 0.0\n  BFI: 0.41\n  recession_k_per_day: 0.896\n  flashiness_RB: 0.316\n  fdc_slope_33_66: 3.50\n  acf1: 0.888\nacceptance_checks:         # a11-a15 should flag a calibration that violates these\n  abs_PBIAS_pct_max: 10.0\n  KGE_beta_range: [0.90, 1.10]\n  KGE_alpha_range: [0.85, 1.15]\n  abs_FHV_pct_max: 25.0\n  BFI_abs_error_max: 0.15\n\n# -----------------------------------------------------------------------------------\n# 6. Benchmarks (calibration metric window) — quote these when interpreting scores\n# -----------------------------------------------------------------------------------\nbenchmarks:\n  mean_flow:        {KGE: -0.4142, NSE: 0.0,   note: \"KGE of the mean-flow benchmark is 1-sqrt(2), not 0 (Knoben et al. 2019)\"}\n  climatology_doy:  {KGE: 0.084,   NSE: 0.127, note: \"15-day smoothed day-of-year mean, calibration window\"}\n  persistence_1day: {KGE: 0.890,   NSE: 0.780, note: \"Q(t) = Q(t-1); ACF1 = 0.888 — a rainfall-runoff model must beat this\"}\n  literature_at_gauge: {SAC_SMA_NSE: 0.796, HBV_NSE: 0.819, NWM_v21_KGE: 0.72, LSTM_NSE: 0.84, note: \"a01, USGS 02472000\"}\n\n# -----------------------------------------------------------------------------------\n# 7. Metric library\n# -----------------------------------------------------------------------------------\nlibrary:\n  module: src.common.metrics_extra\n  registry: METRICS              # name -> callable f(sim, obs, **kw) -> float\n  orientation: ORIENTATION       # +1 larger is better, -1 smaller is better, 0 target value\n  optimum: OPTIMUM\n  transforms: [identity, sqrt, log, inverse, boxcox, power]\n  conventions:\n    units: \"mm/day for sim and obs; caller applies the period mask before calling\"\n    nan_safe: \"pairs with non-finite sim or obs are dropped (src.common.metrics._clean)\"\n    pbias_sign: \"positive = OVER-prediction (hydroGOF convention); the negative of Moriasi et al. (2007)/hydroeval\"\n  do_not_modify: src/common/metrics.py\n\nrationale_report: reports/04_metrics.qmd\n\n```\n:::\n:::\n\n\n::: {#verify .cell execution_count=25}\n``` {.python .cell-code code-fold=\"false\"}\n# The objective shipped in metrics_extra is exactly the one recommended above.\nsel = R.query(\"objective == @REC and model == 'HyMOD' and split.str.startswith('temporal')\")\nchk = simulate_batch(P, PET, np.atleast_2d(sel[[f\"p_{k}\" for k in PNAMES[0]]].to_numpy()[0]), 0)[0]\nassert abs(mx.objective(chk[MM], O) - (0.5 * kge(chk[MM], O) + 0.5 * nse(chk[MM], O))) < 1e-12\nassert abs(mx.objective_cost(chk[MM], O) - (1 - mx.objective(chk[MM], O))) < 1e-12\nassert mx.objective(O, O) == 1.0 and mx.objective_cost(O, O) == 0.0\nprint(\"objective() verified: perfect = 1.0, cost = 1 - objective, maximise.\")\nprint(f\"library: {len(mx.METRICS)} metrics registered in mx.METRICS\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nobjective() verified: perfect = 1.0, cost = 1 - objective, maximise.\nlibrary: 50 metrics registered in mx.METRICS\n```\n:::\n:::\n\n\n# Environment\n\n::: {#versions .cell execution_count=26}\n``` {.python .cell-code}\nimport numpy, scipy, pandas, matplotlib, seaborn, numba, platform\ntry:\n    import hydroeval; hv = hydroeval.__version__\nexcept Exception:\n    hv = \"n/a\"\nprint(f\"python {platform.python_version()} | numpy {numpy.__version__} | pandas {pandas.__version__} | \"\n      f\"scipy {scipy.__version__} | numba {numba.__version__} | matplotlib {matplotlib.__version__} | \"\n      f\"seaborn {seaborn.__version__} | hydroeval {hv} | seed {SEED}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\npython 3.11.16 | numpy 2.0.2 | pandas 3.0.5 | scipy 1.17.1 | numba 0.67.0 | matplotlib 3.11.1 | seaborn 0.13.2 | hydroeval 0.1.0 | seed 42\n```\n:::\n:::\n\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "04_metrics_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}